// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: traffic/v1/feature.proto
// Protobuf Java Version: 4.33.2

package com.traffic.proto.v1;

@com.google.protobuf.Generated
public final class Feature extends com.google.protobuf.GeneratedFile {
  private Feature() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 2,
      /* suffix= */ "",
      "Feature");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_traffic_v1_FeatureStatV1_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_traffic_v1_FeatureStatV1_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_traffic_v1_FeatureSeqV1_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_traffic_v1_FeatureSeqV1_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030traffic/v1/feature.proto\022\ntraffic.v1\032\027" +
      "traffic/v1/common.proto\"\262\006\n\rFeatureStatV" +
      "1\022/\n\006header\030\001 \001(\0132\027.traffic.v1.EventHead" +
      "erR\006header\022!\n\014community_id\030\002 \001(\tR\013commun" +
      "ityId\022\037\n\013object_type\030\003 \001(\tR\nobjectType\022\033" +
      "\n\tobject_id\030\004 \001(\tR\010objectId\022\020\n\003pps\030\n \001(\002" +
      "R\003pps\022\020\n\003bps\030\013 \001(\002R\003bps\022\"\n\rup_down_ratio" +
      "\030\024 \001(\002R\013upDownRatio\022&\n\017bytes_fwd_ratio\030\025" +
      " \001(\002R\rbytesFwdRatio\022\033\n\tsyn_ratio\030\036 \001(\002R\010" +
      "synRatio\022\033\n\tfin_ratio\030\037 \001(\002R\010finRatio\022\033\n" +
      "\trst_ratio\030  \001(\002R\010rstRatio\022\033\n\tack_ratio\030" +
      "! \001(\002R\010ackRatio\022\033\n\tpsh_ratio\030\" \001(\002R\010pshR" +
      "atio\022\036\n\013iat_mean_ms\030( \001(\002R\tiatMeanMs\022\034\n\n" +
      "iat_std_ms\030) \001(\002R\010iatStdMs\022\034\n\niat_min_ms" +
      "\030* \001(\002R\010iatMinMs\022\034\n\niat_max_ms\030+ \001(\002R\010ia" +
      "tMaxMs\022\037\n\013pktlen_mean\0302 \001(\002R\npktlenMean\022" +
      "\035\n\npktlen_std\0303 \001(\002R\tpktlenStd\022\035\n\npktlen" +
      "_min\0304 \001(\002R\tpktlenMin\022\035\n\npktlen_max\0305 \001(" +
      "\002R\tpktlenMax\022$\n\016active_mean_ms\030< \001(\002R\014ac" +
      "tiveMeanMs\022 \n\014idle_mean_ms\030= \001(\002R\nidleMe" +
      "anMs\022\024\n\005extra\030d \003(\002R\005extra\022\031\n\010tag_keys\030e" +
      " \003(\tR\007tagKeys\022\035\n\ntag_values\030f \003(\tR\ttagVa" +
      "lues\"\247\004\n\014FeatureSeqV1\022/\n\006header\030\001 \001(\0132\027." +
      "traffic.v1.EventHeaderR\006header\022!\n\014commun" +
      "ity_id\030\002 \001(\tR\013communityId\022\035\n\nsession_id\030" +
      "\003 \001(\tR\tsessionId\022\033\n\twindow_id\030\004 \001(\tR\010win" +
      "dowId\022\031\n\010ts_start\030\n \001(\003R\007tsStart\022\025\n\006ts_e" +
      "nd\030\013 \001(\003R\005tsEnd\022\035\n\npktlen_seq\030\024 \003(\rR\tpkt" +
      "lenSeq\022\027\n\007dir_seq\030\025 \003(\005R\006dirSeq\022\027\n\007iat_s" +
      "eq\030\026 \003(\002R\006iatSeq\022&\n\017pktlen_seq_hash\030\036 \001(" +
      "\tR\rpktlenSeqHash\022 \n\014iat_seq_hash\030\037 \001(\tR\n" +
      "iatSeqHash\022,\n\022wavelet_energy_fwd\030( \001(\002R\020" +
      "waveletEnergyFwd\022,\n\022wavelet_energy_bwd\030)" +
      " \001(\002R\020waveletEnergyBwd\022.\n\023wavelet_entrop" +
      "y_fwd\030* \001(\002R\021waveletEntropyFwd\022.\n\023wavele" +
      "t_entropy_bwd\030+ \001(\002R\021waveletEntropyBwdBy" +
      "\n\024com.traffic.proto.v1P\001Z_github.com/114" +
      "4160159/traffic-analysis-platform/go/con" +
      "trol-plane/pkg/proto/traffic/v1;trafficv" +
      "1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.traffic.proto.v1.Common.getDescriptor(),
        });
    internal_static_traffic_v1_FeatureStatV1_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_traffic_v1_FeatureStatV1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_traffic_v1_FeatureStatV1_descriptor,
        new java.lang.String[] { "Header", "CommunityId", "ObjectType", "ObjectId", "Pps", "Bps", "UpDownRatio", "BytesFwdRatio", "SynRatio", "FinRatio", "RstRatio", "AckRatio", "PshRatio", "IatMeanMs", "IatStdMs", "IatMinMs", "IatMaxMs", "PktlenMean", "PktlenStd", "PktlenMin", "PktlenMax", "ActiveMeanMs", "IdleMeanMs", "Extra", "TagKeys", "TagValues", });
    internal_static_traffic_v1_FeatureSeqV1_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_traffic_v1_FeatureSeqV1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_traffic_v1_FeatureSeqV1_descriptor,
        new java.lang.String[] { "Header", "CommunityId", "SessionId", "WindowId", "TsStart", "TsEnd", "PktlenSeq", "DirSeq", "IatSeq", "PktlenSeqHash", "IatSeqHash", "WaveletEnergyFwd", "WaveletEnergyBwd", "WaveletEntropyFwd", "WaveletEntropyBwd", });
    descriptor.resolveAllFeaturesImmutable();
    com.traffic.proto.v1.Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
