// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: traffic/v1/feature.proto
// Protobuf Java Version: 4.33.2

package com.traffic.proto.v1;

/**
 * <pre>
 * FeatureStatV1 L1 统计特征
 * 由 Flink Feature Job 计算生成，用于规则检测和模型推理
 * </pre>
 *
 * Protobuf type {@code traffic.v1.FeatureStatV1}
 */
@com.google.protobuf.Generated
public final class FeatureStatV1 extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:traffic.v1.FeatureStatV1)
    FeatureStatV1OrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 2,
      /* suffix= */ "",
      "FeatureStatV1");
  }
  // Use FeatureStatV1.newBuilder() to construct.
  private FeatureStatV1(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private FeatureStatV1() {
    communityId_ = "";
    objectType_ = "";
    objectId_ = "";
    extra_ = emptyFloatList();
    tagKeys_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    tagValues_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.traffic.proto.v1.Feature.internal_static_traffic_v1_FeatureStatV1_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.traffic.proto.v1.Feature.internal_static_traffic_v1_FeatureStatV1_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.traffic.proto.v1.FeatureStatV1.class, com.traffic.proto.v1.FeatureStatV1.Builder.class);
  }

  private int bitField0_;
  public static final int HEADER_FIELD_NUMBER = 1;
  private com.traffic.proto.v1.EventHeader header_;
  /**
   * <code>.traffic.v1.EventHeader header = 1 [json_name = "header"];</code>
   * @return Whether the header field is set.
   */
  @java.lang.Override
  public boolean hasHeader() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.traffic.v1.EventHeader header = 1 [json_name = "header"];</code>
   * @return The header.
   */
  @java.lang.Override
  public com.traffic.proto.v1.EventHeader getHeader() {
    return header_ == null ? com.traffic.proto.v1.EventHeader.getDefaultInstance() : header_;
  }
  /**
   * <code>.traffic.v1.EventHeader header = 1 [json_name = "header"];</code>
   */
  @java.lang.Override
  public com.traffic.proto.v1.EventHeaderOrBuilder getHeaderOrBuilder() {
    return header_ == null ? com.traffic.proto.v1.EventHeader.getDefaultInstance() : header_;
  }

  public static final int COMMUNITY_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object communityId_ = "";
  /**
   * <pre>
   * 关联标识
   * </pre>
   *
   * <code>string community_id = 2 [json_name = "communityId"];</code>
   * @return The communityId.
   */
  @java.lang.Override
  public java.lang.String getCommunityId() {
    java.lang.Object ref = communityId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      communityId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 关联标识
   * </pre>
   *
   * <code>string community_id = 2 [json_name = "communityId"];</code>
   * @return The bytes for communityId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCommunityIdBytes() {
    java.lang.Object ref = communityId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      communityId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OBJECT_TYPE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object objectType_ = "";
  /**
   * <pre>
   * "flow" 或 "session"
   * </pre>
   *
   * <code>string object_type = 3 [json_name = "objectType"];</code>
   * @return The objectType.
   */
  @java.lang.Override
  public java.lang.String getObjectType() {
    java.lang.Object ref = objectType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      objectType_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * "flow" 或 "session"
   * </pre>
   *
   * <code>string object_type = 3 [json_name = "objectType"];</code>
   * @return The bytes for objectType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getObjectTypeBytes() {
    java.lang.Object ref = objectType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      objectType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OBJECT_ID_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object objectId_ = "";
  /**
   * <pre>
   * flow_id 或 session_id
   * </pre>
   *
   * <code>string object_id = 4 [json_name = "objectId"];</code>
   * @return The objectId.
   */
  @java.lang.Override
  public java.lang.String getObjectId() {
    java.lang.Object ref = objectId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      objectId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * flow_id 或 session_id
   * </pre>
   *
   * <code>string object_id = 4 [json_name = "objectId"];</code>
   * @return The bytes for objectId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getObjectIdBytes() {
    java.lang.Object ref = objectId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      objectId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PPS_FIELD_NUMBER = 10;
  private float pps_ = 0F;
  /**
   * <pre>
   * ==================== 速率特征 ====================
   * </pre>
   *
   * <code>float pps = 10 [json_name = "pps"];</code>
   * @return The pps.
   */
  @java.lang.Override
  public float getPps() {
    return pps_;
  }

  public static final int BPS_FIELD_NUMBER = 11;
  private float bps_ = 0F;
  /**
   * <pre>
   * 比特率 (bits per second)
   * </pre>
   *
   * <code>float bps = 11 [json_name = "bps"];</code>
   * @return The bps.
   */
  @java.lang.Override
  public float getBps() {
    return bps_;
  }

  public static final int UP_DOWN_RATIO_FIELD_NUMBER = 20;
  private float upDownRatio_ = 0F;
  /**
   * <pre>
   * ==================== 方向特征 ====================
   * </pre>
   *
   * <code>float up_down_ratio = 20 [json_name = "upDownRatio"];</code>
   * @return The upDownRatio.
   */
  @java.lang.Override
  public float getUpDownRatio() {
    return upDownRatio_;
  }

  public static final int BYTES_FWD_RATIO_FIELD_NUMBER = 21;
  private float bytesFwdRatio_ = 0F;
  /**
   * <pre>
   * 正向字节占比
   * </pre>
   *
   * <code>float bytes_fwd_ratio = 21 [json_name = "bytesFwdRatio"];</code>
   * @return The bytesFwdRatio.
   */
  @java.lang.Override
  public float getBytesFwdRatio() {
    return bytesFwdRatio_;
  }

  public static final int SYN_RATIO_FIELD_NUMBER = 30;
  private float synRatio_ = 0F;
  /**
   * <pre>
   * ==================== TCP 标志特征 ====================
   * </pre>
   *
   * <code>float syn_ratio = 30 [json_name = "synRatio"];</code>
   * @return The synRatio.
   */
  @java.lang.Override
  public float getSynRatio() {
    return synRatio_;
  }

  public static final int FIN_RATIO_FIELD_NUMBER = 31;
  private float finRatio_ = 0F;
  /**
   * <pre>
   * FIN 包占比
   * </pre>
   *
   * <code>float fin_ratio = 31 [json_name = "finRatio"];</code>
   * @return The finRatio.
   */
  @java.lang.Override
  public float getFinRatio() {
    return finRatio_;
  }

  public static final int RST_RATIO_FIELD_NUMBER = 32;
  private float rstRatio_ = 0F;
  /**
   * <pre>
   * RST 包占比
   * </pre>
   *
   * <code>float rst_ratio = 32 [json_name = "rstRatio"];</code>
   * @return The rstRatio.
   */
  @java.lang.Override
  public float getRstRatio() {
    return rstRatio_;
  }

  public static final int ACK_RATIO_FIELD_NUMBER = 33;
  private float ackRatio_ = 0F;
  /**
   * <pre>
   * ACK 包占比
   * </pre>
   *
   * <code>float ack_ratio = 33 [json_name = "ackRatio"];</code>
   * @return The ackRatio.
   */
  @java.lang.Override
  public float getAckRatio() {
    return ackRatio_;
  }

  public static final int PSH_RATIO_FIELD_NUMBER = 34;
  private float pshRatio_ = 0F;
  /**
   * <pre>
   * PSH 包占比
   * </pre>
   *
   * <code>float psh_ratio = 34 [json_name = "pshRatio"];</code>
   * @return The pshRatio.
   */
  @java.lang.Override
  public float getPshRatio() {
    return pshRatio_;
  }

  public static final int IAT_MEAN_MS_FIELD_NUMBER = 40;
  private float iatMeanMs_ = 0F;
  /**
   * <pre>
   * ==================== 时间特征 ====================
   * </pre>
   *
   * <code>float iat_mean_ms = 40 [json_name = "iatMeanMs"];</code>
   * @return The iatMeanMs.
   */
  @java.lang.Override
  public float getIatMeanMs() {
    return iatMeanMs_;
  }

  public static final int IAT_STD_MS_FIELD_NUMBER = 41;
  private float iatStdMs_ = 0F;
  /**
   * <pre>
   * 包间隔标准差
   * </pre>
   *
   * <code>float iat_std_ms = 41 [json_name = "iatStdMs"];</code>
   * @return The iatStdMs.
   */
  @java.lang.Override
  public float getIatStdMs() {
    return iatStdMs_;
  }

  public static final int IAT_MIN_MS_FIELD_NUMBER = 42;
  private float iatMinMs_ = 0F;
  /**
   * <pre>
   * 最小包间隔
   * </pre>
   *
   * <code>float iat_min_ms = 42 [json_name = "iatMinMs"];</code>
   * @return The iatMinMs.
   */
  @java.lang.Override
  public float getIatMinMs() {
    return iatMinMs_;
  }

  public static final int IAT_MAX_MS_FIELD_NUMBER = 43;
  private float iatMaxMs_ = 0F;
  /**
   * <pre>
   * 最大包间隔
   * </pre>
   *
   * <code>float iat_max_ms = 43 [json_name = "iatMaxMs"];</code>
   * @return The iatMaxMs.
   */
  @java.lang.Override
  public float getIatMaxMs() {
    return iatMaxMs_;
  }

  public static final int PKTLEN_MEAN_FIELD_NUMBER = 50;
  private float pktlenMean_ = 0F;
  /**
   * <pre>
   * ==================== 包长特征 ====================
   * </pre>
   *
   * <code>float pktlen_mean = 50 [json_name = "pktlenMean"];</code>
   * @return The pktlenMean.
   */
  @java.lang.Override
  public float getPktlenMean() {
    return pktlenMean_;
  }

  public static final int PKTLEN_STD_FIELD_NUMBER = 51;
  private float pktlenStd_ = 0F;
  /**
   * <pre>
   * 包长标准差
   * </pre>
   *
   * <code>float pktlen_std = 51 [json_name = "pktlenStd"];</code>
   * @return The pktlenStd.
   */
  @java.lang.Override
  public float getPktlenStd() {
    return pktlenStd_;
  }

  public static final int PKTLEN_MIN_FIELD_NUMBER = 52;
  private float pktlenMin_ = 0F;
  /**
   * <pre>
   * 最小包长
   * </pre>
   *
   * <code>float pktlen_min = 52 [json_name = "pktlenMin"];</code>
   * @return The pktlenMin.
   */
  @java.lang.Override
  public float getPktlenMin() {
    return pktlenMin_;
  }

  public static final int PKTLEN_MAX_FIELD_NUMBER = 53;
  private float pktlenMax_ = 0F;
  /**
   * <pre>
   * 最大包长
   * </pre>
   *
   * <code>float pktlen_max = 53 [json_name = "pktlenMax"];</code>
   * @return The pktlenMax.
   */
  @java.lang.Override
  public float getPktlenMax() {
    return pktlenMax_;
  }

  public static final int ACTIVE_MEAN_MS_FIELD_NUMBER = 60;
  private float activeMeanMs_ = 0F;
  /**
   * <pre>
   * ==================== 活跃/空闲特征 ====================
   * </pre>
   *
   * <code>float active_mean_ms = 60 [json_name = "activeMeanMs"];</code>
   * @return The activeMeanMs.
   */
  @java.lang.Override
  public float getActiveMeanMs() {
    return activeMeanMs_;
  }

  public static final int IDLE_MEAN_MS_FIELD_NUMBER = 61;
  private float idleMeanMs_ = 0F;
  /**
   * <pre>
   * 平均空闲时间
   * </pre>
   *
   * <code>float idle_mean_ms = 61 [json_name = "idleMeanMs"];</code>
   * @return The idleMeanMs.
   */
  @java.lang.Override
  public float getIdleMeanMs() {
    return idleMeanMs_;
  }

  public static final int EXTRA_FIELD_NUMBER = 100;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.FloatList extra_ =
      emptyFloatList();
  /**
   * <pre>
   * ==================== 扩展特征 (用于模型) ====================
   * </pre>
   *
   * <code>repeated float extra = 100 [json_name = "extra"];</code>
   * @return A list containing the extra.
   */
  @java.lang.Override
  public java.util.List<java.lang.Float>
      getExtraList() {
    return extra_;
  }
  /**
   * <pre>
   * ==================== 扩展特征 (用于模型) ====================
   * </pre>
   *
   * <code>repeated float extra = 100 [json_name = "extra"];</code>
   * @return The count of extra.
   */
  public int getExtraCount() {
    return extra_.size();
  }
  /**
   * <pre>
   * ==================== 扩展特征 (用于模型) ====================
   * </pre>
   *
   * <code>repeated float extra = 100 [json_name = "extra"];</code>
   * @param index The index of the element to return.
   * @return The extra at the given index.
   */
  public float getExtra(int index) {
    return extra_.getFloat(index);
  }
  private int extraMemoizedSerializedSize = -1;

  public static final int TAG_KEYS_FIELD_NUMBER = 101;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList tagKeys_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <pre>
   * 标签键列表
   * </pre>
   *
   * <code>repeated string tag_keys = 101 [json_name = "tagKeys"];</code>
   * @return A list containing the tagKeys.
   */
  public com.google.protobuf.ProtocolStringList
      getTagKeysList() {
    return tagKeys_;
  }
  /**
   * <pre>
   * 标签键列表
   * </pre>
   *
   * <code>repeated string tag_keys = 101 [json_name = "tagKeys"];</code>
   * @return The count of tagKeys.
   */
  public int getTagKeysCount() {
    return tagKeys_.size();
  }
  /**
   * <pre>
   * 标签键列表
   * </pre>
   *
   * <code>repeated string tag_keys = 101 [json_name = "tagKeys"];</code>
   * @param index The index of the element to return.
   * @return The tagKeys at the given index.
   */
  public java.lang.String getTagKeys(int index) {
    return tagKeys_.get(index);
  }
  /**
   * <pre>
   * 标签键列表
   * </pre>
   *
   * <code>repeated string tag_keys = 101 [json_name = "tagKeys"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the tagKeys at the given index.
   */
  public com.google.protobuf.ByteString
      getTagKeysBytes(int index) {
    return tagKeys_.getByteString(index);
  }

  public static final int TAG_VALUES_FIELD_NUMBER = 102;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList tagValues_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <pre>
   * 标签值列表 (与 tag_keys 一一对应)
   * </pre>
   *
   * <code>repeated string tag_values = 102 [json_name = "tagValues"];</code>
   * @return A list containing the tagValues.
   */
  public com.google.protobuf.ProtocolStringList
      getTagValuesList() {
    return tagValues_;
  }
  /**
   * <pre>
   * 标签值列表 (与 tag_keys 一一对应)
   * </pre>
   *
   * <code>repeated string tag_values = 102 [json_name = "tagValues"];</code>
   * @return The count of tagValues.
   */
  public int getTagValuesCount() {
    return tagValues_.size();
  }
  /**
   * <pre>
   * 标签值列表 (与 tag_keys 一一对应)
   * </pre>
   *
   * <code>repeated string tag_values = 102 [json_name = "tagValues"];</code>
   * @param index The index of the element to return.
   * @return The tagValues at the given index.
   */
  public java.lang.String getTagValues(int index) {
    return tagValues_.get(index);
  }
  /**
   * <pre>
   * 标签值列表 (与 tag_keys 一一对应)
   * </pre>
   *
   * <code>repeated string tag_values = 102 [json_name = "tagValues"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the tagValues at the given index.
   */
  public com.google.protobuf.ByteString
      getTagValuesBytes(int index) {
    return tagValues_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getHeader());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(communityId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, communityId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(objectType_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, objectType_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(objectId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, objectId_);
    }
    if (java.lang.Float.floatToRawIntBits(pps_) != 0) {
      output.writeFloat(10, pps_);
    }
    if (java.lang.Float.floatToRawIntBits(bps_) != 0) {
      output.writeFloat(11, bps_);
    }
    if (java.lang.Float.floatToRawIntBits(upDownRatio_) != 0) {
      output.writeFloat(20, upDownRatio_);
    }
    if (java.lang.Float.floatToRawIntBits(bytesFwdRatio_) != 0) {
      output.writeFloat(21, bytesFwdRatio_);
    }
    if (java.lang.Float.floatToRawIntBits(synRatio_) != 0) {
      output.writeFloat(30, synRatio_);
    }
    if (java.lang.Float.floatToRawIntBits(finRatio_) != 0) {
      output.writeFloat(31, finRatio_);
    }
    if (java.lang.Float.floatToRawIntBits(rstRatio_) != 0) {
      output.writeFloat(32, rstRatio_);
    }
    if (java.lang.Float.floatToRawIntBits(ackRatio_) != 0) {
      output.writeFloat(33, ackRatio_);
    }
    if (java.lang.Float.floatToRawIntBits(pshRatio_) != 0) {
      output.writeFloat(34, pshRatio_);
    }
    if (java.lang.Float.floatToRawIntBits(iatMeanMs_) != 0) {
      output.writeFloat(40, iatMeanMs_);
    }
    if (java.lang.Float.floatToRawIntBits(iatStdMs_) != 0) {
      output.writeFloat(41, iatStdMs_);
    }
    if (java.lang.Float.floatToRawIntBits(iatMinMs_) != 0) {
      output.writeFloat(42, iatMinMs_);
    }
    if (java.lang.Float.floatToRawIntBits(iatMaxMs_) != 0) {
      output.writeFloat(43, iatMaxMs_);
    }
    if (java.lang.Float.floatToRawIntBits(pktlenMean_) != 0) {
      output.writeFloat(50, pktlenMean_);
    }
    if (java.lang.Float.floatToRawIntBits(pktlenStd_) != 0) {
      output.writeFloat(51, pktlenStd_);
    }
    if (java.lang.Float.floatToRawIntBits(pktlenMin_) != 0) {
      output.writeFloat(52, pktlenMin_);
    }
    if (java.lang.Float.floatToRawIntBits(pktlenMax_) != 0) {
      output.writeFloat(53, pktlenMax_);
    }
    if (java.lang.Float.floatToRawIntBits(activeMeanMs_) != 0) {
      output.writeFloat(60, activeMeanMs_);
    }
    if (java.lang.Float.floatToRawIntBits(idleMeanMs_) != 0) {
      output.writeFloat(61, idleMeanMs_);
    }
    if (getExtraList().size() > 0) {
      output.writeUInt32NoTag(802);
      output.writeUInt32NoTag(extraMemoizedSerializedSize);
    }
    for (int i = 0; i < extra_.size(); i++) {
      output.writeFloatNoTag(extra_.getFloat(i));
    }
    for (int i = 0; i < tagKeys_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 101, tagKeys_.getRaw(i));
    }
    for (int i = 0; i < tagValues_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 102, tagValues_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getHeader());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(communityId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, communityId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(objectType_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, objectType_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(objectId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, objectId_);
    }
    if (java.lang.Float.floatToRawIntBits(pps_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(10, pps_);
    }
    if (java.lang.Float.floatToRawIntBits(bps_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(11, bps_);
    }
    if (java.lang.Float.floatToRawIntBits(upDownRatio_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(20, upDownRatio_);
    }
    if (java.lang.Float.floatToRawIntBits(bytesFwdRatio_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(21, bytesFwdRatio_);
    }
    if (java.lang.Float.floatToRawIntBits(synRatio_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(30, synRatio_);
    }
    if (java.lang.Float.floatToRawIntBits(finRatio_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(31, finRatio_);
    }
    if (java.lang.Float.floatToRawIntBits(rstRatio_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(32, rstRatio_);
    }
    if (java.lang.Float.floatToRawIntBits(ackRatio_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(33, ackRatio_);
    }
    if (java.lang.Float.floatToRawIntBits(pshRatio_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(34, pshRatio_);
    }
    if (java.lang.Float.floatToRawIntBits(iatMeanMs_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(40, iatMeanMs_);
    }
    if (java.lang.Float.floatToRawIntBits(iatStdMs_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(41, iatStdMs_);
    }
    if (java.lang.Float.floatToRawIntBits(iatMinMs_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(42, iatMinMs_);
    }
    if (java.lang.Float.floatToRawIntBits(iatMaxMs_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(43, iatMaxMs_);
    }
    if (java.lang.Float.floatToRawIntBits(pktlenMean_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(50, pktlenMean_);
    }
    if (java.lang.Float.floatToRawIntBits(pktlenStd_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(51, pktlenStd_);
    }
    if (java.lang.Float.floatToRawIntBits(pktlenMin_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(52, pktlenMin_);
    }
    if (java.lang.Float.floatToRawIntBits(pktlenMax_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(53, pktlenMax_);
    }
    if (java.lang.Float.floatToRawIntBits(activeMeanMs_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(60, activeMeanMs_);
    }
    if (java.lang.Float.floatToRawIntBits(idleMeanMs_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(61, idleMeanMs_);
    }
    {
      int dataSize = 0;
      dataSize = 4 * getExtraList().size();
      size += dataSize;
      if (!getExtraList().isEmpty()) {
        size += 2;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      extraMemoizedSerializedSize = dataSize;
    }
    {
      int dataSize = 0;
      for (int i = 0; i < tagKeys_.size(); i++) {
        dataSize += computeStringSizeNoTag(tagKeys_.getRaw(i));
      }
      size += dataSize;
      size += 2 * getTagKeysList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < tagValues_.size(); i++) {
        dataSize += computeStringSizeNoTag(tagValues_.getRaw(i));
      }
      size += dataSize;
      size += 2 * getTagValuesList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.traffic.proto.v1.FeatureStatV1)) {
      return super.equals(obj);
    }
    com.traffic.proto.v1.FeatureStatV1 other = (com.traffic.proto.v1.FeatureStatV1) obj;

    if (hasHeader() != other.hasHeader()) return false;
    if (hasHeader()) {
      if (!getHeader()
          .equals(other.getHeader())) return false;
    }
    if (!getCommunityId()
        .equals(other.getCommunityId())) return false;
    if (!getObjectType()
        .equals(other.getObjectType())) return false;
    if (!getObjectId()
        .equals(other.getObjectId())) return false;
    if (java.lang.Float.floatToIntBits(getPps())
        != java.lang.Float.floatToIntBits(
            other.getPps())) return false;
    if (java.lang.Float.floatToIntBits(getBps())
        != java.lang.Float.floatToIntBits(
            other.getBps())) return false;
    if (java.lang.Float.floatToIntBits(getUpDownRatio())
        != java.lang.Float.floatToIntBits(
            other.getUpDownRatio())) return false;
    if (java.lang.Float.floatToIntBits(getBytesFwdRatio())
        != java.lang.Float.floatToIntBits(
            other.getBytesFwdRatio())) return false;
    if (java.lang.Float.floatToIntBits(getSynRatio())
        != java.lang.Float.floatToIntBits(
            other.getSynRatio())) return false;
    if (java.lang.Float.floatToIntBits(getFinRatio())
        != java.lang.Float.floatToIntBits(
            other.getFinRatio())) return false;
    if (java.lang.Float.floatToIntBits(getRstRatio())
        != java.lang.Float.floatToIntBits(
            other.getRstRatio())) return false;
    if (java.lang.Float.floatToIntBits(getAckRatio())
        != java.lang.Float.floatToIntBits(
            other.getAckRatio())) return false;
    if (java.lang.Float.floatToIntBits(getPshRatio())
        != java.lang.Float.floatToIntBits(
            other.getPshRatio())) return false;
    if (java.lang.Float.floatToIntBits(getIatMeanMs())
        != java.lang.Float.floatToIntBits(
            other.getIatMeanMs())) return false;
    if (java.lang.Float.floatToIntBits(getIatStdMs())
        != java.lang.Float.floatToIntBits(
            other.getIatStdMs())) return false;
    if (java.lang.Float.floatToIntBits(getIatMinMs())
        != java.lang.Float.floatToIntBits(
            other.getIatMinMs())) return false;
    if (java.lang.Float.floatToIntBits(getIatMaxMs())
        != java.lang.Float.floatToIntBits(
            other.getIatMaxMs())) return false;
    if (java.lang.Float.floatToIntBits(getPktlenMean())
        != java.lang.Float.floatToIntBits(
            other.getPktlenMean())) return false;
    if (java.lang.Float.floatToIntBits(getPktlenStd())
        != java.lang.Float.floatToIntBits(
            other.getPktlenStd())) return false;
    if (java.lang.Float.floatToIntBits(getPktlenMin())
        != java.lang.Float.floatToIntBits(
            other.getPktlenMin())) return false;
    if (java.lang.Float.floatToIntBits(getPktlenMax())
        != java.lang.Float.floatToIntBits(
            other.getPktlenMax())) return false;
    if (java.lang.Float.floatToIntBits(getActiveMeanMs())
        != java.lang.Float.floatToIntBits(
            other.getActiveMeanMs())) return false;
    if (java.lang.Float.floatToIntBits(getIdleMeanMs())
        != java.lang.Float.floatToIntBits(
            other.getIdleMeanMs())) return false;
    if (!getExtraList()
        .equals(other.getExtraList())) return false;
    if (!getTagKeysList()
        .equals(other.getTagKeysList())) return false;
    if (!getTagValuesList()
        .equals(other.getTagValuesList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasHeader()) {
      hash = (37 * hash) + HEADER_FIELD_NUMBER;
      hash = (53 * hash) + getHeader().hashCode();
    }
    hash = (37 * hash) + COMMUNITY_ID_FIELD_NUMBER;
    hash = (53 * hash) + getCommunityId().hashCode();
    hash = (37 * hash) + OBJECT_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getObjectType().hashCode();
    hash = (37 * hash) + OBJECT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getObjectId().hashCode();
    hash = (37 * hash) + PPS_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getPps());
    hash = (37 * hash) + BPS_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getBps());
    hash = (37 * hash) + UP_DOWN_RATIO_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getUpDownRatio());
    hash = (37 * hash) + BYTES_FWD_RATIO_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getBytesFwdRatio());
    hash = (37 * hash) + SYN_RATIO_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getSynRatio());
    hash = (37 * hash) + FIN_RATIO_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getFinRatio());
    hash = (37 * hash) + RST_RATIO_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getRstRatio());
    hash = (37 * hash) + ACK_RATIO_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getAckRatio());
    hash = (37 * hash) + PSH_RATIO_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getPshRatio());
    hash = (37 * hash) + IAT_MEAN_MS_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getIatMeanMs());
    hash = (37 * hash) + IAT_STD_MS_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getIatStdMs());
    hash = (37 * hash) + IAT_MIN_MS_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getIatMinMs());
    hash = (37 * hash) + IAT_MAX_MS_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getIatMaxMs());
    hash = (37 * hash) + PKTLEN_MEAN_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getPktlenMean());
    hash = (37 * hash) + PKTLEN_STD_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getPktlenStd());
    hash = (37 * hash) + PKTLEN_MIN_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getPktlenMin());
    hash = (37 * hash) + PKTLEN_MAX_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getPktlenMax());
    hash = (37 * hash) + ACTIVE_MEAN_MS_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getActiveMeanMs());
    hash = (37 * hash) + IDLE_MEAN_MS_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getIdleMeanMs());
    if (getExtraCount() > 0) {
      hash = (37 * hash) + EXTRA_FIELD_NUMBER;
      hash = (53 * hash) + getExtraList().hashCode();
    }
    if (getTagKeysCount() > 0) {
      hash = (37 * hash) + TAG_KEYS_FIELD_NUMBER;
      hash = (53 * hash) + getTagKeysList().hashCode();
    }
    if (getTagValuesCount() > 0) {
      hash = (37 * hash) + TAG_VALUES_FIELD_NUMBER;
      hash = (53 * hash) + getTagValuesList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.traffic.proto.v1.FeatureStatV1 parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.traffic.proto.v1.FeatureStatV1 parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.traffic.proto.v1.FeatureStatV1 parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.traffic.proto.v1.FeatureStatV1 parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.traffic.proto.v1.FeatureStatV1 parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.traffic.proto.v1.FeatureStatV1 parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.traffic.proto.v1.FeatureStatV1 parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.traffic.proto.v1.FeatureStatV1 parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.traffic.proto.v1.FeatureStatV1 parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.traffic.proto.v1.FeatureStatV1 parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.traffic.proto.v1.FeatureStatV1 parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.traffic.proto.v1.FeatureStatV1 parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.traffic.proto.v1.FeatureStatV1 prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * FeatureStatV1 L1 统计特征
   * 由 Flink Feature Job 计算生成，用于规则检测和模型推理
   * </pre>
   *
   * Protobuf type {@code traffic.v1.FeatureStatV1}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:traffic.v1.FeatureStatV1)
      com.traffic.proto.v1.FeatureStatV1OrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.traffic.proto.v1.Feature.internal_static_traffic_v1_FeatureStatV1_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.traffic.proto.v1.Feature.internal_static_traffic_v1_FeatureStatV1_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.traffic.proto.v1.FeatureStatV1.class, com.traffic.proto.v1.FeatureStatV1.Builder.class);
    }

    // Construct using com.traffic.proto.v1.FeatureStatV1.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetHeaderFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      header_ = null;
      if (headerBuilder_ != null) {
        headerBuilder_.dispose();
        headerBuilder_ = null;
      }
      communityId_ = "";
      objectType_ = "";
      objectId_ = "";
      pps_ = 0F;
      bps_ = 0F;
      upDownRatio_ = 0F;
      bytesFwdRatio_ = 0F;
      synRatio_ = 0F;
      finRatio_ = 0F;
      rstRatio_ = 0F;
      ackRatio_ = 0F;
      pshRatio_ = 0F;
      iatMeanMs_ = 0F;
      iatStdMs_ = 0F;
      iatMinMs_ = 0F;
      iatMaxMs_ = 0F;
      pktlenMean_ = 0F;
      pktlenStd_ = 0F;
      pktlenMin_ = 0F;
      pktlenMax_ = 0F;
      activeMeanMs_ = 0F;
      idleMeanMs_ = 0F;
      extra_ = emptyFloatList();
      tagKeys_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      tagValues_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.traffic.proto.v1.Feature.internal_static_traffic_v1_FeatureStatV1_descriptor;
    }

    @java.lang.Override
    public com.traffic.proto.v1.FeatureStatV1 getDefaultInstanceForType() {
      return com.traffic.proto.v1.FeatureStatV1.getDefaultInstance();
    }

    @java.lang.Override
    public com.traffic.proto.v1.FeatureStatV1 build() {
      com.traffic.proto.v1.FeatureStatV1 result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.traffic.proto.v1.FeatureStatV1 buildPartial() {
      com.traffic.proto.v1.FeatureStatV1 result = new com.traffic.proto.v1.FeatureStatV1(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.traffic.proto.v1.FeatureStatV1 result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.header_ = headerBuilder_ == null
            ? header_
            : headerBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.communityId_ = communityId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.objectType_ = objectType_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.objectId_ = objectId_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.pps_ = pps_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.bps_ = bps_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.upDownRatio_ = upDownRatio_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.bytesFwdRatio_ = bytesFwdRatio_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.synRatio_ = synRatio_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.finRatio_ = finRatio_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.rstRatio_ = rstRatio_;
      }
      if (((from_bitField0_ & 0x00000800) != 0)) {
        result.ackRatio_ = ackRatio_;
      }
      if (((from_bitField0_ & 0x00001000) != 0)) {
        result.pshRatio_ = pshRatio_;
      }
      if (((from_bitField0_ & 0x00002000) != 0)) {
        result.iatMeanMs_ = iatMeanMs_;
      }
      if (((from_bitField0_ & 0x00004000) != 0)) {
        result.iatStdMs_ = iatStdMs_;
      }
      if (((from_bitField0_ & 0x00008000) != 0)) {
        result.iatMinMs_ = iatMinMs_;
      }
      if (((from_bitField0_ & 0x00010000) != 0)) {
        result.iatMaxMs_ = iatMaxMs_;
      }
      if (((from_bitField0_ & 0x00020000) != 0)) {
        result.pktlenMean_ = pktlenMean_;
      }
      if (((from_bitField0_ & 0x00040000) != 0)) {
        result.pktlenStd_ = pktlenStd_;
      }
      if (((from_bitField0_ & 0x00080000) != 0)) {
        result.pktlenMin_ = pktlenMin_;
      }
      if (((from_bitField0_ & 0x00100000) != 0)) {
        result.pktlenMax_ = pktlenMax_;
      }
      if (((from_bitField0_ & 0x00200000) != 0)) {
        result.activeMeanMs_ = activeMeanMs_;
      }
      if (((from_bitField0_ & 0x00400000) != 0)) {
        result.idleMeanMs_ = idleMeanMs_;
      }
      if (((from_bitField0_ & 0x00800000) != 0)) {
        extra_.makeImmutable();
        result.extra_ = extra_;
      }
      if (((from_bitField0_ & 0x01000000) != 0)) {
        tagKeys_.makeImmutable();
        result.tagKeys_ = tagKeys_;
      }
      if (((from_bitField0_ & 0x02000000) != 0)) {
        tagValues_.makeImmutable();
        result.tagValues_ = tagValues_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.traffic.proto.v1.FeatureStatV1) {
        return mergeFrom((com.traffic.proto.v1.FeatureStatV1)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.traffic.proto.v1.FeatureStatV1 other) {
      if (other == com.traffic.proto.v1.FeatureStatV1.getDefaultInstance()) return this;
      if (other.hasHeader()) {
        mergeHeader(other.getHeader());
      }
      if (!other.getCommunityId().isEmpty()) {
        communityId_ = other.communityId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getObjectType().isEmpty()) {
        objectType_ = other.objectType_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getObjectId().isEmpty()) {
        objectId_ = other.objectId_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (java.lang.Float.floatToRawIntBits(other.getPps()) != 0) {
        setPps(other.getPps());
      }
      if (java.lang.Float.floatToRawIntBits(other.getBps()) != 0) {
        setBps(other.getBps());
      }
      if (java.lang.Float.floatToRawIntBits(other.getUpDownRatio()) != 0) {
        setUpDownRatio(other.getUpDownRatio());
      }
      if (java.lang.Float.floatToRawIntBits(other.getBytesFwdRatio()) != 0) {
        setBytesFwdRatio(other.getBytesFwdRatio());
      }
      if (java.lang.Float.floatToRawIntBits(other.getSynRatio()) != 0) {
        setSynRatio(other.getSynRatio());
      }
      if (java.lang.Float.floatToRawIntBits(other.getFinRatio()) != 0) {
        setFinRatio(other.getFinRatio());
      }
      if (java.lang.Float.floatToRawIntBits(other.getRstRatio()) != 0) {
        setRstRatio(other.getRstRatio());
      }
      if (java.lang.Float.floatToRawIntBits(other.getAckRatio()) != 0) {
        setAckRatio(other.getAckRatio());
      }
      if (java.lang.Float.floatToRawIntBits(other.getPshRatio()) != 0) {
        setPshRatio(other.getPshRatio());
      }
      if (java.lang.Float.floatToRawIntBits(other.getIatMeanMs()) != 0) {
        setIatMeanMs(other.getIatMeanMs());
      }
      if (java.lang.Float.floatToRawIntBits(other.getIatStdMs()) != 0) {
        setIatStdMs(other.getIatStdMs());
      }
      if (java.lang.Float.floatToRawIntBits(other.getIatMinMs()) != 0) {
        setIatMinMs(other.getIatMinMs());
      }
      if (java.lang.Float.floatToRawIntBits(other.getIatMaxMs()) != 0) {
        setIatMaxMs(other.getIatMaxMs());
      }
      if (java.lang.Float.floatToRawIntBits(other.getPktlenMean()) != 0) {
        setPktlenMean(other.getPktlenMean());
      }
      if (java.lang.Float.floatToRawIntBits(other.getPktlenStd()) != 0) {
        setPktlenStd(other.getPktlenStd());
      }
      if (java.lang.Float.floatToRawIntBits(other.getPktlenMin()) != 0) {
        setPktlenMin(other.getPktlenMin());
      }
      if (java.lang.Float.floatToRawIntBits(other.getPktlenMax()) != 0) {
        setPktlenMax(other.getPktlenMax());
      }
      if (java.lang.Float.floatToRawIntBits(other.getActiveMeanMs()) != 0) {
        setActiveMeanMs(other.getActiveMeanMs());
      }
      if (java.lang.Float.floatToRawIntBits(other.getIdleMeanMs()) != 0) {
        setIdleMeanMs(other.getIdleMeanMs());
      }
      if (!other.extra_.isEmpty()) {
        if (extra_.isEmpty()) {
          extra_ = other.extra_;
          extra_.makeImmutable();
          bitField0_ |= 0x00800000;
        } else {
          ensureExtraIsMutable();
          extra_.addAll(other.extra_);
        }
        onChanged();
      }
      if (!other.tagKeys_.isEmpty()) {
        if (tagKeys_.isEmpty()) {
          tagKeys_ = other.tagKeys_;
          bitField0_ |= 0x01000000;
        } else {
          ensureTagKeysIsMutable();
          tagKeys_.addAll(other.tagKeys_);
        }
        onChanged();
      }
      if (!other.tagValues_.isEmpty()) {
        if (tagValues_.isEmpty()) {
          tagValues_ = other.tagValues_;
          bitField0_ |= 0x02000000;
        } else {
          ensureTagValuesIsMutable();
          tagValues_.addAll(other.tagValues_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetHeaderFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              communityId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              objectType_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              objectId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 85: {
              pps_ = input.readFloat();
              bitField0_ |= 0x00000010;
              break;
            } // case 85
            case 93: {
              bps_ = input.readFloat();
              bitField0_ |= 0x00000020;
              break;
            } // case 93
            case 165: {
              upDownRatio_ = input.readFloat();
              bitField0_ |= 0x00000040;
              break;
            } // case 165
            case 173: {
              bytesFwdRatio_ = input.readFloat();
              bitField0_ |= 0x00000080;
              break;
            } // case 173
            case 245: {
              synRatio_ = input.readFloat();
              bitField0_ |= 0x00000100;
              break;
            } // case 245
            case 253: {
              finRatio_ = input.readFloat();
              bitField0_ |= 0x00000200;
              break;
            } // case 253
            case 261: {
              rstRatio_ = input.readFloat();
              bitField0_ |= 0x00000400;
              break;
            } // case 261
            case 269: {
              ackRatio_ = input.readFloat();
              bitField0_ |= 0x00000800;
              break;
            } // case 269
            case 277: {
              pshRatio_ = input.readFloat();
              bitField0_ |= 0x00001000;
              break;
            } // case 277
            case 325: {
              iatMeanMs_ = input.readFloat();
              bitField0_ |= 0x00002000;
              break;
            } // case 325
            case 333: {
              iatStdMs_ = input.readFloat();
              bitField0_ |= 0x00004000;
              break;
            } // case 333
            case 341: {
              iatMinMs_ = input.readFloat();
              bitField0_ |= 0x00008000;
              break;
            } // case 341
            case 349: {
              iatMaxMs_ = input.readFloat();
              bitField0_ |= 0x00010000;
              break;
            } // case 349
            case 405: {
              pktlenMean_ = input.readFloat();
              bitField0_ |= 0x00020000;
              break;
            } // case 405
            case 413: {
              pktlenStd_ = input.readFloat();
              bitField0_ |= 0x00040000;
              break;
            } // case 413
            case 421: {
              pktlenMin_ = input.readFloat();
              bitField0_ |= 0x00080000;
              break;
            } // case 421
            case 429: {
              pktlenMax_ = input.readFloat();
              bitField0_ |= 0x00100000;
              break;
            } // case 429
            case 485: {
              activeMeanMs_ = input.readFloat();
              bitField0_ |= 0x00200000;
              break;
            } // case 485
            case 493: {
              idleMeanMs_ = input.readFloat();
              bitField0_ |= 0x00400000;
              break;
            } // case 493
            case 805: {
              float v = input.readFloat();
              ensureExtraIsMutable();
              extra_.addFloat(v);
              break;
            } // case 805
            case 802: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              int alloc = length > 4096 ? 4096 : length;
              ensureExtraIsMutable(alloc / 4);
              while (input.getBytesUntilLimit() > 0) {
                extra_.addFloat(input.readFloat());
              }
              input.popLimit(limit);
              break;
            } // case 802
            case 810: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureTagKeysIsMutable();
              tagKeys_.add(s);
              break;
            } // case 810
            case 818: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureTagValuesIsMutable();
              tagValues_.add(s);
              break;
            } // case 818
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.traffic.proto.v1.EventHeader header_;
    private com.google.protobuf.SingleFieldBuilder<
        com.traffic.proto.v1.EventHeader, com.traffic.proto.v1.EventHeader.Builder, com.traffic.proto.v1.EventHeaderOrBuilder> headerBuilder_;
    /**
     * <code>.traffic.v1.EventHeader header = 1 [json_name = "header"];</code>
     * @return Whether the header field is set.
     */
    public boolean hasHeader() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.traffic.v1.EventHeader header = 1 [json_name = "header"];</code>
     * @return The header.
     */
    public com.traffic.proto.v1.EventHeader getHeader() {
      if (headerBuilder_ == null) {
        return header_ == null ? com.traffic.proto.v1.EventHeader.getDefaultInstance() : header_;
      } else {
        return headerBuilder_.getMessage();
      }
    }
    /**
     * <code>.traffic.v1.EventHeader header = 1 [json_name = "header"];</code>
     */
    public Builder setHeader(com.traffic.proto.v1.EventHeader value) {
      if (headerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        header_ = value;
      } else {
        headerBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.traffic.v1.EventHeader header = 1 [json_name = "header"];</code>
     */
    public Builder setHeader(
        com.traffic.proto.v1.EventHeader.Builder builderForValue) {
      if (headerBuilder_ == null) {
        header_ = builderForValue.build();
      } else {
        headerBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.traffic.v1.EventHeader header = 1 [json_name = "header"];</code>
     */
    public Builder mergeHeader(com.traffic.proto.v1.EventHeader value) {
      if (headerBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          header_ != null &&
          header_ != com.traffic.proto.v1.EventHeader.getDefaultInstance()) {
          getHeaderBuilder().mergeFrom(value);
        } else {
          header_ = value;
        }
      } else {
        headerBuilder_.mergeFrom(value);
      }
      if (header_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.traffic.v1.EventHeader header = 1 [json_name = "header"];</code>
     */
    public Builder clearHeader() {
      bitField0_ = (bitField0_ & ~0x00000001);
      header_ = null;
      if (headerBuilder_ != null) {
        headerBuilder_.dispose();
        headerBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.traffic.v1.EventHeader header = 1 [json_name = "header"];</code>
     */
    public com.traffic.proto.v1.EventHeader.Builder getHeaderBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return internalGetHeaderFieldBuilder().getBuilder();
    }
    /**
     * <code>.traffic.v1.EventHeader header = 1 [json_name = "header"];</code>
     */
    public com.traffic.proto.v1.EventHeaderOrBuilder getHeaderOrBuilder() {
      if (headerBuilder_ != null) {
        return headerBuilder_.getMessageOrBuilder();
      } else {
        return header_ == null ?
            com.traffic.proto.v1.EventHeader.getDefaultInstance() : header_;
      }
    }
    /**
     * <code>.traffic.v1.EventHeader header = 1 [json_name = "header"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.traffic.proto.v1.EventHeader, com.traffic.proto.v1.EventHeader.Builder, com.traffic.proto.v1.EventHeaderOrBuilder> 
        internalGetHeaderFieldBuilder() {
      if (headerBuilder_ == null) {
        headerBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.traffic.proto.v1.EventHeader, com.traffic.proto.v1.EventHeader.Builder, com.traffic.proto.v1.EventHeaderOrBuilder>(
                getHeader(),
                getParentForChildren(),
                isClean());
        header_ = null;
      }
      return headerBuilder_;
    }

    private java.lang.Object communityId_ = "";
    /**
     * <pre>
     * 关联标识
     * </pre>
     *
     * <code>string community_id = 2 [json_name = "communityId"];</code>
     * @return The communityId.
     */
    public java.lang.String getCommunityId() {
      java.lang.Object ref = communityId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        communityId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 关联标识
     * </pre>
     *
     * <code>string community_id = 2 [json_name = "communityId"];</code>
     * @return The bytes for communityId.
     */
    public com.google.protobuf.ByteString
        getCommunityIdBytes() {
      java.lang.Object ref = communityId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        communityId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 关联标识
     * </pre>
     *
     * <code>string community_id = 2 [json_name = "communityId"];</code>
     * @param value The communityId to set.
     * @return This builder for chaining.
     */
    public Builder setCommunityId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      communityId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 关联标识
     * </pre>
     *
     * <code>string community_id = 2 [json_name = "communityId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearCommunityId() {
      communityId_ = getDefaultInstance().getCommunityId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 关联标识
     * </pre>
     *
     * <code>string community_id = 2 [json_name = "communityId"];</code>
     * @param value The bytes for communityId to set.
     * @return This builder for chaining.
     */
    public Builder setCommunityIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      communityId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object objectType_ = "";
    /**
     * <pre>
     * "flow" 或 "session"
     * </pre>
     *
     * <code>string object_type = 3 [json_name = "objectType"];</code>
     * @return The objectType.
     */
    public java.lang.String getObjectType() {
      java.lang.Object ref = objectType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        objectType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * "flow" 或 "session"
     * </pre>
     *
     * <code>string object_type = 3 [json_name = "objectType"];</code>
     * @return The bytes for objectType.
     */
    public com.google.protobuf.ByteString
        getObjectTypeBytes() {
      java.lang.Object ref = objectType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        objectType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * "flow" 或 "session"
     * </pre>
     *
     * <code>string object_type = 3 [json_name = "objectType"];</code>
     * @param value The objectType to set.
     * @return This builder for chaining.
     */
    public Builder setObjectType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      objectType_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * "flow" 或 "session"
     * </pre>
     *
     * <code>string object_type = 3 [json_name = "objectType"];</code>
     * @return This builder for chaining.
     */
    public Builder clearObjectType() {
      objectType_ = getDefaultInstance().getObjectType();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * "flow" 或 "session"
     * </pre>
     *
     * <code>string object_type = 3 [json_name = "objectType"];</code>
     * @param value The bytes for objectType to set.
     * @return This builder for chaining.
     */
    public Builder setObjectTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      objectType_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object objectId_ = "";
    /**
     * <pre>
     * flow_id 或 session_id
     * </pre>
     *
     * <code>string object_id = 4 [json_name = "objectId"];</code>
     * @return The objectId.
     */
    public java.lang.String getObjectId() {
      java.lang.Object ref = objectId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        objectId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * flow_id 或 session_id
     * </pre>
     *
     * <code>string object_id = 4 [json_name = "objectId"];</code>
     * @return The bytes for objectId.
     */
    public com.google.protobuf.ByteString
        getObjectIdBytes() {
      java.lang.Object ref = objectId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        objectId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * flow_id 或 session_id
     * </pre>
     *
     * <code>string object_id = 4 [json_name = "objectId"];</code>
     * @param value The objectId to set.
     * @return This builder for chaining.
     */
    public Builder setObjectId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      objectId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * flow_id 或 session_id
     * </pre>
     *
     * <code>string object_id = 4 [json_name = "objectId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearObjectId() {
      objectId_ = getDefaultInstance().getObjectId();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * flow_id 或 session_id
     * </pre>
     *
     * <code>string object_id = 4 [json_name = "objectId"];</code>
     * @param value The bytes for objectId to set.
     * @return This builder for chaining.
     */
    public Builder setObjectIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      objectId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private float pps_ ;
    /**
     * <pre>
     * ==================== 速率特征 ====================
     * </pre>
     *
     * <code>float pps = 10 [json_name = "pps"];</code>
     * @return The pps.
     */
    @java.lang.Override
    public float getPps() {
      return pps_;
    }
    /**
     * <pre>
     * ==================== 速率特征 ====================
     * </pre>
     *
     * <code>float pps = 10 [json_name = "pps"];</code>
     * @param value The pps to set.
     * @return This builder for chaining.
     */
    public Builder setPps(float value) {

      pps_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ==================== 速率特征 ====================
     * </pre>
     *
     * <code>float pps = 10 [json_name = "pps"];</code>
     * @return This builder for chaining.
     */
    public Builder clearPps() {
      bitField0_ = (bitField0_ & ~0x00000010);
      pps_ = 0F;
      onChanged();
      return this;
    }

    private float bps_ ;
    /**
     * <pre>
     * 比特率 (bits per second)
     * </pre>
     *
     * <code>float bps = 11 [json_name = "bps"];</code>
     * @return The bps.
     */
    @java.lang.Override
    public float getBps() {
      return bps_;
    }
    /**
     * <pre>
     * 比特率 (bits per second)
     * </pre>
     *
     * <code>float bps = 11 [json_name = "bps"];</code>
     * @param value The bps to set.
     * @return This builder for chaining.
     */
    public Builder setBps(float value) {

      bps_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 比特率 (bits per second)
     * </pre>
     *
     * <code>float bps = 11 [json_name = "bps"];</code>
     * @return This builder for chaining.
     */
    public Builder clearBps() {
      bitField0_ = (bitField0_ & ~0x00000020);
      bps_ = 0F;
      onChanged();
      return this;
    }

    private float upDownRatio_ ;
    /**
     * <pre>
     * ==================== 方向特征 ====================
     * </pre>
     *
     * <code>float up_down_ratio = 20 [json_name = "upDownRatio"];</code>
     * @return The upDownRatio.
     */
    @java.lang.Override
    public float getUpDownRatio() {
      return upDownRatio_;
    }
    /**
     * <pre>
     * ==================== 方向特征 ====================
     * </pre>
     *
     * <code>float up_down_ratio = 20 [json_name = "upDownRatio"];</code>
     * @param value The upDownRatio to set.
     * @return This builder for chaining.
     */
    public Builder setUpDownRatio(float value) {

      upDownRatio_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ==================== 方向特征 ====================
     * </pre>
     *
     * <code>float up_down_ratio = 20 [json_name = "upDownRatio"];</code>
     * @return This builder for chaining.
     */
    public Builder clearUpDownRatio() {
      bitField0_ = (bitField0_ & ~0x00000040);
      upDownRatio_ = 0F;
      onChanged();
      return this;
    }

    private float bytesFwdRatio_ ;
    /**
     * <pre>
     * 正向字节占比
     * </pre>
     *
     * <code>float bytes_fwd_ratio = 21 [json_name = "bytesFwdRatio"];</code>
     * @return The bytesFwdRatio.
     */
    @java.lang.Override
    public float getBytesFwdRatio() {
      return bytesFwdRatio_;
    }
    /**
     * <pre>
     * 正向字节占比
     * </pre>
     *
     * <code>float bytes_fwd_ratio = 21 [json_name = "bytesFwdRatio"];</code>
     * @param value The bytesFwdRatio to set.
     * @return This builder for chaining.
     */
    public Builder setBytesFwdRatio(float value) {

      bytesFwdRatio_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 正向字节占比
     * </pre>
     *
     * <code>float bytes_fwd_ratio = 21 [json_name = "bytesFwdRatio"];</code>
     * @return This builder for chaining.
     */
    public Builder clearBytesFwdRatio() {
      bitField0_ = (bitField0_ & ~0x00000080);
      bytesFwdRatio_ = 0F;
      onChanged();
      return this;
    }

    private float synRatio_ ;
    /**
     * <pre>
     * ==================== TCP 标志特征 ====================
     * </pre>
     *
     * <code>float syn_ratio = 30 [json_name = "synRatio"];</code>
     * @return The synRatio.
     */
    @java.lang.Override
    public float getSynRatio() {
      return synRatio_;
    }
    /**
     * <pre>
     * ==================== TCP 标志特征 ====================
     * </pre>
     *
     * <code>float syn_ratio = 30 [json_name = "synRatio"];</code>
     * @param value The synRatio to set.
     * @return This builder for chaining.
     */
    public Builder setSynRatio(float value) {

      synRatio_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ==================== TCP 标志特征 ====================
     * </pre>
     *
     * <code>float syn_ratio = 30 [json_name = "synRatio"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSynRatio() {
      bitField0_ = (bitField0_ & ~0x00000100);
      synRatio_ = 0F;
      onChanged();
      return this;
    }

    private float finRatio_ ;
    /**
     * <pre>
     * FIN 包占比
     * </pre>
     *
     * <code>float fin_ratio = 31 [json_name = "finRatio"];</code>
     * @return The finRatio.
     */
    @java.lang.Override
    public float getFinRatio() {
      return finRatio_;
    }
    /**
     * <pre>
     * FIN 包占比
     * </pre>
     *
     * <code>float fin_ratio = 31 [json_name = "finRatio"];</code>
     * @param value The finRatio to set.
     * @return This builder for chaining.
     */
    public Builder setFinRatio(float value) {

      finRatio_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * FIN 包占比
     * </pre>
     *
     * <code>float fin_ratio = 31 [json_name = "finRatio"];</code>
     * @return This builder for chaining.
     */
    public Builder clearFinRatio() {
      bitField0_ = (bitField0_ & ~0x00000200);
      finRatio_ = 0F;
      onChanged();
      return this;
    }

    private float rstRatio_ ;
    /**
     * <pre>
     * RST 包占比
     * </pre>
     *
     * <code>float rst_ratio = 32 [json_name = "rstRatio"];</code>
     * @return The rstRatio.
     */
    @java.lang.Override
    public float getRstRatio() {
      return rstRatio_;
    }
    /**
     * <pre>
     * RST 包占比
     * </pre>
     *
     * <code>float rst_ratio = 32 [json_name = "rstRatio"];</code>
     * @param value The rstRatio to set.
     * @return This builder for chaining.
     */
    public Builder setRstRatio(float value) {

      rstRatio_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * RST 包占比
     * </pre>
     *
     * <code>float rst_ratio = 32 [json_name = "rstRatio"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRstRatio() {
      bitField0_ = (bitField0_ & ~0x00000400);
      rstRatio_ = 0F;
      onChanged();
      return this;
    }

    private float ackRatio_ ;
    /**
     * <pre>
     * ACK 包占比
     * </pre>
     *
     * <code>float ack_ratio = 33 [json_name = "ackRatio"];</code>
     * @return The ackRatio.
     */
    @java.lang.Override
    public float getAckRatio() {
      return ackRatio_;
    }
    /**
     * <pre>
     * ACK 包占比
     * </pre>
     *
     * <code>float ack_ratio = 33 [json_name = "ackRatio"];</code>
     * @param value The ackRatio to set.
     * @return This builder for chaining.
     */
    public Builder setAckRatio(float value) {

      ackRatio_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ACK 包占比
     * </pre>
     *
     * <code>float ack_ratio = 33 [json_name = "ackRatio"];</code>
     * @return This builder for chaining.
     */
    public Builder clearAckRatio() {
      bitField0_ = (bitField0_ & ~0x00000800);
      ackRatio_ = 0F;
      onChanged();
      return this;
    }

    private float pshRatio_ ;
    /**
     * <pre>
     * PSH 包占比
     * </pre>
     *
     * <code>float psh_ratio = 34 [json_name = "pshRatio"];</code>
     * @return The pshRatio.
     */
    @java.lang.Override
    public float getPshRatio() {
      return pshRatio_;
    }
    /**
     * <pre>
     * PSH 包占比
     * </pre>
     *
     * <code>float psh_ratio = 34 [json_name = "pshRatio"];</code>
     * @param value The pshRatio to set.
     * @return This builder for chaining.
     */
    public Builder setPshRatio(float value) {

      pshRatio_ = value;
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * PSH 包占比
     * </pre>
     *
     * <code>float psh_ratio = 34 [json_name = "pshRatio"];</code>
     * @return This builder for chaining.
     */
    public Builder clearPshRatio() {
      bitField0_ = (bitField0_ & ~0x00001000);
      pshRatio_ = 0F;
      onChanged();
      return this;
    }

    private float iatMeanMs_ ;
    /**
     * <pre>
     * ==================== 时间特征 ====================
     * </pre>
     *
     * <code>float iat_mean_ms = 40 [json_name = "iatMeanMs"];</code>
     * @return The iatMeanMs.
     */
    @java.lang.Override
    public float getIatMeanMs() {
      return iatMeanMs_;
    }
    /**
     * <pre>
     * ==================== 时间特征 ====================
     * </pre>
     *
     * <code>float iat_mean_ms = 40 [json_name = "iatMeanMs"];</code>
     * @param value The iatMeanMs to set.
     * @return This builder for chaining.
     */
    public Builder setIatMeanMs(float value) {

      iatMeanMs_ = value;
      bitField0_ |= 0x00002000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ==================== 时间特征 ====================
     * </pre>
     *
     * <code>float iat_mean_ms = 40 [json_name = "iatMeanMs"];</code>
     * @return This builder for chaining.
     */
    public Builder clearIatMeanMs() {
      bitField0_ = (bitField0_ & ~0x00002000);
      iatMeanMs_ = 0F;
      onChanged();
      return this;
    }

    private float iatStdMs_ ;
    /**
     * <pre>
     * 包间隔标准差
     * </pre>
     *
     * <code>float iat_std_ms = 41 [json_name = "iatStdMs"];</code>
     * @return The iatStdMs.
     */
    @java.lang.Override
    public float getIatStdMs() {
      return iatStdMs_;
    }
    /**
     * <pre>
     * 包间隔标准差
     * </pre>
     *
     * <code>float iat_std_ms = 41 [json_name = "iatStdMs"];</code>
     * @param value The iatStdMs to set.
     * @return This builder for chaining.
     */
    public Builder setIatStdMs(float value) {

      iatStdMs_ = value;
      bitField0_ |= 0x00004000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 包间隔标准差
     * </pre>
     *
     * <code>float iat_std_ms = 41 [json_name = "iatStdMs"];</code>
     * @return This builder for chaining.
     */
    public Builder clearIatStdMs() {
      bitField0_ = (bitField0_ & ~0x00004000);
      iatStdMs_ = 0F;
      onChanged();
      return this;
    }

    private float iatMinMs_ ;
    /**
     * <pre>
     * 最小包间隔
     * </pre>
     *
     * <code>float iat_min_ms = 42 [json_name = "iatMinMs"];</code>
     * @return The iatMinMs.
     */
    @java.lang.Override
    public float getIatMinMs() {
      return iatMinMs_;
    }
    /**
     * <pre>
     * 最小包间隔
     * </pre>
     *
     * <code>float iat_min_ms = 42 [json_name = "iatMinMs"];</code>
     * @param value The iatMinMs to set.
     * @return This builder for chaining.
     */
    public Builder setIatMinMs(float value) {

      iatMinMs_ = value;
      bitField0_ |= 0x00008000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 最小包间隔
     * </pre>
     *
     * <code>float iat_min_ms = 42 [json_name = "iatMinMs"];</code>
     * @return This builder for chaining.
     */
    public Builder clearIatMinMs() {
      bitField0_ = (bitField0_ & ~0x00008000);
      iatMinMs_ = 0F;
      onChanged();
      return this;
    }

    private float iatMaxMs_ ;
    /**
     * <pre>
     * 最大包间隔
     * </pre>
     *
     * <code>float iat_max_ms = 43 [json_name = "iatMaxMs"];</code>
     * @return The iatMaxMs.
     */
    @java.lang.Override
    public float getIatMaxMs() {
      return iatMaxMs_;
    }
    /**
     * <pre>
     * 最大包间隔
     * </pre>
     *
     * <code>float iat_max_ms = 43 [json_name = "iatMaxMs"];</code>
     * @param value The iatMaxMs to set.
     * @return This builder for chaining.
     */
    public Builder setIatMaxMs(float value) {

      iatMaxMs_ = value;
      bitField0_ |= 0x00010000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 最大包间隔
     * </pre>
     *
     * <code>float iat_max_ms = 43 [json_name = "iatMaxMs"];</code>
     * @return This builder for chaining.
     */
    public Builder clearIatMaxMs() {
      bitField0_ = (bitField0_ & ~0x00010000);
      iatMaxMs_ = 0F;
      onChanged();
      return this;
    }

    private float pktlenMean_ ;
    /**
     * <pre>
     * ==================== 包长特征 ====================
     * </pre>
     *
     * <code>float pktlen_mean = 50 [json_name = "pktlenMean"];</code>
     * @return The pktlenMean.
     */
    @java.lang.Override
    public float getPktlenMean() {
      return pktlenMean_;
    }
    /**
     * <pre>
     * ==================== 包长特征 ====================
     * </pre>
     *
     * <code>float pktlen_mean = 50 [json_name = "pktlenMean"];</code>
     * @param value The pktlenMean to set.
     * @return This builder for chaining.
     */
    public Builder setPktlenMean(float value) {

      pktlenMean_ = value;
      bitField0_ |= 0x00020000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ==================== 包长特征 ====================
     * </pre>
     *
     * <code>float pktlen_mean = 50 [json_name = "pktlenMean"];</code>
     * @return This builder for chaining.
     */
    public Builder clearPktlenMean() {
      bitField0_ = (bitField0_ & ~0x00020000);
      pktlenMean_ = 0F;
      onChanged();
      return this;
    }

    private float pktlenStd_ ;
    /**
     * <pre>
     * 包长标准差
     * </pre>
     *
     * <code>float pktlen_std = 51 [json_name = "pktlenStd"];</code>
     * @return The pktlenStd.
     */
    @java.lang.Override
    public float getPktlenStd() {
      return pktlenStd_;
    }
    /**
     * <pre>
     * 包长标准差
     * </pre>
     *
     * <code>float pktlen_std = 51 [json_name = "pktlenStd"];</code>
     * @param value The pktlenStd to set.
     * @return This builder for chaining.
     */
    public Builder setPktlenStd(float value) {

      pktlenStd_ = value;
      bitField0_ |= 0x00040000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 包长标准差
     * </pre>
     *
     * <code>float pktlen_std = 51 [json_name = "pktlenStd"];</code>
     * @return This builder for chaining.
     */
    public Builder clearPktlenStd() {
      bitField0_ = (bitField0_ & ~0x00040000);
      pktlenStd_ = 0F;
      onChanged();
      return this;
    }

    private float pktlenMin_ ;
    /**
     * <pre>
     * 最小包长
     * </pre>
     *
     * <code>float pktlen_min = 52 [json_name = "pktlenMin"];</code>
     * @return The pktlenMin.
     */
    @java.lang.Override
    public float getPktlenMin() {
      return pktlenMin_;
    }
    /**
     * <pre>
     * 最小包长
     * </pre>
     *
     * <code>float pktlen_min = 52 [json_name = "pktlenMin"];</code>
     * @param value The pktlenMin to set.
     * @return This builder for chaining.
     */
    public Builder setPktlenMin(float value) {

      pktlenMin_ = value;
      bitField0_ |= 0x00080000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 最小包长
     * </pre>
     *
     * <code>float pktlen_min = 52 [json_name = "pktlenMin"];</code>
     * @return This builder for chaining.
     */
    public Builder clearPktlenMin() {
      bitField0_ = (bitField0_ & ~0x00080000);
      pktlenMin_ = 0F;
      onChanged();
      return this;
    }

    private float pktlenMax_ ;
    /**
     * <pre>
     * 最大包长
     * </pre>
     *
     * <code>float pktlen_max = 53 [json_name = "pktlenMax"];</code>
     * @return The pktlenMax.
     */
    @java.lang.Override
    public float getPktlenMax() {
      return pktlenMax_;
    }
    /**
     * <pre>
     * 最大包长
     * </pre>
     *
     * <code>float pktlen_max = 53 [json_name = "pktlenMax"];</code>
     * @param value The pktlenMax to set.
     * @return This builder for chaining.
     */
    public Builder setPktlenMax(float value) {

      pktlenMax_ = value;
      bitField0_ |= 0x00100000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 最大包长
     * </pre>
     *
     * <code>float pktlen_max = 53 [json_name = "pktlenMax"];</code>
     * @return This builder for chaining.
     */
    public Builder clearPktlenMax() {
      bitField0_ = (bitField0_ & ~0x00100000);
      pktlenMax_ = 0F;
      onChanged();
      return this;
    }

    private float activeMeanMs_ ;
    /**
     * <pre>
     * ==================== 活跃/空闲特征 ====================
     * </pre>
     *
     * <code>float active_mean_ms = 60 [json_name = "activeMeanMs"];</code>
     * @return The activeMeanMs.
     */
    @java.lang.Override
    public float getActiveMeanMs() {
      return activeMeanMs_;
    }
    /**
     * <pre>
     * ==================== 活跃/空闲特征 ====================
     * </pre>
     *
     * <code>float active_mean_ms = 60 [json_name = "activeMeanMs"];</code>
     * @param value The activeMeanMs to set.
     * @return This builder for chaining.
     */
    public Builder setActiveMeanMs(float value) {

      activeMeanMs_ = value;
      bitField0_ |= 0x00200000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ==================== 活跃/空闲特征 ====================
     * </pre>
     *
     * <code>float active_mean_ms = 60 [json_name = "activeMeanMs"];</code>
     * @return This builder for chaining.
     */
    public Builder clearActiveMeanMs() {
      bitField0_ = (bitField0_ & ~0x00200000);
      activeMeanMs_ = 0F;
      onChanged();
      return this;
    }

    private float idleMeanMs_ ;
    /**
     * <pre>
     * 平均空闲时间
     * </pre>
     *
     * <code>float idle_mean_ms = 61 [json_name = "idleMeanMs"];</code>
     * @return The idleMeanMs.
     */
    @java.lang.Override
    public float getIdleMeanMs() {
      return idleMeanMs_;
    }
    /**
     * <pre>
     * 平均空闲时间
     * </pre>
     *
     * <code>float idle_mean_ms = 61 [json_name = "idleMeanMs"];</code>
     * @param value The idleMeanMs to set.
     * @return This builder for chaining.
     */
    public Builder setIdleMeanMs(float value) {

      idleMeanMs_ = value;
      bitField0_ |= 0x00400000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 平均空闲时间
     * </pre>
     *
     * <code>float idle_mean_ms = 61 [json_name = "idleMeanMs"];</code>
     * @return This builder for chaining.
     */
    public Builder clearIdleMeanMs() {
      bitField0_ = (bitField0_ & ~0x00400000);
      idleMeanMs_ = 0F;
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.FloatList extra_ = emptyFloatList();
    private void ensureExtraIsMutable() {
      if (!extra_.isModifiable()) {
        extra_ = makeMutableCopy(extra_);
      }
      bitField0_ |= 0x00800000;
    }
    private void ensureExtraIsMutable(int capacity) {
      if (!extra_.isModifiable()) {
        extra_ = makeMutableCopy(extra_, capacity);
      }
      bitField0_ |= 0x00800000;
    }
    /**
     * <pre>
     * ==================== 扩展特征 (用于模型) ====================
     * </pre>
     *
     * <code>repeated float extra = 100 [json_name = "extra"];</code>
     * @return A list containing the extra.
     */
    public java.util.List<java.lang.Float>
        getExtraList() {
      extra_.makeImmutable();
      return extra_;
    }
    /**
     * <pre>
     * ==================== 扩展特征 (用于模型) ====================
     * </pre>
     *
     * <code>repeated float extra = 100 [json_name = "extra"];</code>
     * @return The count of extra.
     */
    public int getExtraCount() {
      return extra_.size();
    }
    /**
     * <pre>
     * ==================== 扩展特征 (用于模型) ====================
     * </pre>
     *
     * <code>repeated float extra = 100 [json_name = "extra"];</code>
     * @param index The index of the element to return.
     * @return The extra at the given index.
     */
    public float getExtra(int index) {
      return extra_.getFloat(index);
    }
    /**
     * <pre>
     * ==================== 扩展特征 (用于模型) ====================
     * </pre>
     *
     * <code>repeated float extra = 100 [json_name = "extra"];</code>
     * @param index The index to set the value at.
     * @param value The extra to set.
     * @return This builder for chaining.
     */
    public Builder setExtra(
        int index, float value) {

      ensureExtraIsMutable();
      extra_.setFloat(index, value);
      bitField0_ |= 0x00800000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ==================== 扩展特征 (用于模型) ====================
     * </pre>
     *
     * <code>repeated float extra = 100 [json_name = "extra"];</code>
     * @param value The extra to add.
     * @return This builder for chaining.
     */
    public Builder addExtra(float value) {

      ensureExtraIsMutable();
      extra_.addFloat(value);
      bitField0_ |= 0x00800000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ==================== 扩展特征 (用于模型) ====================
     * </pre>
     *
     * <code>repeated float extra = 100 [json_name = "extra"];</code>
     * @param values The extra to add.
     * @return This builder for chaining.
     */
    public Builder addAllExtra(
        java.lang.Iterable<? extends java.lang.Float> values) {
      ensureExtraIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, extra_);
      bitField0_ |= 0x00800000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ==================== 扩展特征 (用于模型) ====================
     * </pre>
     *
     * <code>repeated float extra = 100 [json_name = "extra"];</code>
     * @return This builder for chaining.
     */
    public Builder clearExtra() {
      extra_ = emptyFloatList();
      bitField0_ = (bitField0_ & ~0x00800000);
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList tagKeys_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureTagKeysIsMutable() {
      if (!tagKeys_.isModifiable()) {
        tagKeys_ = new com.google.protobuf.LazyStringArrayList(tagKeys_);
      }
      bitField0_ |= 0x01000000;
    }
    /**
     * <pre>
     * 标签键列表
     * </pre>
     *
     * <code>repeated string tag_keys = 101 [json_name = "tagKeys"];</code>
     * @return A list containing the tagKeys.
     */
    public com.google.protobuf.ProtocolStringList
        getTagKeysList() {
      tagKeys_.makeImmutable();
      return tagKeys_;
    }
    /**
     * <pre>
     * 标签键列表
     * </pre>
     *
     * <code>repeated string tag_keys = 101 [json_name = "tagKeys"];</code>
     * @return The count of tagKeys.
     */
    public int getTagKeysCount() {
      return tagKeys_.size();
    }
    /**
     * <pre>
     * 标签键列表
     * </pre>
     *
     * <code>repeated string tag_keys = 101 [json_name = "tagKeys"];</code>
     * @param index The index of the element to return.
     * @return The tagKeys at the given index.
     */
    public java.lang.String getTagKeys(int index) {
      return tagKeys_.get(index);
    }
    /**
     * <pre>
     * 标签键列表
     * </pre>
     *
     * <code>repeated string tag_keys = 101 [json_name = "tagKeys"];</code>
     * @param index The index of the value to return.
     * @return The bytes of the tagKeys at the given index.
     */
    public com.google.protobuf.ByteString
        getTagKeysBytes(int index) {
      return tagKeys_.getByteString(index);
    }
    /**
     * <pre>
     * 标签键列表
     * </pre>
     *
     * <code>repeated string tag_keys = 101 [json_name = "tagKeys"];</code>
     * @param index The index to set the value at.
     * @param value The tagKeys to set.
     * @return This builder for chaining.
     */
    public Builder setTagKeys(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureTagKeysIsMutable();
      tagKeys_.set(index, value);
      bitField0_ |= 0x01000000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 标签键列表
     * </pre>
     *
     * <code>repeated string tag_keys = 101 [json_name = "tagKeys"];</code>
     * @param value The tagKeys to add.
     * @return This builder for chaining.
     */
    public Builder addTagKeys(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureTagKeysIsMutable();
      tagKeys_.add(value);
      bitField0_ |= 0x01000000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 标签键列表
     * </pre>
     *
     * <code>repeated string tag_keys = 101 [json_name = "tagKeys"];</code>
     * @param values The tagKeys to add.
     * @return This builder for chaining.
     */
    public Builder addAllTagKeys(
        java.lang.Iterable<java.lang.String> values) {
      ensureTagKeysIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, tagKeys_);
      bitField0_ |= 0x01000000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 标签键列表
     * </pre>
     *
     * <code>repeated string tag_keys = 101 [json_name = "tagKeys"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTagKeys() {
      tagKeys_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x01000000);;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 标签键列表
     * </pre>
     *
     * <code>repeated string tag_keys = 101 [json_name = "tagKeys"];</code>
     * @param value The bytes of the tagKeys to add.
     * @return This builder for chaining.
     */
    public Builder addTagKeysBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureTagKeysIsMutable();
      tagKeys_.add(value);
      bitField0_ |= 0x01000000;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList tagValues_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureTagValuesIsMutable() {
      if (!tagValues_.isModifiable()) {
        tagValues_ = new com.google.protobuf.LazyStringArrayList(tagValues_);
      }
      bitField0_ |= 0x02000000;
    }
    /**
     * <pre>
     * 标签值列表 (与 tag_keys 一一对应)
     * </pre>
     *
     * <code>repeated string tag_values = 102 [json_name = "tagValues"];</code>
     * @return A list containing the tagValues.
     */
    public com.google.protobuf.ProtocolStringList
        getTagValuesList() {
      tagValues_.makeImmutable();
      return tagValues_;
    }
    /**
     * <pre>
     * 标签值列表 (与 tag_keys 一一对应)
     * </pre>
     *
     * <code>repeated string tag_values = 102 [json_name = "tagValues"];</code>
     * @return The count of tagValues.
     */
    public int getTagValuesCount() {
      return tagValues_.size();
    }
    /**
     * <pre>
     * 标签值列表 (与 tag_keys 一一对应)
     * </pre>
     *
     * <code>repeated string tag_values = 102 [json_name = "tagValues"];</code>
     * @param index The index of the element to return.
     * @return The tagValues at the given index.
     */
    public java.lang.String getTagValues(int index) {
      return tagValues_.get(index);
    }
    /**
     * <pre>
     * 标签值列表 (与 tag_keys 一一对应)
     * </pre>
     *
     * <code>repeated string tag_values = 102 [json_name = "tagValues"];</code>
     * @param index The index of the value to return.
     * @return The bytes of the tagValues at the given index.
     */
    public com.google.protobuf.ByteString
        getTagValuesBytes(int index) {
      return tagValues_.getByteString(index);
    }
    /**
     * <pre>
     * 标签值列表 (与 tag_keys 一一对应)
     * </pre>
     *
     * <code>repeated string tag_values = 102 [json_name = "tagValues"];</code>
     * @param index The index to set the value at.
     * @param value The tagValues to set.
     * @return This builder for chaining.
     */
    public Builder setTagValues(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureTagValuesIsMutable();
      tagValues_.set(index, value);
      bitField0_ |= 0x02000000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 标签值列表 (与 tag_keys 一一对应)
     * </pre>
     *
     * <code>repeated string tag_values = 102 [json_name = "tagValues"];</code>
     * @param value The tagValues to add.
     * @return This builder for chaining.
     */
    public Builder addTagValues(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureTagValuesIsMutable();
      tagValues_.add(value);
      bitField0_ |= 0x02000000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 标签值列表 (与 tag_keys 一一对应)
     * </pre>
     *
     * <code>repeated string tag_values = 102 [json_name = "tagValues"];</code>
     * @param values The tagValues to add.
     * @return This builder for chaining.
     */
    public Builder addAllTagValues(
        java.lang.Iterable<java.lang.String> values) {
      ensureTagValuesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, tagValues_);
      bitField0_ |= 0x02000000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 标签值列表 (与 tag_keys 一一对应)
     * </pre>
     *
     * <code>repeated string tag_values = 102 [json_name = "tagValues"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTagValues() {
      tagValues_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x02000000);;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 标签值列表 (与 tag_keys 一一对应)
     * </pre>
     *
     * <code>repeated string tag_values = 102 [json_name = "tagValues"];</code>
     * @param value The bytes of the tagValues to add.
     * @return This builder for chaining.
     */
    public Builder addTagValuesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureTagValuesIsMutable();
      tagValues_.add(value);
      bitField0_ |= 0x02000000;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:traffic.v1.FeatureStatV1)
  }

  // @@protoc_insertion_point(class_scope:traffic.v1.FeatureStatV1)
  private static final com.traffic.proto.v1.FeatureStatV1 DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.traffic.proto.v1.FeatureStatV1();
  }

  public static com.traffic.proto.v1.FeatureStatV1 getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FeatureStatV1>
      PARSER = new com.google.protobuf.AbstractParser<FeatureStatV1>() {
    @java.lang.Override
    public FeatureStatV1 parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<FeatureStatV1> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FeatureStatV1> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.traffic.proto.v1.FeatureStatV1 getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

