// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: traffic/v1/pcap.proto
// Protobuf Java Version: 4.33.2

package com.traffic.proto.v1;

/**
 * <pre>
 * PcapCutResponse PCAP 裁剪响应
 * </pre>
 *
 * Protobuf type {@code traffic.v1.PcapCutResponse}
 */
@com.google.protobuf.Generated
public final class PcapCutResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:traffic.v1.PcapCutResponse)
    PcapCutResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 2,
      /* suffix= */ "",
      "PcapCutResponse");
  }
  // Use PcapCutResponse.newBuilder() to construct.
  private PcapCutResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private PcapCutResponse() {
    jobId_ = "";
    status_ = "";
    downloadUrl_ = "";
    errorMessage_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.traffic.proto.v1.Pcap.internal_static_traffic_v1_PcapCutResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.traffic.proto.v1.Pcap.internal_static_traffic_v1_PcapCutResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.traffic.proto.v1.PcapCutResponse.class, com.traffic.proto.v1.PcapCutResponse.Builder.class);
  }

  public static final int JOB_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object jobId_ = "";
  /**
   * <code>string job_id = 1 [json_name = "jobId"];</code>
   * @return The jobId.
   */
  @java.lang.Override
  public java.lang.String getJobId() {
    java.lang.Object ref = jobId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      jobId_ = s;
      return s;
    }
  }
  /**
   * <code>string job_id = 1 [json_name = "jobId"];</code>
   * @return The bytes for jobId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getJobIdBytes() {
    java.lang.Object ref = jobId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      jobId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATUS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object status_ = "";
  /**
   * <pre>
   * status: "queued" | "processing" | "completed" | "failed"
   * </pre>
   *
   * <code>string status = 2 [json_name = "status"];</code>
   * @return The status.
   */
  @java.lang.Override
  public java.lang.String getStatus() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      status_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * status: "queued" | "processing" | "completed" | "failed"
   * </pre>
   *
   * <code>string status = 2 [json_name = "status"];</code>
   * @return The bytes for status.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStatusBytes() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      status_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DOWNLOAD_URL_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object downloadUrl_ = "";
  /**
   * <pre>
   * 完成后的下载 URL
   * </pre>
   *
   * <code>string download_url = 3 [json_name = "downloadUrl"];</code>
   * @return The downloadUrl.
   */
  @java.lang.Override
  public java.lang.String getDownloadUrl() {
    java.lang.Object ref = downloadUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      downloadUrl_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 完成后的下载 URL
   * </pre>
   *
   * <code>string download_url = 3 [json_name = "downloadUrl"];</code>
   * @return The bytes for downloadUrl.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDownloadUrlBytes() {
    java.lang.Object ref = downloadUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      downloadUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PROGRESS_PERCENT_FIELD_NUMBER = 4;
  private int progressPercent_ = 0;
  /**
   * <pre>
   * 进度信息
   * </pre>
   *
   * <code>int32 progress_percent = 4 [json_name = "progressPercent"];</code>
   * @return The progressPercent.
   */
  @java.lang.Override
  public int getProgressPercent() {
    return progressPercent_;
  }

  public static final int ERROR_MESSAGE_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object errorMessage_ = "";
  /**
   * <pre>
   * 错误信息
   * </pre>
   *
   * <code>string error_message = 5 [json_name = "errorMessage"];</code>
   * @return The errorMessage.
   */
  @java.lang.Override
  public java.lang.String getErrorMessage() {
    java.lang.Object ref = errorMessage_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      errorMessage_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 错误信息
   * </pre>
   *
   * <code>string error_message = 5 [json_name = "errorMessage"];</code>
   * @return The bytes for errorMessage.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getErrorMessageBytes() {
    java.lang.Object ref = errorMessage_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      errorMessage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOTAL_PACKETS_FIELD_NUMBER = 6;
  private long totalPackets_ = 0L;
  /**
   * <pre>
   * 结果统计
   * </pre>
   *
   * <code>uint64 total_packets = 6 [json_name = "totalPackets"];</code>
   * @return The totalPackets.
   */
  @java.lang.Override
  public long getTotalPackets() {
    return totalPackets_;
  }

  public static final int TOTAL_BYTES_FIELD_NUMBER = 7;
  private long totalBytes_ = 0L;
  /**
   * <code>uint64 total_bytes = 7 [json_name = "totalBytes"];</code>
   * @return The totalBytes.
   */
  @java.lang.Override
  public long getTotalBytes() {
    return totalBytes_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(jobId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, jobId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(status_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, status_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(downloadUrl_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, downloadUrl_);
    }
    if (progressPercent_ != 0) {
      output.writeInt32(4, progressPercent_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(errorMessage_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, errorMessage_);
    }
    if (totalPackets_ != 0L) {
      output.writeUInt64(6, totalPackets_);
    }
    if (totalBytes_ != 0L) {
      output.writeUInt64(7, totalBytes_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(jobId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, jobId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(status_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, status_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(downloadUrl_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, downloadUrl_);
    }
    if (progressPercent_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, progressPercent_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(errorMessage_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, errorMessage_);
    }
    if (totalPackets_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(6, totalPackets_);
    }
    if (totalBytes_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(7, totalBytes_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.traffic.proto.v1.PcapCutResponse)) {
      return super.equals(obj);
    }
    com.traffic.proto.v1.PcapCutResponse other = (com.traffic.proto.v1.PcapCutResponse) obj;

    if (!getJobId()
        .equals(other.getJobId())) return false;
    if (!getStatus()
        .equals(other.getStatus())) return false;
    if (!getDownloadUrl()
        .equals(other.getDownloadUrl())) return false;
    if (getProgressPercent()
        != other.getProgressPercent()) return false;
    if (!getErrorMessage()
        .equals(other.getErrorMessage())) return false;
    if (getTotalPackets()
        != other.getTotalPackets()) return false;
    if (getTotalBytes()
        != other.getTotalBytes()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + JOB_ID_FIELD_NUMBER;
    hash = (53 * hash) + getJobId().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getStatus().hashCode();
    hash = (37 * hash) + DOWNLOAD_URL_FIELD_NUMBER;
    hash = (53 * hash) + getDownloadUrl().hashCode();
    hash = (37 * hash) + PROGRESS_PERCENT_FIELD_NUMBER;
    hash = (53 * hash) + getProgressPercent();
    hash = (37 * hash) + ERROR_MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getErrorMessage().hashCode();
    hash = (37 * hash) + TOTAL_PACKETS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTotalPackets());
    hash = (37 * hash) + TOTAL_BYTES_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTotalBytes());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.traffic.proto.v1.PcapCutResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.traffic.proto.v1.PcapCutResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.traffic.proto.v1.PcapCutResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.traffic.proto.v1.PcapCutResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.traffic.proto.v1.PcapCutResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.traffic.proto.v1.PcapCutResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.traffic.proto.v1.PcapCutResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.traffic.proto.v1.PcapCutResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.traffic.proto.v1.PcapCutResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.traffic.proto.v1.PcapCutResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.traffic.proto.v1.PcapCutResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.traffic.proto.v1.PcapCutResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.traffic.proto.v1.PcapCutResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * PcapCutResponse PCAP 裁剪响应
   * </pre>
   *
   * Protobuf type {@code traffic.v1.PcapCutResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:traffic.v1.PcapCutResponse)
      com.traffic.proto.v1.PcapCutResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.traffic.proto.v1.Pcap.internal_static_traffic_v1_PcapCutResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.traffic.proto.v1.Pcap.internal_static_traffic_v1_PcapCutResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.traffic.proto.v1.PcapCutResponse.class, com.traffic.proto.v1.PcapCutResponse.Builder.class);
    }

    // Construct using com.traffic.proto.v1.PcapCutResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      jobId_ = "";
      status_ = "";
      downloadUrl_ = "";
      progressPercent_ = 0;
      errorMessage_ = "";
      totalPackets_ = 0L;
      totalBytes_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.traffic.proto.v1.Pcap.internal_static_traffic_v1_PcapCutResponse_descriptor;
    }

    @java.lang.Override
    public com.traffic.proto.v1.PcapCutResponse getDefaultInstanceForType() {
      return com.traffic.proto.v1.PcapCutResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.traffic.proto.v1.PcapCutResponse build() {
      com.traffic.proto.v1.PcapCutResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.traffic.proto.v1.PcapCutResponse buildPartial() {
      com.traffic.proto.v1.PcapCutResponse result = new com.traffic.proto.v1.PcapCutResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.traffic.proto.v1.PcapCutResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.jobId_ = jobId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.status_ = status_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.downloadUrl_ = downloadUrl_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.progressPercent_ = progressPercent_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.errorMessage_ = errorMessage_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.totalPackets_ = totalPackets_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.totalBytes_ = totalBytes_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.traffic.proto.v1.PcapCutResponse) {
        return mergeFrom((com.traffic.proto.v1.PcapCutResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.traffic.proto.v1.PcapCutResponse other) {
      if (other == com.traffic.proto.v1.PcapCutResponse.getDefaultInstance()) return this;
      if (!other.getJobId().isEmpty()) {
        jobId_ = other.jobId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getStatus().isEmpty()) {
        status_ = other.status_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getDownloadUrl().isEmpty()) {
        downloadUrl_ = other.downloadUrl_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.getProgressPercent() != 0) {
        setProgressPercent(other.getProgressPercent());
      }
      if (!other.getErrorMessage().isEmpty()) {
        errorMessage_ = other.errorMessage_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (other.getTotalPackets() != 0L) {
        setTotalPackets(other.getTotalPackets());
      }
      if (other.getTotalBytes() != 0L) {
        setTotalBytes(other.getTotalBytes());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              jobId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              status_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              downloadUrl_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              progressPercent_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              errorMessage_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 48: {
              totalPackets_ = input.readUInt64();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              totalBytes_ = input.readUInt64();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object jobId_ = "";
    /**
     * <code>string job_id = 1 [json_name = "jobId"];</code>
     * @return The jobId.
     */
    public java.lang.String getJobId() {
      java.lang.Object ref = jobId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        jobId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string job_id = 1 [json_name = "jobId"];</code>
     * @return The bytes for jobId.
     */
    public com.google.protobuf.ByteString
        getJobIdBytes() {
      java.lang.Object ref = jobId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        jobId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string job_id = 1 [json_name = "jobId"];</code>
     * @param value The jobId to set.
     * @return This builder for chaining.
     */
    public Builder setJobId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      jobId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string job_id = 1 [json_name = "jobId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearJobId() {
      jobId_ = getDefaultInstance().getJobId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string job_id = 1 [json_name = "jobId"];</code>
     * @param value The bytes for jobId to set.
     * @return This builder for chaining.
     */
    public Builder setJobIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      jobId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object status_ = "";
    /**
     * <pre>
     * status: "queued" | "processing" | "completed" | "failed"
     * </pre>
     *
     * <code>string status = 2 [json_name = "status"];</code>
     * @return The status.
     */
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        status_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * status: "queued" | "processing" | "completed" | "failed"
     * </pre>
     *
     * <code>string status = 2 [json_name = "status"];</code>
     * @return The bytes for status.
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * status: "queued" | "processing" | "completed" | "failed"
     * </pre>
     *
     * <code>string status = 2 [json_name = "status"];</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      status_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * status: "queued" | "processing" | "completed" | "failed"
     * </pre>
     *
     * <code>string status = 2 [json_name = "status"];</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      status_ = getDefaultInstance().getStatus();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * status: "queued" | "processing" | "completed" | "failed"
     * </pre>
     *
     * <code>string status = 2 [json_name = "status"];</code>
     * @param value The bytes for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      status_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object downloadUrl_ = "";
    /**
     * <pre>
     * 完成后的下载 URL
     * </pre>
     *
     * <code>string download_url = 3 [json_name = "downloadUrl"];</code>
     * @return The downloadUrl.
     */
    public java.lang.String getDownloadUrl() {
      java.lang.Object ref = downloadUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        downloadUrl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 完成后的下载 URL
     * </pre>
     *
     * <code>string download_url = 3 [json_name = "downloadUrl"];</code>
     * @return The bytes for downloadUrl.
     */
    public com.google.protobuf.ByteString
        getDownloadUrlBytes() {
      java.lang.Object ref = downloadUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        downloadUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 完成后的下载 URL
     * </pre>
     *
     * <code>string download_url = 3 [json_name = "downloadUrl"];</code>
     * @param value The downloadUrl to set.
     * @return This builder for chaining.
     */
    public Builder setDownloadUrl(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      downloadUrl_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 完成后的下载 URL
     * </pre>
     *
     * <code>string download_url = 3 [json_name = "downloadUrl"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDownloadUrl() {
      downloadUrl_ = getDefaultInstance().getDownloadUrl();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 完成后的下载 URL
     * </pre>
     *
     * <code>string download_url = 3 [json_name = "downloadUrl"];</code>
     * @param value The bytes for downloadUrl to set.
     * @return This builder for chaining.
     */
    public Builder setDownloadUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      downloadUrl_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private int progressPercent_ ;
    /**
     * <pre>
     * 进度信息
     * </pre>
     *
     * <code>int32 progress_percent = 4 [json_name = "progressPercent"];</code>
     * @return The progressPercent.
     */
    @java.lang.Override
    public int getProgressPercent() {
      return progressPercent_;
    }
    /**
     * <pre>
     * 进度信息
     * </pre>
     *
     * <code>int32 progress_percent = 4 [json_name = "progressPercent"];</code>
     * @param value The progressPercent to set.
     * @return This builder for chaining.
     */
    public Builder setProgressPercent(int value) {

      progressPercent_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 进度信息
     * </pre>
     *
     * <code>int32 progress_percent = 4 [json_name = "progressPercent"];</code>
     * @return This builder for chaining.
     */
    public Builder clearProgressPercent() {
      bitField0_ = (bitField0_ & ~0x00000008);
      progressPercent_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object errorMessage_ = "";
    /**
     * <pre>
     * 错误信息
     * </pre>
     *
     * <code>string error_message = 5 [json_name = "errorMessage"];</code>
     * @return The errorMessage.
     */
    public java.lang.String getErrorMessage() {
      java.lang.Object ref = errorMessage_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        errorMessage_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 错误信息
     * </pre>
     *
     * <code>string error_message = 5 [json_name = "errorMessage"];</code>
     * @return The bytes for errorMessage.
     */
    public com.google.protobuf.ByteString
        getErrorMessageBytes() {
      java.lang.Object ref = errorMessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 错误信息
     * </pre>
     *
     * <code>string error_message = 5 [json_name = "errorMessage"];</code>
     * @param value The errorMessage to set.
     * @return This builder for chaining.
     */
    public Builder setErrorMessage(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      errorMessage_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 错误信息
     * </pre>
     *
     * <code>string error_message = 5 [json_name = "errorMessage"];</code>
     * @return This builder for chaining.
     */
    public Builder clearErrorMessage() {
      errorMessage_ = getDefaultInstance().getErrorMessage();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 错误信息
     * </pre>
     *
     * <code>string error_message = 5 [json_name = "errorMessage"];</code>
     * @param value The bytes for errorMessage to set.
     * @return This builder for chaining.
     */
    public Builder setErrorMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      errorMessage_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private long totalPackets_ ;
    /**
     * <pre>
     * 结果统计
     * </pre>
     *
     * <code>uint64 total_packets = 6 [json_name = "totalPackets"];</code>
     * @return The totalPackets.
     */
    @java.lang.Override
    public long getTotalPackets() {
      return totalPackets_;
    }
    /**
     * <pre>
     * 结果统计
     * </pre>
     *
     * <code>uint64 total_packets = 6 [json_name = "totalPackets"];</code>
     * @param value The totalPackets to set.
     * @return This builder for chaining.
     */
    public Builder setTotalPackets(long value) {

      totalPackets_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 结果统计
     * </pre>
     *
     * <code>uint64 total_packets = 6 [json_name = "totalPackets"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalPackets() {
      bitField0_ = (bitField0_ & ~0x00000020);
      totalPackets_ = 0L;
      onChanged();
      return this;
    }

    private long totalBytes_ ;
    /**
     * <code>uint64 total_bytes = 7 [json_name = "totalBytes"];</code>
     * @return The totalBytes.
     */
    @java.lang.Override
    public long getTotalBytes() {
      return totalBytes_;
    }
    /**
     * <code>uint64 total_bytes = 7 [json_name = "totalBytes"];</code>
     * @param value The totalBytes to set.
     * @return This builder for chaining.
     */
    public Builder setTotalBytes(long value) {

      totalBytes_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 total_bytes = 7 [json_name = "totalBytes"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalBytes() {
      bitField0_ = (bitField0_ & ~0x00000040);
      totalBytes_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:traffic.v1.PcapCutResponse)
  }

  // @@protoc_insertion_point(class_scope:traffic.v1.PcapCutResponse)
  private static final com.traffic.proto.v1.PcapCutResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.traffic.proto.v1.PcapCutResponse();
  }

  public static com.traffic.proto.v1.PcapCutResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PcapCutResponse>
      PARSER = new com.google.protobuf.AbstractParser<PcapCutResponse>() {
    @java.lang.Override
    public PcapCutResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PcapCutResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PcapCutResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.traffic.proto.v1.PcapCutResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

