// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: traffic/v1/ingest.proto
// Protobuf Java Version: 4.33.2

package com.traffic.proto.v1;

@com.google.protobuf.Generated
public interface ProbeStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:traffic.v1.ProbeStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * CPU 使用率 (0-100)
   * </pre>
   *
   * <code>float cpu_usage = 1 [json_name = "cpuUsage"];</code>
   * @return The cpuUsage.
   */
  float getCpuUsage();

  /**
   * <pre>
   * 内存使用率 (0-100)
   * </pre>
   *
   * <code>float memory_usage = 2 [json_name = "memoryUsage"];</code>
   * @return The memoryUsage.
   */
  float getMemoryUsage();

  /**
   * <pre>
   * 已捕获包数
   * </pre>
   *
   * <code>uint64 packets_captured = 3 [json_name = "packetsCaptured"];</code>
   * @return The packetsCaptured.
   */
  long getPacketsCaptured();

  /**
   * <pre>
   * 丢包数
   * </pre>
   *
   * <code>uint64 packets_dropped = 4 [json_name = "packetsDropped"];</code>
   * @return The packetsDropped.
   */
  long getPacketsDropped();

  /**
   * <pre>
   * 当前捕获速率
   * </pre>
   *
   * <code>float capture_pps = 5 [json_name = "capturePps"];</code>
   * @return The capturePps.
   */
  float getCapturePps();

  /**
   * <pre>
   * 当前上报速率
   * </pre>
   *
   * <code>float upload_bps = 6 [json_name = "uploadBps"];</code>
   * @return The uploadBps.
   */
  float getUploadBps();
}
