---
apiVersion: v1
kind: Namespace
metadata:
  name: middleware
  labels:
    name: middleware
---
apiVersion: v1
kind: Namespace
metadata:
  name: databases
  labels:
    name: databases
---
apiVersion: v1
kind: Namespace
metadata:
  name: traffic-analysis
  labels:
    name: traffic-analysis
---
apiVersion: v1
kind: Namespace
metadata:
  name: flink
  labels:
    name: flink
---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    name: observability
---
apiVersion: v1
kind: Namespace
metadata:
  name: gateway
  labels:
    name: gateway
---
apiVersion: v1
kind: Namespace
metadata:
  name: iam
  labels:
    name: iam
---
apiVersion: v1
kind: Namespace
metadata:
  name: nacos
  labels:
    name: nacos
---
apiVersion: v1
kind: Namespace
metadata:
  name: streampark
  labels:
    name: streampark
---
apiVersion: v1
kind: Namespace
metadata:
  name: argo
  labels:
    name: argo
---
apiVersion: v1
kind: Namespace
metadata:
  name: minio
  labels:
    name: minio
---
apiVersion: v1
kind: Namespace
metadata:
  name: registry
  labels:
    name: registry
