---
apiVersion: v1
items:
- apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"apps/v1","kind":"StatefulSet","metadata":{"annotations":{},"name":"flink-jobmanager","namespace":"flink"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"flink","component":"jobmanager"}},"serviceName":"flink-jobmanager","template":{"metadata":{"labels":{"app":"flink","component":"jobmanager"}},"spec":{"containers":[{"args":["jobmanager"],"env":[{"name":"FLINK_PROPERTIES","value":"jobmanager.rpc.address:
        flink-jobmanager.flink.svc\njobmanager.memory.process.size: 4g\ntaskmanager.memory.process.size:
        8g\ntaskmanager.numberOfTaskSlots: 16\nparallelism.default: 32\nstate.backend:
        rocksdb\nstate.backend.rocksdb.localdir: /home/k8s-data/flink-rocksdb"}],"image":"flink:1.18-scala_2.12","name":"jobmanager","ports":[{"containerPort":6123},{"containerPort":6124},{"containerPort":8081}],"resources":{"limits":{"cpu":"8000m","memory":"16Gi"},"requests":{"cpu":"2000m","memory":"6Gi"}}}],"nodeSelector":{"kubernetes.io/hostname":"8-2tb"},"tolerations":[{"key":"node-role.kubernetes.io/control-plane","operator":"Exists"}]}}}}

        '
    creationTimestamp: '2026-06-05T09:22:42Z'
    generation: 3
    name: flink-jobmanager
    namespace: flink
    resourceVersion: '1421442'
    uid: 5a26fb04-e288-4ecb-a681-a151abd54125
  spec:
    persistentVolumeClaimRetentionPolicy:
      whenDeleted: Retain
      whenScaled: Retain
    podManagementPolicy: OrderedReady
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: flink
        component: jobmanager
    serviceName: flink-jobmanager
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: flink
          component: jobmanager
      spec:
        containers:
        - args:
          - jobmanager
          env:
          - name: FLINK_PROPERTIES
            value: 'jobmanager.rpc.address: flink-jobmanager.flink.svc

              jobmanager.memory.process.size: 4g

              taskmanager.memory.process.size: 8g

              taskmanager.numberOfTaskSlots: 16

              parallelism.default: 32

              state.backend: rocksdb

              state.checkpoints.dir: s3://flink-checkpoints/

              state.savepoints.dir: s3://flink-savepoints/

              state.backend.rocksdb.localdir: /home/k8s-data/flink-rocksdb

              s3.endpoint: http://minio.minio.svc:9000

              s3.path.style.access: true

              fs.allowed-fallback-filesystems: s3

              high-availability.type: kubernetes

              high-availability.cluster-id: flink-traffic

              high-availability.storageDir: /tmp/flink-ha

              kubernetes.cluster-id: flink-traffic

              kubernetes.namespace: flink

              kubernetes.jobmanager.service-account: flink

              restart-strategy: fixed-delay

              restart-strategy.fixed-delay.attempts: 10

              restart-strategy.fixed-delay.delay: 10s'
          image: flink:1.18-scala_2.12
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 60
            periodSeconds: 20
            successThreshold: 1
            tcpSocket:
              port: 6123
            timeoutSeconds: 1
          name: jobmanager
          ports:
          - containerPort: 6123
            protocol: TCP
          - containerPort: 6124
            protocol: TCP
          - containerPort: 8081
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /overview
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: '8'
              memory: 16Gi
            requests:
              cpu: '2'
              memory: 6Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        serviceAccountName: flink
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
    updateStrategy:
      rollingUpdate:
        partition: 0
      type: RollingUpdate
  status:
    availableReplicas: 1
    collisionCount: 0
    currentReplicas: 1
    currentRevision: flink-jobmanager-57555588d5
    observedGeneration: 3
    readyReplicas: 1
    replicas: 1
    updateRevision: flink-jobmanager-57555588d5
    updatedReplicas: 1
- apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"apps/v1","kind":"StatefulSet","metadata":{"annotations":{},"name":"flink-taskmanager","namespace":"flink"},"spec":{"replicas":4,"selector":{"matchLabels":{"app":"flink","component":"taskmanager"}},"serviceName":"flink-taskmanager","template":{"metadata":{"labels":{"app":"flink","component":"taskmanager"}},"spec":{"containers":[{"args":["taskmanager"],"env":[{"name":"FLINK_PROPERTIES","value":"jobmanager.rpc.address:
        flink-jobmanager.flink.svc\ntaskmanager.memory.process.size: 8g\ntaskmanager.numberOfTaskSlots:
        16"}],"image":"flink:1.18-scala_2.12","name":"taskmanager","ports":[{"containerPort":6122}],"resources":{"limits":{"cpu":"16000m","memory":"32Gi"},"requests":{"cpu":"4000m","memory":"10Gi"}}}],"tolerations":[{"key":"node-role.kubernetes.io/control-plane","operator":"Exists"}]}}}}

        '
    creationTimestamp: '2026-06-05T09:22:42Z'
    generation: 5
    name: flink-taskmanager
    namespace: flink
    resourceVersion: '1421177'
    uid: 58664f4d-c955-4f38-bfa5-fc7e1f651e66
  spec:
    persistentVolumeClaimRetentionPolicy:
      whenDeleted: Retain
      whenScaled: Retain
    podManagementPolicy: OrderedReady
    replicas: 2
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: flink
        component: taskmanager
    serviceName: flink-taskmanager
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: flink
          component: taskmanager
      spec:
        containers:
        - args:
          - taskmanager
          env:
          - name: FLINK_PROPERTIES
            value: 'jobmanager.rpc.address: flink-jobmanager.flink.svc

              taskmanager.memory.process.size: 8g

              taskmanager.numberOfTaskSlots: 16

              state.backend: rocksdb

              state.checkpoints.dir: s3://flink-checkpoints/

              state.savepoints.dir: s3://flink-savepoints/

              state.backend.rocksdb.localdir: /home/k8s-data/flink-rocksdb

              s3.endpoint: http://minio.minio.svc:9000

              s3.path.style.access: true'
          image: flink:1.18-scala_2.12
          imagePullPolicy: IfNotPresent
          name: taskmanager
          ports:
          - containerPort: 6122
            protocol: TCP
          resources:
            limits:
              cpu: '16'
              memory: 32Gi
            requests:
              cpu: '4'
              memory: 10Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
    updateStrategy:
      rollingUpdate:
        partition: 0
      type: RollingUpdate
  status:
    availableReplicas: 1
    collisionCount: 0
    currentRevision: flink-taskmanager-55c99bcdc4
    observedGeneration: 5
    readyReplicas: 1
    replicas: 2
    updateRevision: flink-taskmanager-6f9ffb95f4
    updatedReplicas: 2
kind: List
metadata: {}

