---
apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"nebula","component":"meta"},"name":"nebula-meta","namespace":"middleware"},"spec":{"clusterIP":"None","ports":[{"name":"thrift","port":9559},{"name":"http","port":19559}],"publishNotReadyAddresses":true,"selector":{"app":"nebula","component":"meta"}}}

        '
    creationTimestamp: '2026-06-07T01:41:18Z'
    labels:
      app: nebula
      component: meta
    name: nebula-meta
    namespace: middleware
    resourceVersion: '1421252'
    uid: 4e30292a-3ce8-44e7-a956-44fa9ff1bf02
  spec:
    clusterIP: None
    clusterIPs:
    - None
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: thrift
      port: 9559
      protocol: TCP
      targetPort: 9559
    - name: http
      port: 19559
      protocol: TCP
      targetPort: 19559
    publishNotReadyAddresses: true
    selector:
      app: nebula
      component: meta
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"nebula-graph","namespace":"middleware"},"spec":{"loadBalancerIP":"10.0.5.224","ports":[{"name":"thrift","port":9669},{"name":"http","port":19669}],"selector":{"app":"nebula","component":"graph"},"type":"LoadBalancer"}}

        '
    creationTimestamp: '2026-06-07T01:06:52Z'
    name: nebula-graph
    namespace: middleware
    resourceVersion: '1421255'
    uid: 9cc1aae1-6844-4def-97f5-d5d6b240dd66
  spec:
    allocateLoadBalancerNodePorts: true
    clusterIP: 10.104.246.216
    clusterIPs:
    - 10.104.246.216
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    loadBalancerIP: 10.0.5.224
    ports:
    - name: thrift
      nodePort: 30069
      port: 9669
      protocol: TCP
      targetPort: 9669
    - name: http
      nodePort: 31179
      port: 19669
      protocol: TCP
      targetPort: 19669
    selector:
      app: nebula
      component: graph
    sessionAffinity: None
    type: LoadBalancer
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"nebula-graph-headless","namespace":"middleware"},"spec":{"clusterIP":"None","ports":[{"name":"thrift","port":9669},{"name":"http","port":19669}],"selector":{"app":"nebula","component":"graph"}}}

        '
    creationTimestamp: '2026-06-07T01:06:52Z'
    name: nebula-graph-headless
    namespace: middleware
    resourceVersion: '260515'
    uid: b33fc63b-2c6d-4436-a8a6-ef6b4464e3d4
  spec:
    clusterIP: None
    clusterIPs:
    - None
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: thrift
      port: 9669
      protocol: TCP
      targetPort: 9669
    - name: http
      port: 19669
      protocol: TCP
      targetPort: 19669
    selector:
      app: nebula
      component: graph
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"nebula-storage-headless","namespace":"middleware"},"spec":{"clusterIP":"None","ports":[{"name":"thrift","port":9777},{"name":"admin","port":9778},{"name":"http","port":19779}],"publishNotReadyAddresses":true,"selector":{"app":"nebula","component":"storage"}}}

        '
    creationTimestamp: '2026-06-07T01:06:52Z'
    name: nebula-storage-headless
    namespace: middleware
    resourceVersion: '1421257'
    uid: 3f40c342-ec1a-4f50-b843-cbd1d4c50a7b
  spec:
    clusterIP: None
    clusterIPs:
    - None
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: thrift
      port: 9777
      protocol: TCP
      targetPort: 9777
    - name: admin
      port: 9778
      protocol: TCP
      targetPort: 9778
    - name: http
      port: 19779
      protocol: TCP
      targetPort: 19779
    publishNotReadyAddresses: true
    selector:
      app: nebula
      component: storage
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata: {}

