apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"creationTimestamp":null,"name":"nebula-proxy","namespace":"middleware"},"spec":{"ports":[{"port":7002,"protocol":"TCP","targetPort":7002}],"selector":{"app":"nebula-proxy"}},"status":{"loadBalancer":{}}}
  creationTimestamp: "2026-06-12T01:33:37Z"
  name: nebula-proxy
  namespace: middleware
  resourceVersion: "1023281"
  uid: 23492611-95bc-49c0-b4a8-7c8f87de469c
spec:
  clusterIP: 10.100.127.113
  clusterIPs:
  - 10.100.127.113
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 7002
    protocol: TCP
    targetPort: 7002
  selector:
    app: nebula-proxy
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
