apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"creationTimestamp":null,"name":"streampark-proxy","namespace":"streampark"},"spec":{"ports":[{"port":8080,"protocol":"TCP","targetPort":8080}],"selector":{"app":"streampark-proxy"}},"status":{"loadBalancer":{}}}
  creationTimestamp: "2026-06-12T01:33:28Z"
  name: streampark-proxy
  namespace: streampark
  resourceVersion: "1023237"
  uid: ba7099cc-f482-49e3-a57d-98bb9ae534ac
spec:
  clusterIP: 10.111.213.101
  clusterIPs:
  - 10.111.213.101
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: streampark-proxy
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
