apiVersion: v1
kind: ConfigMap
metadata: {name: workflow-controller-configmap, namespace: argo}
data:
  artifactRepository: |
    s3:
      bucket: argo-artifacts
      endpoint: minio.minio.svc:9000
      insecure: false
      caSecret:
        name: minio-client-ca
        key: ca.crt
      accessKeySecret:
        name: minio-argo-artifact-credentials
        key: accesskey
      secretKeySecret:
        name: minio-argo-artifact-credentials
        key: secretkey
