---
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets-source
  labels:
    app.kubernetes.io/name: external-secrets-source
    traffic-platform.io/security-profile: external-secrets-production
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eso-kubernetes-provider-prod-reader
  namespace: external-secrets-source
  labels:
    app.kubernetes.io/name: external-secrets-source
    traffic-platform.io/security-profile: external-secrets-production
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: eso-kubernetes-provider-prod-reader
  namespace: external-secrets-source
  labels:
    app.kubernetes.io/name: external-secrets-source
    traffic-platform.io/security-profile: external-secrets-production
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eso-kubernetes-provider-prod-reader
  namespace: external-secrets-source
  labels:
    app.kubernetes.io/name: external-secrets-source
    traffic-platform.io/security-profile: external-secrets-production
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: eso-kubernetes-provider-prod-reader
subjects:
  - kind: ServiceAccount
    name: eso-kubernetes-provider-prod-reader
    namespace: external-secrets-source
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: traffic-platform-secret-store
  labels:
    app.kubernetes.io/name: traffic-platform-secret-store
    traffic-platform.io/security-profile: external-secrets-production
spec:
  provider:
    kubernetes:
      remoteNamespace: external-secrets-source
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          namespace: external-secrets-source
          key: ca.crt
      auth:
        serviceAccount:
          name: eso-kubernetes-provider-prod-reader
          namespace: external-secrets-source
