import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

const sourceRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const page = fs.readFileSync(path.join(sourceRoot, 'pages', 'CampaignWorkbenchPage.tsx'), 'utf8');
const styles = fs.readFileSync(path.join(sourceRoot, 'styles', 'pages.css'), 'utf8');
const drawerStyles = fs.readFileSync(path.join(sourceRoot, 'styles', 'campaign-workbench-drawer.css'), 'utf8');
const main = fs.readFileSync(path.join(sourceRoot, 'main.tsx'), 'utf8');
const charts = fs.readFileSync(path.join(sourceRoot, 'components', 'charts.tsx'), 'utf8');

describe('campaign workbench business contract', () => {
  it('uses dynamic ECharts instead of decorative progress rings', () => {
    expect(page).toContain("import { CampaignAttackGraphChart, DataQualityDonutChart } from '@/components/charts'");
    expect(page.match(/<DataQualityDonutChart/g)).toHaveLength(2);
    expect(page).toContain('<CampaignAttackGraphChart');
    expect(page).not.toContain('className="taf-campaign-node');
    expect(charts).toContain('export function CampaignAttackGraphChart');
    expect(charts).toContain("name: '战役阶段关联图'");
    expect(charts).toContain("type: 'lines'");
    expect(charts).toContain("type: 'scatter'");
    expect(charts).toContain('data-chart-engine="echarts"');
    expect(charts).toContain('data-series-type="lines+scatter"');
    expect(styles).not.toContain('.taf-campaign-node::before');
    expect(page).toContain('战役风险分布动态图');
    expect(page).toContain('战役证据完整度动态图');
    expect(page).not.toContain('<Progress');
  });

  it('keeps filters, pagination, and all visible actions interactive', () => {
    expect(page).toContain('filterDraft');
    expect(page).toContain('setAppliedFilters(filterDraft)');
    expect(page).toContain('onPressEnter={onSubmit}');
    expect(page).toContain('current: page');
    expect(page).toContain('setPageSize(visualBreakdownMode ? 10 : 8)');
    expect(page).toContain('setPageSize(nextPageSize)');
    expect(page).toContain("queryKey: ['page-snapshot', route.id, requestPage, requestPageSize, appliedFilters]");
    expect(page).toContain('fetchPageSnapshot(route.id, { page: requestPage, pageSize: requestPageSize, campaignFilters: appliedFilters })');
    expect(page).toContain("message.success('已提交服务端查询')");
    expect(page).toContain('visualBreakdownMode ? buildCampaignSimulationRows(apiRows, campaignTotal) : apiRows');
    expect(page).toContain('showTotal: (total) => `共 ${total} 条`');
    expect(page).toContain("submitCampaignAction");
    expect(page).toContain("'campaign-export'");
    expect(page).toContain("'campaign-phase-inspect'");
    expect(page).toContain("'campaign-impact-inspect'");
    expect(page).toContain("'campaign-evidence-view'");
    expect(page).toContain("'campaign-soar-response'");
    expect(page).toContain('导出当前页');
    expect(page).toContain('变更状态');
    expect(page).toContain('SOAR 处置');
    expect(page).not.toContain("'进入 SOAR 处置'");
    expect(page).not.toContain('模拟变更状态');
    expect(page).toContain("'campaign-list-settings'");
    expect(page).toContain("onAction('detail')");
    expect(page).toContain("onAction('status')");
    expect(page).toContain("onAction('more')");
    expect(page).toContain("mode === 'server-persisted-mutation'");
    expect(page).toContain('detail?.evidenceCompletenessAvailable');
    expect(page).toContain("detail?.phaseDataBacked");
    expect(page).toContain("percentAvailable ? `${percent}%` : '--'");
    expect(page).toContain("value: `${current} / ${expected}`");
    expect(page).toContain('detail?.statusTransitions');
    expect(page).toContain('<CaretRightOutlined aria-hidden="true" />');
    expect(page).toContain("['新建', '06-19 09:15', false]");
    expect(page).toContain("['活跃中', '06-20 03:22', true]");
    expect(page).toContain('当前没有可操作的战役');
    expect(page).toContain('需要 alert:write');
    expect(page).toContain('需要 playbook:execute');
    expect(page).not.toContain('campaignEvidenceCompletionPercent');
    expect(page).not.toContain('const ratios = items');
    expect(page).toContain('className="taf-campaign-action-drawer"');
    expect(page).toContain('rootClassName="taf-campaign-detail-drawer"');
    expect(page).toContain('placement="right"');
    expect(page).toContain('width="min(1200px, calc(100dvw - 48px))"');
    expect(page).toContain('const selectCampaign = (record: SnapshotRow) =>');
    expect(page).toContain("next.set('campaign', targetId)");
    expect(page).toContain('onClick: () => selectCampaign(record)');
    expect(page).toContain("'aria-selected': selectedRow ? rowKey(record) === rowKey(selectedRow) : false");
    expect(page).toContain('aria-label="关闭战役详情"');
    expect(page).toContain('className="taf-detail-drawer-tabs"');
    expect(page).toContain("{ key: 'evidence', label: '证据' }");
    expect(page).toContain("{ key: 'audit', label: '审计' }");
    expect(page).toContain("next.set('detailTab', tab)");
    expect(page).toContain("setActiveTab(requestedTab && ['detail', 'evidence', 'audit'].includes(requestedTab) ? requestedTab : 'detail')");
    expect(page).toContain('/attack-chains?chain=${encodedId}');
    expect(page).toContain("next.set('drawer', 'campaign-detail')");
    expect(page).toContain("next.delete('drawer')");
    expect(page).toContain('okButtonProps={{ loading: pending }}');
    expect(page).toContain('disabled={pending}');
    expect(page).toContain('detail={detailQuery.data}');
    expect(page).toContain('campaignImpactValue(detail, label');
    expect(page).toContain('campaignImpactRouteId(scope)');
    expect(page).toContain('setImpactOpen(true)');
    expect(page).toContain('<CampaignImpactModalContent');
    expect(page).toContain('width="min(1040px, calc(100dvw - 96px))"');
    expect(page).not.toContain('navigate(`/campaigns/${encodeURIComponent(selectedCampaignId)}?impact=');
    expect(page).toContain('确认提交处置建议？');
    expect(page).not.toMatch(/<Modal[\s\S]*className="taf-campaign-detail-drawer"/);
    expect(page).toContain('fetchCampaignDetailSnapshot');
    expect(page).toContain('打开完整详情');
    expect(styles).toContain('.taf-campaign-list-panel .ant-table-content');
    expect(styles).toContain('scrollbar-gutter: stable;');
    expect(styles).not.toMatch(/\.taf-campaign-workbench\s*\{[^}]*margin-left:\s*24px/s);
    expect(styles).not.toMatch(/\.taf-campaign-workbench\s*\{[^}]*margin-top:\s*-8px/s);
    expect(styles).toContain('.taf-campaign-evidence-list > span');
    expect(styles).toContain('.taf-campaign-state-step > .anticon');
    expect(styles).toContain('.taf-campaign-detail-drawer .ant-drawer-content-wrapper');
    expect(styles).toContain('right: 40px;');
    expect(styles).toContain('max-height: calc(100dvh - 96px);');
    expect(main).toContain("import '@/styles/campaign-workbench-drawer.css'");
    expect(drawerStyles).toContain('right: 16px;');
    expect(drawerStyles).toContain('max-height: calc(100dvh - 32px);');
    expect(drawerStyles).toContain('.taf-campaign-detail-drawer__workspace[data-active-tab="audit"] > aside:last-child');
    expect(styles).not.toMatch(/\.taf-campaign-evidence span\s*\{/);
    expect(styles).not.toMatch(/\.taf-campaign-evidence-list\s+span\s*\{/);
  });
});
