import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

const sourceRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const pagePath = path.join(sourceRoot, 'pages', 'EncryptedTrafficPage.tsx');
const appShellPath = path.join(sourceRoot, 'layouts', 'AppShell.tsx');
const adapterPath = path.join(sourceRoot, 'services', 'pageSnapshotAdapters.ts');
const apiPlanPath = path.join(sourceRoot, 'services', 'pageApiPlans.ts');
const stylesPath = path.join(sourceRoot, 'styles', 'pages.css');

const read = (filePath: string) => fs.readFileSync(filePath, 'utf8');

describe('encrypted traffic visual implementation', () => {
  it('keeps encrypted traffic data-driven and free of target bitmap replay', () => {
    const page = read(pagePath);
    const adapter = read(adapterPath);
    const apiPlan = read(apiPlanPath);

    expect(page).toContain("queryKey: ['page-snapshot', route.id, timeRange]");
    expect(page).toContain('queryFn: () => fetchPageSnapshot(route.id, { timeRange })');
    expect(page).toContain('data?.visuals?.encryptedTraffic');
    expect(page).toContain('<ProtocolDistribution rows={encryptedVisuals?.protocolRows} trend={encryptedVisuals?.protocolTrend} />');
    expect(page).toContain('<Ja3Table rows={encryptedVisuals?.ja3Rows} />');
    expect(page).toContain('<TunnelFeatureCards rows={encryptedVisuals?.tunnelCards} />');
    expect(page).toContain('<EgressProfile visuals={encryptedVisuals} />');
    expect(page).toContain("const activeTab = resolveEncryptedTrafficTab(searchParams.get('tab'))");
    expect(page).toContain("if (activeTab === 'fingerprint') return <FingerprintContent visuals={encryptedVisuals} />");
    expect(page).toContain("if (activeTab === 'tunnel-detection') return <TunnelDetectionContent visuals={encryptedVisuals} />");
    expect(page).toContain("if (activeTab === 'egress-profile') {");
    expect(page).toContain('<EgressProfileContent');
    expect(page).toContain("{ label: '指纹分析', slug: 'fingerprint' }");
    expect(page).toContain("{ label: '隧道检测', slug: 'tunnel-detection' }");
    expect(page).toContain("{ label: '外联画像', slug: 'egress-profile' }");
    expect(page).toContain("{ label: '证据中心', slug: 'evidence-center' }");
    expect(page).toContain('function FingerprintContent({ visuals }: { visuals?: EncryptedTrafficVisuals })');
    expect(page).toContain('<div className="taf-encrypted-fingerprint-layout">');
    expect(page).toContain('<Ja3Table rows={visuals?.ja3Rows} />');
    expect(page).toContain('<Ja3Scatter points={visuals?.scatterPoints} />');
    expect(page).toContain('rows={visuals?.certificateRows ?? certificateRows}');
    expect(page).toContain('<AdviceList rows={visuals?.adviceRows} />');
    expect(page).toContain('function TunnelDetectionContent({ visuals }: { visuals?: EncryptedTrafficVisuals })');
    expect(page).toContain('<div className="taf-encrypted-tunnel-layout">');
    expect(page).toContain('<TunnelFeatureCards rows={visuals?.tunnelCards} />');
    expect(page).toContain('<TunnelTable rows={visuals?.tunnelRows} />');
    expect(page).toContain('<HeartbeatSeries bars={visuals?.heartbeatBars} />');
    expect(page).toContain('rows={visuals?.tunnelRuleRows ?? tunnelRuleRows}');
    expect(page).toContain("rows={(visuals?.evidenceRows ?? evidenceRows).slice(0, 3)}");
    expect(page).toContain("['可疑 VPN / Proxy', '特征端口/协议指纹', '会话 > 2', '118', '89%', '创建告警']");
    expect(page).toContain('const heartbeatBars = bars && bars.length >= 24 ? bars : fallbackBars;');
    expect(page).toContain('function EgressProfileContent({');
    expect(page).toContain('<div className="taf-egress-board">');
    expect(page).toContain('<EgressAvailability availability={visuals?.egressAvailability} />');
    expect(page).toContain('egressMapNodes');
    expect(page).toContain('function EgressDestinationTable({');
    expect(page).toContain('function EgressAnomalyTrend({');
    expect(page).toContain('function EgressEntityGraph({');
    expect(page).toContain('function EgressActionRail({');
    expect(page).toContain('<WorldActivityMap');
    expect(page).toContain('variant="egress"');
    expect(page).toContain('<ExfilStackedTrendChart');
    expect(page).toContain('<ExfilGraphChart');
    expect(page).toContain('<PcapPacketTrendChart');
    expect(page).toContain('<EvidenceClosureRingChart');
    expect(page).toContain('<EvidenceEntropyTrendChart');
    expect(read(path.join(sourceRoot, 'components', 'charts.tsx'))).toContain('export function EvidenceEntropyTrendChart');
    expect(read(path.join(sourceRoot, 'components', 'charts.tsx'))).toMatch(/EvidenceEntropyTrendChart[\s\S]*?animation: false/);
    expect(page).toContain('function EvidenceAnchorPanel({');
    expect(page).toContain('<EncryptedProtocolTrendChart');
    expect(page).toContain('<EncryptedJa3ScatterChart');
    expect(page).toContain('<HeartbeatTrendChart');
    expect(page).toContain('function EvidenceCenterRail({');
    expect(page).toMatch(/时间范围[\s\S]*?刷新加密流量[\s\S]*?一键分析[\s\S]*?<OverlayContractHost overlays={encryptedTrafficOverlays} compact \/>/);
    expect(page).toContain('const [timeRange, setTimeRange] = useState');
    expect(page).toContain('const runEncryptedTrafficAnalysis = async () =>');
    expect(page).toContain("createEvidenceAction('关联证据分析', currentEvidenceTarget)");
    expect(page).toContain('onLocate={(filters) => {');
    expect(page).toContain('matchesEvidenceLocateFilters(item, locateFilters)');
    expect(page).toContain('function matchesEvidenceLocateFilters(');
    expect(page).toContain('className="taf-encrypted-kpis taf-encrypted-kpis--evidence"');
    expect(page).toContain("onAction('下载 PCAP', currentTarget)");
    expect(page).toContain("onAction('校验证据 Hash', currentTarget)");
    expect(page).toContain("onAction('生成取证任务', currentTarget)");
    expect(page).toContain('submitEncryptedTrafficEvidenceAction');
    expect(page).toContain('onNodeClick={(name) => onSelectDestination?.(name)}');
    expect(page).toContain('selected: node.label === selectedDestination');
    expect(page).toContain('submitEncryptedTrafficEgressAction');
    expect(page).toContain('接口失败不会显示成功');
    expect(page).toContain('onNavigate(`/alerts?destination=${encodeURIComponent(target)}`)');
    expect(page).toContain('anchor.download = `encrypted-egress-${Date.now()}.json`;');
    expect(page).toContain('document.body.append(anchor);');
    expect(page).toContain('function DomainCards({');
    expect(page).toContain('const cards = visuals?.egressDomainCards ?? [];');
    expect(page).not.toContain('buildDomainCards');
    expect(page).not.toMatch(/encrypted-traffic\.(?:png|jpe?g|webp)/i);
    expect(page).not.toMatch(/implementation\.html/i);
    expect(page).not.toMatch(/ui-image-breakdowns/i);
    expect(page).not.toMatch(/screens\/pages/i);
    expect(page).not.toContain('className="taf-encrypted-donut"');
    expect(page).not.toContain('className="taf-encrypted-trend"');

    expect(adapter).toContain("if (page.id === 'encrypted-traffic') return adaptEncryptedTraffic(page, primaryPayload, secondaryPayloads);");
    expect(adapter).toContain('const buildEncryptedTrafficVisuals');
    expect(adapter).toContain('encryptedTraffic: buildEncryptedTrafficVisuals');
    expect(adapter).toContain('rawEgressSources: exfilSources');
    expect(adapter).toContain('const egressAvailability = {');
    expect(adapter).toContain('const egressMapNodes = destinationRows.map');
    expect(adapter).toContain('const useSimulatedEgress = !rawEgressDestinations.length && !rawEgressPaths.length && !rawEgressSessions.length;');
    expect(adapter).toContain("const exfilDestinations = extractNamedList(secondaryPayloads[3], ['top_destinations', 'destinations']);");
    expect(adapter).toContain('const egressTrend = buildEncryptedEgressTrend(rawEgressTrend, useSimulatedEgress);');
    expect(adapter).toContain('const evidenceSessions = extractNamedList(secondaryPayloads[4], [\'sessions\']);');
    expect(adapter).toContain('const buildEncryptedEvidenceCenter');
    expect(adapter).toContain('rawEvidencePcapIndexes: evidencePcapIndexes');
    expect(adapter).toContain('rawEvidenceEntropyTrend: evidenceEntropyTrend');
    expect(adapter).toContain('const useSimulatedEvidence = !rawSessions.length && !rawPcapIndexes.length && !rawPcapTrend.length;');
    expect(adapter).toContain("'simulated'");
    expect(adapter).toContain("'等待外传 API'");
    expect(adapter).toContain("evidence('Encrypted Stats API', '/v1/encrypted-traffic/stats', 'ok')");

    expect(apiPlan).toContain("primary: '/v1/encrypted-traffic/stats'");
    expect(apiPlan).toContain("'/v1/encrypted-traffic/sessions'");
    expect(apiPlan).toContain("'/v1/encrypted-traffic/ja3'");
    expect(apiPlan).toContain("'/v1/encrypted-traffic/tunnels'");
    expect(apiPlan).toContain("'/v1/encrypted-traffic/exfiltration'");
    expect(apiPlan).toContain("'/v1/encrypted-traffic/evidence'");
    expect(apiPlan).toContain("endpoint: '/v1/encrypted-traffic/evidence-actions'");
    expect(apiPlan).toContain("auditEvent: 'ENCRYPTED_EVIDENCE_TASK_REQUESTED'");
    expect(apiPlan).toContain("endpoint: '/v1/encrypted-traffic/egress-actions'");
    expect(apiPlan).toContain("auditEvent: 'ENCRYPTED_EGRESS_ALERT_REQUESTED'");
    expect(read(path.join(sourceRoot, 'services', 'api.ts'))).toContain("export type EncryptedTrafficTimeRange = '近 1 小时' | '近 24 小时' | '近 7 天';");
    expect(read(path.join(sourceRoot, 'services', 'api.ts'))).toContain('start_time: endTime - encryptedTrafficRangeMilliseconds[timeRange]');
    expect(read(path.join(sourceRoot, 'services', 'api.ts'))).toContain('end_time: endTime');
  });

  it('keeps the five primary tabs on one shared shell and fixed desktop tracks', () => {
    const styles = read(stylesPath);
    const appShell = read(appShellPath);

    expect(styles).toContain('grid-template-columns: repeat(5, 88px);');
    expect(styles).toContain('width: 88px;');
    expect(styles).toContain('.taf-encrypted {\n  height: 100%;');
    expect(styles).toContain('flex: 0 0 92px;');
    expect(styles).toContain('taf-shell--encrypted-traffic .taf-encrypted-tabs');
    expect(styles).toContain('position: absolute;');
    expect(styles).toContain('taf-shell--encrypted-traffic .taf-encrypted-grid');
    expect(styles).toContain('taf-shell--encrypted-traffic .taf-encrypted-controls');
    expect(styles).toContain('taf-encrypted-kpis--evidence');
    expect(styles).toContain('taf-evidence-pcap-actions');
    expect(styles).toContain('grid-template-columns: minmax(0, 1.15fr) minmax(0, 0.8fr) minmax(250px, 0.55fr);');
    expect(styles).toContain('.taf-evidence-main-grid > .taf-panel { height: 440px; }');
    expect(styles).toContain('.taf-evidence-bottom-grid > .taf-panel { min-height: 330px; }');
    expect(styles).toContain('flex: 1 1 0;');
    expect(styles).toContain('scrollbar-gutter: stable;');
    expect(styles).not.toContain('taf-shell--encrypted-evidence-target');
    expect(styles).not.toContain('.taf-shell--encrypted-traffic .taf-main {');
    expect(styles).not.toContain('.taf-shell--encrypted-traffic .taf-encrypted {');
    expect(styles).not.toContain('margin: 9px 0 9px 105px;');
    expect(styles).not.toContain('transform: translateY(-150px);');
    expect(appShell).not.toContain('encryptedEvidenceTarget');
    expect(appShell).not.toContain('taf-shell--encrypted-evidence-target');
    expect(appShell).not.toContain('交通流量分析平台');
  });
});
