ARG RUNTIME_IMAGE=debian:bookworm-slim@sha256:abd67ffcfa541b485a3dff59865ab629aa048a6c613e639d36e7456b0b229241
FROM ${RUNTIME_IMAGE}

ARG GO_VERSION=go1.25.12
ARG SOURCE_REVISION=working-tree
COPY --chmod=0555 pki.test /opt/m10-pki/pki.test
COPY --chmod=0555 run_m10_pki_test_binary.sh /usr/local/bin/run-m10-pki-tests
LABEL org.opencontainers.image.title="T1-M10-N008 atomic PKI rotation tests" \
      org.opencontainers.image.version="n008-v1" \
      org.opencontainers.image.revision=${SOURCE_REVISION} \
      traffic.analysis/go-version=${GO_VERSION}
USER 65532:65532
ENTRYPOINT ["/usr/local/bin/run-m10-pki-tests"]
