// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: traffic/v1/ingest.proto

// Protobuf Java Version: 3.25.2
package com.traffic.proto.traffic.v1;

/**
 * Protobuf enum {@code traffic.v1.AssetBindingItemDisposition}
 */
public enum AssetBindingItemDisposition
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>ASSET_BINDING_ITEM_DISPOSITION_UNSPECIFIED = 0;</code>
   */
  ASSET_BINDING_ITEM_DISPOSITION_UNSPECIFIED(0),
  /**
   * <code>ASSET_BINDING_ITEM_DISPOSITION_KAFKA_ACKED = 1;</code>
   */
  ASSET_BINDING_ITEM_DISPOSITION_KAFKA_ACKED(1),
  /**
   * <code>ASSET_BINDING_ITEM_DISPOSITION_DUPLICATE_COMMITTED = 2;</code>
   */
  ASSET_BINDING_ITEM_DISPOSITION_DUPLICATE_COMMITTED(2),
  /**
   * <code>ASSET_BINDING_ITEM_DISPOSITION_REJECTED_INVALID = 3;</code>
   */
  ASSET_BINDING_ITEM_DISPOSITION_REJECTED_INVALID(3),
  /**
   * <code>ASSET_BINDING_ITEM_DISPOSITION_RETRYABLE = 4;</code>
   */
  ASSET_BINDING_ITEM_DISPOSITION_RETRYABLE(4),
  /**
   * <code>ASSET_BINDING_ITEM_DISPOSITION_OUTCOME_UNKNOWN = 5;</code>
   */
  ASSET_BINDING_ITEM_DISPOSITION_OUTCOME_UNKNOWN(5),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>ASSET_BINDING_ITEM_DISPOSITION_UNSPECIFIED = 0;</code>
   */
  public static final int ASSET_BINDING_ITEM_DISPOSITION_UNSPECIFIED_VALUE = 0;
  /**
   * <code>ASSET_BINDING_ITEM_DISPOSITION_KAFKA_ACKED = 1;</code>
   */
  public static final int ASSET_BINDING_ITEM_DISPOSITION_KAFKA_ACKED_VALUE = 1;
  /**
   * <code>ASSET_BINDING_ITEM_DISPOSITION_DUPLICATE_COMMITTED = 2;</code>
   */
  public static final int ASSET_BINDING_ITEM_DISPOSITION_DUPLICATE_COMMITTED_VALUE = 2;
  /**
   * <code>ASSET_BINDING_ITEM_DISPOSITION_REJECTED_INVALID = 3;</code>
   */
  public static final int ASSET_BINDING_ITEM_DISPOSITION_REJECTED_INVALID_VALUE = 3;
  /**
   * <code>ASSET_BINDING_ITEM_DISPOSITION_RETRYABLE = 4;</code>
   */
  public static final int ASSET_BINDING_ITEM_DISPOSITION_RETRYABLE_VALUE = 4;
  /**
   * <code>ASSET_BINDING_ITEM_DISPOSITION_OUTCOME_UNKNOWN = 5;</code>
   */
  public static final int ASSET_BINDING_ITEM_DISPOSITION_OUTCOME_UNKNOWN_VALUE = 5;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static AssetBindingItemDisposition valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static AssetBindingItemDisposition forNumber(int value) {
    switch (value) {
      case 0: return ASSET_BINDING_ITEM_DISPOSITION_UNSPECIFIED;
      case 1: return ASSET_BINDING_ITEM_DISPOSITION_KAFKA_ACKED;
      case 2: return ASSET_BINDING_ITEM_DISPOSITION_DUPLICATE_COMMITTED;
      case 3: return ASSET_BINDING_ITEM_DISPOSITION_REJECTED_INVALID;
      case 4: return ASSET_BINDING_ITEM_DISPOSITION_RETRYABLE;
      case 5: return ASSET_BINDING_ITEM_DISPOSITION_OUTCOME_UNKNOWN;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<AssetBindingItemDisposition>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      AssetBindingItemDisposition> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<AssetBindingItemDisposition>() {
          public AssetBindingItemDisposition findValueByNumber(int number) {
            return AssetBindingItemDisposition.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.traffic.proto.traffic.v1.IngestProto.getDescriptor().getEnumTypes().get(1);
  }

  private static final AssetBindingItemDisposition[] VALUES = values();

  public static AssetBindingItemDisposition valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private AssetBindingItemDisposition(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:traffic.v1.AssetBindingItemDisposition)
}
