// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: traffic/v1/campaign.proto

// Protobuf Java Version: 3.25.2
package com.traffic.proto.traffic.v1;

public interface CampaignQueryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:traffic.v1.CampaignQuery)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string tenant_id = 1 [json_name = "tenantId"];</code>
   * @return The tenantId.
   */
  java.lang.String getTenantId();
  /**
   * <code>string tenant_id = 1 [json_name = "tenantId"];</code>
   * @return The bytes for tenantId.
   */
  com.google.protobuf.ByteString
      getTenantIdBytes();

  /**
   * <code>string campaign_id = 2 [json_name = "campaignId"];</code>
   * @return The campaignId.
   */
  java.lang.String getCampaignId();
  /**
   * <code>string campaign_id = 2 [json_name = "campaignId"];</code>
   * @return The bytes for campaignId.
   */
  com.google.protobuf.ByteString
      getCampaignIdBytes();

  /**
   * <code>int64 start_time = 3 [json_name = "startTime"];</code>
   * @return The startTime.
   */
  long getStartTime();

  /**
   * <code>int64 end_time = 4 [json_name = "endTime"];</code>
   * @return The endTime.
   */
  long getEndTime();

  /**
   * <code>repeated string campaign_types = 5 [json_name = "campaignTypes"];</code>
   * @return A list containing the campaignTypes.
   */
  java.util.List<java.lang.String>
      getCampaignTypesList();
  /**
   * <code>repeated string campaign_types = 5 [json_name = "campaignTypes"];</code>
   * @return The count of campaignTypes.
   */
  int getCampaignTypesCount();
  /**
   * <code>repeated string campaign_types = 5 [json_name = "campaignTypes"];</code>
   * @param index The index of the element to return.
   * @return The campaignTypes at the given index.
   */
  java.lang.String getCampaignTypes(int index);
  /**
   * <code>repeated string campaign_types = 5 [json_name = "campaignTypes"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the campaignTypes at the given index.
   */
  com.google.protobuf.ByteString
      getCampaignTypesBytes(int index);
}
