// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: traffic/v1/ingest.proto

// Protobuf Java Version: 3.25.2
package com.traffic.proto.traffic.v1;

public interface CPUAffinityConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:traffic.v1.CPUAffinityConfig)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated uint32 cpu_cores = 1 [json_name = "cpuCores"];</code>
   * @return A list containing the cpuCores.
   */
  java.util.List<java.lang.Integer> getCpuCoresList();
  /**
   * <code>repeated uint32 cpu_cores = 1 [json_name = "cpuCores"];</code>
   * @return The count of cpuCores.
   */
  int getCpuCoresCount();
  /**
   * <code>repeated uint32 cpu_cores = 1 [json_name = "cpuCores"];</code>
   * @param index The index of the element to return.
   * @return The cpuCores at the given index.
   */
  int getCpuCores(int index);

  /**
   * <code>bool numa_aware = 2 [json_name = "numaAware"];</code>
   * @return The numaAware.
   */
  boolean getNumaAware();
}
