// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: traffic/v1/audit.proto

// Protobuf Java Version: 3.25.2
package com.traffic.proto.traffic.v1;

/**
 * <pre>
 * DeadLetter — 死信队列 (Kafka: dlq.v1)
 * </pre>
 *
 * Protobuf type {@code traffic.v1.DeadLetter}
 */
public final class DeadLetter extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:traffic.v1.DeadLetter)
    DeadLetterOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DeadLetter.newBuilder() to construct.
  private DeadLetter(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DeadLetter() {
    eventId_ = "";
    tenantId_ = "";
    sourceTopic_ = "";
    sourceKey_ = "";
    errorMsg_ = "";
    rawPayload_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DeadLetter();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.traffic.proto.traffic.v1.AuditProto.internal_static_traffic_v1_DeadLetter_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.traffic.proto.traffic.v1.AuditProto.internal_static_traffic_v1_DeadLetter_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.traffic.proto.traffic.v1.DeadLetter.class, com.traffic.proto.traffic.v1.DeadLetter.Builder.class);
  }

  public static final int EVENT_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object eventId_ = "";
  /**
   * <code>string event_id = 1 [json_name = "eventId"];</code>
   * @return The eventId.
   */
  @java.lang.Override
  public java.lang.String getEventId() {
    java.lang.Object ref = eventId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      eventId_ = s;
      return s;
    }
  }
  /**
   * <code>string event_id = 1 [json_name = "eventId"];</code>
   * @return The bytes for eventId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEventIdBytes() {
    java.lang.Object ref = eventId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      eventId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TENANT_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object tenantId_ = "";
  /**
   * <code>string tenant_id = 2 [json_name = "tenantId"];</code>
   * @return The tenantId.
   */
  @java.lang.Override
  public java.lang.String getTenantId() {
    java.lang.Object ref = tenantId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tenantId_ = s;
      return s;
    }
  }
  /**
   * <code>string tenant_id = 2 [json_name = "tenantId"];</code>
   * @return The bytes for tenantId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTenantIdBytes() {
    java.lang.Object ref = tenantId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tenantId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SOURCE_TOPIC_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sourceTopic_ = "";
  /**
   * <code>string source_topic = 3 [json_name = "sourceTopic"];</code>
   * @return The sourceTopic.
   */
  @java.lang.Override
  public java.lang.String getSourceTopic() {
    java.lang.Object ref = sourceTopic_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sourceTopic_ = s;
      return s;
    }
  }
  /**
   * <code>string source_topic = 3 [json_name = "sourceTopic"];</code>
   * @return The bytes for sourceTopic.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSourceTopicBytes() {
    java.lang.Object ref = sourceTopic_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sourceTopic_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SOURCE_KEY_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sourceKey_ = "";
  /**
   * <code>string source_key = 4 [json_name = "sourceKey"];</code>
   * @return The sourceKey.
   */
  @java.lang.Override
  public java.lang.String getSourceKey() {
    java.lang.Object ref = sourceKey_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sourceKey_ = s;
      return s;
    }
  }
  /**
   * <code>string source_key = 4 [json_name = "sourceKey"];</code>
   * @return The bytes for sourceKey.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSourceKeyBytes() {
    java.lang.Object ref = sourceKey_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sourceKey_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ERROR_MSG_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object errorMsg_ = "";
  /**
   * <code>string error_msg = 5 [json_name = "errorMsg"];</code>
   * @return The errorMsg.
   */
  @java.lang.Override
  public java.lang.String getErrorMsg() {
    java.lang.Object ref = errorMsg_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      errorMsg_ = s;
      return s;
    }
  }
  /**
   * <code>string error_msg = 5 [json_name = "errorMsg"];</code>
   * @return The bytes for errorMsg.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getErrorMsgBytes() {
    java.lang.Object ref = errorMsg_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      errorMsg_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RAW_PAYLOAD_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object rawPayload_ = "";
  /**
   * <code>string raw_payload = 6 [json_name = "rawPayload"];</code>
   * @return The rawPayload.
   */
  @java.lang.Override
  public java.lang.String getRawPayload() {
    java.lang.Object ref = rawPayload_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      rawPayload_ = s;
      return s;
    }
  }
  /**
   * <code>string raw_payload = 6 [json_name = "rawPayload"];</code>
   * @return The bytes for rawPayload.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRawPayloadBytes() {
    java.lang.Object ref = rawPayload_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      rawPayload_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RETRY_COUNT_FIELD_NUMBER = 7;
  private int retryCount_ = 0;
  /**
   * <code>uint32 retry_count = 7 [json_name = "retryCount"];</code>
   * @return The retryCount.
   */
  @java.lang.Override
  public int getRetryCount() {
    return retryCount_;
  }

  public static final int CREATED_AT_FIELD_NUMBER = 8;
  private long createdAt_ = 0L;
  /**
   * <pre>
   * unix ms
   * </pre>
   *
   * <code>int64 created_at = 8 [json_name = "createdAt"];</code>
   * @return The createdAt.
   */
  @java.lang.Override
  public long getCreatedAt() {
    return createdAt_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(eventId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, eventId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tenantId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, tenantId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sourceTopic_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, sourceTopic_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sourceKey_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, sourceKey_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(errorMsg_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, errorMsg_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(rawPayload_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, rawPayload_);
    }
    if (retryCount_ != 0) {
      output.writeUInt32(7, retryCount_);
    }
    if (createdAt_ != 0L) {
      output.writeInt64(8, createdAt_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(eventId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, eventId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tenantId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, tenantId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sourceTopic_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, sourceTopic_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sourceKey_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, sourceKey_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(errorMsg_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, errorMsg_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(rawPayload_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, rawPayload_);
    }
    if (retryCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(7, retryCount_);
    }
    if (createdAt_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(8, createdAt_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.traffic.proto.traffic.v1.DeadLetter)) {
      return super.equals(obj);
    }
    com.traffic.proto.traffic.v1.DeadLetter other = (com.traffic.proto.traffic.v1.DeadLetter) obj;

    if (!getEventId()
        .equals(other.getEventId())) return false;
    if (!getTenantId()
        .equals(other.getTenantId())) return false;
    if (!getSourceTopic()
        .equals(other.getSourceTopic())) return false;
    if (!getSourceKey()
        .equals(other.getSourceKey())) return false;
    if (!getErrorMsg()
        .equals(other.getErrorMsg())) return false;
    if (!getRawPayload()
        .equals(other.getRawPayload())) return false;
    if (getRetryCount()
        != other.getRetryCount()) return false;
    if (getCreatedAt()
        != other.getCreatedAt()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + EVENT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getEventId().hashCode();
    hash = (37 * hash) + TENANT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getTenantId().hashCode();
    hash = (37 * hash) + SOURCE_TOPIC_FIELD_NUMBER;
    hash = (53 * hash) + getSourceTopic().hashCode();
    hash = (37 * hash) + SOURCE_KEY_FIELD_NUMBER;
    hash = (53 * hash) + getSourceKey().hashCode();
    hash = (37 * hash) + ERROR_MSG_FIELD_NUMBER;
    hash = (53 * hash) + getErrorMsg().hashCode();
    hash = (37 * hash) + RAW_PAYLOAD_FIELD_NUMBER;
    hash = (53 * hash) + getRawPayload().hashCode();
    hash = (37 * hash) + RETRY_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + getRetryCount();
    hash = (37 * hash) + CREATED_AT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCreatedAt());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.traffic.proto.traffic.v1.DeadLetter parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.traffic.proto.traffic.v1.DeadLetter parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.traffic.proto.traffic.v1.DeadLetter parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.traffic.proto.traffic.v1.DeadLetter parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.traffic.proto.traffic.v1.DeadLetter parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.traffic.proto.traffic.v1.DeadLetter parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.traffic.proto.traffic.v1.DeadLetter parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.traffic.proto.traffic.v1.DeadLetter parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.traffic.proto.traffic.v1.DeadLetter parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.traffic.proto.traffic.v1.DeadLetter parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.traffic.proto.traffic.v1.DeadLetter parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.traffic.proto.traffic.v1.DeadLetter parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.traffic.proto.traffic.v1.DeadLetter prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * DeadLetter — 死信队列 (Kafka: dlq.v1)
   * </pre>
   *
   * Protobuf type {@code traffic.v1.DeadLetter}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:traffic.v1.DeadLetter)
      com.traffic.proto.traffic.v1.DeadLetterOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.traffic.proto.traffic.v1.AuditProto.internal_static_traffic_v1_DeadLetter_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.traffic.proto.traffic.v1.AuditProto.internal_static_traffic_v1_DeadLetter_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.traffic.proto.traffic.v1.DeadLetter.class, com.traffic.proto.traffic.v1.DeadLetter.Builder.class);
    }

    // Construct using com.traffic.proto.traffic.v1.DeadLetter.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      eventId_ = "";
      tenantId_ = "";
      sourceTopic_ = "";
      sourceKey_ = "";
      errorMsg_ = "";
      rawPayload_ = "";
      retryCount_ = 0;
      createdAt_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.traffic.proto.traffic.v1.AuditProto.internal_static_traffic_v1_DeadLetter_descriptor;
    }

    @java.lang.Override
    public com.traffic.proto.traffic.v1.DeadLetter getDefaultInstanceForType() {
      return com.traffic.proto.traffic.v1.DeadLetter.getDefaultInstance();
    }

    @java.lang.Override
    public com.traffic.proto.traffic.v1.DeadLetter build() {
      com.traffic.proto.traffic.v1.DeadLetter result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.traffic.proto.traffic.v1.DeadLetter buildPartial() {
      com.traffic.proto.traffic.v1.DeadLetter result = new com.traffic.proto.traffic.v1.DeadLetter(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.traffic.proto.traffic.v1.DeadLetter result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.eventId_ = eventId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.tenantId_ = tenantId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.sourceTopic_ = sourceTopic_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.sourceKey_ = sourceKey_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.errorMsg_ = errorMsg_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.rawPayload_ = rawPayload_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.retryCount_ = retryCount_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.createdAt_ = createdAt_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.traffic.proto.traffic.v1.DeadLetter) {
        return mergeFrom((com.traffic.proto.traffic.v1.DeadLetter)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.traffic.proto.traffic.v1.DeadLetter other) {
      if (other == com.traffic.proto.traffic.v1.DeadLetter.getDefaultInstance()) return this;
      if (!other.getEventId().isEmpty()) {
        eventId_ = other.eventId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getTenantId().isEmpty()) {
        tenantId_ = other.tenantId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getSourceTopic().isEmpty()) {
        sourceTopic_ = other.sourceTopic_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getSourceKey().isEmpty()) {
        sourceKey_ = other.sourceKey_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getErrorMsg().isEmpty()) {
        errorMsg_ = other.errorMsg_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getRawPayload().isEmpty()) {
        rawPayload_ = other.rawPayload_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (other.getRetryCount() != 0) {
        setRetryCount(other.getRetryCount());
      }
      if (other.getCreatedAt() != 0L) {
        setCreatedAt(other.getCreatedAt());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              eventId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              tenantId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              sourceTopic_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              sourceKey_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              errorMsg_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              rawPayload_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 56: {
              retryCount_ = input.readUInt32();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 64: {
              createdAt_ = input.readInt64();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object eventId_ = "";
    /**
     * <code>string event_id = 1 [json_name = "eventId"];</code>
     * @return The eventId.
     */
    public java.lang.String getEventId() {
      java.lang.Object ref = eventId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        eventId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string event_id = 1 [json_name = "eventId"];</code>
     * @return The bytes for eventId.
     */
    public com.google.protobuf.ByteString
        getEventIdBytes() {
      java.lang.Object ref = eventId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        eventId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string event_id = 1 [json_name = "eventId"];</code>
     * @param value The eventId to set.
     * @return This builder for chaining.
     */
    public Builder setEventId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      eventId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string event_id = 1 [json_name = "eventId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearEventId() {
      eventId_ = getDefaultInstance().getEventId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string event_id = 1 [json_name = "eventId"];</code>
     * @param value The bytes for eventId to set.
     * @return This builder for chaining.
     */
    public Builder setEventIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      eventId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object tenantId_ = "";
    /**
     * <code>string tenant_id = 2 [json_name = "tenantId"];</code>
     * @return The tenantId.
     */
    public java.lang.String getTenantId() {
      java.lang.Object ref = tenantId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tenantId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string tenant_id = 2 [json_name = "tenantId"];</code>
     * @return The bytes for tenantId.
     */
    public com.google.protobuf.ByteString
        getTenantIdBytes() {
      java.lang.Object ref = tenantId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tenantId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string tenant_id = 2 [json_name = "tenantId"];</code>
     * @param value The tenantId to set.
     * @return This builder for chaining.
     */
    public Builder setTenantId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      tenantId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string tenant_id = 2 [json_name = "tenantId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTenantId() {
      tenantId_ = getDefaultInstance().getTenantId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string tenant_id = 2 [json_name = "tenantId"];</code>
     * @param value The bytes for tenantId to set.
     * @return This builder for chaining.
     */
    public Builder setTenantIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      tenantId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object sourceTopic_ = "";
    /**
     * <code>string source_topic = 3 [json_name = "sourceTopic"];</code>
     * @return The sourceTopic.
     */
    public java.lang.String getSourceTopic() {
      java.lang.Object ref = sourceTopic_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sourceTopic_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string source_topic = 3 [json_name = "sourceTopic"];</code>
     * @return The bytes for sourceTopic.
     */
    public com.google.protobuf.ByteString
        getSourceTopicBytes() {
      java.lang.Object ref = sourceTopic_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sourceTopic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string source_topic = 3 [json_name = "sourceTopic"];</code>
     * @param value The sourceTopic to set.
     * @return This builder for chaining.
     */
    public Builder setSourceTopic(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sourceTopic_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string source_topic = 3 [json_name = "sourceTopic"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSourceTopic() {
      sourceTopic_ = getDefaultInstance().getSourceTopic();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string source_topic = 3 [json_name = "sourceTopic"];</code>
     * @param value The bytes for sourceTopic to set.
     * @return This builder for chaining.
     */
    public Builder setSourceTopicBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sourceTopic_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object sourceKey_ = "";
    /**
     * <code>string source_key = 4 [json_name = "sourceKey"];</code>
     * @return The sourceKey.
     */
    public java.lang.String getSourceKey() {
      java.lang.Object ref = sourceKey_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sourceKey_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string source_key = 4 [json_name = "sourceKey"];</code>
     * @return The bytes for sourceKey.
     */
    public com.google.protobuf.ByteString
        getSourceKeyBytes() {
      java.lang.Object ref = sourceKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sourceKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string source_key = 4 [json_name = "sourceKey"];</code>
     * @param value The sourceKey to set.
     * @return This builder for chaining.
     */
    public Builder setSourceKey(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sourceKey_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string source_key = 4 [json_name = "sourceKey"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSourceKey() {
      sourceKey_ = getDefaultInstance().getSourceKey();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string source_key = 4 [json_name = "sourceKey"];</code>
     * @param value The bytes for sourceKey to set.
     * @return This builder for chaining.
     */
    public Builder setSourceKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sourceKey_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object errorMsg_ = "";
    /**
     * <code>string error_msg = 5 [json_name = "errorMsg"];</code>
     * @return The errorMsg.
     */
    public java.lang.String getErrorMsg() {
      java.lang.Object ref = errorMsg_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        errorMsg_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string error_msg = 5 [json_name = "errorMsg"];</code>
     * @return The bytes for errorMsg.
     */
    public com.google.protobuf.ByteString
        getErrorMsgBytes() {
      java.lang.Object ref = errorMsg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string error_msg = 5 [json_name = "errorMsg"];</code>
     * @param value The errorMsg to set.
     * @return This builder for chaining.
     */
    public Builder setErrorMsg(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      errorMsg_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string error_msg = 5 [json_name = "errorMsg"];</code>
     * @return This builder for chaining.
     */
    public Builder clearErrorMsg() {
      errorMsg_ = getDefaultInstance().getErrorMsg();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string error_msg = 5 [json_name = "errorMsg"];</code>
     * @param value The bytes for errorMsg to set.
     * @return This builder for chaining.
     */
    public Builder setErrorMsgBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      errorMsg_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.lang.Object rawPayload_ = "";
    /**
     * <code>string raw_payload = 6 [json_name = "rawPayload"];</code>
     * @return The rawPayload.
     */
    public java.lang.String getRawPayload() {
      java.lang.Object ref = rawPayload_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        rawPayload_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string raw_payload = 6 [json_name = "rawPayload"];</code>
     * @return The bytes for rawPayload.
     */
    public com.google.protobuf.ByteString
        getRawPayloadBytes() {
      java.lang.Object ref = rawPayload_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rawPayload_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string raw_payload = 6 [json_name = "rawPayload"];</code>
     * @param value The rawPayload to set.
     * @return This builder for chaining.
     */
    public Builder setRawPayload(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      rawPayload_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>string raw_payload = 6 [json_name = "rawPayload"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRawPayload() {
      rawPayload_ = getDefaultInstance().getRawPayload();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string raw_payload = 6 [json_name = "rawPayload"];</code>
     * @param value The bytes for rawPayload to set.
     * @return This builder for chaining.
     */
    public Builder setRawPayloadBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      rawPayload_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private int retryCount_ ;
    /**
     * <code>uint32 retry_count = 7 [json_name = "retryCount"];</code>
     * @return The retryCount.
     */
    @java.lang.Override
    public int getRetryCount() {
      return retryCount_;
    }
    /**
     * <code>uint32 retry_count = 7 [json_name = "retryCount"];</code>
     * @param value The retryCount to set.
     * @return This builder for chaining.
     */
    public Builder setRetryCount(int value) {

      retryCount_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 retry_count = 7 [json_name = "retryCount"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRetryCount() {
      bitField0_ = (bitField0_ & ~0x00000040);
      retryCount_ = 0;
      onChanged();
      return this;
    }

    private long createdAt_ ;
    /**
     * <pre>
     * unix ms
     * </pre>
     *
     * <code>int64 created_at = 8 [json_name = "createdAt"];</code>
     * @return The createdAt.
     */
    @java.lang.Override
    public long getCreatedAt() {
      return createdAt_;
    }
    /**
     * <pre>
     * unix ms
     * </pre>
     *
     * <code>int64 created_at = 8 [json_name = "createdAt"];</code>
     * @param value The createdAt to set.
     * @return This builder for chaining.
     */
    public Builder setCreatedAt(long value) {

      createdAt_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * unix ms
     * </pre>
     *
     * <code>int64 created_at = 8 [json_name = "createdAt"];</code>
     * @return This builder for chaining.
     */
    public Builder clearCreatedAt() {
      bitField0_ = (bitField0_ & ~0x00000080);
      createdAt_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:traffic.v1.DeadLetter)
  }

  // @@protoc_insertion_point(class_scope:traffic.v1.DeadLetter)
  private static final com.traffic.proto.traffic.v1.DeadLetter DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.traffic.proto.traffic.v1.DeadLetter();
  }

  public static com.traffic.proto.traffic.v1.DeadLetter getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DeadLetter>
      PARSER = new com.google.protobuf.AbstractParser<DeadLetter>() {
    @java.lang.Override
    public DeadLetter parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<DeadLetter> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DeadLetter> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.traffic.proto.traffic.v1.DeadLetter getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

