// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: traffic/v1/feature.proto

// Protobuf Java Version: 3.25.2
package com.traffic.proto.traffic.v1;

/**
 * <pre>
 * FeatureFingerprint L3 指纹特征
 * </pre>
 *
 * Protobuf type {@code traffic.v1.FeatureFingerprint}
 */
public final class FeatureFingerprint extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:traffic.v1.FeatureFingerprint)
    FeatureFingerprintOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FeatureFingerprint.newBuilder() to construct.
  private FeatureFingerprint(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FeatureFingerprint() {
    communityId_ = "";
    sessionId_ = "";
    tlsVersion_ = "";
    ja3_ = "";
    sniHash_ = "";
    certSha256_ = "";
    hexFreq_ = emptyFloatList();
    hexRatio_ = emptyFloatList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FeatureFingerprint();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.traffic.proto.traffic.v1.FeatureProto.internal_static_traffic_v1_FeatureFingerprint_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.traffic.proto.traffic.v1.FeatureProto.internal_static_traffic_v1_FeatureFingerprint_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.traffic.proto.traffic.v1.FeatureFingerprint.class, com.traffic.proto.traffic.v1.FeatureFingerprint.Builder.class);
  }

  private int bitField0_;
  public static final int HEADER_FIELD_NUMBER = 1;
  private com.traffic.proto.traffic.v1.EventHeader header_;
  /**
   * <code>.traffic.v1.EventHeader header = 1 [json_name = "header"];</code>
   * @return Whether the header field is set.
   */
  @java.lang.Override
  public boolean hasHeader() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.traffic.v1.EventHeader header = 1 [json_name = "header"];</code>
   * @return The header.
   */
  @java.lang.Override
  public com.traffic.proto.traffic.v1.EventHeader getHeader() {
    return header_ == null ? com.traffic.proto.traffic.v1.EventHeader.getDefaultInstance() : header_;
  }
  /**
   * <code>.traffic.v1.EventHeader header = 1 [json_name = "header"];</code>
   */
  @java.lang.Override
  public com.traffic.proto.traffic.v1.EventHeaderOrBuilder getHeaderOrBuilder() {
    return header_ == null ? com.traffic.proto.traffic.v1.EventHeader.getDefaultInstance() : header_;
  }

  public static final int COMMUNITY_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object communityId_ = "";
  /**
   * <code>string community_id = 2 [json_name = "communityId"];</code>
   * @return The communityId.
   */
  @java.lang.Override
  public java.lang.String getCommunityId() {
    java.lang.Object ref = communityId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      communityId_ = s;
      return s;
    }
  }
  /**
   * <code>string community_id = 2 [json_name = "communityId"];</code>
   * @return The bytes for communityId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCommunityIdBytes() {
    java.lang.Object ref = communityId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      communityId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SESSION_ID_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sessionId_ = "";
  /**
   * <code>string session_id = 3 [json_name = "sessionId"];</code>
   * @return The sessionId.
   */
  @java.lang.Override
  public java.lang.String getSessionId() {
    java.lang.Object ref = sessionId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sessionId_ = s;
      return s;
    }
  }
  /**
   * <code>string session_id = 3 [json_name = "sessionId"];</code>
   * @return The bytes for sessionId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSessionIdBytes() {
    java.lang.Object ref = sessionId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sessionId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TS_FIELD_NUMBER = 4;
  private long ts_ = 0L;
  /**
   * <code>int64 ts = 4 [json_name = "ts"];</code>
   * @return The ts.
   */
  @java.lang.Override
  public long getTs() {
    return ts_;
  }

  public static final int IS_ENCRYPTED_FIELD_NUMBER = 5;
  private int isEncrypted_ = 0;
  /**
   * <code>uint32 is_encrypted = 5 [json_name = "isEncrypted"];</code>
   * @return The isEncrypted.
   */
  @java.lang.Override
  public int getIsEncrypted() {
    return isEncrypted_;
  }

  public static final int TLS_VERSION_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object tlsVersion_ = "";
  /**
   * <code>string tls_version = 6 [json_name = "tlsVersion"];</code>
   * @return The tlsVersion.
   */
  @java.lang.Override
  public java.lang.String getTlsVersion() {
    java.lang.Object ref = tlsVersion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tlsVersion_ = s;
      return s;
    }
  }
  /**
   * <code>string tls_version = 6 [json_name = "tlsVersion"];</code>
   * @return The bytes for tlsVersion.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTlsVersionBytes() {
    java.lang.Object ref = tlsVersion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tlsVersion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int JA3_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object ja3_ = "";
  /**
   * <code>string ja3 = 7 [json_name = "ja3"];</code>
   * @return The ja3.
   */
  @java.lang.Override
  public java.lang.String getJa3() {
    java.lang.Object ref = ja3_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ja3_ = s;
      return s;
    }
  }
  /**
   * <code>string ja3 = 7 [json_name = "ja3"];</code>
   * @return The bytes for ja3.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getJa3Bytes() {
    java.lang.Object ref = ja3_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ja3_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SNI_HASH_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sniHash_ = "";
  /**
   * <code>string sni_hash = 8 [json_name = "sniHash"];</code>
   * @return The sniHash.
   */
  @java.lang.Override
  public java.lang.String getSniHash() {
    java.lang.Object ref = sniHash_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sniHash_ = s;
      return s;
    }
  }
  /**
   * <code>string sni_hash = 8 [json_name = "sniHash"];</code>
   * @return The bytes for sniHash.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSniHashBytes() {
    java.lang.Object ref = sniHash_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sniHash_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CERT_SHA256_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private volatile java.lang.Object certSha256_ = "";
  /**
   * <code>string cert_sha256 = 9 [json_name = "certSha256"];</code>
   * @return The certSha256.
   */
  @java.lang.Override
  public java.lang.String getCertSha256() {
    java.lang.Object ref = certSha256_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      certSha256_ = s;
      return s;
    }
  }
  /**
   * <code>string cert_sha256 = 9 [json_name = "certSha256"];</code>
   * @return The bytes for certSha256.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCertSha256Bytes() {
    java.lang.Object ref = certSha256_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      certSha256_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CERT_IS_SELF_SIGNED_FIELD_NUMBER = 10;
  private int certIsSelfSigned_ = 0;
  /**
   * <code>uint32 cert_is_self_signed = 10 [json_name = "certIsSelfSigned"];</code>
   * @return The certIsSelfSigned.
   */
  @java.lang.Override
  public int getCertIsSelfSigned() {
    return certIsSelfSigned_;
  }

  public static final int PUBKEY_LEN_FIELD_NUMBER = 11;
  private int pubkeyLen_ = 0;
  /**
   * <code>uint32 pubkey_len = 11 [json_name = "pubkeyLen"];</code>
   * @return The pubkeyLen.
   */
  @java.lang.Override
  public int getPubkeyLen() {
    return pubkeyLen_;
  }

  public static final int HEX_FREQ_FIELD_NUMBER = 12;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.FloatList hexFreq_ =
      emptyFloatList();
  /**
   * <code>repeated float hex_freq = 12 [json_name = "hexFreq"];</code>
   * @return A list containing the hexFreq.
   */
  @java.lang.Override
  public java.util.List<java.lang.Float>
      getHexFreqList() {
    return hexFreq_;
  }
  /**
   * <code>repeated float hex_freq = 12 [json_name = "hexFreq"];</code>
   * @return The count of hexFreq.
   */
  public int getHexFreqCount() {
    return hexFreq_.size();
  }
  /**
   * <code>repeated float hex_freq = 12 [json_name = "hexFreq"];</code>
   * @param index The index of the element to return.
   * @return The hexFreq at the given index.
   */
  public float getHexFreq(int index) {
    return hexFreq_.getFloat(index);
  }
  private int hexFreqMemoizedSerializedSize = -1;

  public static final int HEX_RATIO_FIELD_NUMBER = 13;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.FloatList hexRatio_ =
      emptyFloatList();
  /**
   * <code>repeated float hex_ratio = 13 [json_name = "hexRatio"];</code>
   * @return A list containing the hexRatio.
   */
  @java.lang.Override
  public java.util.List<java.lang.Float>
      getHexRatioList() {
    return hexRatio_;
  }
  /**
   * <code>repeated float hex_ratio = 13 [json_name = "hexRatio"];</code>
   * @return The count of hexRatio.
   */
  public int getHexRatioCount() {
    return hexRatio_.size();
  }
  /**
   * <code>repeated float hex_ratio = 13 [json_name = "hexRatio"];</code>
   * @param index The index of the element to return.
   * @return The hexRatio at the given index.
   */
  public float getHexRatio(int index) {
    return hexRatio_.getFloat(index);
  }
  private int hexRatioMemoizedSerializedSize = -1;

  public static final int ENTROPY_PAYLOAD_FIELD_NUMBER = 14;
  private float entropyPayload_ = 0F;
  /**
   * <code>float entropy_payload = 14 [json_name = "entropyPayload"];</code>
   * @return The entropyPayload.
   */
  @java.lang.Override
  public float getEntropyPayload() {
    return entropyPayload_;
  }

  public static final int CHI_SQUARE_BFD_FIELD_NUMBER = 15;
  private float chiSquareBfd_ = 0F;
  /**
   * <code>float chi_square_bfd = 15 [json_name = "chiSquareBfd"];</code>
   * @return The chiSquareBfd.
   */
  @java.lang.Override
  public float getChiSquareBfd() {
    return chiSquareBfd_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getHeader());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(communityId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, communityId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sessionId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, sessionId_);
    }
    if (ts_ != 0L) {
      output.writeInt64(4, ts_);
    }
    if (isEncrypted_ != 0) {
      output.writeUInt32(5, isEncrypted_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tlsVersion_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, tlsVersion_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(ja3_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, ja3_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sniHash_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, sniHash_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(certSha256_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, certSha256_);
    }
    if (certIsSelfSigned_ != 0) {
      output.writeUInt32(10, certIsSelfSigned_);
    }
    if (pubkeyLen_ != 0) {
      output.writeUInt32(11, pubkeyLen_);
    }
    if (getHexFreqList().size() > 0) {
      output.writeUInt32NoTag(98);
      output.writeUInt32NoTag(hexFreqMemoizedSerializedSize);
    }
    for (int i = 0; i < hexFreq_.size(); i++) {
      output.writeFloatNoTag(hexFreq_.getFloat(i));
    }
    if (getHexRatioList().size() > 0) {
      output.writeUInt32NoTag(106);
      output.writeUInt32NoTag(hexRatioMemoizedSerializedSize);
    }
    for (int i = 0; i < hexRatio_.size(); i++) {
      output.writeFloatNoTag(hexRatio_.getFloat(i));
    }
    if (java.lang.Float.floatToRawIntBits(entropyPayload_) != 0) {
      output.writeFloat(14, entropyPayload_);
    }
    if (java.lang.Float.floatToRawIntBits(chiSquareBfd_) != 0) {
      output.writeFloat(15, chiSquareBfd_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getHeader());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(communityId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, communityId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sessionId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, sessionId_);
    }
    if (ts_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, ts_);
    }
    if (isEncrypted_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(5, isEncrypted_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tlsVersion_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, tlsVersion_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(ja3_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, ja3_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sniHash_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, sniHash_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(certSha256_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, certSha256_);
    }
    if (certIsSelfSigned_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(10, certIsSelfSigned_);
    }
    if (pubkeyLen_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(11, pubkeyLen_);
    }
    {
      int dataSize = 0;
      dataSize = 4 * getHexFreqList().size();
      size += dataSize;
      if (!getHexFreqList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      hexFreqMemoizedSerializedSize = dataSize;
    }
    {
      int dataSize = 0;
      dataSize = 4 * getHexRatioList().size();
      size += dataSize;
      if (!getHexRatioList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      hexRatioMemoizedSerializedSize = dataSize;
    }
    if (java.lang.Float.floatToRawIntBits(entropyPayload_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(14, entropyPayload_);
    }
    if (java.lang.Float.floatToRawIntBits(chiSquareBfd_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(15, chiSquareBfd_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.traffic.proto.traffic.v1.FeatureFingerprint)) {
      return super.equals(obj);
    }
    com.traffic.proto.traffic.v1.FeatureFingerprint other = (com.traffic.proto.traffic.v1.FeatureFingerprint) obj;

    if (hasHeader() != other.hasHeader()) return false;
    if (hasHeader()) {
      if (!getHeader()
          .equals(other.getHeader())) return false;
    }
    if (!getCommunityId()
        .equals(other.getCommunityId())) return false;
    if (!getSessionId()
        .equals(other.getSessionId())) return false;
    if (getTs()
        != other.getTs()) return false;
    if (getIsEncrypted()
        != other.getIsEncrypted()) return false;
    if (!getTlsVersion()
        .equals(other.getTlsVersion())) return false;
    if (!getJa3()
        .equals(other.getJa3())) return false;
    if (!getSniHash()
        .equals(other.getSniHash())) return false;
    if (!getCertSha256()
        .equals(other.getCertSha256())) return false;
    if (getCertIsSelfSigned()
        != other.getCertIsSelfSigned()) return false;
    if (getPubkeyLen()
        != other.getPubkeyLen()) return false;
    if (!getHexFreqList()
        .equals(other.getHexFreqList())) return false;
    if (!getHexRatioList()
        .equals(other.getHexRatioList())) return false;
    if (java.lang.Float.floatToIntBits(getEntropyPayload())
        != java.lang.Float.floatToIntBits(
            other.getEntropyPayload())) return false;
    if (java.lang.Float.floatToIntBits(getChiSquareBfd())
        != java.lang.Float.floatToIntBits(
            other.getChiSquareBfd())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasHeader()) {
      hash = (37 * hash) + HEADER_FIELD_NUMBER;
      hash = (53 * hash) + getHeader().hashCode();
    }
    hash = (37 * hash) + COMMUNITY_ID_FIELD_NUMBER;
    hash = (53 * hash) + getCommunityId().hashCode();
    hash = (37 * hash) + SESSION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getSessionId().hashCode();
    hash = (37 * hash) + TS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTs());
    hash = (37 * hash) + IS_ENCRYPTED_FIELD_NUMBER;
    hash = (53 * hash) + getIsEncrypted();
    hash = (37 * hash) + TLS_VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getTlsVersion().hashCode();
    hash = (37 * hash) + JA3_FIELD_NUMBER;
    hash = (53 * hash) + getJa3().hashCode();
    hash = (37 * hash) + SNI_HASH_FIELD_NUMBER;
    hash = (53 * hash) + getSniHash().hashCode();
    hash = (37 * hash) + CERT_SHA256_FIELD_NUMBER;
    hash = (53 * hash) + getCertSha256().hashCode();
    hash = (37 * hash) + CERT_IS_SELF_SIGNED_FIELD_NUMBER;
    hash = (53 * hash) + getCertIsSelfSigned();
    hash = (37 * hash) + PUBKEY_LEN_FIELD_NUMBER;
    hash = (53 * hash) + getPubkeyLen();
    if (getHexFreqCount() > 0) {
      hash = (37 * hash) + HEX_FREQ_FIELD_NUMBER;
      hash = (53 * hash) + getHexFreqList().hashCode();
    }
    if (getHexRatioCount() > 0) {
      hash = (37 * hash) + HEX_RATIO_FIELD_NUMBER;
      hash = (53 * hash) + getHexRatioList().hashCode();
    }
    hash = (37 * hash) + ENTROPY_PAYLOAD_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getEntropyPayload());
    hash = (37 * hash) + CHI_SQUARE_BFD_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getChiSquareBfd());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.traffic.proto.traffic.v1.FeatureFingerprint parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.traffic.proto.traffic.v1.FeatureFingerprint parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.traffic.proto.traffic.v1.FeatureFingerprint parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.traffic.proto.traffic.v1.FeatureFingerprint parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.traffic.proto.traffic.v1.FeatureFingerprint parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.traffic.proto.traffic.v1.FeatureFingerprint parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.traffic.proto.traffic.v1.FeatureFingerprint parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.traffic.proto.traffic.v1.FeatureFingerprint parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.traffic.proto.traffic.v1.FeatureFingerprint parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.traffic.proto.traffic.v1.FeatureFingerprint parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.traffic.proto.traffic.v1.FeatureFingerprint parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.traffic.proto.traffic.v1.FeatureFingerprint parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.traffic.proto.traffic.v1.FeatureFingerprint prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * FeatureFingerprint L3 指纹特征
   * </pre>
   *
   * Protobuf type {@code traffic.v1.FeatureFingerprint}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:traffic.v1.FeatureFingerprint)
      com.traffic.proto.traffic.v1.FeatureFingerprintOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.traffic.proto.traffic.v1.FeatureProto.internal_static_traffic_v1_FeatureFingerprint_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.traffic.proto.traffic.v1.FeatureProto.internal_static_traffic_v1_FeatureFingerprint_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.traffic.proto.traffic.v1.FeatureFingerprint.class, com.traffic.proto.traffic.v1.FeatureFingerprint.Builder.class);
    }

    // Construct using com.traffic.proto.traffic.v1.FeatureFingerprint.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getHeaderFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      header_ = null;
      if (headerBuilder_ != null) {
        headerBuilder_.dispose();
        headerBuilder_ = null;
      }
      communityId_ = "";
      sessionId_ = "";
      ts_ = 0L;
      isEncrypted_ = 0;
      tlsVersion_ = "";
      ja3_ = "";
      sniHash_ = "";
      certSha256_ = "";
      certIsSelfSigned_ = 0;
      pubkeyLen_ = 0;
      hexFreq_ = emptyFloatList();
      hexRatio_ = emptyFloatList();
      entropyPayload_ = 0F;
      chiSquareBfd_ = 0F;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.traffic.proto.traffic.v1.FeatureProto.internal_static_traffic_v1_FeatureFingerprint_descriptor;
    }

    @java.lang.Override
    public com.traffic.proto.traffic.v1.FeatureFingerprint getDefaultInstanceForType() {
      return com.traffic.proto.traffic.v1.FeatureFingerprint.getDefaultInstance();
    }

    @java.lang.Override
    public com.traffic.proto.traffic.v1.FeatureFingerprint build() {
      com.traffic.proto.traffic.v1.FeatureFingerprint result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.traffic.proto.traffic.v1.FeatureFingerprint buildPartial() {
      com.traffic.proto.traffic.v1.FeatureFingerprint result = new com.traffic.proto.traffic.v1.FeatureFingerprint(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.traffic.proto.traffic.v1.FeatureFingerprint result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.header_ = headerBuilder_ == null
            ? header_
            : headerBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.communityId_ = communityId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.sessionId_ = sessionId_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.ts_ = ts_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.isEncrypted_ = isEncrypted_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.tlsVersion_ = tlsVersion_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.ja3_ = ja3_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.sniHash_ = sniHash_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.certSha256_ = certSha256_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.certIsSelfSigned_ = certIsSelfSigned_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.pubkeyLen_ = pubkeyLen_;
      }
      if (((from_bitField0_ & 0x00000800) != 0)) {
        hexFreq_.makeImmutable();
        result.hexFreq_ = hexFreq_;
      }
      if (((from_bitField0_ & 0x00001000) != 0)) {
        hexRatio_.makeImmutable();
        result.hexRatio_ = hexRatio_;
      }
      if (((from_bitField0_ & 0x00002000) != 0)) {
        result.entropyPayload_ = entropyPayload_;
      }
      if (((from_bitField0_ & 0x00004000) != 0)) {
        result.chiSquareBfd_ = chiSquareBfd_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.traffic.proto.traffic.v1.FeatureFingerprint) {
        return mergeFrom((com.traffic.proto.traffic.v1.FeatureFingerprint)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.traffic.proto.traffic.v1.FeatureFingerprint other) {
      if (other == com.traffic.proto.traffic.v1.FeatureFingerprint.getDefaultInstance()) return this;
      if (other.hasHeader()) {
        mergeHeader(other.getHeader());
      }
      if (!other.getCommunityId().isEmpty()) {
        communityId_ = other.communityId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getSessionId().isEmpty()) {
        sessionId_ = other.sessionId_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.getTs() != 0L) {
        setTs(other.getTs());
      }
      if (other.getIsEncrypted() != 0) {
        setIsEncrypted(other.getIsEncrypted());
      }
      if (!other.getTlsVersion().isEmpty()) {
        tlsVersion_ = other.tlsVersion_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (!other.getJa3().isEmpty()) {
        ja3_ = other.ja3_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (!other.getSniHash().isEmpty()) {
        sniHash_ = other.sniHash_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      if (!other.getCertSha256().isEmpty()) {
        certSha256_ = other.certSha256_;
        bitField0_ |= 0x00000100;
        onChanged();
      }
      if (other.getCertIsSelfSigned() != 0) {
        setCertIsSelfSigned(other.getCertIsSelfSigned());
      }
      if (other.getPubkeyLen() != 0) {
        setPubkeyLen(other.getPubkeyLen());
      }
      if (!other.hexFreq_.isEmpty()) {
        if (hexFreq_.isEmpty()) {
          hexFreq_ = other.hexFreq_;
          hexFreq_.makeImmutable();
          bitField0_ |= 0x00000800;
        } else {
          ensureHexFreqIsMutable();
          hexFreq_.addAll(other.hexFreq_);
        }
        onChanged();
      }
      if (!other.hexRatio_.isEmpty()) {
        if (hexRatio_.isEmpty()) {
          hexRatio_ = other.hexRatio_;
          hexRatio_.makeImmutable();
          bitField0_ |= 0x00001000;
        } else {
          ensureHexRatioIsMutable();
          hexRatio_.addAll(other.hexRatio_);
        }
        onChanged();
      }
      if (other.getEntropyPayload() != 0F) {
        setEntropyPayload(other.getEntropyPayload());
      }
      if (other.getChiSquareBfd() != 0F) {
        setChiSquareBfd(other.getChiSquareBfd());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getHeaderFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              communityId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              sessionId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              ts_ = input.readInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              isEncrypted_ = input.readUInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 50: {
              tlsVersion_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              ja3_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              sniHash_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 74: {
              certSha256_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            case 80: {
              certIsSelfSigned_ = input.readUInt32();
              bitField0_ |= 0x00000200;
              break;
            } // case 80
            case 88: {
              pubkeyLen_ = input.readUInt32();
              bitField0_ |= 0x00000400;
              break;
            } // case 88
            case 101: {
              float v = input.readFloat();
              ensureHexFreqIsMutable();
              hexFreq_.addFloat(v);
              break;
            } // case 101
            case 98: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              int alloc = length > 4096 ? 4096 : length;
              ensureHexFreqIsMutable(alloc / 4);
              while (input.getBytesUntilLimit() > 0) {
                hexFreq_.addFloat(input.readFloat());
              }
              input.popLimit(limit);
              break;
            } // case 98
            case 109: {
              float v = input.readFloat();
              ensureHexRatioIsMutable();
              hexRatio_.addFloat(v);
              break;
            } // case 109
            case 106: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              int alloc = length > 4096 ? 4096 : length;
              ensureHexRatioIsMutable(alloc / 4);
              while (input.getBytesUntilLimit() > 0) {
                hexRatio_.addFloat(input.readFloat());
              }
              input.popLimit(limit);
              break;
            } // case 106
            case 117: {
              entropyPayload_ = input.readFloat();
              bitField0_ |= 0x00002000;
              break;
            } // case 117
            case 125: {
              chiSquareBfd_ = input.readFloat();
              bitField0_ |= 0x00004000;
              break;
            } // case 125
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.traffic.proto.traffic.v1.EventHeader header_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.traffic.proto.traffic.v1.EventHeader, com.traffic.proto.traffic.v1.EventHeader.Builder, com.traffic.proto.traffic.v1.EventHeaderOrBuilder> headerBuilder_;
    /**
     * <code>.traffic.v1.EventHeader header = 1 [json_name = "header"];</code>
     * @return Whether the header field is set.
     */
    public boolean hasHeader() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.traffic.v1.EventHeader header = 1 [json_name = "header"];</code>
     * @return The header.
     */
    public com.traffic.proto.traffic.v1.EventHeader getHeader() {
      if (headerBuilder_ == null) {
        return header_ == null ? com.traffic.proto.traffic.v1.EventHeader.getDefaultInstance() : header_;
      } else {
        return headerBuilder_.getMessage();
      }
    }
    /**
     * <code>.traffic.v1.EventHeader header = 1 [json_name = "header"];</code>
     */
    public Builder setHeader(com.traffic.proto.traffic.v1.EventHeader value) {
      if (headerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        header_ = value;
      } else {
        headerBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.traffic.v1.EventHeader header = 1 [json_name = "header"];</code>
     */
    public Builder setHeader(
        com.traffic.proto.traffic.v1.EventHeader.Builder builderForValue) {
      if (headerBuilder_ == null) {
        header_ = builderForValue.build();
      } else {
        headerBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.traffic.v1.EventHeader header = 1 [json_name = "header"];</code>
     */
    public Builder mergeHeader(com.traffic.proto.traffic.v1.EventHeader value) {
      if (headerBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          header_ != null &&
          header_ != com.traffic.proto.traffic.v1.EventHeader.getDefaultInstance()) {
          getHeaderBuilder().mergeFrom(value);
        } else {
          header_ = value;
        }
      } else {
        headerBuilder_.mergeFrom(value);
      }
      if (header_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.traffic.v1.EventHeader header = 1 [json_name = "header"];</code>
     */
    public Builder clearHeader() {
      bitField0_ = (bitField0_ & ~0x00000001);
      header_ = null;
      if (headerBuilder_ != null) {
        headerBuilder_.dispose();
        headerBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.traffic.v1.EventHeader header = 1 [json_name = "header"];</code>
     */
    public com.traffic.proto.traffic.v1.EventHeader.Builder getHeaderBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getHeaderFieldBuilder().getBuilder();
    }
    /**
     * <code>.traffic.v1.EventHeader header = 1 [json_name = "header"];</code>
     */
    public com.traffic.proto.traffic.v1.EventHeaderOrBuilder getHeaderOrBuilder() {
      if (headerBuilder_ != null) {
        return headerBuilder_.getMessageOrBuilder();
      } else {
        return header_ == null ?
            com.traffic.proto.traffic.v1.EventHeader.getDefaultInstance() : header_;
      }
    }
    /**
     * <code>.traffic.v1.EventHeader header = 1 [json_name = "header"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.traffic.proto.traffic.v1.EventHeader, com.traffic.proto.traffic.v1.EventHeader.Builder, com.traffic.proto.traffic.v1.EventHeaderOrBuilder> 
        getHeaderFieldBuilder() {
      if (headerBuilder_ == null) {
        headerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.traffic.proto.traffic.v1.EventHeader, com.traffic.proto.traffic.v1.EventHeader.Builder, com.traffic.proto.traffic.v1.EventHeaderOrBuilder>(
                getHeader(),
                getParentForChildren(),
                isClean());
        header_ = null;
      }
      return headerBuilder_;
    }

    private java.lang.Object communityId_ = "";
    /**
     * <code>string community_id = 2 [json_name = "communityId"];</code>
     * @return The communityId.
     */
    public java.lang.String getCommunityId() {
      java.lang.Object ref = communityId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        communityId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string community_id = 2 [json_name = "communityId"];</code>
     * @return The bytes for communityId.
     */
    public com.google.protobuf.ByteString
        getCommunityIdBytes() {
      java.lang.Object ref = communityId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        communityId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string community_id = 2 [json_name = "communityId"];</code>
     * @param value The communityId to set.
     * @return This builder for chaining.
     */
    public Builder setCommunityId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      communityId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string community_id = 2 [json_name = "communityId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearCommunityId() {
      communityId_ = getDefaultInstance().getCommunityId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string community_id = 2 [json_name = "communityId"];</code>
     * @param value The bytes for communityId to set.
     * @return This builder for chaining.
     */
    public Builder setCommunityIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      communityId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object sessionId_ = "";
    /**
     * <code>string session_id = 3 [json_name = "sessionId"];</code>
     * @return The sessionId.
     */
    public java.lang.String getSessionId() {
      java.lang.Object ref = sessionId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sessionId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string session_id = 3 [json_name = "sessionId"];</code>
     * @return The bytes for sessionId.
     */
    public com.google.protobuf.ByteString
        getSessionIdBytes() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sessionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string session_id = 3 [json_name = "sessionId"];</code>
     * @param value The sessionId to set.
     * @return This builder for chaining.
     */
    public Builder setSessionId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sessionId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string session_id = 3 [json_name = "sessionId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSessionId() {
      sessionId_ = getDefaultInstance().getSessionId();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string session_id = 3 [json_name = "sessionId"];</code>
     * @param value The bytes for sessionId to set.
     * @return This builder for chaining.
     */
    public Builder setSessionIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sessionId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private long ts_ ;
    /**
     * <code>int64 ts = 4 [json_name = "ts"];</code>
     * @return The ts.
     */
    @java.lang.Override
    public long getTs() {
      return ts_;
    }
    /**
     * <code>int64 ts = 4 [json_name = "ts"];</code>
     * @param value The ts to set.
     * @return This builder for chaining.
     */
    public Builder setTs(long value) {

      ts_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int64 ts = 4 [json_name = "ts"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTs() {
      bitField0_ = (bitField0_ & ~0x00000008);
      ts_ = 0L;
      onChanged();
      return this;
    }

    private int isEncrypted_ ;
    /**
     * <code>uint32 is_encrypted = 5 [json_name = "isEncrypted"];</code>
     * @return The isEncrypted.
     */
    @java.lang.Override
    public int getIsEncrypted() {
      return isEncrypted_;
    }
    /**
     * <code>uint32 is_encrypted = 5 [json_name = "isEncrypted"];</code>
     * @param value The isEncrypted to set.
     * @return This builder for chaining.
     */
    public Builder setIsEncrypted(int value) {

      isEncrypted_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 is_encrypted = 5 [json_name = "isEncrypted"];</code>
     * @return This builder for chaining.
     */
    public Builder clearIsEncrypted() {
      bitField0_ = (bitField0_ & ~0x00000010);
      isEncrypted_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object tlsVersion_ = "";
    /**
     * <code>string tls_version = 6 [json_name = "tlsVersion"];</code>
     * @return The tlsVersion.
     */
    public java.lang.String getTlsVersion() {
      java.lang.Object ref = tlsVersion_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tlsVersion_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string tls_version = 6 [json_name = "tlsVersion"];</code>
     * @return The bytes for tlsVersion.
     */
    public com.google.protobuf.ByteString
        getTlsVersionBytes() {
      java.lang.Object ref = tlsVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tlsVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string tls_version = 6 [json_name = "tlsVersion"];</code>
     * @param value The tlsVersion to set.
     * @return This builder for chaining.
     */
    public Builder setTlsVersion(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      tlsVersion_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>string tls_version = 6 [json_name = "tlsVersion"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTlsVersion() {
      tlsVersion_ = getDefaultInstance().getTlsVersion();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string tls_version = 6 [json_name = "tlsVersion"];</code>
     * @param value The bytes for tlsVersion to set.
     * @return This builder for chaining.
     */
    public Builder setTlsVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      tlsVersion_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private java.lang.Object ja3_ = "";
    /**
     * <code>string ja3 = 7 [json_name = "ja3"];</code>
     * @return The ja3.
     */
    public java.lang.String getJa3() {
      java.lang.Object ref = ja3_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ja3_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string ja3 = 7 [json_name = "ja3"];</code>
     * @return The bytes for ja3.
     */
    public com.google.protobuf.ByteString
        getJa3Bytes() {
      java.lang.Object ref = ja3_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ja3_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string ja3 = 7 [json_name = "ja3"];</code>
     * @param value The ja3 to set.
     * @return This builder for chaining.
     */
    public Builder setJa3(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ja3_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>string ja3 = 7 [json_name = "ja3"];</code>
     * @return This builder for chaining.
     */
    public Builder clearJa3() {
      ja3_ = getDefaultInstance().getJa3();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <code>string ja3 = 7 [json_name = "ja3"];</code>
     * @param value The bytes for ja3 to set.
     * @return This builder for chaining.
     */
    public Builder setJa3Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ja3_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private java.lang.Object sniHash_ = "";
    /**
     * <code>string sni_hash = 8 [json_name = "sniHash"];</code>
     * @return The sniHash.
     */
    public java.lang.String getSniHash() {
      java.lang.Object ref = sniHash_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sniHash_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string sni_hash = 8 [json_name = "sniHash"];</code>
     * @return The bytes for sniHash.
     */
    public com.google.protobuf.ByteString
        getSniHashBytes() {
      java.lang.Object ref = sniHash_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sniHash_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sni_hash = 8 [json_name = "sniHash"];</code>
     * @param value The sniHash to set.
     * @return This builder for chaining.
     */
    public Builder setSniHash(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sniHash_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>string sni_hash = 8 [json_name = "sniHash"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSniHash() {
      sniHash_ = getDefaultInstance().getSniHash();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <code>string sni_hash = 8 [json_name = "sniHash"];</code>
     * @param value The bytes for sniHash to set.
     * @return This builder for chaining.
     */
    public Builder setSniHashBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sniHash_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    private java.lang.Object certSha256_ = "";
    /**
     * <code>string cert_sha256 = 9 [json_name = "certSha256"];</code>
     * @return The certSha256.
     */
    public java.lang.String getCertSha256() {
      java.lang.Object ref = certSha256_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        certSha256_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string cert_sha256 = 9 [json_name = "certSha256"];</code>
     * @return The bytes for certSha256.
     */
    public com.google.protobuf.ByteString
        getCertSha256Bytes() {
      java.lang.Object ref = certSha256_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        certSha256_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string cert_sha256 = 9 [json_name = "certSha256"];</code>
     * @param value The certSha256 to set.
     * @return This builder for chaining.
     */
    public Builder setCertSha256(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      certSha256_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>string cert_sha256 = 9 [json_name = "certSha256"];</code>
     * @return This builder for chaining.
     */
    public Builder clearCertSha256() {
      certSha256_ = getDefaultInstance().getCertSha256();
      bitField0_ = (bitField0_ & ~0x00000100);
      onChanged();
      return this;
    }
    /**
     * <code>string cert_sha256 = 9 [json_name = "certSha256"];</code>
     * @param value The bytes for certSha256 to set.
     * @return This builder for chaining.
     */
    public Builder setCertSha256Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      certSha256_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }

    private int certIsSelfSigned_ ;
    /**
     * <code>uint32 cert_is_self_signed = 10 [json_name = "certIsSelfSigned"];</code>
     * @return The certIsSelfSigned.
     */
    @java.lang.Override
    public int getCertIsSelfSigned() {
      return certIsSelfSigned_;
    }
    /**
     * <code>uint32 cert_is_self_signed = 10 [json_name = "certIsSelfSigned"];</code>
     * @param value The certIsSelfSigned to set.
     * @return This builder for chaining.
     */
    public Builder setCertIsSelfSigned(int value) {

      certIsSelfSigned_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 cert_is_self_signed = 10 [json_name = "certIsSelfSigned"];</code>
     * @return This builder for chaining.
     */
    public Builder clearCertIsSelfSigned() {
      bitField0_ = (bitField0_ & ~0x00000200);
      certIsSelfSigned_ = 0;
      onChanged();
      return this;
    }

    private int pubkeyLen_ ;
    /**
     * <code>uint32 pubkey_len = 11 [json_name = "pubkeyLen"];</code>
     * @return The pubkeyLen.
     */
    @java.lang.Override
    public int getPubkeyLen() {
      return pubkeyLen_;
    }
    /**
     * <code>uint32 pubkey_len = 11 [json_name = "pubkeyLen"];</code>
     * @param value The pubkeyLen to set.
     * @return This builder for chaining.
     */
    public Builder setPubkeyLen(int value) {

      pubkeyLen_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 pubkey_len = 11 [json_name = "pubkeyLen"];</code>
     * @return This builder for chaining.
     */
    public Builder clearPubkeyLen() {
      bitField0_ = (bitField0_ & ~0x00000400);
      pubkeyLen_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.FloatList hexFreq_ = emptyFloatList();
    private void ensureHexFreqIsMutable() {
      if (!hexFreq_.isModifiable()) {
        hexFreq_ = makeMutableCopy(hexFreq_);
      }
      bitField0_ |= 0x00000800;
    }
    private void ensureHexFreqIsMutable(int capacity) {
      if (!hexFreq_.isModifiable()) {
        hexFreq_ = makeMutableCopy(hexFreq_, capacity);
      }
      bitField0_ |= 0x00000800;
    }
    /**
     * <code>repeated float hex_freq = 12 [json_name = "hexFreq"];</code>
     * @return A list containing the hexFreq.
     */
    public java.util.List<java.lang.Float>
        getHexFreqList() {
      hexFreq_.makeImmutable();
      return hexFreq_;
    }
    /**
     * <code>repeated float hex_freq = 12 [json_name = "hexFreq"];</code>
     * @return The count of hexFreq.
     */
    public int getHexFreqCount() {
      return hexFreq_.size();
    }
    /**
     * <code>repeated float hex_freq = 12 [json_name = "hexFreq"];</code>
     * @param index The index of the element to return.
     * @return The hexFreq at the given index.
     */
    public float getHexFreq(int index) {
      return hexFreq_.getFloat(index);
    }
    /**
     * <code>repeated float hex_freq = 12 [json_name = "hexFreq"];</code>
     * @param index The index to set the value at.
     * @param value The hexFreq to set.
     * @return This builder for chaining.
     */
    public Builder setHexFreq(
        int index, float value) {

      ensureHexFreqIsMutable();
      hexFreq_.setFloat(index, value);
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <code>repeated float hex_freq = 12 [json_name = "hexFreq"];</code>
     * @param value The hexFreq to add.
     * @return This builder for chaining.
     */
    public Builder addHexFreq(float value) {

      ensureHexFreqIsMutable();
      hexFreq_.addFloat(value);
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <code>repeated float hex_freq = 12 [json_name = "hexFreq"];</code>
     * @param values The hexFreq to add.
     * @return This builder for chaining.
     */
    public Builder addAllHexFreq(
        java.lang.Iterable<? extends java.lang.Float> values) {
      ensureHexFreqIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, hexFreq_);
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <code>repeated float hex_freq = 12 [json_name = "hexFreq"];</code>
     * @return This builder for chaining.
     */
    public Builder clearHexFreq() {
      hexFreq_ = emptyFloatList();
      bitField0_ = (bitField0_ & ~0x00000800);
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.FloatList hexRatio_ = emptyFloatList();
    private void ensureHexRatioIsMutable() {
      if (!hexRatio_.isModifiable()) {
        hexRatio_ = makeMutableCopy(hexRatio_);
      }
      bitField0_ |= 0x00001000;
    }
    private void ensureHexRatioIsMutable(int capacity) {
      if (!hexRatio_.isModifiable()) {
        hexRatio_ = makeMutableCopy(hexRatio_, capacity);
      }
      bitField0_ |= 0x00001000;
    }
    /**
     * <code>repeated float hex_ratio = 13 [json_name = "hexRatio"];</code>
     * @return A list containing the hexRatio.
     */
    public java.util.List<java.lang.Float>
        getHexRatioList() {
      hexRatio_.makeImmutable();
      return hexRatio_;
    }
    /**
     * <code>repeated float hex_ratio = 13 [json_name = "hexRatio"];</code>
     * @return The count of hexRatio.
     */
    public int getHexRatioCount() {
      return hexRatio_.size();
    }
    /**
     * <code>repeated float hex_ratio = 13 [json_name = "hexRatio"];</code>
     * @param index The index of the element to return.
     * @return The hexRatio at the given index.
     */
    public float getHexRatio(int index) {
      return hexRatio_.getFloat(index);
    }
    /**
     * <code>repeated float hex_ratio = 13 [json_name = "hexRatio"];</code>
     * @param index The index to set the value at.
     * @param value The hexRatio to set.
     * @return This builder for chaining.
     */
    public Builder setHexRatio(
        int index, float value) {

      ensureHexRatioIsMutable();
      hexRatio_.setFloat(index, value);
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }
    /**
     * <code>repeated float hex_ratio = 13 [json_name = "hexRatio"];</code>
     * @param value The hexRatio to add.
     * @return This builder for chaining.
     */
    public Builder addHexRatio(float value) {

      ensureHexRatioIsMutable();
      hexRatio_.addFloat(value);
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }
    /**
     * <code>repeated float hex_ratio = 13 [json_name = "hexRatio"];</code>
     * @param values The hexRatio to add.
     * @return This builder for chaining.
     */
    public Builder addAllHexRatio(
        java.lang.Iterable<? extends java.lang.Float> values) {
      ensureHexRatioIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, hexRatio_);
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }
    /**
     * <code>repeated float hex_ratio = 13 [json_name = "hexRatio"];</code>
     * @return This builder for chaining.
     */
    public Builder clearHexRatio() {
      hexRatio_ = emptyFloatList();
      bitField0_ = (bitField0_ & ~0x00001000);
      onChanged();
      return this;
    }

    private float entropyPayload_ ;
    /**
     * <code>float entropy_payload = 14 [json_name = "entropyPayload"];</code>
     * @return The entropyPayload.
     */
    @java.lang.Override
    public float getEntropyPayload() {
      return entropyPayload_;
    }
    /**
     * <code>float entropy_payload = 14 [json_name = "entropyPayload"];</code>
     * @param value The entropyPayload to set.
     * @return This builder for chaining.
     */
    public Builder setEntropyPayload(float value) {

      entropyPayload_ = value;
      bitField0_ |= 0x00002000;
      onChanged();
      return this;
    }
    /**
     * <code>float entropy_payload = 14 [json_name = "entropyPayload"];</code>
     * @return This builder for chaining.
     */
    public Builder clearEntropyPayload() {
      bitField0_ = (bitField0_ & ~0x00002000);
      entropyPayload_ = 0F;
      onChanged();
      return this;
    }

    private float chiSquareBfd_ ;
    /**
     * <code>float chi_square_bfd = 15 [json_name = "chiSquareBfd"];</code>
     * @return The chiSquareBfd.
     */
    @java.lang.Override
    public float getChiSquareBfd() {
      return chiSquareBfd_;
    }
    /**
     * <code>float chi_square_bfd = 15 [json_name = "chiSquareBfd"];</code>
     * @param value The chiSquareBfd to set.
     * @return This builder for chaining.
     */
    public Builder setChiSquareBfd(float value) {

      chiSquareBfd_ = value;
      bitField0_ |= 0x00004000;
      onChanged();
      return this;
    }
    /**
     * <code>float chi_square_bfd = 15 [json_name = "chiSquareBfd"];</code>
     * @return This builder for chaining.
     */
    public Builder clearChiSquareBfd() {
      bitField0_ = (bitField0_ & ~0x00004000);
      chiSquareBfd_ = 0F;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:traffic.v1.FeatureFingerprint)
  }

  // @@protoc_insertion_point(class_scope:traffic.v1.FeatureFingerprint)
  private static final com.traffic.proto.traffic.v1.FeatureFingerprint DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.traffic.proto.traffic.v1.FeatureFingerprint();
  }

  public static com.traffic.proto.traffic.v1.FeatureFingerprint getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FeatureFingerprint>
      PARSER = new com.google.protobuf.AbstractParser<FeatureFingerprint>() {
    @java.lang.Override
    public FeatureFingerprint parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<FeatureFingerprint> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FeatureFingerprint> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.traffic.proto.traffic.v1.FeatureFingerprint getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

