// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: traffic/v1/ingest.proto
// Protobuf Java Version: 4.33.2

package com.traffic.proto.traffic.v1;

@com.google.protobuf.Generated
public interface HeartbeatResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:traffic.v1.HeartbeatResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool ok = 1 [json_name = "ok"];</code>
   * @return The ok.
   */
  boolean getOk();

  /**
   * <pre>
   * 可选: 服务端下发的配置更新
   * </pre>
   *
   * <code>.traffic.v1.ProbeConfig config = 2 [json_name = "config"];</code>
   * @return Whether the config field is set.
   */
  boolean hasConfig();
  /**
   * <pre>
   * 可选: 服务端下发的配置更新
   * </pre>
   *
   * <code>.traffic.v1.ProbeConfig config = 2 [json_name = "config"];</code>
   * @return The config.
   */
  com.traffic.proto.traffic.v1.ProbeConfig getConfig();
  /**
   * <pre>
   * 可选: 服务端下发的配置更新
   * </pre>
   *
   * <code>.traffic.v1.ProbeConfig config = 2 [json_name = "config"];</code>
   */
  com.traffic.proto.traffic.v1.ProbeConfigOrBuilder getConfigOrBuilder();
}
