// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: traffic/v1/ingest.proto
// Protobuf Java Version: 4.33.2

package com.traffic.proto.traffic.v1;

@com.google.protobuf.Generated
public interface HeartbeatRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:traffic.v1.HeartbeatRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string probe_id = 1 [json_name = "probeId"];</code>
   * @return The probeId.
   */
  java.lang.String getProbeId();
  /**
   * <code>string probe_id = 1 [json_name = "probeId"];</code>
   * @return The bytes for probeId.
   */
  com.google.protobuf.ByteString
      getProbeIdBytes();

  /**
   * <code>string tenant_id = 2 [json_name = "tenantId"];</code>
   * @return The tenantId.
   */
  java.lang.String getTenantId();
  /**
   * <code>string tenant_id = 2 [json_name = "tenantId"];</code>
   * @return The bytes for tenantId.
   */
  com.google.protobuf.ByteString
      getTenantIdBytes();

  /**
   * <code>int64 timestamp = 3 [json_name = "timestamp"];</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <pre>
   * 探针状态信息
   * </pre>
   *
   * <code>.traffic.v1.ProbeStatus status = 4 [json_name = "status"];</code>
   * @return Whether the status field is set.
   */
  boolean hasStatus();
  /**
   * <pre>
   * 探针状态信息
   * </pre>
   *
   * <code>.traffic.v1.ProbeStatus status = 4 [json_name = "status"];</code>
   * @return The status.
   */
  com.traffic.proto.traffic.v1.ProbeStatus getStatus();
  /**
   * <pre>
   * 探针状态信息
   * </pre>
   *
   * <code>.traffic.v1.ProbeStatus status = 4 [json_name = "status"];</code>
   */
  com.traffic.proto.traffic.v1.ProbeStatusOrBuilder getStatusOrBuilder();
}
