// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: traffic/v1/analysis.proto

// Protobuf Java Version: 3.25.2
package com.traffic.proto.traffic.v1;

/**
 * <pre>
 * 证据完整性状态。
 * </pre>
 *
 * Protobuf enum {@code traffic.v1.IntegrityState}
 */
public enum IntegrityState
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>INTEGRITY_STATE_UNSPECIFIED = 0;</code>
   */
  INTEGRITY_STATE_UNSPECIFIED(0),
  /**
   * <code>INTEGRITY_STATE_VERIFIED = 1;</code>
   */
  INTEGRITY_STATE_VERIFIED(1),
  /**
   * <code>INTEGRITY_STATE_UNVERIFIED = 2;</code>
   */
  INTEGRITY_STATE_UNVERIFIED(2),
  /**
   * <code>INTEGRITY_STATE_FAILED = 3;</code>
   */
  INTEGRITY_STATE_FAILED(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>INTEGRITY_STATE_UNSPECIFIED = 0;</code>
   */
  public static final int INTEGRITY_STATE_UNSPECIFIED_VALUE = 0;
  /**
   * <code>INTEGRITY_STATE_VERIFIED = 1;</code>
   */
  public static final int INTEGRITY_STATE_VERIFIED_VALUE = 1;
  /**
   * <code>INTEGRITY_STATE_UNVERIFIED = 2;</code>
   */
  public static final int INTEGRITY_STATE_UNVERIFIED_VALUE = 2;
  /**
   * <code>INTEGRITY_STATE_FAILED = 3;</code>
   */
  public static final int INTEGRITY_STATE_FAILED_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static IntegrityState valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static IntegrityState forNumber(int value) {
    switch (value) {
      case 0: return INTEGRITY_STATE_UNSPECIFIED;
      case 1: return INTEGRITY_STATE_VERIFIED;
      case 2: return INTEGRITY_STATE_UNVERIFIED;
      case 3: return INTEGRITY_STATE_FAILED;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<IntegrityState>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      IntegrityState> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<IntegrityState>() {
          public IntegrityState findValueByNumber(int number) {
            return IntegrityState.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.traffic.proto.traffic.v1.AnalysisProto.getDescriptor().getEnumTypes().get(14);
  }

  private static final IntegrityState[] VALUES = values();

  public static IntegrityState valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private IntegrityState(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:traffic.v1.IntegrityState)
}
