// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: traffic/v1/analysis.proto

// Protobuf Java Version: 3.25.2
package com.traffic.proto.traffic.v1;

public interface ListRunResultsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:traffic.v1.ListRunResultsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string tenant_id = 1 [json_name = "tenantId"];</code>
   * @return The tenantId.
   */
  java.lang.String getTenantId();
  /**
   * <code>string tenant_id = 1 [json_name = "tenantId"];</code>
   * @return The bytes for tenantId.
   */
  com.google.protobuf.ByteString
      getTenantIdBytes();

  /**
   * <code>string run_id = 2 [json_name = "runId"];</code>
   * @return The runId.
   */
  java.lang.String getRunId();
  /**
   * <code>string run_id = 2 [json_name = "runId"];</code>
   * @return The bytes for runId.
   */
  com.google.protobuf.ByteString
      getRunIdBytes();

  /**
   * <code>.traffic.v1.DetectorDisposition disposition = 3 [json_name = "disposition"];</code>
   * @return The enum numeric value on the wire for disposition.
   */
  int getDispositionValue();
  /**
   * <code>.traffic.v1.DetectorDisposition disposition = 3 [json_name = "disposition"];</code>
   * @return The disposition.
   */
  com.traffic.proto.traffic.v1.DetectorDisposition getDisposition();

  /**
   * <code>int32 limit = 4 [json_name = "limit"];</code>
   * @return The limit.
   */
  int getLimit();

  /**
   * <code>string cursor = 5 [json_name = "cursor"];</code>
   * @return The cursor.
   */
  java.lang.String getCursor();
  /**
   * <code>string cursor = 5 [json_name = "cursor"];</code>
   * @return The bytes for cursor.
   */
  com.google.protobuf.ByteString
      getCursorBytes();
}
