// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: traffic/v1/pcap.proto

// Protobuf Java Version: 3.25.2
package com.traffic.proto.traffic.v1;

public interface PcapCutResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:traffic.v1.PcapCutResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string job_id = 1 [json_name = "jobId"];</code>
   * @return The jobId.
   */
  java.lang.String getJobId();
  /**
   * <code>string job_id = 1 [json_name = "jobId"];</code>
   * @return The bytes for jobId.
   */
  com.google.protobuf.ByteString
      getJobIdBytes();

  /**
   * <code>string status = 2 [json_name = "status"];</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 2 [json_name = "status"];</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>string download_url = 3 [json_name = "downloadUrl"];</code>
   * @return The downloadUrl.
   */
  java.lang.String getDownloadUrl();
  /**
   * <code>string download_url = 3 [json_name = "downloadUrl"];</code>
   * @return The bytes for downloadUrl.
   */
  com.google.protobuf.ByteString
      getDownloadUrlBytes();

  /**
   * <code>int32 progress_percent = 4 [json_name = "progressPercent"];</code>
   * @return The progressPercent.
   */
  int getProgressPercent();

  /**
   * <code>string error_message = 5 [json_name = "errorMessage"];</code>
   * @return The errorMessage.
   */
  java.lang.String getErrorMessage();
  /**
   * <code>string error_message = 5 [json_name = "errorMessage"];</code>
   * @return The bytes for errorMessage.
   */
  com.google.protobuf.ByteString
      getErrorMessageBytes();

  /**
   * <code>uint64 total_packets = 6 [json_name = "totalPackets"];</code>
   * @return The totalPackets.
   */
  long getTotalPackets();

  /**
   * <code>uint64 total_bytes = 7 [json_name = "totalBytes"];</code>
   * @return The totalBytes.
   */
  long getTotalBytes();

  /**
   * <code>int32 files_scanned = 8 [json_name = "filesScanned"];</code>
   * @return The filesScanned.
   */
  int getFilesScanned();

  /**
   * <code>int32 files_matched = 9 [json_name = "filesMatched"];</code>
   * @return The filesMatched.
   */
  int getFilesMatched();

  /**
   * <code>int64 created_at = 10 [json_name = "createdAt"];</code>
   * @return The createdAt.
   */
  long getCreatedAt();

  /**
   * <code>int64 started_at = 11 [json_name = "startedAt"];</code>
   * @return The startedAt.
   */
  long getStartedAt();

  /**
   * <code>int64 completed_at = 12 [json_name = "completedAt"];</code>
   * @return The completedAt.
   */
  long getCompletedAt();

  /**
   * <code>int64 expires_at = 13 [json_name = "expiresAt"];</code>
   * @return The expiresAt.
   */
  long getExpiresAt();
}
