// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: traffic/v1/analysis.proto

// Protobuf Java Version: 3.25.2
package com.traffic.proto.traffic.v1;

/**
 * <pre>
 * 执行节点 attempt 状态。
 * </pre>
 *
 * Protobuf enum {@code traffic.v1.StageAttemptState}
 */
public enum StageAttemptState
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>STAGE_ATTEMPT_STATE_UNSPECIFIED = 0;</code>
   */
  STAGE_ATTEMPT_STATE_UNSPECIFIED(0),
  /**
   * <code>STAGE_ATTEMPT_STATE_PENDING = 1;</code>
   */
  STAGE_ATTEMPT_STATE_PENDING(1),
  /**
   * <code>STAGE_ATTEMPT_STATE_DISPATCHED = 2;</code>
   */
  STAGE_ATTEMPT_STATE_DISPATCHED(2),
  /**
   * <code>STAGE_ATTEMPT_STATE_RUNNING = 3;</code>
   */
  STAGE_ATTEMPT_STATE_RUNNING(3),
  /**
   * <code>STAGE_ATTEMPT_STATE_SUCCEEDED = 4;</code>
   */
  STAGE_ATTEMPT_STATE_SUCCEEDED(4),
  /**
   * <code>STAGE_ATTEMPT_STATE_PARTIAL = 5;</code>
   */
  STAGE_ATTEMPT_STATE_PARTIAL(5),
  /**
   * <code>STAGE_ATTEMPT_STATE_FAILED = 6;</code>
   */
  STAGE_ATTEMPT_STATE_FAILED(6),
  /**
   * <code>STAGE_ATTEMPT_STATE_CANCEL_REQUESTED = 7;</code>
   */
  STAGE_ATTEMPT_STATE_CANCEL_REQUESTED(7),
  /**
   * <code>STAGE_ATTEMPT_STATE_CANCELLED = 8;</code>
   */
  STAGE_ATTEMPT_STATE_CANCELLED(8),
  /**
   * <code>STAGE_ATTEMPT_STATE_SKIPPED = 9;</code>
   */
  STAGE_ATTEMPT_STATE_SKIPPED(9),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>STAGE_ATTEMPT_STATE_UNSPECIFIED = 0;</code>
   */
  public static final int STAGE_ATTEMPT_STATE_UNSPECIFIED_VALUE = 0;
  /**
   * <code>STAGE_ATTEMPT_STATE_PENDING = 1;</code>
   */
  public static final int STAGE_ATTEMPT_STATE_PENDING_VALUE = 1;
  /**
   * <code>STAGE_ATTEMPT_STATE_DISPATCHED = 2;</code>
   */
  public static final int STAGE_ATTEMPT_STATE_DISPATCHED_VALUE = 2;
  /**
   * <code>STAGE_ATTEMPT_STATE_RUNNING = 3;</code>
   */
  public static final int STAGE_ATTEMPT_STATE_RUNNING_VALUE = 3;
  /**
   * <code>STAGE_ATTEMPT_STATE_SUCCEEDED = 4;</code>
   */
  public static final int STAGE_ATTEMPT_STATE_SUCCEEDED_VALUE = 4;
  /**
   * <code>STAGE_ATTEMPT_STATE_PARTIAL = 5;</code>
   */
  public static final int STAGE_ATTEMPT_STATE_PARTIAL_VALUE = 5;
  /**
   * <code>STAGE_ATTEMPT_STATE_FAILED = 6;</code>
   */
  public static final int STAGE_ATTEMPT_STATE_FAILED_VALUE = 6;
  /**
   * <code>STAGE_ATTEMPT_STATE_CANCEL_REQUESTED = 7;</code>
   */
  public static final int STAGE_ATTEMPT_STATE_CANCEL_REQUESTED_VALUE = 7;
  /**
   * <code>STAGE_ATTEMPT_STATE_CANCELLED = 8;</code>
   */
  public static final int STAGE_ATTEMPT_STATE_CANCELLED_VALUE = 8;
  /**
   * <code>STAGE_ATTEMPT_STATE_SKIPPED = 9;</code>
   */
  public static final int STAGE_ATTEMPT_STATE_SKIPPED_VALUE = 9;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static StageAttemptState valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static StageAttemptState forNumber(int value) {
    switch (value) {
      case 0: return STAGE_ATTEMPT_STATE_UNSPECIFIED;
      case 1: return STAGE_ATTEMPT_STATE_PENDING;
      case 2: return STAGE_ATTEMPT_STATE_DISPATCHED;
      case 3: return STAGE_ATTEMPT_STATE_RUNNING;
      case 4: return STAGE_ATTEMPT_STATE_SUCCEEDED;
      case 5: return STAGE_ATTEMPT_STATE_PARTIAL;
      case 6: return STAGE_ATTEMPT_STATE_FAILED;
      case 7: return STAGE_ATTEMPT_STATE_CANCEL_REQUESTED;
      case 8: return STAGE_ATTEMPT_STATE_CANCELLED;
      case 9: return STAGE_ATTEMPT_STATE_SKIPPED;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<StageAttemptState>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      StageAttemptState> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<StageAttemptState>() {
          public StageAttemptState findValueByNumber(int number) {
            return StageAttemptState.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.traffic.proto.traffic.v1.AnalysisProto.getDescriptor().getEnumTypes().get(9);
  }

  private static final StageAttemptState[] VALUES = values();

  public static StageAttemptState valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private StageAttemptState(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:traffic.v1.StageAttemptState)
}
