// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: traffic/v1/analysis.proto

// Protobuf Java Version: 3.25.2
package com.traffic.proto.traffic.v1;

/**
 * <pre>
 * 即时分析触发(三步向导最终提交;default/custom 均为主业务链执行环节)。
 * </pre>
 *
 * Protobuf type {@code traffic.v1.SubmitTriggerRequest}
 */
public final class SubmitTriggerRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:traffic.v1.SubmitTriggerRequest)
    SubmitTriggerRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SubmitTriggerRequest.newBuilder() to construct.
  private SubmitTriggerRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SubmitTriggerRequest() {
    tenantId_ = "";
    taskDefinitionId_ = "";
    planSource_ = 0;
    customOverridesJson_ = "";
    sourceKind_ = 0;
    sourceSpecJson_ = "";
    clientIdempotencyKey_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SubmitTriggerRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.traffic.proto.traffic.v1.AnalysisProto.internal_static_traffic_v1_SubmitTriggerRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.traffic.proto.traffic.v1.AnalysisProto.internal_static_traffic_v1_SubmitTriggerRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.traffic.proto.traffic.v1.SubmitTriggerRequest.class, com.traffic.proto.traffic.v1.SubmitTriggerRequest.Builder.class);
  }

  public static final int TENANT_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object tenantId_ = "";
  /**
   * <code>string tenant_id = 1 [json_name = "tenantId"];</code>
   * @return The tenantId.
   */
  @java.lang.Override
  public java.lang.String getTenantId() {
    java.lang.Object ref = tenantId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tenantId_ = s;
      return s;
    }
  }
  /**
   * <code>string tenant_id = 1 [json_name = "tenantId"];</code>
   * @return The bytes for tenantId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTenantIdBytes() {
    java.lang.Object ref = tenantId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tenantId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TASK_DEFINITION_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object taskDefinitionId_ = "";
  /**
   * <code>string task_definition_id = 2 [json_name = "taskDefinitionId"];</code>
   * @return The taskDefinitionId.
   */
  @java.lang.Override
  public java.lang.String getTaskDefinitionId() {
    java.lang.Object ref = taskDefinitionId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      taskDefinitionId_ = s;
      return s;
    }
  }
  /**
   * <code>string task_definition_id = 2 [json_name = "taskDefinitionId"];</code>
   * @return The bytes for taskDefinitionId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTaskDefinitionIdBytes() {
    java.lang.Object ref = taskDefinitionId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      taskDefinitionId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PLAN_SOURCE_FIELD_NUMBER = 3;
  private int planSource_ = 0;
  /**
   * <code>.traffic.v1.PlanSource plan_source = 3 [json_name = "planSource"];</code>
   * @return The enum numeric value on the wire for planSource.
   */
  @java.lang.Override public int getPlanSourceValue() {
    return planSource_;
  }
  /**
   * <code>.traffic.v1.PlanSource plan_source = 3 [json_name = "planSource"];</code>
   * @return The planSource.
   */
  @java.lang.Override public com.traffic.proto.traffic.v1.PlanSource getPlanSource() {
    com.traffic.proto.traffic.v1.PlanSource result = com.traffic.proto.traffic.v1.PlanSource.forNumber(planSource_);
    return result == null ? com.traffic.proto.traffic.v1.PlanSource.UNRECOGNIZED : result;
  }

  public static final int CUSTOM_OVERRIDES_JSON_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object customOverridesJson_ = "";
  /**
   * <pre>
   * custom 时才携带;覆盖项=探针/采集源/特征/识别模型/检测模型/规则/阈值
   * </pre>
   *
   * <code>string custom_overrides_json = 4 [json_name = "customOverridesJson"];</code>
   * @return The customOverridesJson.
   */
  @java.lang.Override
  public java.lang.String getCustomOverridesJson() {
    java.lang.Object ref = customOverridesJson_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      customOverridesJson_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * custom 时才携带;覆盖项=探针/采集源/特征/识别模型/检测模型/规则/阈值
   * </pre>
   *
   * <code>string custom_overrides_json = 4 [json_name = "customOverridesJson"];</code>
   * @return The bytes for customOverridesJson.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCustomOverridesJsonBytes() {
    java.lang.Object ref = customOverridesJson_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      customOverridesJson_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SOURCE_KIND_FIELD_NUMBER = 5;
  private int sourceKind_ = 0;
  /**
   * <code>.traffic.v1.SourceKind source_kind = 5 [json_name = "sourceKind"];</code>
   * @return The enum numeric value on the wire for sourceKind.
   */
  @java.lang.Override public int getSourceKindValue() {
    return sourceKind_;
  }
  /**
   * <code>.traffic.v1.SourceKind source_kind = 5 [json_name = "sourceKind"];</code>
   * @return The sourceKind.
   */
  @java.lang.Override public com.traffic.proto.traffic.v1.SourceKind getSourceKind() {
    com.traffic.proto.traffic.v1.SourceKind result = com.traffic.proto.traffic.v1.SourceKind.forNumber(sourceKind_);
    return result == null ? com.traffic.proto.traffic.v1.SourceKind.UNRECOGNIZED : result;
  }

  public static final int SOURCE_SPEC_JSON_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sourceSpecJson_ = "";
  /**
   * <pre>
   * PCAP_REPLAY 必填 object_ref+window
   * </pre>
   *
   * <code>string source_spec_json = 6 [json_name = "sourceSpecJson"];</code>
   * @return The sourceSpecJson.
   */
  @java.lang.Override
  public java.lang.String getSourceSpecJson() {
    java.lang.Object ref = sourceSpecJson_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sourceSpecJson_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * PCAP_REPLAY 必填 object_ref+window
   * </pre>
   *
   * <code>string source_spec_json = 6 [json_name = "sourceSpecJson"];</code>
   * @return The bytes for sourceSpecJson.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSourceSpecJsonBytes() {
    java.lang.Object ref = sourceSpecJson_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sourceSpecJson_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CLIENT_IDEMPOTENCY_KEY_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object clientIdempotencyKey_ = "";
  /**
   * <code>string client_idempotency_key = 7 [json_name = "clientIdempotencyKey"];</code>
   * @return The clientIdempotencyKey.
   */
  @java.lang.Override
  public java.lang.String getClientIdempotencyKey() {
    java.lang.Object ref = clientIdempotencyKey_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      clientIdempotencyKey_ = s;
      return s;
    }
  }
  /**
   * <code>string client_idempotency_key = 7 [json_name = "clientIdempotencyKey"];</code>
   * @return The bytes for clientIdempotencyKey.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getClientIdempotencyKeyBytes() {
    java.lang.Object ref = clientIdempotencyKey_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      clientIdempotencyKey_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tenantId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, tenantId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(taskDefinitionId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, taskDefinitionId_);
    }
    if (planSource_ != com.traffic.proto.traffic.v1.PlanSource.PLAN_SOURCE_UNSPECIFIED.getNumber()) {
      output.writeEnum(3, planSource_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(customOverridesJson_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, customOverridesJson_);
    }
    if (sourceKind_ != com.traffic.proto.traffic.v1.SourceKind.SOURCE_KIND_UNSPECIFIED.getNumber()) {
      output.writeEnum(5, sourceKind_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sourceSpecJson_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, sourceSpecJson_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(clientIdempotencyKey_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, clientIdempotencyKey_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tenantId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, tenantId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(taskDefinitionId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, taskDefinitionId_);
    }
    if (planSource_ != com.traffic.proto.traffic.v1.PlanSource.PLAN_SOURCE_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, planSource_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(customOverridesJson_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, customOverridesJson_);
    }
    if (sourceKind_ != com.traffic.proto.traffic.v1.SourceKind.SOURCE_KIND_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, sourceKind_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sourceSpecJson_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, sourceSpecJson_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(clientIdempotencyKey_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, clientIdempotencyKey_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.traffic.proto.traffic.v1.SubmitTriggerRequest)) {
      return super.equals(obj);
    }
    com.traffic.proto.traffic.v1.SubmitTriggerRequest other = (com.traffic.proto.traffic.v1.SubmitTriggerRequest) obj;

    if (!getTenantId()
        .equals(other.getTenantId())) return false;
    if (!getTaskDefinitionId()
        .equals(other.getTaskDefinitionId())) return false;
    if (planSource_ != other.planSource_) return false;
    if (!getCustomOverridesJson()
        .equals(other.getCustomOverridesJson())) return false;
    if (sourceKind_ != other.sourceKind_) return false;
    if (!getSourceSpecJson()
        .equals(other.getSourceSpecJson())) return false;
    if (!getClientIdempotencyKey()
        .equals(other.getClientIdempotencyKey())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TENANT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getTenantId().hashCode();
    hash = (37 * hash) + TASK_DEFINITION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getTaskDefinitionId().hashCode();
    hash = (37 * hash) + PLAN_SOURCE_FIELD_NUMBER;
    hash = (53 * hash) + planSource_;
    hash = (37 * hash) + CUSTOM_OVERRIDES_JSON_FIELD_NUMBER;
    hash = (53 * hash) + getCustomOverridesJson().hashCode();
    hash = (37 * hash) + SOURCE_KIND_FIELD_NUMBER;
    hash = (53 * hash) + sourceKind_;
    hash = (37 * hash) + SOURCE_SPEC_JSON_FIELD_NUMBER;
    hash = (53 * hash) + getSourceSpecJson().hashCode();
    hash = (37 * hash) + CLIENT_IDEMPOTENCY_KEY_FIELD_NUMBER;
    hash = (53 * hash) + getClientIdempotencyKey().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.traffic.proto.traffic.v1.SubmitTriggerRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.traffic.proto.traffic.v1.SubmitTriggerRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.traffic.proto.traffic.v1.SubmitTriggerRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.traffic.proto.traffic.v1.SubmitTriggerRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.traffic.proto.traffic.v1.SubmitTriggerRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.traffic.proto.traffic.v1.SubmitTriggerRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.traffic.proto.traffic.v1.SubmitTriggerRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.traffic.proto.traffic.v1.SubmitTriggerRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.traffic.proto.traffic.v1.SubmitTriggerRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.traffic.proto.traffic.v1.SubmitTriggerRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.traffic.proto.traffic.v1.SubmitTriggerRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.traffic.proto.traffic.v1.SubmitTriggerRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.traffic.proto.traffic.v1.SubmitTriggerRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 即时分析触发(三步向导最终提交;default/custom 均为主业务链执行环节)。
   * </pre>
   *
   * Protobuf type {@code traffic.v1.SubmitTriggerRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:traffic.v1.SubmitTriggerRequest)
      com.traffic.proto.traffic.v1.SubmitTriggerRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.traffic.proto.traffic.v1.AnalysisProto.internal_static_traffic_v1_SubmitTriggerRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.traffic.proto.traffic.v1.AnalysisProto.internal_static_traffic_v1_SubmitTriggerRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.traffic.proto.traffic.v1.SubmitTriggerRequest.class, com.traffic.proto.traffic.v1.SubmitTriggerRequest.Builder.class);
    }

    // Construct using com.traffic.proto.traffic.v1.SubmitTriggerRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      tenantId_ = "";
      taskDefinitionId_ = "";
      planSource_ = 0;
      customOverridesJson_ = "";
      sourceKind_ = 0;
      sourceSpecJson_ = "";
      clientIdempotencyKey_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.traffic.proto.traffic.v1.AnalysisProto.internal_static_traffic_v1_SubmitTriggerRequest_descriptor;
    }

    @java.lang.Override
    public com.traffic.proto.traffic.v1.SubmitTriggerRequest getDefaultInstanceForType() {
      return com.traffic.proto.traffic.v1.SubmitTriggerRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.traffic.proto.traffic.v1.SubmitTriggerRequest build() {
      com.traffic.proto.traffic.v1.SubmitTriggerRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.traffic.proto.traffic.v1.SubmitTriggerRequest buildPartial() {
      com.traffic.proto.traffic.v1.SubmitTriggerRequest result = new com.traffic.proto.traffic.v1.SubmitTriggerRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.traffic.proto.traffic.v1.SubmitTriggerRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.tenantId_ = tenantId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.taskDefinitionId_ = taskDefinitionId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.planSource_ = planSource_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.customOverridesJson_ = customOverridesJson_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.sourceKind_ = sourceKind_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.sourceSpecJson_ = sourceSpecJson_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.clientIdempotencyKey_ = clientIdempotencyKey_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.traffic.proto.traffic.v1.SubmitTriggerRequest) {
        return mergeFrom((com.traffic.proto.traffic.v1.SubmitTriggerRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.traffic.proto.traffic.v1.SubmitTriggerRequest other) {
      if (other == com.traffic.proto.traffic.v1.SubmitTriggerRequest.getDefaultInstance()) return this;
      if (!other.getTenantId().isEmpty()) {
        tenantId_ = other.tenantId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getTaskDefinitionId().isEmpty()) {
        taskDefinitionId_ = other.taskDefinitionId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.planSource_ != 0) {
        setPlanSourceValue(other.getPlanSourceValue());
      }
      if (!other.getCustomOverridesJson().isEmpty()) {
        customOverridesJson_ = other.customOverridesJson_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.sourceKind_ != 0) {
        setSourceKindValue(other.getSourceKindValue());
      }
      if (!other.getSourceSpecJson().isEmpty()) {
        sourceSpecJson_ = other.sourceSpecJson_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (!other.getClientIdempotencyKey().isEmpty()) {
        clientIdempotencyKey_ = other.clientIdempotencyKey_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              tenantId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              taskDefinitionId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              planSource_ = input.readEnum();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              customOverridesJson_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 40: {
              sourceKind_ = input.readEnum();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 50: {
              sourceSpecJson_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              clientIdempotencyKey_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object tenantId_ = "";
    /**
     * <code>string tenant_id = 1 [json_name = "tenantId"];</code>
     * @return The tenantId.
     */
    public java.lang.String getTenantId() {
      java.lang.Object ref = tenantId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tenantId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string tenant_id = 1 [json_name = "tenantId"];</code>
     * @return The bytes for tenantId.
     */
    public com.google.protobuf.ByteString
        getTenantIdBytes() {
      java.lang.Object ref = tenantId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tenantId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string tenant_id = 1 [json_name = "tenantId"];</code>
     * @param value The tenantId to set.
     * @return This builder for chaining.
     */
    public Builder setTenantId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      tenantId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string tenant_id = 1 [json_name = "tenantId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTenantId() {
      tenantId_ = getDefaultInstance().getTenantId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string tenant_id = 1 [json_name = "tenantId"];</code>
     * @param value The bytes for tenantId to set.
     * @return This builder for chaining.
     */
    public Builder setTenantIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      tenantId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object taskDefinitionId_ = "";
    /**
     * <code>string task_definition_id = 2 [json_name = "taskDefinitionId"];</code>
     * @return The taskDefinitionId.
     */
    public java.lang.String getTaskDefinitionId() {
      java.lang.Object ref = taskDefinitionId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        taskDefinitionId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string task_definition_id = 2 [json_name = "taskDefinitionId"];</code>
     * @return The bytes for taskDefinitionId.
     */
    public com.google.protobuf.ByteString
        getTaskDefinitionIdBytes() {
      java.lang.Object ref = taskDefinitionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        taskDefinitionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string task_definition_id = 2 [json_name = "taskDefinitionId"];</code>
     * @param value The taskDefinitionId to set.
     * @return This builder for chaining.
     */
    public Builder setTaskDefinitionId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      taskDefinitionId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string task_definition_id = 2 [json_name = "taskDefinitionId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTaskDefinitionId() {
      taskDefinitionId_ = getDefaultInstance().getTaskDefinitionId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string task_definition_id = 2 [json_name = "taskDefinitionId"];</code>
     * @param value The bytes for taskDefinitionId to set.
     * @return This builder for chaining.
     */
    public Builder setTaskDefinitionIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      taskDefinitionId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private int planSource_ = 0;
    /**
     * <code>.traffic.v1.PlanSource plan_source = 3 [json_name = "planSource"];</code>
     * @return The enum numeric value on the wire for planSource.
     */
    @java.lang.Override public int getPlanSourceValue() {
      return planSource_;
    }
    /**
     * <code>.traffic.v1.PlanSource plan_source = 3 [json_name = "planSource"];</code>
     * @param value The enum numeric value on the wire for planSource to set.
     * @return This builder for chaining.
     */
    public Builder setPlanSourceValue(int value) {
      planSource_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.traffic.v1.PlanSource plan_source = 3 [json_name = "planSource"];</code>
     * @return The planSource.
     */
    @java.lang.Override
    public com.traffic.proto.traffic.v1.PlanSource getPlanSource() {
      com.traffic.proto.traffic.v1.PlanSource result = com.traffic.proto.traffic.v1.PlanSource.forNumber(planSource_);
      return result == null ? com.traffic.proto.traffic.v1.PlanSource.UNRECOGNIZED : result;
    }
    /**
     * <code>.traffic.v1.PlanSource plan_source = 3 [json_name = "planSource"];</code>
     * @param value The planSource to set.
     * @return This builder for chaining.
     */
    public Builder setPlanSource(com.traffic.proto.traffic.v1.PlanSource value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000004;
      planSource_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.traffic.v1.PlanSource plan_source = 3 [json_name = "planSource"];</code>
     * @return This builder for chaining.
     */
    public Builder clearPlanSource() {
      bitField0_ = (bitField0_ & ~0x00000004);
      planSource_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object customOverridesJson_ = "";
    /**
     * <pre>
     * custom 时才携带;覆盖项=探针/采集源/特征/识别模型/检测模型/规则/阈值
     * </pre>
     *
     * <code>string custom_overrides_json = 4 [json_name = "customOverridesJson"];</code>
     * @return The customOverridesJson.
     */
    public java.lang.String getCustomOverridesJson() {
      java.lang.Object ref = customOverridesJson_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        customOverridesJson_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * custom 时才携带;覆盖项=探针/采集源/特征/识别模型/检测模型/规则/阈值
     * </pre>
     *
     * <code>string custom_overrides_json = 4 [json_name = "customOverridesJson"];</code>
     * @return The bytes for customOverridesJson.
     */
    public com.google.protobuf.ByteString
        getCustomOverridesJsonBytes() {
      java.lang.Object ref = customOverridesJson_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        customOverridesJson_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * custom 时才携带;覆盖项=探针/采集源/特征/识别模型/检测模型/规则/阈值
     * </pre>
     *
     * <code>string custom_overrides_json = 4 [json_name = "customOverridesJson"];</code>
     * @param value The customOverridesJson to set.
     * @return This builder for chaining.
     */
    public Builder setCustomOverridesJson(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      customOverridesJson_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * custom 时才携带;覆盖项=探针/采集源/特征/识别模型/检测模型/规则/阈值
     * </pre>
     *
     * <code>string custom_overrides_json = 4 [json_name = "customOverridesJson"];</code>
     * @return This builder for chaining.
     */
    public Builder clearCustomOverridesJson() {
      customOverridesJson_ = getDefaultInstance().getCustomOverridesJson();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * custom 时才携带;覆盖项=探针/采集源/特征/识别模型/检测模型/规则/阈值
     * </pre>
     *
     * <code>string custom_overrides_json = 4 [json_name = "customOverridesJson"];</code>
     * @param value The bytes for customOverridesJson to set.
     * @return This builder for chaining.
     */
    public Builder setCustomOverridesJsonBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      customOverridesJson_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private int sourceKind_ = 0;
    /**
     * <code>.traffic.v1.SourceKind source_kind = 5 [json_name = "sourceKind"];</code>
     * @return The enum numeric value on the wire for sourceKind.
     */
    @java.lang.Override public int getSourceKindValue() {
      return sourceKind_;
    }
    /**
     * <code>.traffic.v1.SourceKind source_kind = 5 [json_name = "sourceKind"];</code>
     * @param value The enum numeric value on the wire for sourceKind to set.
     * @return This builder for chaining.
     */
    public Builder setSourceKindValue(int value) {
      sourceKind_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.traffic.v1.SourceKind source_kind = 5 [json_name = "sourceKind"];</code>
     * @return The sourceKind.
     */
    @java.lang.Override
    public com.traffic.proto.traffic.v1.SourceKind getSourceKind() {
      com.traffic.proto.traffic.v1.SourceKind result = com.traffic.proto.traffic.v1.SourceKind.forNumber(sourceKind_);
      return result == null ? com.traffic.proto.traffic.v1.SourceKind.UNRECOGNIZED : result;
    }
    /**
     * <code>.traffic.v1.SourceKind source_kind = 5 [json_name = "sourceKind"];</code>
     * @param value The sourceKind to set.
     * @return This builder for chaining.
     */
    public Builder setSourceKind(com.traffic.proto.traffic.v1.SourceKind value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000010;
      sourceKind_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.traffic.v1.SourceKind source_kind = 5 [json_name = "sourceKind"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSourceKind() {
      bitField0_ = (bitField0_ & ~0x00000010);
      sourceKind_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object sourceSpecJson_ = "";
    /**
     * <pre>
     * PCAP_REPLAY 必填 object_ref+window
     * </pre>
     *
     * <code>string source_spec_json = 6 [json_name = "sourceSpecJson"];</code>
     * @return The sourceSpecJson.
     */
    public java.lang.String getSourceSpecJson() {
      java.lang.Object ref = sourceSpecJson_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sourceSpecJson_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * PCAP_REPLAY 必填 object_ref+window
     * </pre>
     *
     * <code>string source_spec_json = 6 [json_name = "sourceSpecJson"];</code>
     * @return The bytes for sourceSpecJson.
     */
    public com.google.protobuf.ByteString
        getSourceSpecJsonBytes() {
      java.lang.Object ref = sourceSpecJson_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sourceSpecJson_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * PCAP_REPLAY 必填 object_ref+window
     * </pre>
     *
     * <code>string source_spec_json = 6 [json_name = "sourceSpecJson"];</code>
     * @param value The sourceSpecJson to set.
     * @return This builder for chaining.
     */
    public Builder setSourceSpecJson(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sourceSpecJson_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * PCAP_REPLAY 必填 object_ref+window
     * </pre>
     *
     * <code>string source_spec_json = 6 [json_name = "sourceSpecJson"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSourceSpecJson() {
      sourceSpecJson_ = getDefaultInstance().getSourceSpecJson();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * PCAP_REPLAY 必填 object_ref+window
     * </pre>
     *
     * <code>string source_spec_json = 6 [json_name = "sourceSpecJson"];</code>
     * @param value The bytes for sourceSpecJson to set.
     * @return This builder for chaining.
     */
    public Builder setSourceSpecJsonBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sourceSpecJson_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private java.lang.Object clientIdempotencyKey_ = "";
    /**
     * <code>string client_idempotency_key = 7 [json_name = "clientIdempotencyKey"];</code>
     * @return The clientIdempotencyKey.
     */
    public java.lang.String getClientIdempotencyKey() {
      java.lang.Object ref = clientIdempotencyKey_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientIdempotencyKey_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string client_idempotency_key = 7 [json_name = "clientIdempotencyKey"];</code>
     * @return The bytes for clientIdempotencyKey.
     */
    public com.google.protobuf.ByteString
        getClientIdempotencyKeyBytes() {
      java.lang.Object ref = clientIdempotencyKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientIdempotencyKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string client_idempotency_key = 7 [json_name = "clientIdempotencyKey"];</code>
     * @param value The clientIdempotencyKey to set.
     * @return This builder for chaining.
     */
    public Builder setClientIdempotencyKey(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      clientIdempotencyKey_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>string client_idempotency_key = 7 [json_name = "clientIdempotencyKey"];</code>
     * @return This builder for chaining.
     */
    public Builder clearClientIdempotencyKey() {
      clientIdempotencyKey_ = getDefaultInstance().getClientIdempotencyKey();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <code>string client_idempotency_key = 7 [json_name = "clientIdempotencyKey"];</code>
     * @param value The bytes for clientIdempotencyKey to set.
     * @return This builder for chaining.
     */
    public Builder setClientIdempotencyKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      clientIdempotencyKey_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:traffic.v1.SubmitTriggerRequest)
  }

  // @@protoc_insertion_point(class_scope:traffic.v1.SubmitTriggerRequest)
  private static final com.traffic.proto.traffic.v1.SubmitTriggerRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.traffic.proto.traffic.v1.SubmitTriggerRequest();
  }

  public static com.traffic.proto.traffic.v1.SubmitTriggerRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SubmitTriggerRequest>
      PARSER = new com.google.protobuf.AbstractParser<SubmitTriggerRequest>() {
    @java.lang.Override
    public SubmitTriggerRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SubmitTriggerRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SubmitTriggerRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.traffic.proto.traffic.v1.SubmitTriggerRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}
