// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: traffic/v1/ingest.proto

// Protobuf Java Version: 3.25.2
package com.traffic.proto.traffic.v1;

/**
 * Protobuf type {@code traffic.v1.UploadPcapIndexRequest}
 */
public final class UploadPcapIndexRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:traffic.v1.UploadPcapIndexRequest)
    UploadPcapIndexRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UploadPcapIndexRequest.newBuilder() to construct.
  private UploadPcapIndexRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UploadPcapIndexRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new UploadPcapIndexRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.traffic.proto.traffic.v1.IngestProto.internal_static_traffic_v1_UploadPcapIndexRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.traffic.proto.traffic.v1.IngestProto.internal_static_traffic_v1_UploadPcapIndexRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.traffic.proto.traffic.v1.UploadPcapIndexRequest.class, com.traffic.proto.traffic.v1.UploadPcapIndexRequest.Builder.class);
  }

  private int bitField0_;
  public static final int INDEX_FIELD_NUMBER = 1;
  private com.traffic.proto.traffic.v1.PcapIndexMeta index_;
  /**
   * <code>.traffic.v1.PcapIndexMeta index = 1 [json_name = "index"];</code>
   * @return Whether the index field is set.
   */
  @java.lang.Override
  public boolean hasIndex() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.traffic.v1.PcapIndexMeta index = 1 [json_name = "index"];</code>
   * @return The index.
   */
  @java.lang.Override
  public com.traffic.proto.traffic.v1.PcapIndexMeta getIndex() {
    return index_ == null ? com.traffic.proto.traffic.v1.PcapIndexMeta.getDefaultInstance() : index_;
  }
  /**
   * <code>.traffic.v1.PcapIndexMeta index = 1 [json_name = "index"];</code>
   */
  @java.lang.Override
  public com.traffic.proto.traffic.v1.PcapIndexMetaOrBuilder getIndexOrBuilder() {
    return index_ == null ? com.traffic.proto.traffic.v1.PcapIndexMeta.getDefaultInstance() : index_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getIndex());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getIndex());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.traffic.proto.traffic.v1.UploadPcapIndexRequest)) {
      return super.equals(obj);
    }
    com.traffic.proto.traffic.v1.UploadPcapIndexRequest other = (com.traffic.proto.traffic.v1.UploadPcapIndexRequest) obj;

    if (hasIndex() != other.hasIndex()) return false;
    if (hasIndex()) {
      if (!getIndex()
          .equals(other.getIndex())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasIndex()) {
      hash = (37 * hash) + INDEX_FIELD_NUMBER;
      hash = (53 * hash) + getIndex().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.traffic.proto.traffic.v1.UploadPcapIndexRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.traffic.proto.traffic.v1.UploadPcapIndexRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.traffic.proto.traffic.v1.UploadPcapIndexRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.traffic.proto.traffic.v1.UploadPcapIndexRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.traffic.proto.traffic.v1.UploadPcapIndexRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.traffic.proto.traffic.v1.UploadPcapIndexRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.traffic.proto.traffic.v1.UploadPcapIndexRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.traffic.proto.traffic.v1.UploadPcapIndexRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.traffic.proto.traffic.v1.UploadPcapIndexRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.traffic.proto.traffic.v1.UploadPcapIndexRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.traffic.proto.traffic.v1.UploadPcapIndexRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.traffic.proto.traffic.v1.UploadPcapIndexRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.traffic.proto.traffic.v1.UploadPcapIndexRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code traffic.v1.UploadPcapIndexRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:traffic.v1.UploadPcapIndexRequest)
      com.traffic.proto.traffic.v1.UploadPcapIndexRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.traffic.proto.traffic.v1.IngestProto.internal_static_traffic_v1_UploadPcapIndexRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.traffic.proto.traffic.v1.IngestProto.internal_static_traffic_v1_UploadPcapIndexRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.traffic.proto.traffic.v1.UploadPcapIndexRequest.class, com.traffic.proto.traffic.v1.UploadPcapIndexRequest.Builder.class);
    }

    // Construct using com.traffic.proto.traffic.v1.UploadPcapIndexRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getIndexFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      index_ = null;
      if (indexBuilder_ != null) {
        indexBuilder_.dispose();
        indexBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.traffic.proto.traffic.v1.IngestProto.internal_static_traffic_v1_UploadPcapIndexRequest_descriptor;
    }

    @java.lang.Override
    public com.traffic.proto.traffic.v1.UploadPcapIndexRequest getDefaultInstanceForType() {
      return com.traffic.proto.traffic.v1.UploadPcapIndexRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.traffic.proto.traffic.v1.UploadPcapIndexRequest build() {
      com.traffic.proto.traffic.v1.UploadPcapIndexRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.traffic.proto.traffic.v1.UploadPcapIndexRequest buildPartial() {
      com.traffic.proto.traffic.v1.UploadPcapIndexRequest result = new com.traffic.proto.traffic.v1.UploadPcapIndexRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.traffic.proto.traffic.v1.UploadPcapIndexRequest result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.index_ = indexBuilder_ == null
            ? index_
            : indexBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.traffic.proto.traffic.v1.UploadPcapIndexRequest) {
        return mergeFrom((com.traffic.proto.traffic.v1.UploadPcapIndexRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.traffic.proto.traffic.v1.UploadPcapIndexRequest other) {
      if (other == com.traffic.proto.traffic.v1.UploadPcapIndexRequest.getDefaultInstance()) return this;
      if (other.hasIndex()) {
        mergeIndex(other.getIndex());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getIndexFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.traffic.proto.traffic.v1.PcapIndexMeta index_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.traffic.proto.traffic.v1.PcapIndexMeta, com.traffic.proto.traffic.v1.PcapIndexMeta.Builder, com.traffic.proto.traffic.v1.PcapIndexMetaOrBuilder> indexBuilder_;
    /**
     * <code>.traffic.v1.PcapIndexMeta index = 1 [json_name = "index"];</code>
     * @return Whether the index field is set.
     */
    public boolean hasIndex() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.traffic.v1.PcapIndexMeta index = 1 [json_name = "index"];</code>
     * @return The index.
     */
    public com.traffic.proto.traffic.v1.PcapIndexMeta getIndex() {
      if (indexBuilder_ == null) {
        return index_ == null ? com.traffic.proto.traffic.v1.PcapIndexMeta.getDefaultInstance() : index_;
      } else {
        return indexBuilder_.getMessage();
      }
    }
    /**
     * <code>.traffic.v1.PcapIndexMeta index = 1 [json_name = "index"];</code>
     */
    public Builder setIndex(com.traffic.proto.traffic.v1.PcapIndexMeta value) {
      if (indexBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        index_ = value;
      } else {
        indexBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.traffic.v1.PcapIndexMeta index = 1 [json_name = "index"];</code>
     */
    public Builder setIndex(
        com.traffic.proto.traffic.v1.PcapIndexMeta.Builder builderForValue) {
      if (indexBuilder_ == null) {
        index_ = builderForValue.build();
      } else {
        indexBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.traffic.v1.PcapIndexMeta index = 1 [json_name = "index"];</code>
     */
    public Builder mergeIndex(com.traffic.proto.traffic.v1.PcapIndexMeta value) {
      if (indexBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          index_ != null &&
          index_ != com.traffic.proto.traffic.v1.PcapIndexMeta.getDefaultInstance()) {
          getIndexBuilder().mergeFrom(value);
        } else {
          index_ = value;
        }
      } else {
        indexBuilder_.mergeFrom(value);
      }
      if (index_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.traffic.v1.PcapIndexMeta index = 1 [json_name = "index"];</code>
     */
    public Builder clearIndex() {
      bitField0_ = (bitField0_ & ~0x00000001);
      index_ = null;
      if (indexBuilder_ != null) {
        indexBuilder_.dispose();
        indexBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.traffic.v1.PcapIndexMeta index = 1 [json_name = "index"];</code>
     */
    public com.traffic.proto.traffic.v1.PcapIndexMeta.Builder getIndexBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getIndexFieldBuilder().getBuilder();
    }
    /**
     * <code>.traffic.v1.PcapIndexMeta index = 1 [json_name = "index"];</code>
     */
    public com.traffic.proto.traffic.v1.PcapIndexMetaOrBuilder getIndexOrBuilder() {
      if (indexBuilder_ != null) {
        return indexBuilder_.getMessageOrBuilder();
      } else {
        return index_ == null ?
            com.traffic.proto.traffic.v1.PcapIndexMeta.getDefaultInstance() : index_;
      }
    }
    /**
     * <code>.traffic.v1.PcapIndexMeta index = 1 [json_name = "index"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.traffic.proto.traffic.v1.PcapIndexMeta, com.traffic.proto.traffic.v1.PcapIndexMeta.Builder, com.traffic.proto.traffic.v1.PcapIndexMetaOrBuilder> 
        getIndexFieldBuilder() {
      if (indexBuilder_ == null) {
        indexBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.traffic.proto.traffic.v1.PcapIndexMeta, com.traffic.proto.traffic.v1.PcapIndexMeta.Builder, com.traffic.proto.traffic.v1.PcapIndexMetaOrBuilder>(
                getIndex(),
                getParentForChildren(),
                isClean());
        index_ = null;
      }
      return indexBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:traffic.v1.UploadPcapIndexRequest)
  }

  // @@protoc_insertion_point(class_scope:traffic.v1.UploadPcapIndexRequest)
  private static final com.traffic.proto.traffic.v1.UploadPcapIndexRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.traffic.proto.traffic.v1.UploadPcapIndexRequest();
  }

  public static com.traffic.proto.traffic.v1.UploadPcapIndexRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UploadPcapIndexRequest>
      PARSER = new com.google.protobuf.AbstractParser<UploadPcapIndexRequest>() {
    @java.lang.Override
    public UploadPcapIndexRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<UploadPcapIndexRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UploadPcapIndexRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.traffic.proto.traffic.v1.UploadPcapIndexRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

