import type { ActionEndpointPlan, EndpointPlan } from '@/services/pageApiPlans';

const encryptedAction = (
  id: string,
  label: string,
  endpoint: '/v1/encrypted-traffic/egress-actions' | '/v1/encrypted-traffic/evidence-actions',
  auditEvent: string,
  action: string,
  guardrails: string[],
): ActionEndpointPlan => ({
  id,
  label,
  method: 'POST',
  endpoint,
  requiredScopes: ['alert:write'],
  acceptedScopes: ['alert:write', 'alert:*', 'admin:*', '*'],
  auditEvent,
  defaultBody: { action },
  guardrails,
});

export const encryptedTrafficPagePlan: EndpointPlan = {
  primary: '/v1/encrypted-traffic/stats',
  secondary: [
    '/v1/encrypted-traffic/sessions',
    '/v1/encrypted-traffic/ja3',
    '/v1/encrypted-traffic/tunnels',
    '/v1/encrypted-traffic/exfiltration',
    '/v1/encrypted-traffic/evidence',
  ],
  actions: [
    encryptedAction(
      'egress-create-alert',
      'Create encrypted egress alert request',
      '/v1/encrypted-traffic/egress-actions',
      'ENCRYPTED_EGRESS_ALERT_REQUESTED',
      'create_alert',
      [
        'target and action are required',
        'the request must persist an audit_logs row before reporting success',
        'a request is not presented as a confirmed alert until the rule service evaluates it',
      ],
    ),
    encryptedAction(
      'egress-evidence-lookup',
      'Audit encrypted egress evidence lookup',
      '/v1/encrypted-traffic/egress-actions',
      'ENCRYPTED_EGRESS_EVIDENCE_LOOKUP',
      'lookup_evidence',
      [
        'target and action are required',
        'the lookup audit must persist before the UI opens the evidence route',
      ],
    ),
    encryptedAction(
      'egress-entity-graph',
      'Audit encrypted egress graph drilldown',
      '/v1/encrypted-traffic/egress-actions',
      'ENCRYPTED_EGRESS_GRAPH_DRILLDOWN',
      'entity_graph',
      [
        'target and action are required',
        'the drilldown audit must persist before the UI opens the graph route',
      ],
    ),
    encryptedAction(
      'egress-audit-write',
      'Write encrypted egress analysis audit',
      '/v1/encrypted-traffic/egress-actions',
      'ENCRYPTED_EGRESS_AUDIT_WRITTEN',
      'write_audit',
      [
        'target and action are required',
        'the API must return failure when audit persistence fails',
      ],
    ),
    encryptedAction(
      'egress-response-request',
      'Submit encrypted egress response request',
      '/v1/encrypted-traffic/egress-actions',
      'ENCRYPTED_EGRESS_RESPONSE_REQUESTED',
      'response_request',
      [
        'target and action are required',
        'response requests must persist an audit_logs row before reporting success',
      ],
    ),
    encryptedAction(
      'evidence-create-task',
      'Create encrypted evidence task request',
      '/v1/encrypted-traffic/evidence-actions',
      'ENCRYPTED_EVIDENCE_TASK_REQUESTED',
      'create_task',
      [
        'target and action are required',
        'the request must persist an audit_logs row before reporting success',
        'the UI must label the result as an evidence-task request rather than a completed collection job',
      ],
    ),
    encryptedAction(
      'evidence-download-pcap',
      'Request encrypted evidence PCAP download',
      '/v1/encrypted-traffic/evidence-actions',
      'ENCRYPTED_EVIDENCE_PCAP_DOWNLOAD_REQUESTED',
      'download_pcap',
      ['target and action are required', 'the request must persist an audit_logs row before reporting success'],
    ),
    encryptedAction(
      'evidence-verify-hash',
      'Request encrypted evidence hash verification',
      '/v1/encrypted-traffic/evidence-actions',
      'ENCRYPTED_EVIDENCE_HASH_VERIFICATION_REQUESTED',
      'verify_hash',
      ['target and action are required', 'the request must persist an audit_logs row before reporting success'],
    ),
    encryptedAction(
      'evidence-export-package',
      'Request encrypted evidence package export',
      '/v1/encrypted-traffic/evidence-actions',
      'ENCRYPTED_EVIDENCE_EXPORT_REQUESTED',
      'export_package',
      ['target and action are required', 'the request must persist an audit_logs row before reporting success'],
    ),
    encryptedAction(
      'evidence-associate-analysis',
      'Request encrypted evidence correlation analysis',
      '/v1/encrypted-traffic/evidence-actions',
      'ENCRYPTED_EVIDENCE_ANALYSIS_REQUESTED',
      'associate_analysis',
      ['target and action are required', 'the request must persist an audit_logs row before reporting success'],
    ),
    encryptedAction(
      'evidence-preserve',
      'Request encrypted evidence preservation',
      '/v1/encrypted-traffic/evidence-actions',
      'ENCRYPTED_EVIDENCE_PRESERVATION_REQUESTED',
      'preserve_evidence',
      ['target and action are required', 'the request must persist an audit_logs row before reporting success'],
    ),
    encryptedAction(
      'evidence-link-alert',
      'Link encrypted evidence to alerts',
      '/v1/encrypted-traffic/evidence-actions',
      'ENCRYPTED_EVIDENCE_ALERT_LINK_REQUESTED',
      'link_alert',
      ['target and action are required', 'the request must persist an audit_logs row before reporting success'],
    ),
    encryptedAction(
      'evidence-expert-review',
      'Request encrypted evidence expert review',
      '/v1/encrypted-traffic/evidence-actions',
      'ENCRYPTED_EVIDENCE_EXPERT_REVIEW_REQUESTED',
      'expert_review',
      ['target and action are required', 'the request must persist an audit_logs row before reporting success'],
    ),
    encryptedAction(
      'evidence-gap-mark',
      'Mark encrypted evidence gap',
      '/v1/encrypted-traffic/evidence-actions',
      'ENCRYPTED_EVIDENCE_GAP_MARKED',
      'mark_gap',
      ['target and action are required', 'the request must persist an audit_logs row before reporting success'],
    ),
    encryptedAction(
      'evidence-submit-recommendation',
      'Submit encrypted evidence recommendation',
      '/v1/encrypted-traffic/evidence-actions',
      'ENCRYPTED_EVIDENCE_RECOMMENDATION_SUBMITTED',
      'submit_recommendation',
      ['target and action are required', 'the request must persist an audit_logs row before reporting success'],
    ),
    encryptedAction(
      'evidence-export-report',
      'Request encrypted evidence report export',
      '/v1/encrypted-traffic/evidence-actions',
      'ENCRYPTED_EVIDENCE_REPORT_EXPORT_REQUESTED',
      'export_report',
      ['target and action are required', 'the request must persist an audit_logs row before reporting success'],
    ),
    encryptedAction(
      'evidence-write-audit',
      'Write encrypted evidence review audit',
      '/v1/encrypted-traffic/evidence-actions',
      'ENCRYPTED_EVIDENCE_AUDIT_WRITTEN',
      'write_audit',
      [
        'target and action are required',
        'the API must return failure when audit persistence fails',
      ],
    ),
  ],
};

