export type EndpointPlan = {
  primary: string;
  secondary?: string[];
  pageLoadSecondary?: string[];
  actions?: ActionEndpointPlan[];
};

export type EndpointMethod = "GET" | "POST" | "PUT" | "PATCH" | "DELETE";

export type ActionEndpointPlan = {
  id: string;
  label: string;
  method: EndpointMethod;
  endpoint: string;
  requiredScopes: string[];
  acceptedScopes?: string[];
  auditEvent: string;
  defaultBody?: Record<string, unknown>;
  guardrails: string[];
};

export const pageApiPlans: Record<string, EndpointPlan> = {
  dashboard: {
    primary: "/v1/dashboard/stats",
    secondary: ["/v1/dashboard/alerts/trend", "/v1/dashboard/attack-phases"],
    actions: [
      {
        id: "dashboard-task-create",
        label: "创建闭环任务",
        method: "POST",
        endpoint: "/v1/dashboard/tasks",
        requiredScopes: ["dashboard:write"],
        acceptedScopes: ["dashboard:write", "dashboard:*", "admin:*", "*"],
        auditEvent: "DASHBOARD_TASK_CREATED",
        defaultBody: {
          task_type: "closure",
          target: "dashboard",
          priority: "high",
        },
        guardrails: [
          "task type and target are required",
          "task creation must preserve tenant and current dashboard context",
          "successful submissions must write DASHBOARD_TASK_CREATED audit_logs rows",
        ],
      },
      {
        id: "dashboard-evidence-task-create",
        label: "补齐证据",
        method: "POST",
        endpoint: "/v1/dashboard/tasks/evidence",
        requiredScopes: ["dashboard:write"],
        acceptedScopes: ["dashboard:write", "forensics:write", "admin:*", "*"],
        auditEvent: "DASHBOARD_EVIDENCE_TASK_CREATED",
        defaultBody: { task_type: "evidence_repair", target: "evidence-gap" },
        guardrails: [
          "evidence target is required",
          "task must preserve source event references",
        ],
      },
      {
        id: "dashboard-feedback-task-create",
        label: "回流样本",
        method: "POST",
        endpoint: "/v1/dashboard/tasks/feedback",
        requiredScopes: ["dashboard:write"],
        acceptedScopes: ["dashboard:write", "feedback:write", "admin:*", "*"],
        auditEvent: "DASHBOARD_FEEDBACK_TASK_CREATED",
        defaultBody: { task_type: "feedback_replay", target: "feedback-gap" },
        guardrails: [
          "feedback target is required",
          "sample payloads must remain masked",
        ],
      },
      {
        id: "dashboard-audit-task-create",
        label: "完善留痕",
        method: "POST",
        endpoint: "/v1/dashboard/tasks/audit",
        requiredScopes: ["dashboard:write"],
        acceptedScopes: ["dashboard:write", "audit:write", "admin:*", "*"],
        auditEvent: "DASHBOARD_AUDIT_TASK_CREATED",
        defaultBody: { task_type: "audit_repair", target: "audit-gap" },
        guardrails: [
          "audit gap target is required",
          "existing audit records must remain immutable",
        ],
      },
      {
        id: "dashboard-sla-task-create",
        label: "跟进处理",
        method: "POST",
        endpoint: "/v1/dashboard/tasks/sla",
        requiredScopes: ["dashboard:write"],
        acceptedScopes: ["dashboard:write", "alert:write", "admin:*", "*"],
        auditEvent: "DASHBOARD_SLA_TASK_CREATED",
        defaultBody: { task_type: "sla_followup", target: "overdue-ticket" },
        guardrails: [
          "SLA target is required",
          "task priority must reflect remaining SLA",
        ],
      },
      {
        id: "dashboard-compliance-task-create",
        label: "修复门禁",
        method: "POST",
        endpoint: "/v1/dashboard/tasks/compliance",
        requiredScopes: ["dashboard:write"],
        acceptedScopes: ["dashboard:write", "compliance:write", "admin:*", "*"],
        auditEvent: "DASHBOARD_COMPLIANCE_TASK_CREATED",
        defaultBody: {
          task_type: "compliance_repair",
          target: "compliance-gap",
        },
        guardrails: [
          "compliance target is required",
          "approval gates must not be bypassed",
        ],
      },
    ],
  },
  screen: {
    primary: "/v1/dashboard/stats",
    secondary: [
      "/v1/dashboard/encrypted/trend",
      "/v1/dashboard/attack-phases",
      "/v1/probes",
    ],
  },
  topics: {
    primary: "/v1/topics/tunnel",
    secondary: [
      "/v1/topics/exfil",
      "/v1/topics/apt",
      "/v1/topics/views",
      "/v1/topics/subscriptions",
    ],
    actions: [
      {
        id: "topic-view-save",
        label: "Save topic view",
        method: "POST",
        endpoint: "/v1/topics/views",
        requiredScopes: ["topic:write"],
        acceptedScopes: ["topic:write", "topic:*", "admin:*", "*"],
        auditEvent: "TOPIC_VIEW_SAVED",
        defaultBody: {
          topic: "tunnel",
          name: "核心隧道专题视图",
          filters: { risk: "high" },
          visibility: "team",
        },
        guardrails: [
          "topic and name are required",
          "saved views must persist topic_saved_views rows",
          "successful saves must write TOPIC_VIEW_SAVED audit_logs rows",
        ],
      },
      {
        id: "topic-scope-update",
        label: "Update topic scope",
        method: "PUT",
        endpoint: "/v1/topics/scopes/{topic}",
        requiredScopes: ["topic:write"],
        acceptedScopes: ["topic:write", "topic:*", "admin:*", "*"],
        auditEvent: "TOPIC_SCOPE_UPDATED",
        defaultBody: {
          scope_name: "核心园区出口",
          included_assets: ["core-switch"],
          risk_levels: ["high", "critical"],
          time_window: "24h",
        },
        guardrails: [
          "topic must be one of tunnel, exfil or apt",
          "scope updates must upsert topic_scope_overrides rows",
          "successful updates must write TOPIC_SCOPE_UPDATED audit_logs rows",
        ],
      },
      {
        id: "topic-subscription-create",
        label: "Create topic subscription",
        method: "POST",
        endpoint: "/v1/topics/subscriptions",
        requiredScopes: ["topic:write"],
        acceptedScopes: ["topic:write", "topic:*", "admin:*", "*"],
        auditEvent: "TOPIC_SUBSCRIPTION_CREATED",
        defaultBody: {
          topic: "tunnel",
          channel: "webhook",
          threshold: "high",
          schedule: "realtime",
          recipients: ["soc-duty"],
        },
        guardrails: [
          "topic and recipients are required",
          "subscriptions must persist topic_subscriptions rows",
          "viewer writes must return 403 before persistence",
        ],
      },
      {
        id: "topic-subscription-toggle",
        label: "Toggle topic subscription",
        method: "PATCH",
        endpoint: "/v1/topics/subscriptions/{id}",
        requiredScopes: ["topic:write"],
        acceptedScopes: ["topic:write", "topic:*", "admin:*", "*"],
        auditEvent: "TOPIC_SUBSCRIPTION_UPDATED",
        defaultBody: { enabled: false },
        guardrails: [
          "cross-tenant subscription updates must return 404",
          "toggle state must persist in topic_subscriptions",
          "successful toggles must write TOPIC_SUBSCRIPTION_UPDATED audit_logs rows",
        ],
      },
      {
        id: "topic-report-export",
        label: "Export topic report",
        method: "POST",
        endpoint: "/v1/topics/reports/export",
        requiredScopes: ["topic:export"],
        acceptedScopes: [
          "topic:export",
          "topic:write",
          "topic:*",
          "admin:*",
          "*",
        ],
        auditEvent: "TOPIC_REPORT_EXPORTED",
        defaultBody: { topic: "tunnel", format: "json" },
        guardrails: [
          "topic report export must persist topic_exports rows",
          "export responses must include file_key and retention metadata",
          "successful exports must write TOPIC_REPORT_EXPORTED audit_logs rows",
        ],
      },
      {
        id: "topic-evidence-package-export",
        label: "Export topic evidence package",
        method: "POST",
        endpoint: "/v1/topics/evidence-packages/export",
        requiredScopes: ["topic:export"],
        acceptedScopes: [
          "topic:export",
          "topic:write",
          "topic:*",
          "admin:*",
          "*",
        ],
        auditEvent: "TOPIC_EVIDENCE_PACKAGE_EXPORTED",
        defaultBody: { topic: "exfil", format: "json" },
        guardrails: [
          "evidence package export must persist topic_exports rows",
          "export must preserve tenant isolation",
          "successful exports must write TOPIC_EVIDENCE_PACKAGE_EXPORTED audit_logs rows",
        ],
      },
    ],
  },
  "topic-tunnel": { primary: "/v1/topics/tunnel" },
  "topic-exfil": { primary: "/v1/topics/exfil" },
  "topic-apt": { primary: "/v1/topics/apt" },
  probes: {
    primary: "/v1/probes",
    actions: [
      {
        id: "probe-batch-upgrade",
        label: "Batch upgrade probes",
        method: "POST",
        endpoint: "/v1/probes/batch-upgrade",
        requiredScopes: ["probe:write"],
        acceptedScopes: ["probe:write", "admin:*", "*"],
        auditEvent: "PROBE_BATCH_UPGRADE_QUEUED",
        defaultBody: {
          probe_ids: ["PROBE-DC-01"],
          target_version: "v3.4.8",
          rollout_strategy: "canary",
        },
        guardrails: [
          "target_version and at least one probe_id are required",
          "batch upgrades must persist queued probe_operations rows without claiming agent completion",
          "accepted upgrades must write PROBE_BATCH_UPGRADE_QUEUED audit_logs rows",
        ],
      },
      {
        id: "probe-batch-state",
        label: "Batch enable probes",
        method: "POST",
        endpoint: "/v1/probes/batch-state",
        requiredScopes: ["probe:write"],
        acceptedScopes: ["probe:write", "admin:*", "*"],
        auditEvent: "PROBE_BATCH_STATE_QUEUED",
        defaultBody: {
          probe_ids: ["PROBE-DC-01"],
          desired_state: "active",
          reason: "operator requested from probes page",
        },
        guardrails: [
          "desired_state must be active or inactive",
          "tenant isolation must be checked before state changes",
          "each probe change must persist a probe_operations row and one aggregate audit event",
        ],
      },
      {
        id: "probe-config-push",
        label: "Push probe capture policy",
        method: "POST",
        endpoint: "/v1/probes/{id}/config",
        requiredScopes: ["probe:write"],
        acceptedScopes: ["probe:write", "admin:*", "*"],
        auditEvent: "PROBE_CONFIG_PUSH_QUEUED",
        defaultBody: {
          config_version: "campus-full-capture-20260630",
          capture_mode: "af_packet",
          interfaces: ["eth2", "eth3"],
          archive_path: "s3://pcap-archive/probes/",
          batch_send_mbps: 2000,
        },
        guardrails: [
          "config_version is required",
          "configuration pushes must persist probe_operations rows",
          "configuration remains queued until a probe control consumer acknowledges it",
          "tenant_id must come from the authenticated token for write operations",
        ],
      },
      {
        id: "probe-connectivity-test",
        label: "Run probe connectivity test",
        method: "POST",
        endpoint: "/v1/probes/{id}/connectivity-test",
        requiredScopes: ["probe:write"],
        acceptedScopes: ["probe:write", "admin:*", "*"],
        auditEvent: "PROBE_CONNECTIVITY_TEST_QUEUED",
        defaultBody: { targets: ["ingest-gateway", "kafka", "clickhouse"] },
        guardrails: [
          "connectivity checks must remain queued until the target probe reports measured results",
          "viewer writes must return 403 before persistence",
          "cross-tenant probe operations must return 404",
        ],
      },
      {
        id: "probe-cert-rotate",
        label: "Rotate probe mTLS certificate",
        method: "POST",
        endpoint: "/v1/probes/{id}/certificates/rotate",
        requiredScopes: ["probe:write"],
        acceptedScopes: ["probe:write", "admin:*", "*"],
        auditEvent: "PROBE_CERT_ROTATE_QUEUED",
        defaultBody: {
          secret_ref:
            "k8s://traffic-analysis/traffic-credentials#PROBE_MTLS_CERT",
          rotation_window: "immediate",
        },
        guardrails: [
          "certificate rotation must use secret_ref only",
          "plaintext certificate, private_key, token or password fields must be rejected",
          "accepted rotations must write PROBE_CERT_ROTATE_QUEUED audit_logs rows",
        ],
      },
      {
        id: "probe-restart",
        label: "Restart probe",
        method: "POST",
        endpoint: "/v1/probes/{id}/restart",
        requiredScopes: ["probe:write"],
        acceptedScopes: ["probe:write", "admin:*", "*"],
        auditEvent: "PROBE_RESTART_QUEUED",
        defaultBody: { reason: "operator requested from probes page" },
        guardrails: [
          "restart requests must target one tenant-owned probe",
          "restart requests must persist probe_operations and audit_logs records",
          "the API reports queued until the probe control channel acknowledges execution",
        ],
      },
    ],
  },
  "data-quality": {
    primary: "/v1/data-quality",
    actions: [
      {
        id: "dlq-fallback-replay",
        label: "DLQ fallback replay",
        method: "POST",
        endpoint: "/v1/dlq/replay/fallback",
        requiredScopes: ["dlq:replay"],
        acceptedScopes: ["dlq:replay", "dlq:*", "admin:write", "admin:*", "*"],
        auditEvent: "dlq_replay_approved",
        defaultBody: { dry_run: true },
        guardrails: [
          "approved_by must differ from requested_by",
          "approval_id, reason, repair_summary and idempotency_key are required",
          "dry_run=true is the UI default before execution replay",
        ],
      },
      {
        id: "data-quality-context-action",
        label: "Data quality contextual action",
        method: "POST",
        endpoint: "/v1/data-quality/actions",
        requiredScopes: ["data-quality:write"],
        acceptedScopes: [
          "data-quality:write",
          "data-quality:*",
          "admin:*",
          "*",
        ],
        auditEvent: "DATA_QUALITY_ACTION_REQUESTED",
        defaultBody: {
          view: "overview",
          action: "inspect",
          target: "current-selection",
          dry_run: true,
        },
        guardrails: [
          "view, action and target are required",
          "write actions must default to dry_run=true until explicit confirmation",
          "successful requests must preserve tenant context and write DATA_QUALITY_ACTION_REQUESTED audit_logs rows",
        ],
      },
    ],
  },
  alerts: {
    primary: "/v1/alerts",
    pageLoadSecondary: ["/v1/alerts/stats", "/v1/alerts/trend"],
  },
  "alert-detail": {
    primary: "/v1/alerts/{id}",
    secondary: ["/v1/alerts/{id}/evidence", "/v1/alerts/{id}/feedback"],
    actions: [
      {
        id: "alert-report-export",
        label: "Export alert report",
        method: "POST",
        endpoint: "/v1/alerts/{id}/reports/export",
        requiredScopes: ["alert:read"],
        acceptedScopes: [
          "alert:read",
          "alert:write",
          "alert:*",
          "admin:*",
          "*",
        ],
        auditEvent: "ALERT_REPORT_EXPORT_REQUESTED",
        defaultBody: { format: "pdf" },
        guardrails: [
          "export must contain only the current tenant alert and approved evidence",
          "successful exports must write audit_logs",
        ],
      },
      {
        id: "alert-campaign-link",
        label: "Link alert to campaign",
        method: "POST",
        endpoint: "/v1/alerts/{id}/campaign-links",
        requiredScopes: ["alert:write"],
        acceptedScopes: [
          "alert:write",
          "alert:*",
          "campaign:write",
          "admin:*",
          "*",
        ],
        auditEvent: "ALERT_CAMPAIGN_LINK_REQUESTED",
        defaultBody: { campaign_hint: "auto" },
        guardrails: [
          "campaign link must preserve tenant isolation",
          "successful requests must write audit_logs",
        ],
      },
      {
        id: "alert-evidence-access",
        label: "Request alert evidence access",
        method: "POST",
        endpoint: "/v1/alerts/{id}/evidence/access",
        requiredScopes: ["alert:read"],
        acceptedScopes: [
          "alert:read",
          "evidence:read",
          "alert:*",
          "admin:*",
          "*",
        ],
        auditEvent: "ALERT_EVIDENCE_ACCESS_REQUESTED",
        defaultBody: { purpose: "investigation" },
        guardrails: [
          "evidence access must record the selected evidence and requester",
          "signed URL must be short-lived",
        ],
      },
      {
        id: "alert-response-request",
        label: "Request alert response action",
        method: "POST",
        endpoint: "/v1/alerts/{id}/response-actions",
        requiredScopes: ["alert:write"],
        acceptedScopes: [
          "alert:write",
          "alert:*",
          "playbook:execute",
          "admin:*",
          "*",
        ],
        auditEvent: "ALERT_RESPONSE_ACTION_REQUESTED",
        defaultBody: { dry_run: true },
        guardrails: [
          "high impact responses require confirmation and dry_run=true by default",
          "successful requests must write audit_logs",
        ],
      },
      {
        id: "alert-investigation-note",
        label: "Record alert investigation note",
        method: "POST",
        endpoint: "/v1/alerts/{id}/investigation-notes",
        requiredScopes: ["alert:write"],
        acceptedScopes: ["alert:write", "alert:*", "admin:*", "*"],
        auditEvent: "ALERT_INVESTIGATION_NOTE_RECORDED",
        defaultBody: { source: "alert-detail" },
        guardrails: [
          "notes must include the selected alert and actor",
          "successful writes must retain the audit trace",
        ],
      },
    ],
  },
  campaigns: {
    primary: "/v1/campaigns",
    actions: [
      {
        id: "campaign-export",
        label: "Export campaigns",
        method: "POST",
        endpoint: "/v1/campaigns/actions",
        requiredScopes: ["alert:read"],
        acceptedScopes: ["alert:read", "alert:write", "admin:*", "*"],
        auditEvent: "CAMPAIGN_EXPORT_REQUESTED",
        defaultBody: {
          action_id: "campaign-export",
          format: "csv",
          selection: "current-filter",
        },
        guardrails: [
          "exports must preserve the current tenant and filter context",
          "export requests must write an audit record",
        ],
      },
      {
        id: "campaign-list-settings",
        label: "Update campaign list settings",
        method: "POST",
        endpoint: "/v1/campaigns/actions",
        requiredScopes: ["alert:read"],
        acceptedScopes: ["alert:read", "alert:write", "admin:*", "*"],
        auditEvent: "CAMPAIGN_LIST_SETTINGS_UPDATED",
        defaultBody: {
          action_id: "campaign-list-settings",
          page_size: 20,
          visible_columns: "default",
        },
        guardrails: [
          "list settings must be scoped to the current user",
          "settings changes must write an audit record",
        ],
      },
      {
        id: "campaign-assign-owner",
        label: "Assign campaign owner",
        method: "POST",
        endpoint: "/v1/campaigns/{id}/actions",
        requiredScopes: ["alert:write"],
        acceptedScopes: ["alert:write", "admin:*", "*"],
        auditEvent: "CAMPAIGN_OWNER_ASSIGNED",
        defaultBody: {
          action_id: "campaign-assign-owner",
          action: "assign_owner",
          owner: "current-user",
        },
        guardrails: [
          "campaign and owner are required",
          "owner changes must preserve tenant isolation and write an audit record",
        ],
      },
      {
        id: "campaign-status-change",
        label: "Change campaign status",
        method: "POST",
        endpoint: "/v1/campaigns/{id}/actions",
        requiredScopes: ["alert:write"],
        acceptedScopes: ["alert:write", "admin:*", "*"],
        auditEvent: "CAMPAIGN_STATUS_CHANGED",
        defaultBody: {
          action_id: "campaign-status-change",
          action: "status_change",
          status: "investigating",
        },
        guardrails: [
          "campaign and status are required",
          "status transitions must be validated and audited",
        ],
      },
      {
        id: "campaign-context-action",
        label: "Run campaign contextual action",
        method: "POST",
        endpoint: "/v1/campaigns/{id}/actions",
        requiredScopes: ["alert:write"],
        acceptedScopes: ["alert:write", "admin:*", "*"],
        auditEvent: "CAMPAIGN_CONTEXT_ACTION_REQUESTED",
        defaultBody: {
          action_id: "campaign-context-action",
          action: "inspect",
        },
        guardrails: [
          "campaign and action are required",
          "mutating contextual actions require explicit confirmation",
        ],
      },
      {
        id: "campaign-detail-view",
        label: "View campaign detail",
        method: "POST",
        endpoint: "/v1/campaigns/{id}/actions",
        requiredScopes: ["alert:read"],
        acceptedScopes: ["alert:read", "alert:write", "admin:*", "*"],
        auditEvent: "CAMPAIGN_DETAIL_VIEWED",
        defaultBody: {
          action_id: "campaign-detail-view",
          action: "detail_view",
        },
        guardrails: [
          "campaign reads must preserve tenant isolation",
          "detail views must write an audit record",
        ],
      },
      {
        id: "campaign-phase-inspect",
        label: "Inspect campaign phase",
        method: "POST",
        endpoint: "/v1/campaigns/{id}/actions",
        requiredScopes: ["alert:read"],
        acceptedScopes: ["alert:read", "alert:write", "admin:*", "*"],
        auditEvent: "CAMPAIGN_PHASE_VIEWED",
        defaultBody: {
          action_id: "campaign-phase-inspect",
          action: "phase_inspect",
        },
        guardrails: [
          "campaign and phase are required",
          "phase inspection must write an audit record",
        ],
      },
      {
        id: "campaign-impact-inspect",
        label: "Inspect campaign impact scope",
        method: "POST",
        endpoint: "/v1/campaigns/{id}/actions",
        requiredScopes: ["alert:read"],
        acceptedScopes: ["alert:read", "alert:write", "admin:*", "*"],
        auditEvent: "CAMPAIGN_IMPACT_VIEWED",
        defaultBody: {
          action_id: "campaign-impact-inspect",
          action: "impact_inspect",
        },
        guardrails: [
          "campaign and impact scope are required",
          "impact inspection must write an audit record",
        ],
      },
      {
        id: "campaign-evidence-view",
        label: "View campaign evidence",
        method: "POST",
        endpoint: "/v1/campaigns/{id}/actions",
        requiredScopes: ["alert:read"],
        acceptedScopes: ["alert:read", "alert:write", "admin:*", "*"],
        auditEvent: "CAMPAIGN_EVIDENCE_VIEWED",
        defaultBody: {
          action_id: "campaign-evidence-view",
          action: "evidence_view",
        },
        guardrails: [
          "evidence reads must preserve tenant isolation",
          "evidence access must write an audit record",
        ],
      },
      {
        id: "campaign-report-generate",
        label: "Generate campaign report",
        method: "POST",
        endpoint: "/v1/campaigns/{id}/actions",
        requiredScopes: ["alert:write"],
        acceptedScopes: ["alert:write", "admin:*", "*"],
        auditEvent: "CAMPAIGN_REPORT_REQUESTED",
        defaultBody: {
          action_id: "campaign-report-generate",
          action: "report_generate",
          format: "pdf",
          include_evidence: true,
        },
        guardrails: [
          "report generation must preserve tenant and campaign context",
          "report requests must write an audit record",
        ],
      },
      {
        id: "campaign-attack-chain-view",
        label: "View campaign attack chain",
        method: "POST",
        endpoint: "/v1/campaigns/{id}/actions",
        requiredScopes: ["alert:read"],
        acceptedScopes: ["alert:read", "alert:write", "admin:*", "*"],
        auditEvent: "CAMPAIGN_ATTACK_CHAIN_VIEWED",
        defaultBody: {
          action_id: "campaign-attack-chain-view",
          action: "attack_chain_view",
        },
        guardrails: [
          "attack-chain reads must preserve tenant isolation",
          "attack-chain access must write an audit record",
        ],
      },
      {
        id: "campaign-graph-view",
        label: "View campaign entity graph",
        method: "POST",
        endpoint: "/v1/campaigns/{id}/actions",
        requiredScopes: ["graph:read"],
        acceptedScopes: ["graph:read", "admin:*", "*"],
        auditEvent: "CAMPAIGN_GRAPH_VIEWED",
        defaultBody: { action_id: "campaign-graph-view", action: "graph_view" },
        guardrails: [
          "graph queries must preserve tenant isolation",
          "graph access must write an audit record",
        ],
      },
      {
        id: "campaign-soar-response",
        label: "Request campaign SOAR response",
        method: "POST",
        endpoint: "/v1/campaigns/{id}/actions",
        requiredScopes: ["playbook:execute"],
        acceptedScopes: ["playbook:execute", "admin:*", "*"],
        auditEvent: "CAMPAIGN_SOAR_RESPONSE_REQUESTED",
        defaultBody: {
          action_id: "campaign-soar-response",
          action: "soar_response",
          dry_run: true,
        },
        guardrails: [
          "SOAR responses must default to dry_run=true",
          "high-impact execution requires confirmation and an audit record",
        ],
      },
    ],
  },
  "campaign-detail": { primary: "/v1/campaigns/{id}" },
  "attack-chains": { primary: "/v1/attack-chains" },
  "encrypted-traffic": {
    primary: "/v1/encrypted-traffic/stats",
    secondary: [
      "/v1/encrypted-traffic/sessions",
      "/v1/encrypted-traffic/ja3",
      "/v1/encrypted-traffic/tunnels",
      "/v1/encrypted-traffic/exfiltration",
      "/v1/encrypted-traffic/evidence",
    ],
    actions: [
      {
        id: "egress-create-alert",
        label: "Create encrypted egress alert request",
        method: "POST",
        endpoint: "/v1/encrypted-traffic/egress-actions",
        requiredScopes: ["alert:write"],
        acceptedScopes: ["alert:write", "alert:*", "admin:*", "*"],
        auditEvent: "ENCRYPTED_EGRESS_ALERT_REQUESTED",
        defaultBody: { action: "create_alert" },
        guardrails: [
          "target and action are required",
          "the request must persist an audit_logs row before reporting success",
          "a request is not presented as a confirmed alert until the rule service evaluates it",
        ],
      },
      {
        id: "egress-evidence-lookup",
        label: "Audit encrypted egress evidence lookup",
        method: "POST",
        endpoint: "/v1/encrypted-traffic/egress-actions",
        requiredScopes: ["alert:write"],
        acceptedScopes: ["alert:write", "alert:*", "admin:*", "*"],
        auditEvent: "ENCRYPTED_EGRESS_EVIDENCE_LOOKUP",
        defaultBody: { action: "lookup_evidence" },
        guardrails: [
          "target and action are required",
          "the lookup audit must persist before the UI opens the evidence route",
        ],
      },
      {
        id: "egress-entity-graph",
        label: "Audit encrypted egress graph drilldown",
        method: "POST",
        endpoint: "/v1/encrypted-traffic/egress-actions",
        requiredScopes: ["alert:write"],
        acceptedScopes: ["alert:write", "alert:*", "admin:*", "*"],
        auditEvent: "ENCRYPTED_EGRESS_GRAPH_DRILLDOWN",
        defaultBody: { action: "entity_graph" },
        guardrails: [
          "target and action are required",
          "the drilldown audit must persist before the UI opens the graph route",
        ],
      },
      {
        id: "egress-audit-write",
        label: "Write encrypted egress analysis audit",
        method: "POST",
        endpoint: "/v1/encrypted-traffic/egress-actions",
        requiredScopes: ["alert:write"],
        acceptedScopes: ["alert:write", "alert:*", "admin:*", "*"],
        auditEvent: "ENCRYPTED_EGRESS_AUDIT_WRITTEN",
        defaultBody: { action: "write_audit" },
        guardrails: [
          "target and action are required",
          "the API must return failure when audit persistence fails",
        ],
      },
      {
        id: "egress-response-request",
        label: "Submit encrypted egress response request",
        method: "POST",
        endpoint: "/v1/encrypted-traffic/egress-actions",
        requiredScopes: ["alert:write"],
        acceptedScopes: ["alert:write", "alert:*", "admin:*", "*"],
        auditEvent: "ENCRYPTED_EGRESS_RESPONSE_REQUESTED",
        defaultBody: { action: "response_request" },
        guardrails: [
          "target and action are required",
          "response requests must persist an audit_logs row before reporting success",
        ],
      },
      {
        id: "evidence-create-task",
        label: "Create encrypted evidence task request",
        method: "POST",
        endpoint: "/v1/encrypted-traffic/evidence-actions",
        requiredScopes: ["alert:write"],
        acceptedScopes: ["alert:write", "alert:*", "admin:*", "*"],
        auditEvent: "ENCRYPTED_EVIDENCE_TASK_REQUESTED",
        defaultBody: { action: "create_task" },
        guardrails: [
          "target and action are required",
          "the request must persist an audit_logs row before reporting success",
          "the UI must label the result as an evidence-task request rather than a completed collection job",
        ],
      },
      {
        id: "evidence-download-pcap",
        label: "Request encrypted evidence PCAP download",
        method: "POST",
        endpoint: "/v1/encrypted-traffic/evidence-actions",
        requiredScopes: ["alert:write"],
        acceptedScopes: ["alert:write", "alert:*", "admin:*", "*"],
        auditEvent: "ENCRYPTED_EVIDENCE_PCAP_DOWNLOAD_REQUESTED",
        defaultBody: { action: "download_pcap" },
        guardrails: [
          "target and action are required",
          "the request must persist an audit_logs row before reporting success",
        ],
      },
      {
        id: "evidence-verify-hash",
        label: "Request encrypted evidence hash verification",
        method: "POST",
        endpoint: "/v1/encrypted-traffic/evidence-actions",
        requiredScopes: ["alert:write"],
        acceptedScopes: ["alert:write", "alert:*", "admin:*", "*"],
        auditEvent: "ENCRYPTED_EVIDENCE_HASH_VERIFICATION_REQUESTED",
        defaultBody: { action: "verify_hash" },
        guardrails: [
          "target and action are required",
          "the request must persist an audit_logs row before reporting success",
        ],
      },
      {
        id: "evidence-export-package",
        label: "Request encrypted evidence package export",
        method: "POST",
        endpoint: "/v1/encrypted-traffic/evidence-actions",
        requiredScopes: ["alert:write"],
        acceptedScopes: ["alert:write", "alert:*", "admin:*", "*"],
        auditEvent: "ENCRYPTED_EVIDENCE_EXPORT_REQUESTED",
        defaultBody: { action: "export_package" },
        guardrails: [
          "target and action are required",
          "the request must persist an audit_logs row before reporting success",
        ],
      },
      {
        id: "evidence-associate-analysis",
        label: "Request encrypted evidence correlation analysis",
        method: "POST",
        endpoint: "/v1/encrypted-traffic/evidence-actions",
        requiredScopes: ["alert:write"],
        acceptedScopes: ["alert:write", "alert:*", "admin:*", "*"],
        auditEvent: "ENCRYPTED_EVIDENCE_ANALYSIS_REQUESTED",
        defaultBody: { action: "associate_analysis" },
        guardrails: [
          "target and action are required",
          "the request must persist an audit_logs row before reporting success",
        ],
      },
      {
        id: "evidence-preserve",
        label: "Request encrypted evidence preservation",
        method: "POST",
        endpoint: "/v1/encrypted-traffic/evidence-actions",
        requiredScopes: ["alert:write"],
        acceptedScopes: ["alert:write", "alert:*", "admin:*", "*"],
        auditEvent: "ENCRYPTED_EVIDENCE_PRESERVATION_REQUESTED",
        defaultBody: { action: "preserve_evidence" },
        guardrails: [
          "target and action are required",
          "the request must persist an audit_logs row before reporting success",
        ],
      },
      {
        id: "evidence-link-alert",
        label: "Link encrypted evidence to alerts",
        method: "POST",
        endpoint: "/v1/encrypted-traffic/evidence-actions",
        requiredScopes: ["alert:write"],
        acceptedScopes: ["alert:write", "alert:*", "admin:*", "*"],
        auditEvent: "ENCRYPTED_EVIDENCE_ALERT_LINK_REQUESTED",
        defaultBody: { action: "link_alert" },
        guardrails: [
          "target and action are required",
          "the request must persist an audit_logs row before reporting success",
        ],
      },
      {
        id: "evidence-expert-review",
        label: "Request encrypted evidence expert review",
        method: "POST",
        endpoint: "/v1/encrypted-traffic/evidence-actions",
        requiredScopes: ["alert:write"],
        acceptedScopes: ["alert:write", "alert:*", "admin:*", "*"],
        auditEvent: "ENCRYPTED_EVIDENCE_EXPERT_REVIEW_REQUESTED",
        defaultBody: { action: "expert_review" },
        guardrails: [
          "target and action are required",
          "the request must persist an audit_logs row before reporting success",
        ],
      },
      {
        id: "evidence-gap-mark",
        label: "Mark encrypted evidence gap",
        method: "POST",
        endpoint: "/v1/encrypted-traffic/evidence-actions",
        requiredScopes: ["alert:write"],
        acceptedScopes: ["alert:write", "alert:*", "admin:*", "*"],
        auditEvent: "ENCRYPTED_EVIDENCE_GAP_MARKED",
        defaultBody: { action: "mark_gap" },
        guardrails: [
          "target and action are required",
          "the request must persist an audit_logs row before reporting success",
        ],
      },
      {
        id: "evidence-submit-recommendation",
        label: "Submit encrypted evidence recommendation",
        method: "POST",
        endpoint: "/v1/encrypted-traffic/evidence-actions",
        requiredScopes: ["alert:write"],
        acceptedScopes: ["alert:write", "alert:*", "admin:*", "*"],
        auditEvent: "ENCRYPTED_EVIDENCE_RECOMMENDATION_SUBMITTED",
        defaultBody: { action: "submit_recommendation" },
        guardrails: [
          "target and action are required",
          "the request must persist an audit_logs row before reporting success",
        ],
      },
      {
        id: "evidence-export-report",
        label: "Request encrypted evidence report export",
        method: "POST",
        endpoint: "/v1/encrypted-traffic/evidence-actions",
        requiredScopes: ["alert:write"],
        acceptedScopes: ["alert:write", "alert:*", "admin:*", "*"],
        auditEvent: "ENCRYPTED_EVIDENCE_REPORT_EXPORT_REQUESTED",
        defaultBody: { action: "export_report" },
        guardrails: [
          "target and action are required",
          "the request must persist an audit_logs row before reporting success",
        ],
      },
      {
        id: "evidence-write-audit",
        label: "Write encrypted evidence review audit",
        method: "POST",
        endpoint: "/v1/encrypted-traffic/evidence-actions",
        requiredScopes: ["alert:write"],
        acceptedScopes: ["alert:write", "alert:*", "admin:*", "*"],
        auditEvent: "ENCRYPTED_EVIDENCE_AUDIT_WRITTEN",
        defaultBody: { action: "write_audit" },
        guardrails: [
          "target and action are required",
          "the API must return failure when audit persistence fails",
        ],
      },
    ],
  },
  forensics: {
    primary: "/v1/pcap/jobs",
    secondary: [
      "/v1/pcap/stats",
      "/v1/encrypted-traffic/sessions",
      "/v1/encrypted-traffic/evidence",
      "/v1/audit/logs",
    ],
    actions: [
      {
        id: "forensics-create-job",
        label: "Create PCAP forensics job",
        method: "POST",
        endpoint: "/v1/pcap/jobs",
        requiredScopes: ["pcap:write"],
        acceptedScopes: ["pcap:write", "pcap:*", "admin:*", "*"],
        auditEvent: "PCAP_CUT",
        guardrails: [
          "start_time and end_time are required",
          "time range must not exceed 24 hours",
        ],
      },
      {
        id: "forensics-verify-pcap",
        label: "Verify PCAP SHA-256",
        method: "POST",
        endpoint: "/v1/pcap/verify",
        requiredScopes: ["pcap:read"],
        acceptedScopes: ["pcap:read", "pcap:*", "admin:*", "*"],
        auditEvent: "PCAP_INTEGRITY_VERIFY",
        guardrails: [
          "key is required",
          "cross-tenant object access must return 403",
        ],
      },
      {
        id: "forensics-presign-pcap",
        label: "Generate PCAP signed URL",
        method: "POST",
        endpoint: "/v1/pcap/presign",
        requiredScopes: ["pcap:download"],
        acceptedScopes: ["pcap:download", "pcap:*", "admin:*", "*"],
        auditEvent: "PCAP_DOWNLOAD",
        guardrails: ["key is required", "expiry_seconds must not exceed 86400"],
      },
      {
        id: "forensics-cancel-job",
        label: "Cancel PCAP forensics job",
        method: "POST",
        endpoint: "/v1/pcap/jobs/{id}/cancel",
        requiredScopes: ["pcap:write"],
        acceptedScopes: ["pcap:write", "pcap:*", "admin:*", "*"],
        auditEvent: "PCAP_CANCEL",
        guardrails: [
          "only queued or processing jobs can be cancelled",
          "cross-tenant cancel requests must return 403",
          "successful cancels must be persisted in tasks and audit_logs",
        ],
      },
    ],
  },
  assets: {
    primary: "/v1/assets",
    secondary: [
      "/v1/assets/stats",
      "/v1/assets/discovery/runs",
      "/v1/assets/discovery/neighbors",
    ],
    actions: [
      {
        id: "asset-discovery-credential-register",
        label: "Register SNMP/LLDP credential reference",
        method: "POST",
        endpoint: "/v1/assets/discovery/credentials",
        requiredScopes: ["asset:discover"],
        acceptedScopes: ["asset:discover", "asset:*", "admin:*", "*"],
        auditEvent: "ASSET_DISCOVERY_CREDENTIAL_REGISTER",
        defaultBody: {
          protocol: "snmp_lldp",
          secret_ref:
            "k8s://traffic-analysis/traffic-credentials#ASSET_DISCOVERY_SNMP",
        },
        guardrails: [
          "plaintext SNMP community or credentials must not be sent to the API",
          "secret_ref must point to a Kubernetes Secret or ExternalSecret-backed value",
        ],
      },
      {
        id: "asset-active-discovery-run",
        label: "Run SNMP/LLDP active discovery",
        method: "POST",
        endpoint: "/v1/assets/discovery/runs",
        requiredScopes: ["asset:discover"],
        acceptedScopes: ["asset:discover", "asset:*", "admin:*", "*"],
        auditEvent: "ASSET_ACTIVE_DISCOVERY_RUN",
        defaultBody: {
          mode: "snmp_lldp",
          observations: [],
        },
        guardrails: [
          "active discovery must write asset_discovery_runs and asset_topology_links",
          "observed SNMP/LLDP assets must upsert /v1/assets inventory records",
          "tenant_id must come from the authenticated request or tenant-scoped body",
        ],
      },
    ],
  },
  graph: { primary: "/v1/graph/explore" },
  fusion: {
    primary: "/v1/fusion/workbench",
    secondary: [
      "/v1/fusion/stats",
      "/v1/fusion/entities",
      "/v1/threat-intel/entries",
      "/v1/fusion/value-report",
    ],
    actions: [
      {
        id: "fusion-conflict-resolve",
        label: "Fusion conflict resolve",
        method: "POST",
        endpoint: "/v1/fusion/conflicts/{id}/resolve",
        requiredScopes: ["rule:write"],
        acceptedScopes: ["rule:write", "rule:*", "admin:*", "*"],
        auditEvent: "FUSION_CONFLICT_RESOLVED",
        defaultBody: { strategy: "authoritative-source" },
        guardrails: [
          "field_name, selected_source and selected_value are required",
          "tenant_id is taken from the authenticated token for write operations",
          "resolution must be written to fusion_conflict_resolutions and audit_logs",
        ],
      },
      {
        id: "fusion-rule-update",
        label: "Fusion rule update",
        method: "PATCH",
        endpoint: "/v1/fusion/rules/{id}",
        requiredScopes: ["rule:write"],
        acceptedScopes: ["rule:write", "rule:*", "admin:*", "*"],
        auditEvent: "FUSION_RULE_UPDATED",
        defaultBody: { status: "draft", confidence_threshold: 0.85 },
        guardrails: [
          "confidence_threshold is clamped to 0..1",
          "rule edits must increment fusion_rule_overrides.version",
          "rule edits must be queryable through audit_logs",
        ],
      },
      {
        id: "fusion-evidence-export",
        label: "Fusion evidence export",
        method: "POST",
        endpoint: "/v1/fusion/evidence-packages",
        requiredScopes: ["rule:write"],
        acceptedScopes: ["rule:write", "rule:*", "admin:*", "*"],
        auditEvent: "FUSION_EVIDENCE_EXPORTED",
        guardrails: [
          "conflict_id is required and tenant scoped",
          "evidence payload must be generated from the persisted conflict state",
          "the sha256, filename and export action must be written to audit_logs",
        ],
      },
    ],
  },
  baselines: {
    primary: "/v1/baselines",
    secondary: ["/v1/baselines/{id}", "/v1/baselines/{id}/analytics", "/v1/baselines/{id}/versions", "/v1/baselines/{id}/actions"],
    pageLoadSecondary: ["/v1/baselines/{id}/analytics", "/v1/baselines/{id}/versions", "/v1/baselines/{id}/actions"],
    actions: [
      {
        id: "baseline-governance-action",
        label: "Queue audited baseline governance action",
        method: "POST",
        endpoint: "/v1/baselines/{id}/actions",
        requiredScopes: ["alert:write"],
        acceptedScopes: ["alert:write", "alert:*", "admin:*", "*"],
        auditEvent: "BEHAVIOR_BASELINE_ACTION",
        guardrails: [
          "the baseline must exist in the authenticated tenant",
          "governance reason is required and rollback targets must have a persisted snapshot",
          "queued actions must persist behavior_baseline_actions, behavior_baseline_outbox and audit_logs in one transaction",
          "queued is not a completed downstream result",
        ],
      },
      {
        id: "baseline-reset",
        label: "Reset behavior baseline",
        method: "POST",
        endpoint: "/v1/baselines/{id}/reset",
        requiredScopes: ["alert:write"],
        acceptedScopes: ["alert:write", "alert:*", "admin:*", "*"],
        auditEvent: "BEHAVIOR_BASELINE_RESET",
        guardrails: [
          "baseline reset requires alert:write or admin scope",
          "tenant_id must come from the authenticated token for write operations",
          "successful resets must persist behavior_baseline_resets and audit_logs rows",
        ],
      },
    ],
  },
  rules: {
    primary: "/v1/rules",
    secondary: [
      "/v1/rules/{id}",
      "/v1/rules/{id}/versions",
      "/v1/rules/{id}/workbench",
    ],
    actions: [
      {
        id: "rule-workbench-action",
        label: "Queue rule workbench action",
        method: "POST",
        endpoint: "/v1/rules/{id}/actions",
        requiredScopes: ["rule:write"],
        acceptedScopes: ["rule:write", "rule:*", "admin:*", "*"],
        auditEvent: "RULE_WORKBENCH_ACTION",
        guardrails: [
          "the selected rule must belong to the authenticated tenant",
          "the action job and audit_logs row must commit in one transaction",
          "the response must return a durable job_id instead of a client-only success",
        ],
      },
      {
        id: "rule-enable",
        label: "Enable rule",
        method: "POST",
        endpoint: "/v1/rules/{id}/enable",
        requiredScopes: ["rule:enable"],
        acceptedScopes: ["rule:enable", "rule:write", "rule:*", "admin:*", "*"],
        auditEvent: "RULE_ENABLE",
        guardrails: [
          "cross-tenant enable requests must return 403",
          "enabling must persist enabled=true, status=active and increment rule version",
          "successful enables must write rule_outbox and audit_logs",
        ],
      },
      {
        id: "rule-disable",
        label: "Disable rule",
        method: "POST",
        endpoint: "/v1/rules/{id}/disable",
        requiredScopes: ["rule:enable"],
        acceptedScopes: ["rule:enable", "rule:write", "rule:*", "admin:*", "*"],
        auditEvent: "RULE_DISABLE",
        guardrails: [
          "cross-tenant disable requests must return 403",
          "disabling must persist enabled=false, status=disabled and increment rule version",
          "successful disables must write rule_outbox and audit_logs",
        ],
      },
    ],
  },
  deployments: {
    primary: "/v1/deployments",
    actions: [
      {
        id: "deployment-start-gray",
        label: "Start gray deployment",
        method: "POST",
        endpoint: "/v1/deployments/{id}/gray",
        requiredScopes: ["deploy:gray"],
        acceptedScopes: ["deploy:gray", "deploy:*", "admin:*", "*"],
        auditEvent: "DEPLOY_GRAY",
        guardrails: [
          "only planned deployments can enter gray state",
          "only one gray deployment can be active per tenant",
          "successful gray starts must persist deployment_history and audit_logs",
        ],
      },
      {
        id: "deployment-activate",
        label: "Activate deployment",
        method: "POST",
        endpoint: "/v1/deployments/{id}/activate",
        requiredScopes: ["deploy:activate"],
        acceptedScopes: ["deploy:activate", "deploy:*", "admin:*", "*"],
        auditEvent: "DEPLOY_ACTIVATE",
        guardrails: [
          "only planned or gray deployments can become active",
          "activation must supersede any previous active deployment for the same tenant",
          "successful activations must persist deployment_history and audit_logs",
        ],
      },
      {
        id: "deployment-pause",
        label: "Pause deployment",
        method: "POST",
        endpoint: "/v1/deployments/{id}/pause",
        requiredScopes: ["deploy:activate"],
        acceptedScopes: ["deploy:activate", "deploy:*", "admin:*", "*"],
        auditEvent: "DEPLOY_PAUSE",
        guardrails: [
          "only gray or active deployments can be paused",
          "pause requests must preserve tenant isolation",
          "successful pauses must persist deployment_history and audit_logs",
        ],
      },
      {
        id: "deployment-resume",
        label: "Resume deployment",
        method: "POST",
        endpoint: "/v1/deployments/{id}/resume",
        requiredScopes: ["deploy:activate"],
        acceptedScopes: ["deploy:activate", "deploy:*", "admin:*", "*"],
        auditEvent: "DEPLOY_RESUME",
        guardrails: [
          "only paused deployments can be resumed",
          "resume requests must preserve tenant isolation",
          "successful resumes must persist deployment_history and audit_logs",
        ],
      },
      {
        id: "deployment-rollback",
        label: "Rollback deployment",
        method: "POST",
        endpoint: "/v1/deployments/{id}/rollback",
        requiredScopes: ["deploy:rollback"],
        acceptedScopes: ["deploy:rollback", "deploy:*", "admin:*", "*"],
        auditEvent: "DEPLOY_ROLLBACK",
        guardrails: [
          "only gray, active, paused or failed deployments can be rolled back",
          "cross-tenant rollback requests must return 403",
          "successful rollbacks must persist deployment_history and audit_logs",
        ],
      },
    ],
  },
  models: {
    primary: "/v1/models",
    actions: [
      {
        id: "model-version-register",
        label: "Register model version",
        method: "POST",
        endpoint: "/v1/models/{id}/versions",
        requiredScopes: ["model:create"],
        acceptedScopes: ["model:create", "model:*", "admin:*", "*"],
        auditEvent: "MODEL_VERSION_CREATE",
        defaultBody: {
          version: "v-next",
          artifact_uri: "s3://traffic-models/{tenant}/{model}/model.bin",
          feature_set_id: "feature-set-id",
          model_type: "xgboost",
          metrics: { f1_score: 0.9 },
        },
        guardrails: [
          "model_id and tenant_id are taken from the path and authenticated context",
          "registered versions must start in registered state",
          "successful registration must persist model_versions and audit_logs",
        ],
      },
      {
        id: "model-version-activate",
        label: "Activate model version",
        method: "POST",
        endpoint: "/v1/models/{id}/versions/{version}/activate",
        requiredScopes: ["model:activate"],
        acceptedScopes: ["model:activate", "model:*", "admin:*", "*"],
        auditEvent: "MODEL_VERSION_ACTIVATE",
        guardrails: [
          "only registered or validating versions can become active",
          "all persisted review gates must be approved before activation",
          "the model registry requires gray_percent=100; staged traffic belongs to the deployment workflow",
          "activation must deprecate any previous active version for the same model",
          "successful activations must persist model_versions and audit_logs",
        ],
      },
      {
        id: "model-version-deprecate",
        label: "Deprecate model version",
        method: "POST",
        endpoint: "/v1/models/{id}/versions/{version}/deprecate",
        requiredScopes: ["model:activate"],
        acceptedScopes: ["model:activate", "model:*", "admin:*", "*"],
        auditEvent: "MODEL_VERSION_DEPRECATE",
        guardrails: [
          "only active or validating versions can be deprecated",
          "registered versions must return 409 until they enter an allowed state",
          "successful deprecations must persist model_versions and audit_logs",
        ],
      },
      {
        id: "model-feedback-append",
        label: "Append model feedback samples",
        method: "POST",
        endpoint: "/v1/models/{id}/feedback-samples",
        requiredScopes: ["model:write"],
        acceptedScopes: ["model:write", "model:*", "admin:*", "*"],
        auditEvent: "MODEL_FEEDBACK_INGEST_REQUESTED",
        defaultBody: {
          dataset_id: "feedback-latest",
          sample_count: 5231,
          source: "analyst_feedback",
        },
        guardrails: [
          "inline sample payloads are forbidden",
          "the tenant-scoped dataset reference and masked samples are validated by the ingestion consumer before append",
        ],
      },
      {
        id: "model-retrain-request",
        label: "Request model retraining",
        method: "POST",
        endpoint: "/v1/models/{id}/retrain",
        requiredScopes: ["model:write"],
        acceptedScopes: ["model:write", "model:*", "admin:*", "*"],
        auditEvent: "MODEL_RETRAIN_REQUESTED",
        defaultBody: {
          dataset_id: "ds_ueba_latest",
          strategy: "incremental",
          reason: "feedback_and_drift",
        },
        guardrails: [
          "dataset quality gates are evaluated by the training consumer",
          "duplicate queued or running retrain jobs return 409",
        ],
      },
      {
        id: "model-evaluation-request",
        label: "Evaluate model version",
        method: "POST",
        endpoint: "/v1/models/{id}/versions/{version}/evaluate",
        requiredScopes: ["model:write"],
        acceptedScopes: ["model:write", "model:*", "admin:*", "*"],
        auditEvent: "MODEL_EVALUATION_REQUESTED",
        defaultBody: {
          dataset_id: "validation-latest",
          include_explanations: true,
        },
        guardrails: [
          "the evaluation consumer resolves the dataset to an immutable checksum",
          "dispatch preserves tenant, model, version, dataset and job lineage",
        ],
      },
      {
        id: "model-version-rollback",
        label: "Rollback model version",
        method: "POST",
        endpoint: "/v1/models/{id}/versions/{version}/rollback",
        requiredScopes: ["model:activate"],
        acceptedScopes: ["model:activate", "model:*", "admin:*", "*"],
        auditEvent: "MODEL_VERSION_ROLLBACK_REQUESTED",
        defaultBody: {
          target_version: "previous-active",
          reason: "operator_request",
        },
        guardrails: [
          "target version must be deprecated and all review gates approved",
          "rollback audit preserves the displaced active version and waits for model-update broker acknowledgement",
        ],
      },
      {
        id: "model-context-action",
        label: "Execute model context action",
        method: "POST",
        endpoint: "/v1/models/{id}/actions",
        requiredScopes: ["model:write"],
        acceptedScopes: ["model:write", "model:*", "admin:*", "*"],
        auditEvent: "MODEL_CONTEXT_ACTION_REQUESTED",
        defaultBody: { action: "inspect", target: "selected-model" },
        guardrails: [
          "action and target are required",
          "mutating actions must require explicit confirmation",
        ],
      },
    ],
  },
  mlops: {
    primary: "/v1/mlops/status",
    secondary: ["/v1/mlops/conditions"],
    actions: [
      {
        id: "mlops-pipeline-create",
        label: "Create MLOps pipeline",
        method: "POST",
        endpoint: "/v1/mlops/retrain",
        requiredScopes: ["model:write"],
        acceptedScopes: ["model:write", "model:*", "admin:*", "*"],
        auditEvent: "MLOPS_RETRAIN_SUBMITTED",
        defaultBody: {
          model_type: "xgboost",
          lookback_days: 7,
          feature_set_id: "v1",
        },
        guardrails: [
          "the server submits the versioned Argo WorkflowTemplate",
          "tenant context must come from the authenticated token",
        ],
      },
      {
        id: "mlops-training-submit",
        label: "Submit training task",
        method: "POST",
        endpoint: "/v1/mlops/retrain",
        requiredScopes: ["model:write"],
        acceptedScopes: ["model:write", "model:*", "admin:*", "*"],
        auditEvent: "MLOPS_RETRAIN_SUBMITTED",
        defaultBody: {
          model_type: "xgboost",
          lookback_days: 7,
          feature_set_id: "v1",
        },
        guardrails: [
          "the response must include a real Argo workflow name",
          "tenant and model are server-authoritative",
        ],
      },
      {
        id: "mlops-task-retry",
        label: "Retry MLOps task",
        method: "POST",
        endpoint: "/v1/mlops/workflows/{id}/retry",
        requiredScopes: ["model:write"],
        acceptedScopes: ["model:write", "model:*", "admin:*", "*"],
        auditEvent: "MLOPS_WORKFLOW_RESUBMITTED",
        defaultBody: {},
        guardrails: [
          "only failed tasks can retry in production",
          "retry must preserve the original trace id",
        ],
      },
      {
        id: "mlops-task-stop",
        label: "Stop MLOps task",
        method: "POST",
        endpoint: "/v1/mlops/workflows/{id}/stop",
        requiredScopes: ["model:write"],
        acceptedScopes: ["model:write", "model:*", "admin:*", "*"],
        auditEvent: "MLOPS_WORKFLOW_STOP_REQUESTED",
        defaultBody: {},
        guardrails: [
          "stop requires explicit confirmation",
          "artifacts and audit trace must be retained",
        ],
      },
      {
        id: "mlops-label-request",
        label: "Request sample labeling",
        method: "POST",
        endpoint: "/v1/mlops/label-jobs",
        requiredScopes: ["model:write"],
        acceptedScopes: ["model:write", "model:*", "admin:*", "*"],
        auditEvent: "MLOPS_LABELING_UNAVAILABLE",
        defaultBody: { sample_ids: [], priority: "normal" },
        guardrails: [
          "samples must be masked",
          "sample ownership must match tenant context",
        ],
      },
      {
        id: "mlops-model-register",
        label: "Register trained model",
        method: "POST",
        endpoint: "/v1/models/{id}/versions",
        requiredScopes: ["model:create"],
        acceptedScopes: ["model:create", "model:*", "admin:*", "*"],
        auditEvent: "MODEL_VERSION_REGISTRATION_UNAVAILABLE",
        defaultBody: {
          version: "v-next",
          source: "mlops-pipeline",
          metrics: { f1_score: 0.9 },
        },
        guardrails: [
          "model package signature must pass",
          "registration must preserve training lineage",
        ],
      },
      {
        id: "mlops-task-inspect",
        label: "Inspect MLOps task",
        method: "GET",
        endpoint: "/v1/mlops/workflows/{id}",
        requiredScopes: ["model:read"],
        acceptedScopes: ["model:read", "model:*", "admin:*", "*"],
        auditEvent: "READ_ONLY",
        guardrails: [
          "task detail must preserve tenant isolation",
          "task lineage and data mode must be visible",
        ],
      },
      {
        id: "mlops-context-action",
        label: "Execute MLOps context action",
        method: "GET",
        endpoint: "/v1/mlops/workflows/{id}",
        requiredScopes: ["model:read"],
        acceptedScopes: ["model:read", "model:*", "admin:*", "*"],
        auditEvent: "READ_ONLY",
        defaultBody: { action: "inspect" },
        guardrails: [
          "action and task id are required",
          "mutating actions require explicit confirmation",
        ],
      },
      {
        id: "mlops-feedback-inspect",
        label: "Inspect feedback sample",
        method: "GET",
        endpoint: "/v1/mlops/feedback/{id}",
        requiredScopes: ["model:read"],
        acceptedScopes: ["model:read", "model:*", "admin:*", "*"],
        auditEvent: "READ_ONLY",
        guardrails: [
          "feedback sample access must preserve tenant isolation",
          "sensitive fields must remain masked",
        ],
      },
      {
        id: "mlops-model-version-inspect",
        label: "Inspect registered model version",
        method: "GET",
        endpoint: "/v1/models/{id}/versions/{version}",
        requiredScopes: ["model:read"],
        acceptedScopes: ["model:read", "model:*", "admin:*", "*"],
        auditEvent: "READ_ONLY",
        guardrails: [
          "model and version lineage must be preserved",
          "cross-tenant reads must return 404",
        ],
      },
    ],
  },
  playbooks: {
    primary: "/v1/playbooks/catalog",
    secondary: ["/v1/playbooks/executions"],
    actions: [
      {
        id: "playbook-execute",
        label: "Execute SOAR playbook",
        method: "POST",
        endpoint: "/v1/playbooks/{name}/execute",
        requiredScopes: ["alert:write"],
        acceptedScopes: ["alert:write", "alert:*", "admin:*", "*"],
        auditEvent: "PLAYBOOK_EXECUTED",
        defaultBody: {
          alert_type: "scan",
          severity: "critical",
          score: 0.96,
          related_alert_count: 9,
          asset_risk: "high",
        },
        guardrails: [
          "manual execution must respect enabled and max_runs state",
          "execution must be persisted in alert_playbook_executions",
          "tenant_id is taken from the authenticated token or X-Tenant-ID",
        ],
      },
      {
        id: "playbook-state-update",
        label: "Update SOAR playbook state",
        method: "PATCH",
        endpoint: "/v1/playbooks/{name}",
        requiredScopes: ["alert:write"],
        acceptedScopes: ["alert:write", "alert:*", "admin:*", "*"],
        auditEvent: "PLAYBOOK_STATE_UPDATED",
        defaultBody: { enabled: true, max_runs: 10, cooldown_seconds: 3600 },
        guardrails: [
          "max_runs and cooldown_seconds must be non-negative",
          "disabled playbooks must reject execute requests",
          "state updates must be persisted in alert_playbook_overrides",
        ],
      },
    ],
  },
  whitelist: {
    primary: "/v1/whitelist",
    secondary: ["/v1/whitelist/check"],
    pageLoadSecondary: [],
    actions: [
      {
        id: "whitelist-create",
        label: "Create whitelist entry",
        method: "POST",
        endpoint: "/v1/whitelist",
        requiredScopes: ["alert:write"],
        acceptedScopes: ["alert:write", "admin:*", "*"],
        auditEvent: "WHITELIST_CREATED",
        defaultBody: {
          type: "domain",
          value: "known-business.example",
          reason: "false_positive",
          status: "draft",
          approval_status: "draft",
        },
        guardrails: [
          "tenant_id must come from the authenticated token",
          "type and value are required",
          "successful creates must write WHITELIST_CREATED audit_logs rows",
        ],
      },
      {
        id: "whitelist-submit-approval",
        label: "Submit whitelist approval",
        method: "PATCH",
        endpoint: "/v1/whitelist/{id}",
        requiredScopes: ["alert:write"],
        acceptedScopes: ["alert:write", "admin:*", "*"],
        auditEvent: "WHITELIST_APPROVAL_SUBMITTED",
        defaultBody: { approval_status: "pending", status: "pending" },
        guardrails: [
          "approval submission must preserve tenant isolation",
          "cross-tenant updates must return 404",
          "successful submissions must write WHITELIST_APPROVAL_SUBMITTED audit_logs rows",
        ],
      },
      {
        id: "whitelist-extend",
        label: "Extend whitelist expiry",
        method: "PATCH",
        endpoint: "/v1/whitelist/{id}",
        requiredScopes: ["alert:write"],
        acceptedScopes: ["alert:write", "admin:*", "*"],
        auditEvent: "WHITELIST_EXTENDED",
        defaultBody: { expires_at: "2030-01-01T00:00:00Z" },
        guardrails: [
          "expires_at must be a future timestamp for active entries",
          "extension must persist to the whitelist row",
          "successful extensions must write WHITELIST_EXTENDED audit_logs rows",
        ],
      },
      {
        id: "whitelist-disable",
        label: "Disable whitelist entry",
        method: "PATCH",
        endpoint: "/v1/whitelist/{id}",
        requiredScopes: ["alert:write"],
        acceptedScopes: ["alert:write", "admin:*", "*"],
        auditEvent: "WHITELIST_DISABLED",
        defaultBody: { status: "disabled" },
        guardrails: [
          "disabled entries must stop matching /v1/whitelist/check",
          "viewer writes must return 403 before persistence",
          "successful disables must write WHITELIST_DISABLED audit_logs rows",
        ],
      },
    ],
  },
  compliance: {
    primary: "/v1/compliance/reports",
    secondary: ["/v1/compliance/audit-trail"],
    actions: [
      {
        id: "compliance-report-generate",
        label: "Generate compliance report",
        method: "POST",
        endpoint: "/v1/compliance/reports/generate",
        requiredScopes: ["compliance:write"],
        acceptedScopes: ["compliance:write", "admin:*", "*"],
        auditEvent: "COMPLIANCE_REPORT_GENERATED",
        defaultBody: { report_type: "weekly" },
        guardrails: [
          "report generation requires compliance:write or an administrative wildcard",
          "generated reports must persist compliance_reports rows",
          "missing evidence and non-pass sections must never be represented as a completed pass",
          "successful generation must write COMPLIANCE_REPORT_GENERATED audit_logs rows",
        ],
      },
      {
        id: "compliance-evidence-package-export",
        label: "Export compliance evidence package",
        method: "POST",
        endpoint: "/v1/compliance/reports/{id}/evidence-package",
        requiredScopes: ["compliance:export"],
        acceptedScopes: ["compliance:export", "admin:*", "*"],
        auditEvent: "COMPLIANCE_EVIDENCE_EXPORTED",
        guardrails: [
          "the package must be generated on the server from a tenant-scoped persisted report",
          "manifest and report payload must be bundled with a SHA-256 checksum",
          "the download must fail closed when its audit row cannot be committed",
        ],
      },
      {
        id: "compliance-report-export",
        label: "Export compliance runtime report",
        method: "POST",
        endpoint: "/v1/compliance/reports/{id}/export",
        requiredScopes: ["compliance:export"],
        acceptedScopes: ["compliance:export", "admin:*", "*"],
        auditEvent: "COMPLIANCE_REPORT_EXPORTED",
        defaultBody: { format: "pdf" },
        guardrails: [
          "PDF and DOCX artifacts must contain the persisted summary, all sections and report audit trail",
          "the artifact MIME type, file structure and SHA-256 must match the returned payload",
          "invalidated legacy reports must return 404 and cannot be exported",
        ],
      },
      {
        id: "compliance-remediations-create",
        label: "Create compliance remediation tasks",
        method: "POST",
        endpoint: "/v1/compliance/reports/{id}/remediations",
        requiredScopes: ["compliance:remediate"],
        acceptedScopes: ["compliance:remediate", "admin:*", "*"],
        auditEvent: "COMPLIANCE_REMEDIATIONS_CREATED",
        guardrails: [
          "one persistent task exists per tenant, report and non-pass section",
          "repeat requests reuse task IDs and report created versus reused counts",
          "invalidated legacy reports must not create remediation tasks",
        ],
      },
      {
        id: "compliance-report-finalize",
        label: "Finalize compliance report snapshot",
        method: "POST",
        endpoint: "/v1/compliance/reports/{id}/finalize",
        requiredScopes: ["compliance:finalize"],
        acceptedScopes: ["compliance:finalize", "admin:*", "*"],
        auditEvent: "COMPLIANCE_REPORT_FINALIZED",
        guardrails: [
          "the finalization hash must use the same canonical report serialization as the evidence manifest",
          "repeat finalization must return 409 and database rows are immutable",
          "invalidated legacy reports must not be finalized",
        ],
      },
    ],
  },
  "audit-log": {
    primary: "/v1/audit/logs",
    actions: [
      {
        id: "audit-query-save",
        label: "Save tenant audit query",
        method: "POST",
        endpoint: "/v1/audit/saved-queries",
        requiredScopes: ["audit:write"],
        acceptedScopes: ["audit:write", "audit:*", "admin:*", "*"],
        auditEvent: "AUDIT_SAVED_QUERY_CREATED",
        guardrails: ["query filters are tenant scoped", "the saved query and audit event are committed atomically"],
      },
      {
        id: "audit-export",
        label: "Export immutable audit evidence",
        method: "POST",
        endpoint: "/v1/audit/exports",
        requiredScopes: ["audit:export"],
        acceptedScopes: ["audit:export", "audit:*", "admin:*", "*"],
        auditEvent: "AUDIT_EVIDENCE_EXPORTED",
        guardrails: ["server renders the artifact from tenant-filtered rows", "exports above the synchronous limit fail rather than truncate", "response includes total matching rows, filename, MIME type, row count and SHA-256", "export metadata is persisted before success"],
      },
      {
        id: "audit-review-create",
        label: "Create a high-risk audit review",
        method: "POST",
        endpoint: "/v1/audit/reviews",
        requiredScopes: ["audit:write"],
        acceptedScopes: ["audit:write", "audit:*", "admin:*", "*"],
        auditEvent: "AUDIT_REVIEW_TRIGGERED",
        guardrails: ["the target audit event belongs to the active tenant", "review reason is required", "review and audit rows are committed atomically"],
      },
      {
        id: "audit-integrity-check",
        label: "Verify the tenant audit log digest",
        method: "POST",
        endpoint: "/v1/audit/integrity-checks",
        requiredScopes: ["audit:write"],
        acceptedScopes: ["audit:write", "audit:*", "admin:*", "*"],
        auditEvent: "AUDIT_INTEGRITY_CHECK_COMPLETED",
        guardrails: ["the digest covers canonical ordered event content", "a fixed-window manifest detects missing or added rows", "new baselines never report a fully passed verification", "the check result and root SHA-256 are persisted"],
      },
    ],
  },
  notifications: {
    primary: "/v1/notifications/workbench",
    secondary: [],
    actions: [
      {
        id: "notification-settings-update",
        label: "Update notification settings",
        method: "PUT",
        endpoint: "/v1/notifications/settings",
        requiredScopes: ["admin:*"],
        acceptedScopes: ["admin:*", "*"],
        auditEvent: "NOTIFICATION_SETTINGS_UPDATED",
        defaultBody: {
          enabled: true,
          min_severity: "high",
          channels: { email: true, webhook: false },
          secret_ref: "traffic-analysis/notification-secret",
        },
        guardrails: [
          "plaintext webhook tokens, passwords and API keys must be rejected",
          "channel credentials must be represented by secret_ref only",
          "successful updates must write NOTIFICATION_SETTINGS_UPDATED audit_logs rows",
        ],
      },
      {
        id: "notification-test-send",
        label: "Send notification test",
        method: "POST",
        endpoint: "/v1/notifications/test",
        requiredScopes: ["admin:*"],
        acceptedScopes: ["admin:*", "*"],
        auditEvent: "NOTIFICATION_TEST_SENT",
        guardrails: [
          "test sends require admin:*",
          "test sends must not expose channel secrets in responses",
          "successful test sends must write NOTIFICATION_TEST_SENT audit_logs rows",
        ],
      },
      {
        id: "notification-subscription-create",
        label: "Create notification subscription",
        method: "POST",
        endpoint: "/v1/notifications/subscriptions",
        requiredScopes: ["admin:*"],
        acceptedScopes: ["admin:*", "*"],
        auditEvent: "NOTIFICATION_RULE_CREATED",
        guardrails: ["name and at least one supported channel are required", "tenant_id is taken from authenticated context", "the rule and its audit event are persisted"],
      },
      {
        id: "notification-subscription-update",
        label: "Update notification subscription",
        method: "PATCH",
        endpoint: "/v1/notifications/subscriptions/{id}",
        requiredScopes: ["admin:*"],
        acceptedScopes: ["admin:*", "*"],
        auditEvent: "NOTIFICATION_RULE_UPDATED",
        guardrails: ["cross-tenant rule ids return 404", "empty patch fields do not erase stored fields", "updates write an audit event"],
      },
      {
        id: "notification-template-create",
        label: "Create notification template",
        method: "POST",
        endpoint: "/v1/notifications/templates",
        requiredScopes: ["admin:*"],
        acceptedScopes: ["admin:*", "*"],
        auditEvent: "NOTIFICATION_TEMPLATE_CREATED",
        guardrails: ["template type, name and body are required", "template variables are stored as a schema", "plaintext channel credentials are never accepted"],
      },
      {
        id: "notification-template-update",
        label: "Update notification template",
        method: "PATCH",
        endpoint: "/v1/notifications/templates/{id}",
        requiredScopes: ["admin:*"],
        acceptedScopes: ["admin:*", "*"],
        auditEvent: "NOTIFICATION_TEMPLATE_UPDATED",
        guardrails: ["each update increments the persisted version", "cross-tenant template ids return 404", "preview never executes a send"],
      },
      {
        id: "notification-template-test",
        label: "Test notification template",
        method: "POST",
        endpoint: "/v1/notifications/templates/{id}/test",
        requiredScopes: ["admin:*"],
        acceptedScopes: ["admin:*", "*"],
        auditEvent: "NOTIFICATION_TEMPLATE_TESTED",
        guardrails: ["the template must belong to the active tenant", "the test creates a delivery record and audit event", "the response contains no secrets"],
      },
      {
        id: "notification-escalation-create",
        label: "Create escalation policy",
        method: "POST",
        endpoint: "/v1/notifications/escalation-policies",
        requiredScopes: ["admin:*"],
        acceptedScopes: ["admin:*", "*"],
        auditEvent: "NOTIFICATION_ESCALATION_CREATED",
        guardrails: ["at least one stage is required", "every stage has a non-negative delay and target role", "the policy is tenant scoped"],
      },
      {
        id: "notification-delivery-retry",
        label: "Retry notification delivery",
        method: "POST",
        endpoint: "/v1/notifications/deliveries/{id}/retry",
        requiredScopes: ["admin:*"],
        acceptedScopes: ["admin:*", "*"],
        auditEvent: "NOTIFICATION_DELIVERY_RETRIED",
        guardrails: ["the delivery must belong to the active tenant", "retry count and trace id are persisted", "the retry action is audited"],
      },
      {
        id: "notification-silence-rule-create",
        label: "Create notification silence rule",
        method: "POST",
        endpoint: "/v1/notifications/silence-rules",
        requiredScopes: ["admin:*"],
        acceptedScopes: ["admin:*", "*"],
        auditEvent: "NOTIFICATION_SILENCE_RULE_CREATED",
        defaultBody: {
          name: "maintenance-window",
          scope: "main-campus",
          starts_at: "2026-06-30T22:00:00Z",
          ends_at: "2026-07-01T02:00:00Z",
          affected_targets: ["core-switch"],
          policy: "night-escalation",
          reason: "scheduled maintenance",
        },
        guardrails: [
          "ends_at must be after starts_at",
          "tenant_id is taken from the authenticated token",
          "successful creates must persist notification_silence_rules and audit_logs",
        ],
      },
      {
        id: "notification-silence-rule-toggle",
        label: "Toggle notification silence rule",
        method: "PATCH",
        endpoint: "/v1/notifications/silence-rules/{id}",
        requiredScopes: ["admin:*"],
        acceptedScopes: ["admin:*", "*"],
        auditEvent: "NOTIFICATION_SILENCE_RULE_UPDATED",
        defaultBody: { enabled: false },
        guardrails: [
          "cross-tenant silence rule updates must return 404",
          "enabled is required for toggle requests",
          "successful toggles must update notification_silence_rules and audit_logs",
        ],
      },
    ],
  },
  settings: {
    primary: "/v1/auth/system-settings",
    secondary: [
      "/v1/tokens/scopes",
      "/v1/tokens",
      "/v1/tokens/scopes/probe",
      "/v1/auth/settings/display",
    ],
    actions: [
      {
        id: "settings-system-save",
        label: "Save tenant system settings",
        method: "PUT",
        endpoint: "/v1/auth/system-settings",
        requiredScopes: ["admin:write"],
        acceptedScopes: ["admin:write", "admin:*", "*"],
        auditEvent: "system_settings_update",
        guardrails: [
          "tenant_id and updated_by must come from the authenticated token",
          "expected_revision must prevent lost updates",
          "integration credentials must remain secret_ref values",
        ],
      },
      {
        id: "settings-scope-review",
        label: "Review tenant scopes",
        method: "POST",
        endpoint: "/v1/auth/system-settings/actions/scope-review",
        requiredScopes: ["admin:write"],
        acceptedScopes: ["admin:write", "admin:*", "*"],
        auditEvent: "system_settings_scope_review",
        guardrails: ["result must be derived from tenant roles and token aggregates", "the action must not claim to synchronize or mutate permissions", "successful reviews must write audit_logs"],
      },
      {
        id: "settings-connection-test",
        label: "Test integrations",
        method: "POST",
        endpoint: "/v1/auth/system-settings/actions/connection-test",
        requiredScopes: ["admin:write"],
        acceptedScopes: ["admin:write", "admin:*", "*"],
        auditEvent: "system_settings_connection_test",
        guardrails: ["test results must come from a real endpoint reachability probe and persist last_tested_at", "failed probes must be reported as degraded rather than healthy", "secret values must never be returned"],
      },
      {
        id: "settings-security-audit",
        label: "Run security audit",
        method: "POST",
        endpoint: "/v1/auth/system-settings/actions/security-audit",
        requiredScopes: ["admin:write"],
        acceptedScopes: ["admin:write", "admin:*", "*"],
        auditEvent: "system_settings_security_audit",
        guardrails: ["findings must use persisted settings", "successful actions must write audit_logs"],
      },
      {
        id: "settings-impact",
        label: "Review change impact",
        method: "GET",
        endpoint: "/v1/auth/system-settings/impact",
        requiredScopes: ["admin:read"],
        acceptedScopes: ["admin:read", "admin:write", "admin:*", "*"],
        auditEvent: "system_settings_impact_view",
        guardrails: ["response must state scope, risk, permission and audit action"],
      },
      {
        id: "settings-preferences-save",
        label: "Save user settings",
        method: "PUT",
        endpoint: "/v1/auth/settings/{category}",
        requiredScopes: ["token:read"],
        acceptedScopes: ["token:read", "admin:*", "*"],
        auditEvent: "USER_UPDATE",
        defaultBody: {
          page_size: 50,
          refresh_interval: 30,
          default_time_range: "last_24h",
          timezone: "Asia/Shanghai",
          show_ws_status: true,
        },
        guardrails: [
          "settings category must be notifications or display",
          "tenant_id and user_id must come from the authenticated token",
          "successful saves must persist user_settings and emit USER_UPDATE action=settings_update when audit logging is enabled",
        ],
      },
      {
        id: "settings-token-create",
        label: "Create API token",
        method: "POST",
        endpoint: "/v1/tokens",
        requiredScopes: ["token:write"],
        acceptedScopes: ["token:write", "*"],
        auditEvent: "create_token",
        defaultBody: {
          name: "ops-token",
          scopes: ["alert:read", "token:read"],
          expires_in_sec: 300,
        },
        guardrails: [
          "token creation requires token:write (only global * also satisfies it)",
          "requested scopes must not exceed the authenticated caller permissions",
          "plain token is returned only once and token_hash must never be returned",
          "successful creates must persist api_tokens and audit_logs action=create_token rows in one transaction",
        ],
      },
      {
        id: "settings-token-regenerate",
        label: "Regenerate API token",
        method: "POST",
        endpoint: "/v1/tokens/{id}/regenerate",
        requiredScopes: ["token:write"],
        acceptedScopes: ["token:write", "*"],
        auditEvent: "regenerate_token",
        guardrails: [
          "regeneration requires token:write (only global * also satisfies it)",
          "the caller must be allowed to delegate every scope copied from the old token",
          "old raw token must be rejected after regenerate",
          "old revoke, new credential creation and regenerate_token audit must commit atomically",
        ],
      },
      {
        id: "settings-token-revoke",
        label: "Revoke API token",
        method: "POST",
        endpoint: "/v1/tokens/{id}/revoke",
        requiredScopes: ["token:write"],
        acceptedScopes: ["token:write", "*"],
        auditEvent: "revoke_token",
        guardrails: [
          "revoke requires token:write (only global * also satisfies it)",
          "the caller must be allowed to delegate every scope held by the target token",
          "revoked raw tokens must fail /v1/tokens/validate",
          "successful revokes must persist status=revoked and write revoke_token audit_logs rows",
        ],
      },
      {
        id: "settings-token-scope-update",
        label: "Update API token scopes",
        method: "PUT",
        endpoint: "/v1/tokens/{id}/scopes",
        requiredScopes: ["token:write"],
        acceptedScopes: ["token:write", "*"],
        auditEvent: "update_token_scopes",
        defaultBody: { scopes: ["alert:read", "token:read"] },
        guardrails: [
          "scope updates require token:write (only global * also satisfies it)",
          "the caller must be allowed to delegate every existing target scope",
          "invalid scopes must be rejected by auth-service",
          "requested scopes must not exceed the authenticated caller permissions",
          "successful scope changes and update_token_scopes audit must commit atomically",
        ],
      },
      {
        id: "settings-token-validate",
        label: "Validate API token",
        method: "POST",
        endpoint: "/v1/tokens/validate",
        requiredScopes: ["token:read"],
        acceptedScopes: ["token:read", "token:write", "admin:*", "*"],
        auditEvent: "validate_token",
        guardrails: [
          "connection tests must submit the token only to /v1/tokens/validate",
          "validation responses must not expose token_hash",
          "expired, regenerated or revoked raw tokens must return invalid credentials",
        ],
      },
    ],
  },
};

export const getPageApiPlan = (pageId: string) =>
  pageApiPlans[pageId] ?? { primary: `/v1/${pageId}` };

export const getPageLoadSecondaryEndpoints = (pageId: string) => {
  const plan = getPageApiPlan(pageId);
  return (plan.pageLoadSecondary ?? plan.secondary ?? []).filter(
    (endpoint) => !hasEndpointPlaceholder(endpoint),
  );
};

export const getPageActionPlans = (pageId: string) =>
  getPageApiPlan(pageId).actions ?? [];

export const getPageActionPlan = (pageId: string, actionId: string) =>
  getPageActionPlans(pageId).find((action) => action.id === actionId);

export const getPlanEndpoints = (plan: EndpointPlan) => [
  plan.primary,
  ...(plan.secondary ?? []),
  ...(plan.actions ?? []).map((action) => action.endpoint),
];

const hasEndpointPlaceholder = (endpoint: string) => /\{[^}]+\}/.test(endpoint);
