import { encryptedTrafficPagePlan } from '@/services/encryptedTrafficPagePlan';

export type EndpointPlan = {
  primary: string;
  secondary?: string[];
  pageLoadSecondary?: string[];
  actions?: ActionEndpointPlan[];
};

export type EndpointMethod = "GET" | "POST" | "PUT" | "PATCH" | "DELETE";

export type ActionEndpointPlan = {
  id: string;
  label: string;
  method: EndpointMethod;
  endpoint: string;
  requiredScopes: string[];
  acceptedScopes?: string[];
  auditEvent: string;
  defaultBody?: Record<string, unknown>;
  guardrails: string[];
};

export const pageApiPlans: Record<string, EndpointPlan> = {

  "analysis-tasks": { primary: "/v1/analysis/tasks", secondary: [] },
  "analysis-schedules": { primary: "/v1/analysis/schedules", secondary: [] },
  "analysis-orchestration": { primary: "/v1/analysis/plans", secondary: ["/v1/analysis/tasks"] },
  "analysis-runs": {
    primary: "/v1/analysis/runs",
    secondary: ["/v1/analysis/tasks"],
    actions: [
      {
        id: "analysis-trigger-submit",
        label: "即时分析提交",
        method: "POST",
        endpoint: "/v1/analysis/triggers",
        requiredScopes: ["analysis:run"],
        acceptedScopes: ["analysis:run", "admin:*", "*"],
        auditEvent: "ANALYSIS_TRIGGER_SUBMITTED",
        guardrails: ["幂等键一次生成重试复用", "202 仅在物化事务提交后返回"],
      },
      {
        id: "analysis-run-cancel",
        label: "取消运行",
        method: "POST",
        endpoint: "/v1/analysis/runs/{runId}:cancel",
        requiredScopes: ["analysis:run"],
        acceptedScopes: ["analysis:run", "admin:*", "*"],
        auditEvent: "ANALYSIS_RUN_CANCEL_REQUESTED",
        guardrails: ["终态先胜 replay", "取消完成以运行详情为准"],
      },
    ],
  },
  "analysis-task-definition-detail": {
    primary: "/v1/analysis/task-definitions/{taskDefinitionId}",
    secondary: ["/v1/analysis/task-definitions/{taskDefinitionId}/plans", "/v1/analysis/task-definitions/{taskDefinitionId}/report-policies"],
    actions: [
      {
        id: "analysis-task-definition-activate",
        label: "激活任务定义",
        method: "POST",
        endpoint: "/v1/analysis/task-definitions/{taskDefinitionId}/activate",
        requiredScopes: ["analysis:write"],
        acceptedScopes: ["analysis:write", "admin:*", "*"],
        auditEvent: "ANALYSIS_TASK_DEFINITION_ACTIVATED",
        guardrails: ["If-Match expected revision", "保存不联动计划"],
      },
      {
        id: "analysis-task-definition-suspend",
        label: "挂起任务定义",
        method: "POST",
        endpoint: "/v1/analysis/task-definitions/{taskDefinitionId}/suspend",
        requiredScopes: ["analysis:write"],
        acceptedScopes: ["analysis:write", "admin:*", "*"],
        auditEvent: "ANALYSIS_TASK_DEFINITION_SUSPENDED",
        guardrails: ["If-Match expected revision", "只影响未来触发"],
      },
    ],
  },
  "analysis-run-detail": {
    primary: "/v1/analysis/runs/{runId}",
    secondary: [],
    actions: [
      {
        id: "analysis-report-request",
        label: "生成人读报告",
        method: "POST",
        endpoint: "/v1/analysis/runs/{runId}/report",
        requiredScopes: ["analysis:run"],
        acceptedScopes: ["analysis:run", "admin:*", "*"],
        auditEvent: "ANALYSIS_REPORT_REQUESTED",
        guardrails: ["仅终态可请求", "报告失败不回退运行终态"],
      },
    ],
  },
  "analysis-reports": { primary: "/v1/analysis/runs", secondary: [] },
  "analysis-resources": { primary: "/v1/analysis/queue", secondary: [] },

  dashboard: {
    primary: "/v1/dashboard/snapshot",
    secondary: [],
    actions: [
      {
        id: "dashboard-task-create",
        label: "创建闭环任务",
        method: "POST",
        endpoint: "/v1/dashboard/tasks",
        requiredScopes: ["dashboard:write"],
        acceptedScopes: ["dashboard:write", "dashboard:*", "admin:*", "*"],
        auditEvent: "DASHBOARD_TASK_CREATED",
        defaultBody: {
          task_type: "closure",
          target: "dashboard",
          priority: "high",
        },
        guardrails: [
          "task type and target are required",
          "task creation must preserve tenant and current dashboard context",
          "successful submissions must write DASHBOARD_TASK_CREATED audit_logs rows",
        ],
      },
      {
        id: "dashboard-evidence-task-create",
        label: "补齐证据",
        method: "POST",
        endpoint: "/v1/dashboard/tasks/evidence",
        requiredScopes: ["dashboard:write"],
        acceptedScopes: ["dashboard:write", "forensics:write", "admin:*", "*"],
        auditEvent: "DASHBOARD_EVIDENCE_TASK_CREATED",
        defaultBody: { task_type: "evidence_repair", target: "evidence-gap" },
        guardrails: [
          "evidence target is required",
          "task must preserve source event references",
        ],
      },
      {
        id: "dashboard-feedback-task-create",
        label: "回流样本",
        method: "POST",
        endpoint: "/v1/dashboard/tasks/feedback",
        requiredScopes: ["dashboard:write"],
        acceptedScopes: ["dashboard:write", "feedback:write", "admin:*", "*"],
        auditEvent: "DASHBOARD_FEEDBACK_TASK_CREATED",
        defaultBody: { task_type: "feedback_replay", target: "feedback-gap" },
        guardrails: [
          "feedback target is required",
          "sample payloads must remain masked",
        ],
      },
      {
        id: "dashboard-audit-task-create",
        label: "完善留痕",
        method: "POST",
        endpoint: "/v1/dashboard/tasks/audit",
        requiredScopes: ["dashboard:write"],
        acceptedScopes: ["dashboard:write", "audit:write", "admin:*", "*"],
        auditEvent: "DASHBOARD_AUDIT_TASK_CREATED",
        defaultBody: { task_type: "audit_repair", target: "audit-gap" },
        guardrails: [
          "audit gap target is required",
          "existing audit records must remain immutable",
        ],
      },
      {
        id: "dashboard-sla-task-create",
        label: "跟进处理",
        method: "POST",
        endpoint: "/v1/dashboard/tasks/sla",
        requiredScopes: ["dashboard:write"],
        acceptedScopes: ["dashboard:write", "alert:write", "admin:*", "*"],
        auditEvent: "DASHBOARD_SLA_TASK_CREATED",
        defaultBody: { task_type: "sla_followup", target: "overdue-ticket" },
        guardrails: [
          "SLA target is required",
          "task priority must reflect remaining SLA",
        ],
      },
      {
        id: "dashboard-compliance-task-create",
        label: "修复门禁",
        method: "POST",
        endpoint: "/v1/dashboard/tasks/compliance",
        requiredScopes: ["dashboard:write"],
        acceptedScopes: ["dashboard:write", "compliance:write", "admin:*", "*"],
        auditEvent: "DASHBOARD_COMPLIANCE_TASK_CREATED",
        defaultBody: {
          task_type: "compliance_repair",
          target: "compliance-gap",
        },
        guardrails: [
          "compliance target is required",
          "approval gates must not be bypassed",
        ],
      },
    ],
  },
  screen: {
    primary: "/v1/dashboard/stats",
    secondary: [
      "/v1/dashboard/encrypted/trend",
      "/v1/dashboard/attack-phases",
      "/v1/probes",
    ],
  },
  topics: {
    primary: "/v1/topics/tunnel",
    secondary: [
      "/v1/topics/exfil",
      "/v1/topics/apt",
      "/v1/topics/views",
      "/v1/topics/subscriptions",
    ],
    actions: [
      {
        id: "topic-view-save",
        label: "Save topic view",
        method: "POST",
        endpoint: "/v1/topics/views",
        requiredScopes: ["topic:write"],
        acceptedScopes: ["topic:write", "topic:*", "admin:*", "*"],
        auditEvent: "TOPIC_VIEW_SAVED",
        defaultBody: {
          topic: "tunnel",
          name: "核心隧道专题视图",
          filters: { risk: "high" },
          visibility: "team",
        },
        guardrails: [
          "topic and name are required",
          "saved views must persist topic_saved_views rows",
          "successful saves must write TOPIC_VIEW_SAVED audit_logs rows",
        ],
      },
      {
        id: "topic-scope-update",
        label: "Update topic scope",
        method: "PUT",
        endpoint: "/v1/topics/scopes/{topic}",
        requiredScopes: ["topic:write"],
        acceptedScopes: ["topic:write", "topic:*", "admin:*", "*"],
        auditEvent: "TOPIC_SCOPE_UPDATED",
        defaultBody: {
          scope_name: "核心园区出口",
          included_assets: ["core-switch"],
          risk_levels: ["high", "critical"],
          time_window: "24h",
        },
        guardrails: [
          "topic must be one of tunnel, exfil or apt",
          "scope updates must upsert topic_scope_overrides rows",
          "successful updates must write TOPIC_SCOPE_UPDATED audit_logs rows",
        ],
      },
      {
        id: "topic-subscription-create",
        label: "Create topic subscription",
        method: "POST",
        endpoint: "/v1/topics/subscriptions",
        requiredScopes: ["topic:write"],
        acceptedScopes: ["topic:write", "topic:*", "admin:*", "*"],
        auditEvent: "TOPIC_SUBSCRIPTION_CREATED",
        defaultBody: {
          topic: "tunnel",
          channel: "webhook",
          threshold: "high",
          schedule: "realtime",
          recipients: ["soc-duty"],
        },
        guardrails: [
          "topic and recipients are required",
          "subscriptions must persist topic_subscriptions rows",
          "viewer writes must return 403 before persistence",
        ],
      },
      {
        id: "topic-subscription-toggle",
        label: "Toggle topic subscription",
        method: "PATCH",
        endpoint: "/v1/topics/subscriptions/{id}",
        requiredScopes: ["topic:write"],
        acceptedScopes: ["topic:write", "topic:*", "admin:*", "*"],
        auditEvent: "TOPIC_SUBSCRIPTION_UPDATED",
        defaultBody: { enabled: false },
        guardrails: [
          "cross-tenant subscription updates must return 404",
          "toggle state must persist in topic_subscriptions",
          "successful toggles must write TOPIC_SUBSCRIPTION_UPDATED audit_logs rows",
        ],
      },
      {
        id: "topic-report-export",
        label: "Export topic report",
        method: "POST",
        endpoint: "/v1/topics/reports/export",
        requiredScopes: ["topic:export"],
        acceptedScopes: [
          "topic:export",
          "topic:write",
          "topic:*",
          "admin:*",
          "*",
        ],
        auditEvent: "TOPIC_REPORT_EXPORTED",
        defaultBody: { topic: "tunnel", format: "json" },
        guardrails: [
          "topic report export must persist topic_exports rows",
          "export responses must include file_key and retention metadata",
          "successful exports must write TOPIC_REPORT_EXPORTED audit_logs rows",
        ],
      },
      {
        id: "topic-evidence-package-export",
        label: "Export topic evidence package",
        method: "POST",
        endpoint: "/v1/topics/evidence-packages/export",
        requiredScopes: ["topic:export"],
        acceptedScopes: [
          "topic:export",
          "topic:write",
          "topic:*",
          "admin:*",
          "*",
        ],
        auditEvent: "TOPIC_EVIDENCE_PACKAGE_EXPORTED",
        defaultBody: { topic: "exfil", format: "json" },
        guardrails: [
          "evidence package export must persist topic_exports rows",
          "export must preserve tenant isolation",
          "successful exports must write TOPIC_EVIDENCE_PACKAGE_EXPORTED audit_logs rows",
        ],
      },
      {
        id: "topic-action-submit",
        label: "Submit topic operation",
        method: "POST",
        endpoint: "/v1/topics/{topic}/actions",
        requiredScopes: ["topic:write"],
        acceptedScopes: ["topic:write", "topic:*", "admin:*", "*"],
        auditEvent: "TOPIC_ACTION_REQUESTED",
        defaultBody: {
          action: "extract_pcap",
          label: "提取隧道 PCAP",
          target: "",
          data_mode: "live",
        },
        guardrails: [
          "topic action and target are required",
          "topic actions must persist topic_actions rows",
          "action row and TOPIC_ACTION_REQUESTED audit log must commit atomically",
        ],
      },
    ],
  },
  "topic-tunnel": { primary: "/v1/topics/tunnel/snapshot" },
  "topic-exfil": { primary: "/v1/topics/exfil/snapshot" },
  "topic-apt": { primary: "/v1/topics/apt/snapshot" },
  probes: {
    primary: "/v1/probes",
    secondary: [
      "/v1/probes/topology",
      "/v1/probes/operations/{operation_id}",
    ],
    actions: [
      {
        id: "probe-batch-upgrade",
        label: "Batch upgrade probes",
        method: "POST",
        endpoint: "/v1/probes/batch-upgrade",
        requiredScopes: ["probe:write"],
        acceptedScopes: ["probe:write", "admin:*", "*"],
        auditEvent: "PROBE_BATCH_UPGRADE_QUEUED",
        defaultBody: {
          probe_ids: ["PROBE-DC-01"],
          target_version: "v3.4.8",
          rollout_strategy: "canary",
        },
        guardrails: [
          "target_version and at least one probe_id are required",
          "batch upgrades must persist accepted probe_operations rows without claiming agent completion",
          "accepted upgrades must preserve the legacy PROBE_BATCH_UPGRADE_QUEUED audit event identifier",
        ],
      },
      {
        id: "probe-batch-state",
        label: "Batch enable probes",
        method: "POST",
        endpoint: "/v1/probes/batch-state",
        requiredScopes: ["probe:write"],
        acceptedScopes: ["probe:write", "admin:*", "*"],
        auditEvent: "PROBE_BATCH_STATE_QUEUED",
        defaultBody: {
          probe_ids: ["PROBE-DC-01"],
          desired_state: "active",
          reason: "operator requested from probes page",
        },
        guardrails: [
          "desired_state must be active or inactive",
          "tenant isolation must be checked before state changes",
          "each probe change must persist a probe_operations row and one aggregate audit event",
        ],
      },
      {
        id: "probe-config-push",
        label: "Push probe capture policy",
        method: "POST",
        endpoint: "/v1/probes/{id}/config",
        requiredScopes: ["probe:write"],
        acceptedScopes: ["probe:write", "admin:*", "*"],
        auditEvent: "PROBE_CONFIG_PUSH_QUEUED",
        defaultBody: {
          config_version: "campus-full-capture-20260630",
          capture_mode: "af_packet",
          interfaces: ["eth2", "eth3"],
          archive_path: "s3://pcap-archive/probes/",
          batch_send_mbps: 2000,
        },
        guardrails: [
          "config_version is required",
          "configuration pushes must persist probe_operations rows",
          "configuration remains accepted until a matching probe ACK reaches a terminal state",
          "tenant_id must come from the authenticated token for write operations",
        ],
      },
      {
        id: "probe-connectivity-test",
        label: "Run probe connectivity test",
        method: "POST",
        endpoint: "/v1/probes/{id}/connectivity-test",
        requiredScopes: ["probe:write"],
        acceptedScopes: ["probe:write", "admin:*", "*"],
        auditEvent: "PROBE_CONNECTIVITY_TEST_QUEUED",
        defaultBody: { targets: ["ingest-gateway", "kafka", "clickhouse"] },
        guardrails: [
          "connectivity checks must remain accepted until the target probe reports measured results",
          "viewer writes must return 403 before persistence",
          "cross-tenant probe operations must return 404",
        ],
      },
      {
        id: "probe-cert-rotate",
        label: "Rotate probe mTLS certificate",
        method: "POST",
        endpoint: "/v1/probes/{id}/certificates/rotate",
        requiredScopes: ["probe:write"],
        acceptedScopes: ["probe:write", "admin:*", "*"],
        auditEvent: "PROBE_CERT_ROTATE_QUEUED",
        defaultBody: {
          secret_ref:
            "k8s://traffic-analysis/traffic-credentials#PROBE_MTLS_CERT",
          rotation_window: "immediate",
        },
        guardrails: [
          "certificate rotation must use secret_ref only",
          "plaintext certificate, private_key, token or password fields must be rejected",
          "accepted rotations must preserve the legacy PROBE_CERT_ROTATE_QUEUED audit event identifier",
        ],
      },
      {
        id: "probe-restart",
        label: "Restart probe",
        method: "POST",
        endpoint: "/v1/probes/{id}/restart",
        requiredScopes: ["probe:write"],
        acceptedScopes: ["probe:write", "admin:*", "*"],
        auditEvent: "PROBE_RESTART_QUEUED",
        defaultBody: { reason: "operator requested from probes page" },
        guardrails: [
          "restart requests must target one tenant-owned probe",
          "restart requests must persist probe_operations and audit_logs records",
          "the API reports accepted until the probe control channel acknowledges execution",
        ],
      },
    ],
  },
  "data-quality": {
    primary: "/v1/data-quality",
    actions: [
      {
        id: "dlq-fallback-replay",
        label: "DLQ fallback replay",
        method: "POST",
        endpoint: "/v1/dlq/replay/fallback",
        requiredScopes: ["dlq:replay"],
        acceptedScopes: ["dlq:replay", "dlq:*", "admin:write", "admin:*", "*"],
        auditEvent: "dlq_replay_approved",
        defaultBody: { dry_run: true },
        guardrails: [
          "approved_by must differ from requested_by",
          "approval_id, reason, repair_summary and idempotency_key are required",
          "dry_run=true is the UI default before execution replay",
        ],
      },
      {
        id: "data-quality-context-action",
        label: "Data quality contextual action",
        method: "POST",
        endpoint: "/v1/data-quality/actions",
        requiredScopes: ["data-quality:write"],
        acceptedScopes: [
          "data-quality:write",
          "data-quality:*",
          "admin:*",
          "*",
        ],
        auditEvent: "DATA_QUALITY_ACTION_REQUESTED",
        defaultBody: {
          view: "overview",
          action: "inspect",
          target: "current-selection",
          dry_run: true,
        },
        guardrails: [
          "view, action and target are required",
          "write actions must default to dry_run=true until explicit confirmation",
          "successful requests must preserve tenant context and write DATA_QUALITY_ACTION_REQUESTED audit_logs rows",
        ],
      },
    ],
  },
  alerts: {
    primary: "/v1/alerts",
    pageLoadSecondary: ["/v1/alerts/stats", "/v1/alerts/trend"],
  },
  "alert-detail": {
    primary: "/v1/alerts/{id}",
    secondary: [
      "/v1/alerts/{id}/evidence",
      "/v1/alerts/{id}/feedback",
      "/v1/alerts/{id}/campaign-links",
      "/v1/alerts/{id}/reports/{job_id}",
      "/v1/alerts/{id}/reports/{job_id}/cancel",
      "/v1/alerts/{id}/reports/{job_id}/compensations",
      "/v1/alerts/{id}/reports/{job_id}/download",
    ],
    actions: [
      {
        id: "alert-label-update",
        label: "Update alert labels",
        method: "PUT",
        endpoint: "/v1/alerts/{id}/labels",
        requiredScopes: ["alert:write"],
        acceptedScopes: ["alert:write", "alert:*", "admin:*", "*"],
        auditEvent: "ALERT_LABELS_UPDATED",
        defaultBody: { labels: [], reason: "" },
        guardrails: [
          "label updates must use the alert append-only version path",
          "successful writes must retain the actor and reason in audit_logs",
        ],
      },
      {
        id: "alert-report-export",
        label: "Export alert report",
        method: "POST",
        endpoint: "/v1/alerts/{id}/reports/export",
        requiredScopes: ["alert:export"],
        acceptedScopes: [
          "alert:export",
          "alert:*",
          "admin:*",
          "*",
        ],
        auditEvent: "ALERT_REPORT_EXPORT_REQUESTED",
        defaultBody: { format: "pdf" },
        guardrails: [
          "export must contain only the current tenant alert and approved evidence",
          "successful exports must write audit_logs",
        ],
      },
      {
        id: "alert-report-cancel",
        label: "Cancel alert report",
        method: "POST",
        endpoint: "/v1/alerts/{id}/reports/{job_id}/cancel",
        requiredScopes: ["alert:export"],
        acceptedScopes: ["alert:export", "alert:*", "admin:*", "*"],
        auditEvent: "ALERT_REPORT_EXPORT_CANCEL_REQUESTED",
        defaultBody: { expected_revision: 0, reason: "" },
        guardrails: [
          "accepted jobs cancel atomically and running jobs enter cancel_requested",
          "cancelled is terminal only after an exact temporary object cleanup succeeds",
          "revision, idempotency, history, outbox and audit must commit in one transaction",
        ],
      },
      {
        id: "alert-report-compensate",
        label: "Compensate alert report cleanup",
        method: "POST",
        endpoint: "/v1/alerts/{id}/reports/{job_id}/compensations",
        requiredScopes: ["alert:export"],
        acceptedScopes: ["alert:export", "alert:*", "admin:*", "*"],
        auditEvent: "ALERT_REPORT_EXPORT_COMPENSATION_REQUESTED",
        defaultBody: { expected_revision: 0, reason: "" },
        guardrails: [
          "compensation is allowed only when cancellation cleanup retained a residual object manifest",
          "the worker removes only the immutable manifest bucket and key",
          "compensated is terminal only after object removal, history, outbox and audit commit",
        ],
      },
      {
        id: "alert-campaign-link",
        label: "Link alert to campaign",
        method: "POST",
        endpoint: "/v1/alerts/{id}/campaign-links",
        requiredScopes: ["alert:write", "campaign:write"],
        acceptedScopes: [
          "alert:write",
          "alert:*",
          "campaign:write",
          "admin:*",
          "*",
        ],
        auditEvent: "ALERT_CAMPAIGN_LINK_REQUESTED",
        defaultBody: { campaign_hint: "auto" },
        guardrails: [
          "campaign link must preserve tenant isolation",
          "successful requests must write audit_logs",
        ],
      },
      {
        id: "alert-campaign-unlink",
        label: "Unlink alert from campaign",
        method: "DELETE",
        endpoint: "/v1/alerts/{id}/campaign-links/{campaign_id}",
        requiredScopes: ["alert:write", "campaign:write"],
        acceptedScopes: [
          "alert:write",
          "alert:*",
          "campaign:write",
          "admin:*",
          "*",
        ],
        auditEvent: "ALERT_CAMPAIGN_UNLINKED",
        defaultBody: {},
        guardrails: [
          "relation and current campaign aggregate revisions must both be checked",
          "unlink is an append-only compensating command and must retain relation history",
          "successful requests must atomically update member_count, both outboxes and audit_logs",
        ],
      },
      {
        id: "alert-evidence-access",
        label: "Request alert evidence access",
        method: "POST",
        endpoint: "/v1/alerts/{id}/evidence/access",
        requiredScopes: ["alert:read"],
        acceptedScopes: [
          "alert:read",
          "evidence:read",
          "alert:*",
          "admin:*",
          "*",
        ],
        auditEvent: "ALERT_EVIDENCE_ACCESS_REQUESTED",
        defaultBody: { purpose: "investigation" },
        guardrails: [
          "evidence access must record the selected evidence and requester",
          "signed URL must be short-lived",
        ],
      },
      {
        id: "alert-response-request",
        label: "Request alert response action",
        method: "POST",
        endpoint: "/v1/alerts/{id}/response-actions",
        requiredScopes: ["alert:write"],
        acceptedScopes: [
          "alert:write",
          "alert:*",
          "playbook:execute",
          "admin:*",
          "*",
        ],
        auditEvent: "ALERT_RESPONSE_ACTION_REQUESTED",
        defaultBody: { dry_run: true },
        guardrails: [
          "high impact responses require confirmation and dry_run=true by default",
          "successful requests must write audit_logs",
        ],
      },
      {
        id: "alert-response-status",
        label: "Read alert response state",
        method: "GET",
        endpoint: "/v1/alerts/{id}/response-actions/{job_id}",
        requiredScopes: ["alert:read"],
        acceptedScopes: ["alert:read", "alert:write", "alert:*", "admin:*", "*"],
        auditEvent: "ALERT_RESPONSE_ACTION_READ",
        defaultBody: {},
        guardrails: [
          "the alert id, job id and authenticated tenant must all match",
          "the response must distinguish approval, outbox and terminal receipt state",
        ],
      },
      {
        id: "alert-response-approval",
        label: "Approve or reject alert response",
        method: "POST",
        endpoint: "/v1/alerts/{id}/response-actions/{job_id}/approval",
        requiredScopes: ["playbook:approve"],
        acceptedScopes: ["playbook:approve", "admin:*", "*"],
        auditEvent: "ALERT_RESPONSE_ACTION_APPROVED",
        defaultBody: { decision: "approve", expected_revision: 1, reason: "" },
        guardrails: [
          "the requester cannot approve or reject the same action",
          "approval, revision transition, audit and approved outbox are one transaction",
        ],
      },
      {
        id: "alert-response-cancel",
        label: "Cancel queued alert response",
        method: "POST",
        endpoint: "/v1/alerts/{id}/response-actions/{job_id}/cancel",
        requiredScopes: ["alert:write"],
        acceptedScopes: ["alert:write", "alert:*", "admin:*", "*"],
        auditEvent: "ALERT_RESPONSE_ACTION_CANCELLED",
        defaultBody: { expected_revision: 1, reason: "" },
        guardrails: [
          "cancellation cannot overtake a leased or published outbox row",
          "terminal receipts cannot be overwritten",
        ],
      },
      {
        id: "alert-response-compensate",
        label: "Request alert response compensation",
        method: "POST",
        endpoint: "/v1/alerts/{id}/response-actions/{job_id}/compensations",
        requiredScopes: ["playbook:approve"],
        acceptedScopes: ["playbook:approve", "admin:*", "*"],
        auditEvent: "ALERT_RESPONSE_COMPENSATION_BLOCKED",
        defaultBody: { expected_revision: 1, reason: "" },
        guardrails: [
          "compensation requires a catalogued inverse and a terminal receipt with external_effect=true",
          "an unavailable compensation executor is reported as blocked and never as success",
        ],
      },
      {
        id: "alert-investigation-note",
        label: "Record alert investigation note",
        method: "POST",
        endpoint: "/v1/alerts/{id}/investigation-notes",
        requiredScopes: ["alert:write"],
        acceptedScopes: ["alert:write", "alert:*", "admin:*", "*"],
        auditEvent: "ALERT_INVESTIGATION_NOTE_RECORDED",
        defaultBody: { source: "alert-detail" },
        guardrails: [
          "notes must include the selected alert and actor",
          "successful writes must retain the audit trace",
        ],
      },
    ],
  },
  campaigns: {
    primary: "/v1/campaigns",
    secondary: ["/v1/campaigns/{id}", "/v1/campaigns/{id}/members"],
    actions: [
      {
        id: "campaign-export",
        label: "Export campaigns",
        method: "POST",
        endpoint: "/v1/campaigns/actions",
        requiredScopes: ["alert:read"],
        acceptedScopes: ["alert:read", "alert:write", "admin:*", "*"],
        auditEvent: "CAMPAIGN_EXPORT_REQUESTED",
        defaultBody: {
          action_id: "campaign-export",
          format: "csv",
          selection: "current-filter",
        },
        guardrails: [
          "exports must preserve the current tenant and filter context",
          "export requests must write an audit record",
        ],
      },
      {
        id: "campaign-list-settings",
        label: "Update campaign list settings",
        method: "POST",
        endpoint: "/v1/campaigns/actions",
        requiredScopes: ["alert:read"],
        acceptedScopes: ["alert:read", "alert:write", "admin:*", "*"],
        auditEvent: "CAMPAIGN_LIST_SETTINGS_UPDATED",
        defaultBody: {
          action_id: "campaign-list-settings",
          page_size: 20,
          visible_columns: "default",
        },
        guardrails: [
          "list settings must be scoped to the current user",
          "settings changes must write an audit record",
        ],
      },
      {
        id: "campaign-assign-owner",
        label: "Assign campaign owner",
        method: "POST",
        endpoint: "/v1/campaigns/{id}/actions",
        requiredScopes: ["campaign:write"],
        acceptedScopes: ["campaign:write", "alert:write", "admin:*", "*"],
        auditEvent: "CAMPAIGN_OWNER_ASSIGNED",
        defaultBody: {
          action_id: "campaign-assign-owner",
          action: "assign_owner",
          owner: "current-user",
        },
        guardrails: [
          "campaign and owner are required",
          "the mutation must carry the lifecycle snapshot displayed by the browser",
          "owner changes must preserve tenant isolation and write an audit record",
        ],
      },
      {
        id: "campaign-status-change",
        label: "Change campaign status",
        method: "POST",
        endpoint: "/v1/campaigns/{id}/actions",
        requiredScopes: ["campaign:write"],
        acceptedScopes: ["campaign:write", "alert:write", "admin:*", "*"],
        auditEvent: "CAMPAIGN_STATUS_CHANGED",
        defaultBody: {
          action_id: "campaign-status-change",
          action: "status_change",
          status: "investigating",
        },
        guardrails: [
          "campaign and status are required",
          "the mutation must carry the lifecycle snapshot displayed by the browser",
          "status transitions must be validated and audited",
        ],
      },
      {
        id: "campaign-merge",
        label: "Merge campaign into target",
        method: "POST",
        endpoint: "/v1/campaigns/{id}/actions",
        requiredScopes: ["campaign:write"],
        acceptedScopes: ["campaign:write", "alert:write", "admin:*", "*"],
        auditEvent: "CAMPAIGN_MERGED",
        defaultBody: {
          action_id: "campaign-merge",
          target_campaign_id: "",
          expected_revision: 0,
          target_expected_revision: 0,
          reason: "",
        },
        guardrails: [
          "source and target campaigns must be distinct and tenant scoped",
          "the source mutation must carry the lifecycle snapshot displayed by the browser",
          "both aggregate revisions, the bounded member manifest and the idempotency key are required",
        ],
      },
      {
        id: "campaign-context-action",
        label: "Run campaign contextual action",
        method: "POST",
        endpoint: "/v1/campaigns/{id}/actions",
        requiredScopes: ["campaign:write"],
        acceptedScopes: ["campaign:write", "alert:write", "admin:*", "*"],
        auditEvent: "CAMPAIGN_CONTEXT_ACTION_REQUESTED",
        defaultBody: {
          action_id: "campaign-context-action",
          action: "inspect",
        },
        guardrails: [
          "campaign and action are required",
          "mutating requests must carry the lifecycle snapshot displayed by the browser",
          "mutating contextual actions require explicit confirmation",
        ],
      },
      {
        id: "campaign-detail-view",
        label: "View campaign detail",
        method: "POST",
        endpoint: "/v1/campaigns/{id}/actions",
        requiredScopes: ["alert:read"],
        acceptedScopes: ["alert:read", "alert:write", "admin:*", "*"],
        auditEvent: "CAMPAIGN_DETAIL_VIEWED",
        defaultBody: {
          action_id: "campaign-detail-view",
          action: "detail_view",
        },
        guardrails: [
          "campaign reads must preserve tenant isolation",
          "detail views must write an audit record",
        ],
      },
      {
        id: "campaign-phase-inspect",
        label: "Inspect campaign phase",
        method: "POST",
        endpoint: "/v1/campaigns/{id}/actions",
        requiredScopes: ["alert:read"],
        acceptedScopes: ["alert:read", "alert:write", "admin:*", "*"],
        auditEvent: "CAMPAIGN_PHASE_VIEWED",
        defaultBody: {
          action_id: "campaign-phase-inspect",
          action: "phase_inspect",
        },
        guardrails: [
          "campaign and phase are required",
          "phase inspection must write an audit record",
        ],
      },
      {
        id: "campaign-impact-inspect",
        label: "Inspect campaign impact scope",
        method: "POST",
        endpoint: "/v1/campaigns/{id}/actions",
        requiredScopes: ["alert:read"],
        acceptedScopes: ["alert:read", "alert:write", "admin:*", "*"],
        auditEvent: "CAMPAIGN_IMPACT_VIEWED",
        defaultBody: {
          action_id: "campaign-impact-inspect",
          action: "impact_inspect",
        },
        guardrails: [
          "campaign and impact scope are required",
          "impact inspection must write an audit record",
        ],
      },
      {
        id: "campaign-evidence-view",
        label: "View campaign evidence",
        method: "POST",
        endpoint: "/v1/campaigns/{id}/actions",
        requiredScopes: ["alert:read"],
        acceptedScopes: ["alert:read", "alert:write", "admin:*", "*"],
        auditEvent: "CAMPAIGN_EVIDENCE_VIEWED",
        defaultBody: {
          action_id: "campaign-evidence-view",
          action: "evidence_view",
        },
        guardrails: [
          "evidence reads must preserve tenant isolation",
          "evidence access must write an audit record",
        ],
      },
      {
        id: "campaign-report-generate",
        label: "Generate campaign report",
        method: "POST",
        endpoint: "/v1/campaigns/{id}/actions",
        requiredScopes: ["campaign:write"],
        acceptedScopes: ["campaign:write", "alert:write", "admin:*", "*"],
        auditEvent: "CAMPAIGN_REPORT_REQUESTED",
        defaultBody: {
          action_id: "campaign-report-generate",
          action: "report_generate",
          format: "pdf",
          include_evidence: true,
        },
        guardrails: [
          "report generation must preserve tenant and campaign context",
          "the report request must bind source_snapshot_id to the lifecycle snapshot displayed by the browser",
          "report requests must write an audit record",
        ],
      },
      {
        id: "campaign-report-status",
        label: "Read campaign report status",
        method: "GET",
        endpoint: "/v1/campaigns/{id}/reports/{report_id}",
        requiredScopes: ["campaign:read"],
        acceptedScopes: ["campaign:read", "campaign:write", "alert:read", "alert:write", "admin:*", "*"],
        auditEvent: "CAMPAIGN_REPORT_STATUS_READ",
        guardrails: [
          "report status must be tenant and campaign scoped",
          "accepted and running are not final success",
          "the browser must poll until an explicit terminal state",
        ],
      },
      {
        id: "campaign-report-download",
        label: "Download completed campaign report",
        method: "GET",
        endpoint: "/v1/campaigns/{id}/reports/{report_id}/download",
        requiredScopes: ["campaign:report"],
        acceptedScopes: ["campaign:report", "campaign:write", "alert:write", "admin:*", "*"],
        auditEvent: "CAMPAIGN_REPORT_DOWNLOADED",
        guardrails: [
          "only completed reports may be downloaded",
          "the object size and SHA256 must match the PostgreSQL manifest",
          "successful downloads must write an audit record",
        ],
      },
      {
        id: "campaign-attack-chain-view",
        label: "View campaign attack chain",
        method: "POST",
        endpoint: "/v1/campaigns/{id}/actions",
        requiredScopes: ["alert:read"],
        acceptedScopes: ["alert:read", "alert:write", "admin:*", "*"],
        auditEvent: "CAMPAIGN_ATTACK_CHAIN_VIEWED",
        defaultBody: {
          action_id: "campaign-attack-chain-view",
          action: "attack_chain_view",
        },
        guardrails: [
          "attack-chain reads must preserve tenant isolation",
          "attack-chain access must write an audit record",
        ],
      },
      {
        id: "campaign-graph-view",
        label: "View campaign entity graph",
        method: "POST",
        endpoint: "/v1/campaigns/{id}/actions",
        requiredScopes: ["graph:read"],
        acceptedScopes: ["graph:read", "admin:*", "*"],
        auditEvent: "CAMPAIGN_GRAPH_VIEWED",
        defaultBody: { action_id: "campaign-graph-view", action: "graph_view" },
        guardrails: [
          "graph queries must preserve tenant isolation",
          "graph access must write an audit record",
        ],
      },
      {
        id: "campaign-soar-response",
        label: "Request campaign SOAR response",
        method: "POST",
        endpoint: "/v1/campaigns/{id}/actions",
        requiredScopes: ["playbook:execute"],
        acceptedScopes: ["playbook:execute", "admin:*", "*"],
        auditEvent: "CAMPAIGN_SOAR_RESPONSE_REQUESTED",
        defaultBody: {
          action_id: "campaign-soar-response",
          action: "soar_response",
          dry_run: false,
        },
        guardrails: [
          "SOAR requests commit pending_approval without claiming an external effect",
          "an approved execution must carry the lifecycle snapshot displayed by the browser",
          "requester and approver must be different identities",
          "terminal success requires a durable provider receipt proving an external effect",
        ],
      },
      {
        id: "campaign-soar-status",
        label: "Read campaign SOAR workflow",
        method: "GET",
        endpoint: "/v1/campaigns/{id}/soar-jobs/{job_id}",
        requiredScopes: ["campaign:read"],
        acceptedScopes: ["campaign:read", "campaign:write", "alert:read", "alert:write", "playbook:read", "admin:*", "*"],
        auditEvent: "CAMPAIGN_SOAR_STATUS_READ",
        guardrails: ["tenant and campaign identity must match the durable workflow row"],
      },
      {
        id: "campaign-soar-approval",
        label: "Approve or reject campaign SOAR workflow",
        method: "POST",
        endpoint: "/v1/campaigns/{id}/soar-jobs/{job_id}/approval",
        requiredScopes: ["playbook:approve"],
        acceptedScopes: ["playbook:approve", "admin:*", "*"],
        auditEvent: "CAMPAIGN_SOAR_APPROVAL_DECIDED",
        guardrails: ["requester cannot approve or reject the same job", "expected revision and idempotency key are mandatory"],
      },
      {
        id: "campaign-soar-cancel",
        label: "Cancel undispatched campaign SOAR workflow",
        method: "POST",
        endpoint: "/v1/campaigns/{id}/soar-jobs/{job_id}/cancel",
        requiredScopes: ["playbook:execute"],
        acceptedScopes: ["playbook:execute", "campaign:write", "admin:*", "*"],
        auditEvent: "CAMPAIGN_SOAR_CANCELLED",
        guardrails: ["only pending or undispatched work can be cancelled"],
      },
      {
        id: "campaign-soar-compensate",
        label: "Compensate campaign SOAR external effect",
        method: "POST",
        endpoint: "/v1/campaigns/{id}/soar-jobs/{job_id}/compensate",
        requiredScopes: ["playbook:approve"],
        acceptedScopes: ["playbook:approve", "admin:*", "*"],
        auditEvent: "CAMPAIGN_SOAR_COMPENSATION_APPROVED",
        guardrails: ["compensation requires an execution receipt proving an external effect", "original requester cannot approve compensation"],
      },
    ],
  },
  "campaign-detail": { primary: "/v1/campaigns/{id}" },
  "attack-chains": { primary: "/v1/attack-chains" },
  "encrypted-traffic": encryptedTrafficPagePlan,
  forensics: {
    primary: "/v1/pcap/jobs",
    secondary: [
      "/v1/pcap/stats",
      "/v1/encrypted-traffic/sessions",
      "/v1/encrypted-traffic/evidence",
      "/v1/audit/logs",
    ],
    actions: [
      {
        id: "forensics-create-job",
        label: "Create PCAP forensics job",
        method: "POST",
        endpoint: "/v1/pcap/jobs",
        requiredScopes: ["pcap:write"],
        acceptedScopes: ["pcap:write", "pcap:*", "admin:*", "*"],
        auditEvent: "PCAP_CUT",
        guardrails: [
          "start_time and end_time are required",
          "time range must not exceed 24 hours",
        ],
      },
      {
        id: "forensics-verify-pcap",
        label: "Verify PCAP SHA-256",
        method: "POST",
        endpoint: "/v1/pcap/verify",
        requiredScopes: ["pcap:read"],
        acceptedScopes: ["pcap:read", "pcap:*", "admin:*", "*"],
        auditEvent: "PCAP_INTEGRITY_VERIFY",
        guardrails: [
          "key is required",
          "cross-tenant object access must return 403",
          "versioned results must be verified against the exact manifest bucket, key and object version",
        ],
      },
      {
        id: "forensics-presign-pcap",
        label: "Generate PCAP signed URL",
        method: "POST",
        endpoint: "/v1/pcap/presign",
        requiredScopes: ["pcap:download"],
        acceptedScopes: ["pcap:download", "pcap:*", "admin:*", "*"],
        auditEvent: "PCAP_DOWNLOAD",
        guardrails: [
          "key and download purpose are required for versioned results",
          "expiry_seconds must not exceed 86400",
          "the signed URL must remain bound to the exact manifest object version",
        ],
      },
      {
        id: "forensics-cancel-job",
        label: "Cancel PCAP forensics job",
        method: "POST",
        endpoint: "/v1/pcap/jobs/{id}/cancel",
        requiredScopes: ["pcap:write"],
        acceptedScopes: ["pcap:write", "pcap:*", "admin:*", "*"],
        auditEvent: "PCAP_CANCEL",
        guardrails: [
          "only queued or processing jobs can be cancelled",
          "cross-tenant cancel requests must return 403",
          "successful cancels must be persisted in tasks and audit_logs",
        ],
      },
      {
        id: "forensics-retry-job",
        label: "Retry the same immutable PCAP forensics job",
        method: "POST",
        endpoint: "/v1/pcap/jobs/{id}/retry",
        requiredScopes: ["pcap:write"],
        acceptedScopes: ["pcap:write", "pcap:*", "admin:*", "*"],
        auditEvent: "PCAP_RETRY",
        guardrails: [
          "only failed or cancelled jobs can be retried",
          "If-Match, Idempotency-Key and X-Action-Reason are mandatory",
          "retry preserves the original frozen request and task identity",
        ],
      },
    ],
  },
  assets: {
    primary: "/v1/assets",
    secondary: [
      "/v1/assets/stats",
      "/v1/assets/discovery/runs",
      "/v1/assets/discovery/neighbors",
      "/v1/assets/{id}",
      "/v1/assets/{id}/details",
      "/v1/assets/{id}/history",
      "/v1/assets/{id}/topology",
      "/v1/assets/{asset_id}/snapshot",
      "/v1/assets/{asset_id}/governance/work-orders",
      "/v1/assets/governance/work-orders/{work_order_id}",
    ],
    actions: [
      {
        id: "asset-governance-work-order-create",
        label: "Create authoritative asset governance work order",
        method: "POST",
        endpoint: "/v1/assets/{asset_id}/governance/work-orders",
        requiredScopes: ["asset:govern"],
        acceptedScopes: ["asset:govern", "asset:*", "admin:*", "*"],
        auditEvent: "ASSET_GOVERNANCE_WORK_ORDER_REQUESTED",
        guardrails: [
          "Idempotency-Key, expected_asset_revision, owner, deadline and business reason are required",
          "HTTP 202 only means the internal work order is durably accepted and pending approval",
          "tenant identity is derived only from the verified access token",
        ],
      },
      ...([
        ["asset-governance-approve", "Approve asset governance work order"],
        ["asset-governance-reject", "Reject asset governance work order"],
        ["asset-governance-start", "Start asset governance execution"],
        ["asset-governance-complete", "Complete asset governance execution"],
        ["asset-governance-fail", "Fail asset governance execution"],
        ["asset-governance-cancel", "Cancel active asset governance work order"],
        ["asset-governance-compensate", "Compensate completed asset governance work order"],
      ] as const).map(([id, label]) => ({
        id,
        label,
        method: "POST" as const,
        endpoint: "/v1/assets/governance/work-orders/{work_order_id}/actions",
        requiredScopes: ["asset:govern"],
        acceptedScopes: ["asset:govern", "asset:*", "admin:*", "*"],
        auditEvent: `ASSET_GOVERNANCE_${id.replace("asset-governance-", "").toUpperCase()}`,
        guardrails: [
          "Idempotency-Key, expected_revision and business reason are required",
          "the requester cannot approve their own work order and only the assigned owner can start execution",
          "completion requires evidence when configured; compensation is optimistic and never deletes history",
        ],
      })),
      {
        id: "asset-discovery-credential-register",
        label: "Register SNMP/LLDP credential reference",
        method: "POST",
        endpoint: "/v1/assets/discovery/credentials",
        requiredScopes: ["asset:discover"],
        acceptedScopes: ["asset:discover", "asset:*", "admin:*", "*"],
        auditEvent: "ASSET_DISCOVERY_CREDENTIAL_REGISTER",
        defaultBody: {
          protocol: "snmp_lldp",
          secret_ref:
            "k8s://traffic-analysis/traffic-credentials#ASSET_DISCOVERY_SNMP",
        },
        guardrails: [
          "plaintext SNMP community or credentials must not be sent to the API",
          "secret_ref must point to a Kubernetes Secret or ExternalSecret-backed value",
        ],
      },
      {
        id: "asset-active-discovery-run",
        label: "Run SNMP/LLDP active discovery",
        method: "POST",
        endpoint: "/v1/assets/discovery/runs",
        requiredScopes: ["asset:discover"],
        acceptedScopes: ["asset:discover", "asset:*", "admin:*", "*"],
        auditEvent: "ASSET_ACTIVE_DISCOVERY_RUN",
        defaultBody: {
          mode: "snmp_lldp",
          observations: [],
        },
        guardrails: [
          "active discovery must write asset_discovery_runs and asset_topology_links",
          "observed SNMP/LLDP assets must upsert /v1/assets inventory records",
          "tenant_id must come from the authenticated request or tenant-scoped body",
        ],
      },
      {
        id: "asset-inventory-export",
        label: "Create tenant-scoped asset export job",
        method: "POST",
        endpoint: "/v1/assets/exports",
        requiredScopes: ["asset:export"],
        acceptedScopes: ["asset:export", "asset:*", "admin:*", "*"],
        auditEvent: "ASSET_EXPORT_REQUESTED",
        defaultBody: {
          action_id: "asset-inventory-export",
          format: "csv",
          columns: ["display_code", "ip_address", "hostname", "asset_type", "status", "last_seen"],
          filter: {},
        },
        guardrails: [
          "Idempotency-Key and a business reason are required",
          "HTTP 202 only means accepted; the browser must poll authoritative job state",
          "the server freezes the full tenant-scoped query and enforces row and byte budgets",
          "completed jobs must reference a checksum-verified MinIO object through a PostgreSQL manifest",
        ],
      },
      {
        id: "asset-column-preference-update",
        label: "Update authenticated user asset columns",
        method: "PUT",
        endpoint: "/v1/assets/preferences/columns",
        requiredScopes: ["asset:read"],
        acceptedScopes: ["asset:read", "asset:*", "admin:*", "*"],
        auditEvent: "ASSET_COLUMN_PREFERENCE_UPDATED",
        defaultBody: {
          view_id: "asset-inventory",
          columns: ["display_code", "ip_address", "hostname", "asset_type", "status", "last_seen"],
          expected_revision: 0,
        },
        guardrails: [
          "tenant_id and user_id come only from the authenticated identity",
          "expected_revision prevents one browser session from overwriting another",
          "at least one supported canonical column and a reason are required",
        ],
      },
      {
        id: "asset-inventory-export-download",
        label: "Download verified asset export artifact",
        method: "GET",
        endpoint: "/v1/assets/exports/{job_id}/download",
        requiredScopes: ["asset:export"],
        acceptedScopes: ["asset:export", "asset:*", "admin:*", "*"],
        auditEvent: "ASSET_EXPORT_DOWNLOADED",
        guardrails: [
          "the job must be completed, unexpired and owned by the authenticated tenant",
          "object size and sha256 must match the PostgreSQL manifest before bytes are served",
          "the download audit must commit before the response is released",
        ],
      },
    ],
  },
  graph: { primary: "/v1/graph/explore" },
  fusion: {
    primary: "/v1/fusion/workbench",
    secondary: [
      "/v1/fusion/stats",
      "/v1/fusion/entities",
      "/v1/threat-intel/entries",
      "/v1/fusion/value-report",
    ],
    actions: [
      {
        id: "fusion-conflict-resolve",
        label: "Fusion conflict resolve",
        method: "POST",
        endpoint: "/v1/fusion/conflicts/{id}/resolve",
        requiredScopes: ["rule:write"],
        acceptedScopes: ["rule:write", "rule:*", "admin:*", "*"],
        auditEvent: "FUSION_CONFLICT_RESOLVED",
        defaultBody: { strategy: "authoritative-source" },
        guardrails: [
          "field_name, selected_source and selected_value are required",
          "tenant_id is taken from the authenticated token for write operations",
          "resolution must be written to fusion_conflict_resolutions and audit_logs",
        ],
      },
      {
        id: "fusion-rule-update",
        label: "Fusion rule update",
        method: "PATCH",
        endpoint: "/v1/fusion/rules/{id}",
        requiredScopes: ["rule:write"],
        acceptedScopes: ["rule:write", "rule:*", "admin:*", "*"],
        auditEvent: "FUSION_RULE_UPDATED",
        defaultBody: { status: "draft", confidence_threshold: 0.85 },
        guardrails: [
          "confidence_threshold is clamped to 0..1",
          "rule edits must increment fusion_rule_overrides.version",
          "rule edits must be queryable through audit_logs",
        ],
      },
      {
        id: "fusion-evidence-export",
        label: "Fusion evidence export",
        method: "POST",
        endpoint: "/v1/fusion/evidence-packages",
        requiredScopes: ["rule:write"],
        acceptedScopes: ["rule:write", "rule:*", "admin:*", "*"],
        auditEvent: "FUSION_EVIDENCE_EXPORTED",
        guardrails: [
          "conflict_id is required and tenant scoped",
          "evidence payload must be generated from the persisted conflict state",
          "the sha256, filename and export action must be written to audit_logs",
        ],
      },
    ],
  },
  baselines: {
    primary: "/v1/baselines",
    secondary: ["/v1/baselines/{id}", "/v1/baselines/{id}/analytics", "/v1/baselines/{id}/versions", "/v1/baselines/{id}/actions"],
    pageLoadSecondary: ["/v1/baselines/{id}/analytics", "/v1/baselines/{id}/versions", "/v1/baselines/{id}/actions"],
    actions: [
      {
        id: "baseline-governance-action",
        label: "Queue audited baseline governance action",
        method: "POST",
        endpoint: "/v1/baselines/{id}/actions",
        requiredScopes: ["alert:write"],
        acceptedScopes: ["alert:write", "alert:*", "admin:*", "*"],
        auditEvent: "BEHAVIOR_BASELINE_ACTION",
        guardrails: [
          "the baseline must exist in the authenticated tenant",
          "governance reason is required and rollback targets must have a persisted snapshot",
          "queued actions must persist behavior_baseline_actions, behavior_baseline_outbox and audit_logs in one transaction",
          "queued is not a completed downstream result",
        ],
      },
      {
        id: "baseline-reset",
        label: "Reset behavior baseline",
        method: "POST",
        endpoint: "/v1/baselines/{id}/reset",
        requiredScopes: ["alert:write"],
        acceptedScopes: ["alert:write", "alert:*", "admin:*", "*"],
        auditEvent: "BEHAVIOR_BASELINE_RESET",
        guardrails: [
          "baseline reset requires alert:write or admin scope",
          "tenant_id must come from the authenticated token for write operations",
          "successful resets must persist behavior_baseline_resets and audit_logs rows",
        ],
      },
    ],
  },
  rules: {
    primary: "/v1/rules",
    secondary: [
      "/v1/rules/{id}",
      "/v1/rules/{id}/versions",
      "/v1/rules/{id}/workbench",
      "/v1/rules/{id}/operations/{event_id}",
    ],
    actions: [
      {
        id: "rule-workbench-action",
        label: "Queue rule workbench action",
        method: "POST",
        endpoint: "/v1/rules/{id}/actions",
        requiredScopes: ["rule:write"],
        acceptedScopes: ["rule:write", "rule:*", "admin:*", "*"],
        auditEvent: "RULE_WORKBENCH_ACTION",
        guardrails: [
          "the selected rule must belong to the authenticated tenant",
          "the action job and audit_logs row must commit in one transaction",
          "the response must return a durable job_id instead of a client-only success",
        ],
      },
      {
        id: "rule-enable",
        label: "Enable rule",
        method: "POST",
        endpoint: "/v1/rules/{id}/enable",
        requiredScopes: ["rule:enable"],
        acceptedScopes: ["rule:enable", "rule:write", "rule:*", "admin:*", "*"],
        auditEvent: "RULE_ENABLE",
        guardrails: [
          "cross-tenant enable requests must return 403",
          "enabling must persist enabled=true, status=active and increment rule version",
          "successful enables must write rule_outbox and audit_logs",
        ],
      },
      {
        id: "rule-disable",
        label: "Disable rule",
        method: "POST",
        endpoint: "/v1/rules/{id}/disable",
        requiredScopes: ["rule:enable"],
        acceptedScopes: ["rule:enable", "rule:write", "rule:*", "admin:*", "*"],
        auditEvent: "RULE_DISABLE",
        guardrails: [
          "cross-tenant disable requests must return 403",
          "disabling must persist enabled=false, status=disabled and increment rule version",
          "successful disables must write rule_outbox and audit_logs",
        ],
      },
      {
        id: "rule-rollback",
        label: "Rollback rule version",
        method: "POST",
        endpoint: "/v1/rules/{id}/rollback",
        requiredScopes: ["rule:write"],
        acceptedScopes: ["rule:write", "rule:*", "admin:*", "*"],
        auditEvent: "RULE_ROLLBACK",
        guardrails: [
          "target_version must refer to an older checksum-verified snapshot of the same tenant rule",
          "expected_version must match the current row and the restored definition must use current_version plus one",
          "the CAS update, rollback snapshot and update outbox event must commit in one PostgreSQL transaction",
          "HTTP 202 and broker publication are pending states until the operation endpoint reports the exact Flink subtask ACK set",
        ],
      },
    ],
  },
  deployments: {
    primary: "/v1/deployments",
    actions: [
      {
        id: "deployment-start-gray",
        label: "Start gray deployment",
        method: "POST",
        endpoint: "/v1/deployments/{id}/gray",
        requiredScopes: ["deploy:gray"],
        acceptedScopes: ["deploy:gray", "deploy:*", "admin:*", "*"],
        auditEvent: "DEPLOY_GRAY",
        guardrails: [
          "only planned deployments can enter gray state",
          "only one gray deployment can be active per tenant",
          "successful gray starts must persist deployment_history and audit_logs",
        ],
      },
      {
        id: "deployment-activate",
        label: "Activate deployment",
        method: "POST",
        endpoint: "/v1/deployments/{id}/activate",
        requiredScopes: ["deploy:activate"],
        acceptedScopes: ["deploy:activate", "deploy:*", "admin:*", "*"],
        auditEvent: "DEPLOY_ACTIVATE",
        guardrails: [
          "only planned or gray deployments can become active",
          "activation must supersede any previous active deployment for the same tenant",
          "successful activations must persist deployment_history and audit_logs",
        ],
      },
      {
        id: "deployment-pause",
        label: "Pause deployment",
        method: "POST",
        endpoint: "/v1/deployments/{id}/pause",
        requiredScopes: ["deploy:activate"],
        acceptedScopes: ["deploy:activate", "deploy:*", "admin:*", "*"],
        auditEvent: "DEPLOY_PAUSE",
        guardrails: [
          "only gray or active deployments can be paused",
          "pause requests must preserve tenant isolation",
          "successful pauses must persist deployment_history and audit_logs",
        ],
      },
      {
        id: "deployment-resume",
        label: "Resume deployment",
        method: "POST",
        endpoint: "/v1/deployments/{id}/resume",
        requiredScopes: ["deploy:activate"],
        acceptedScopes: ["deploy:activate", "deploy:*", "admin:*", "*"],
        auditEvent: "DEPLOY_RESUME",
        guardrails: [
          "only paused deployments can be resumed",
          "resume requests must preserve tenant isolation",
          "successful resumes must persist deployment_history and audit_logs",
        ],
      },
      {
        id: "deployment-rollback",
        label: "Rollback deployment",
        method: "POST",
        endpoint: "/v1/deployments/{id}/rollback",
        requiredScopes: ["deploy:rollback"],
        acceptedScopes: ["deploy:rollback", "deploy:*", "admin:*", "*"],
        auditEvent: "DEPLOY_ROLLBACK",
        guardrails: [
          "only gray, active, paused or failed deployments can be rolled back",
          "cross-tenant rollback requests must return 403",
          "successful rollbacks must persist deployment_history and audit_logs",
        ],
      },
    ],
  },
  models: {
    primary: "/v1/models",
    actions: [
      {
        id: "model-version-register",
        label: "Register model version",
        method: "POST",
        endpoint: "/v1/models/{id}/versions",
        requiredScopes: ["model:create"],
        acceptedScopes: ["model:create", "model:*", "admin:*", "*"],
        auditEvent: "MODEL_VERSION_CREATE",
        guardrails: [
          "model_id and tenant_id are taken from the path and authenticated context",
          "registered versions must start in registered state",
          "successful registration must persist model_versions and audit_logs",
        ],
      },
      {
        id: "model-version-activate",
        label: "Activate model version",
        method: "POST",
        endpoint: "/v1/models/{id}/versions/{version}/activate",
        requiredScopes: ["model:activate"],
        acceptedScopes: ["model:activate", "model:*", "admin:*", "*"],
        auditEvent: "MODEL_VERSION_ACTIVATE",
        guardrails: [
          "only registered or validating versions can become active",
          "all persisted review gates must be approved before activation",
          "the model registry requires gray_percent=100; staged traffic belongs to the deployment workflow",
          "activation must deprecate any previous active version for the same model",
          "successful activations must persist model_versions and audit_logs",
        ],
      },
      {
        id: "model-version-deprecate",
        label: "Deprecate model version",
        method: "POST",
        endpoint: "/v1/models/{id}/versions/{version}/deprecate",
        requiredScopes: ["model:activate"],
        acceptedScopes: ["model:activate", "model:*", "admin:*", "*"],
        auditEvent: "MODEL_VERSION_DEPRECATE",
        guardrails: [
          "only active or validating versions can be deprecated",
          "registered versions must return 409 until they enter an allowed state",
          "successful deprecations must persist model_versions and audit_logs",
        ],
      },
      {
        id: "model-feedback-append",
        label: "Append model feedback samples",
        method: "POST",
        endpoint: "/v1/models/{id}/feedback-samples",
        requiredScopes: ["model:write"],
        acceptedScopes: ["model:write", "model:*", "admin:*", "*"],
        auditEvent: "MODEL_FEEDBACK_INGEST_REQUESTED",
        guardrails: [
          "inline sample payloads are forbidden",
          "the tenant-scoped dataset reference and masked samples are validated by the ingestion consumer before append",
        ],
      },
      {
        id: "model-retrain-request",
        label: "Request model retraining",
        method: "POST",
        endpoint: "/v1/models/{id}/retrain",
        requiredScopes: ["model:write"],
        acceptedScopes: ["model:write", "model:*", "admin:*", "*"],
        auditEvent: "MODEL_RETRAIN_REQUESTED",
        guardrails: [
          "dataset quality gates are evaluated by the training consumer",
          "duplicate queued or running retrain jobs return 409",
        ],
      },
      {
        id: "model-evaluation-request",
        label: "Evaluate model version",
        method: "POST",
        endpoint: "/v1/models/{id}/versions/{version}/evaluate",
        requiredScopes: ["model:write"],
        acceptedScopes: ["model:write", "model:*", "admin:*", "*"],
        auditEvent: "MODEL_EVALUATION_REQUESTED",
        guardrails: [
          "the evaluation consumer resolves the dataset to an immutable checksum",
          "dispatch preserves tenant, model, version, dataset and job lineage",
        ],
      },
      {
        id: "model-version-rollback",
        label: "Rollback model version",
        method: "POST",
        endpoint: "/v1/models/{id}/versions/{version}/rollback",
        requiredScopes: ["model:activate"],
        acceptedScopes: ["model:activate", "model:*", "admin:*", "*"],
        auditEvent: "MODEL_VERSION_ROLLBACK_REQUESTED",
        guardrails: [
          "target version must be deprecated and all review gates approved",
          "rollback audit preserves the displaced active version and waits for model-update broker acknowledgement",
        ],
      },
      {
        id: "model-context-action",
        label: "Execute model context action",
        method: "POST",
        endpoint: "/v1/models/{id}/actions",
        requiredScopes: ["model:write"],
        acceptedScopes: ["model:write", "model:*", "admin:*", "*"],
        auditEvent: "MODEL_CONTEXT_ACTION_REQUESTED",
        guardrails: [
          "action and target are required",
          "mutating actions must require explicit confirmation",
        ],
      },
    ],
  },
  mlops: {
    primary: "/v1/mlops/status",
    secondary: ["/v1/mlops/conditions"],
    actions: [
      {
        id: "mlops-pipeline-create",
        label: "Create MLOps pipeline",
        method: "POST",
        endpoint: "/v1/mlops/retrain",
        requiredScopes: ["model:write"],
        acceptedScopes: ["model:write", "model:*", "admin:*", "*"],
        auditEvent: "MLOPS_RETRAIN_SUBMITTED",
        defaultBody: {
          model_type: "xgboost",
          lookback_days: 7,
          feature_set_id: "v1",
        },
        guardrails: [
          "the server submits the versioned Argo WorkflowTemplate",
          "tenant context must come from the authenticated token",
        ],
      },
      {
        id: "mlops-training-submit",
        label: "Submit training task",
        method: "POST",
        endpoint: "/v1/mlops/retrain",
        requiredScopes: ["model:write"],
        acceptedScopes: ["model:write", "model:*", "admin:*", "*"],
        auditEvent: "MLOPS_RETRAIN_SUBMITTED",
        defaultBody: {
          model_type: "xgboost",
          lookback_days: 7,
          feature_set_id: "v1",
        },
        guardrails: [
          "the response must include a real Argo workflow name",
          "tenant and model are server-authoritative",
        ],
      },
      {
        id: "mlops-task-retry",
        label: "Retry MLOps task",
        method: "POST",
        endpoint: "/v1/mlops/workflows/{id}/retry",
        requiredScopes: ["model:write"],
        acceptedScopes: ["model:write", "model:*", "admin:*", "*"],
        auditEvent: "MLOPS_WORKFLOW_RESUBMITTED",
        defaultBody: {},
        guardrails: [
          "only failed tasks can retry in production",
          "retry must preserve the original trace id",
        ],
      },
      {
        id: "mlops-task-stop",
        label: "Stop MLOps task",
        method: "POST",
        endpoint: "/v1/mlops/workflows/{id}/stop",
        requiredScopes: ["model:write"],
        acceptedScopes: ["model:write", "model:*", "admin:*", "*"],
        auditEvent: "MLOPS_WORKFLOW_STOP_REQUESTED",
        defaultBody: {},
        guardrails: [
          "stop requires explicit confirmation",
          "artifacts and audit trace must be retained",
        ],
      },
      {
        id: "mlops-label-request",
        label: "Request sample labeling",
        method: "POST",
        endpoint: "/v1/mlops/label-jobs",
        requiredScopes: ["model:write"],
        acceptedScopes: ["model:write", "model:*", "admin:*", "*"],
        auditEvent: "MLOPS_LABELING_UNAVAILABLE",
        defaultBody: { sample_ids: [], priority: "normal" },
        guardrails: [
          "samples must be masked",
          "sample ownership must match tenant context",
        ],
      },
      {
        id: "mlops-model-register",
        label: "Register trained model",
        method: "POST",
        endpoint: "/v1/models/{id}/versions",
        requiredScopes: ["model:create"],
        acceptedScopes: ["model:create", "model:*", "admin:*", "*"],
        auditEvent: "MODEL_VERSION_REGISTRATION_UNAVAILABLE",
        defaultBody: {
          version: "v-next",
          source: "mlops-pipeline",
          metrics: { f1_score: 0.9 },
        },
        guardrails: [
          "model package signature must pass",
          "registration must preserve training lineage",
        ],
      },
      {
        id: "mlops-task-inspect",
        label: "Inspect MLOps task",
        method: "GET",
        endpoint: "/v1/mlops/workflows/{id}",
        requiredScopes: ["model:read"],
        acceptedScopes: ["model:read", "model:*", "admin:*", "*"],
        auditEvent: "READ_ONLY",
        guardrails: [
          "task detail must preserve tenant isolation",
          "task lineage and data mode must be visible",
        ],
      },
      {
        id: "mlops-context-action",
        label: "Execute MLOps context action",
        method: "GET",
        endpoint: "/v1/mlops/workflows/{id}",
        requiredScopes: ["model:read"],
        acceptedScopes: ["model:read", "model:*", "admin:*", "*"],
        auditEvent: "READ_ONLY",
        defaultBody: { action: "inspect" },
        guardrails: [
          "action and task id are required",
          "mutating actions require explicit confirmation",
        ],
      },
      {
        id: "mlops-feedback-inspect",
        label: "Inspect feedback sample",
        method: "GET",
        endpoint: "/v1/mlops/feedback/{id}",
        requiredScopes: ["model:read"],
        acceptedScopes: ["model:read", "model:*", "admin:*", "*"],
        auditEvent: "READ_ONLY",
        guardrails: [
          "feedback sample access must preserve tenant isolation",
          "sensitive fields must remain masked",
        ],
      },
      {
        id: "mlops-model-version-inspect",
        label: "Inspect registered model version",
        method: "GET",
        endpoint: "/v1/models/{id}/versions/{version}",
        requiredScopes: ["model:read"],
        acceptedScopes: ["model:read", "model:*", "admin:*", "*"],
        auditEvent: "READ_ONLY",
        guardrails: [
          "model and version lineage must be preserved",
          "cross-tenant reads must return 404",
        ],
      },
    ],
  },
  playbooks: {
    primary: "/v1/playbooks/catalog",
    secondary: ["/v1/playbooks/executions"],
    actions: [
      {
        id: "playbook-execute",
        label: "Request versioned SOAR playbook execution",
        method: "POST",
        endpoint: "/v1/playbooks/{name}/execute",
        requiredScopes: ["playbook:execute"],
        acceptedScopes: ["playbook:execute", "playbook:write", "alert:write", "admin:*", "*"],
        auditEvent: "PLAYBOOK_EXECUTION_REQUESTED",
        defaultBody: {
          expected_version: 1,
          reason: "security operations requested this approved playbook execution",
          alert_context: {
            alert_id: "alert-id-required",
            alert_type: "scan",
            severity: "critical",
          },
        },
        guardrails: [
          "only the current approved and enabled playbook revision may be accepted",
          "Idempotency-Key, expected_version, a real alert_id and an explicit reason are required",
          "acceptance, independent approval, provider execution and compensation are distinct states",
          "HTTP acceptance or provider 2xx without durable per-step receipts must never be displayed as success",
          "execution, audit and outbox acceptance must commit in one PostgreSQL transaction",
          "tenant_id and actor are taken from the authenticated identity",
        ],
      },
      {
        id: "playbook-execution-status",
        label: "Read authoritative playbook execution status",
        method: "GET",
        endpoint: "/v1/playbooks/executions/{execution_id}",
        requiredScopes: ["playbook:read"],
        acceptedScopes: ["playbook:read", "admin:*", "*"],
        auditEvent: "READ_ONLY",
        guardrails: [
          "execution reads are tenant scoped and cross-tenant identities return not found",
          "workflow_revision and provider receipts are authoritative",
        ],
      },
      {
        id: "playbook-execution-approval",
        label: "Independently approve or reject a playbook execution",
        method: "POST",
        endpoint: "/v1/playbooks/executions/{execution_id}/approval",
        requiredScopes: ["playbook:approve"],
        acceptedScopes: ["playbook:approve", "admin:*", "*"],
        auditEvent: "PLAYBOOK_EXECUTION_APPROVED",
        defaultBody: { decision: "approve", expected_revision: 1, reason: "independent reviewer approved this execution" },
        guardrails: [
          "the requester cannot approve or reject the same execution",
          "Idempotency-Key and the current workflow_revision are required",
        ],
      },
      {
        id: "playbook-execution-cancel",
        label: "Cancel an undispatched playbook execution",
        method: "POST",
        endpoint: "/v1/playbooks/executions/{execution_id}/cancel",
        requiredScopes: ["playbook:execute"],
        acceptedScopes: ["playbook:execute", "playbook:write", "alert:write", "admin:*", "*"],
        auditEvent: "PLAYBOOK_EXECUTION_CANCELLED",
        defaultBody: { expected_revision: 1, reason: "operator cancelled the undispatched execution" },
        guardrails: [
          "only pending or approved but undispatched executions can be cancelled",
          "a leased or terminal provider effect cannot be relabelled cancelled",
        ],
      },
      {
        id: "playbook-execution-compensate",
        label: "Independently approve playbook compensation",
        method: "POST",
        endpoint: "/v1/playbooks/executions/{execution_id}/compensate",
        requiredScopes: ["playbook:approve"],
        acceptedScopes: ["playbook:approve", "admin:*", "*"],
        auditEvent: "PLAYBOOK_COMPENSATION_REQUESTED",
        defaultBody: { expected_revision: 1, reason: "independent reviewer approved compensation" },
        guardrails: [
          "compensation requires a completed or partial execution with a durable external-effect receipt",
          "the original requester cannot approve compensation",
          "compensation uses a stable phase idempotency identity and immutable reverse-step receipts",
        ],
      },
      {
        id: "playbook-state-update",
        label: "Update SOAR playbook state",
        method: "PATCH",
        endpoint: "/v1/playbooks/{name}",
        requiredScopes: ["playbook:write"],
        acceptedScopes: ["playbook:write", "admin:*", "*"],
        auditEvent: "PLAYBOOK_STATE_UPDATED",
        defaultBody: { enabled: true, expected_version: 1 },
        guardrails: [
          "expected_version must match the current PostgreSQL definition revision",
          "only an approved definition may be enabled",
          "definition state transitions and audit records must commit atomically",
        ],
      },
    ],
  },
  whitelist: {
    primary: "/v1/whitelist",
    secondary: ["/v1/whitelist/check"],
    pageLoadSecondary: [],
    actions: [
      {
        id: "whitelist-create",
        label: "Create whitelist entry",
        method: "POST",
        endpoint: "/v1/whitelist",
        requiredScopes: ["alert:write"],
        acceptedScopes: ["alert:write", "admin:*", "*"],
        auditEvent: "WHITELIST_CREATED",
        defaultBody: {
          type: "domain",
          value: "known-business.example",
          reason: "false_positive",
          status: "draft",
          approval_status: "draft",
        },
        guardrails: [
          "tenant_id must come from the authenticated token",
          "type and value are required",
          "successful creates must write WHITELIST_CREATED audit_logs rows",
        ],
      },
      {
        id: "whitelist-submit-approval",
        label: "Submit whitelist approval",
        method: "PATCH",
        endpoint: "/v1/whitelist/{id}",
        requiredScopes: ["alert:write"],
        acceptedScopes: ["alert:write", "admin:*", "*"],
        auditEvent: "WHITELIST_APPROVAL_SUBMITTED",
        defaultBody: { approval_status: "pending", status: "pending" },
        guardrails: [
          "approval submission must preserve tenant isolation",
          "cross-tenant updates must return 404",
          "successful submissions must write WHITELIST_APPROVAL_SUBMITTED audit_logs rows",
        ],
      },
      {
        id: "whitelist-extend",
        label: "Extend whitelist expiry",
        method: "PATCH",
        endpoint: "/v1/whitelist/{id}",
        requiredScopes: ["alert:write"],
        acceptedScopes: ["alert:write", "admin:*", "*"],
        auditEvent: "WHITELIST_EXTENDED",
        defaultBody: { expires_at: "2030-01-01T00:00:00Z" },
        guardrails: [
          "expires_at must be a future timestamp for active entries",
          "extension must persist to the whitelist row",
          "successful extensions must write WHITELIST_EXTENDED audit_logs rows",
        ],
      },
      {
        id: "whitelist-disable",
        label: "Disable whitelist entry",
        method: "PATCH",
        endpoint: "/v1/whitelist/{id}",
        requiredScopes: ["alert:write"],
        acceptedScopes: ["alert:write", "admin:*", "*"],
        auditEvent: "WHITELIST_DISABLED",
        defaultBody: { status: "disabled" },
        guardrails: [
          "disabled entries must stop matching /v1/whitelist/check",
          "viewer writes must return 403 before persistence",
          "successful disables must write WHITELIST_DISABLED audit_logs rows",
        ],
      },
    ],
  },
  compliance: {
    primary: "/v1/compliance/reports",
    secondary: ["/v1/compliance/audit-trail"],
    actions: [
      {
        id: "compliance-report-generate",
        label: "Generate compliance report",
        method: "POST",
        endpoint: "/v1/compliance/reports/generate",
        requiredScopes: ["compliance:write"],
        acceptedScopes: ["compliance:write", "admin:*", "*"],
        auditEvent: "COMPLIANCE_REPORT_GENERATED",
        defaultBody: { report_type: "weekly" },
        guardrails: [
          "report generation requires compliance:write or an administrative wildcard",
          "generated reports must persist compliance_reports rows",
          "missing evidence and non-pass sections must never be represented as a completed pass",
          "successful generation must write COMPLIANCE_REPORT_GENERATED audit_logs rows",
        ],
      },
      {
        id: "compliance-evidence-package-export",
        label: "Export compliance evidence package",
        method: "POST",
        endpoint: "/v1/compliance/reports/{id}/evidence-package",
        requiredScopes: ["compliance:export"],
        acceptedScopes: ["compliance:export", "admin:*", "*"],
        auditEvent: "COMPLIANCE_EVIDENCE_EXPORTED",
        guardrails: [
          "the package must be generated on the server from a tenant-scoped persisted report",
          "manifest and report payload must be bundled with a SHA-256 checksum",
          "the download must fail closed when its audit row cannot be committed",
        ],
      },
      {
        id: "compliance-report-export",
        label: "Export compliance runtime report",
        method: "POST",
        endpoint: "/v1/compliance/reports/{id}/export",
        requiredScopes: ["compliance:export"],
        acceptedScopes: ["compliance:export", "admin:*", "*"],
        auditEvent: "COMPLIANCE_REPORT_EXPORTED",
        defaultBody: { format: "pdf" },
        guardrails: [
          "PDF and DOCX artifacts must contain the persisted summary, all sections and report audit trail",
          "the artifact MIME type, file structure and SHA-256 must match the returned payload",
          "invalidated legacy reports must return 404 and cannot be exported",
        ],
      },
      {
        id: "compliance-remediations-create",
        label: "Create compliance remediation tasks",
        method: "POST",
        endpoint: "/v1/compliance/reports/{id}/remediations",
        requiredScopes: ["compliance:remediate"],
        acceptedScopes: ["compliance:remediate", "admin:*", "*"],
        auditEvent: "COMPLIANCE_REMEDIATIONS_CREATED",
        guardrails: [
          "one persistent task exists per tenant, report and non-pass section",
          "repeat requests reuse task IDs and report created versus reused counts",
          "invalidated legacy reports must not create remediation tasks",
        ],
      },
      {
        id: "compliance-report-finalize",
        label: "Finalize compliance report snapshot",
        method: "POST",
        endpoint: "/v1/compliance/reports/{id}/finalize",
        requiredScopes: ["compliance:finalize"],
        acceptedScopes: ["compliance:finalize", "admin:*", "*"],
        auditEvent: "COMPLIANCE_REPORT_FINALIZED",
        guardrails: [
          "the finalization hash must use the same canonical report serialization as the evidence manifest",
          "repeat finalization must return 409 and database rows are immutable",
          "invalidated legacy reports must not be finalized",
        ],
      },
    ],
  },
  "audit-log": {
    primary: "/v1/audit/logs",
    actions: [
      {
        id: "audit-query-save",
        label: "Save tenant audit query",
        method: "POST",
        endpoint: "/v1/audit/saved-queries",
        requiredScopes: ["audit:write"],
        acceptedScopes: ["audit:write", "audit:*", "admin:*", "*"],
        auditEvent: "AUDIT_SAVED_QUERY_CREATED",
        guardrails: ["query filters are tenant scoped", "the saved query and audit event are committed atomically"],
      },
      {
        id: "audit-export",
        label: "Export immutable audit evidence",
        method: "POST",
        endpoint: "/v1/audit/exports",
        requiredScopes: ["audit:export"],
        acceptedScopes: ["audit:export", "audit:*", "admin:*", "*"],
        auditEvent: "AUDIT_EVIDENCE_EXPORTED",
        guardrails: ["server renders the artifact from tenant-filtered rows", "exports above the synchronous limit fail rather than truncate", "response includes total matching rows, filename, MIME type, row count and SHA-256", "export metadata is persisted before success"],
      },
      {
        id: "audit-review-create",
        label: "Create a high-risk audit review",
        method: "POST",
        endpoint: "/v1/audit/reviews",
        requiredScopes: ["audit:write"],
        acceptedScopes: ["audit:write", "audit:*", "admin:*", "*"],
        auditEvent: "AUDIT_REVIEW_TRIGGERED",
        guardrails: ["the target audit event belongs to the active tenant", "review reason is required", "review and audit rows are committed atomically"],
      },
      {
        id: "audit-integrity-check",
        label: "Verify the tenant audit log digest",
        method: "POST",
        endpoint: "/v1/audit/integrity-checks",
        requiredScopes: ["audit:write"],
        acceptedScopes: ["audit:write", "audit:*", "admin:*", "*"],
        auditEvent: "AUDIT_INTEGRITY_CHECK_COMPLETED",
        guardrails: ["the digest covers canonical ordered event content", "a fixed-window manifest detects missing or added rows", "new baselines never report a fully passed verification", "the check result and root SHA-256 are persisted"],
      },
    ],
  },
  notifications: {
    primary: "/v1/notifications/workbench",
    secondary: [],
    actions: [
      {
        id: "notification-settings-update",
        label: "Update notification settings",
        method: "PUT",
        endpoint: "/v1/notifications/settings",
        requiredScopes: ["admin:*"],
        acceptedScopes: ["admin:*", "*"],
        auditEvent: "NOTIFICATION_SETTINGS_UPDATED",
        defaultBody: {
          enabled: true,
          min_severity: "high",
          channels: { email: true, webhook: false },
          secret_ref: "traffic-analysis/notification-secret",
        },
        guardrails: [
          "plaintext webhook tokens, passwords and API keys must be rejected",
          "channel credentials must be represented by secret_ref only",
          "successful updates must write NOTIFICATION_SETTINGS_UPDATED audit_logs rows",
        ],
      },
      {
        id: "notification-test-send",
        label: "Send notification test",
        method: "POST",
        endpoint: "/v1/notifications/test",
        requiredScopes: ["admin:*"],
        acceptedScopes: ["admin:*", "*"],
        auditEvent: "NOTIFICATION_TEST_SENT",
        guardrails: [
          "test sends require admin:*",
          "test sends must not expose channel secrets in responses",
          "successful test sends must write NOTIFICATION_TEST_SENT audit_logs rows",
        ],
      },
      {
        id: "notification-subscription-create",
        label: "Create notification subscription",
        method: "POST",
        endpoint: "/v1/notifications/subscriptions",
        requiredScopes: ["admin:*"],
        acceptedScopes: ["admin:*", "*"],
        auditEvent: "NOTIFICATION_RULE_CREATED",
        guardrails: ["name and at least one supported channel are required", "tenant_id is taken from authenticated context", "the rule and its audit event are persisted"],
      },
      {
        id: "notification-subscription-update",
        label: "Update notification subscription",
        method: "PATCH",
        endpoint: "/v1/notifications/subscriptions/{id}",
        requiredScopes: ["admin:*"],
        acceptedScopes: ["admin:*", "*"],
        auditEvent: "NOTIFICATION_RULE_UPDATED",
        guardrails: ["cross-tenant rule ids return 404", "empty patch fields do not erase stored fields", "updates write an audit event"],
      },
      {
        id: "notification-template-create",
        label: "Create notification template",
        method: "POST",
        endpoint: "/v1/notifications/templates",
        requiredScopes: ["admin:*"],
        acceptedScopes: ["admin:*", "*"],
        auditEvent: "NOTIFICATION_TEMPLATE_CREATED",
        guardrails: ["template type, name and body are required", "template variables are stored as a schema", "plaintext channel credentials are never accepted"],
      },
      {
        id: "notification-template-update",
        label: "Update notification template",
        method: "PATCH",
        endpoint: "/v1/notifications/templates/{id}",
        requiredScopes: ["admin:*"],
        acceptedScopes: ["admin:*", "*"],
        auditEvent: "NOTIFICATION_TEMPLATE_UPDATED",
        guardrails: ["each update increments the persisted version", "cross-tenant template ids return 404", "preview never executes a send"],
      },
      {
        id: "notification-template-test",
        label: "Test notification template",
        method: "POST",
        endpoint: "/v1/notifications/templates/{id}/test",
        requiredScopes: ["admin:*"],
        acceptedScopes: ["admin:*", "*"],
        auditEvent: "NOTIFICATION_TEMPLATE_TESTED",
        guardrails: ["the template must belong to the active tenant", "the test creates a delivery record and audit event", "the response contains no secrets"],
      },
      {
        id: "notification-escalation-create",
        label: "Create escalation policy",
        method: "POST",
        endpoint: "/v1/notifications/escalation-policies",
        requiredScopes: ["admin:*"],
        acceptedScopes: ["admin:*", "*"],
        auditEvent: "NOTIFICATION_ESCALATION_CREATED",
        guardrails: ["at least one stage is required", "every stage has a non-negative delay and target role", "the policy is tenant scoped"],
      },
      {
        id: "notification-delivery-retry",
        label: "Retry notification delivery",
        method: "POST",
        endpoint: "/v1/notifications/deliveries/{id}/retry",
        requiredScopes: ["admin:*"],
        acceptedScopes: ["admin:*", "*"],
        auditEvent: "NOTIFICATION_DELIVERY_RETRIED",
        guardrails: ["the delivery must belong to the active tenant", "retry count and trace id are persisted", "the retry action is audited"],
      },
      {
        id: "notification-silence-rule-create",
        label: "Create notification silence rule",
        method: "POST",
        endpoint: "/v1/notifications/silence-rules",
        requiredScopes: ["admin:*"],
        acceptedScopes: ["admin:*", "*"],
        auditEvent: "NOTIFICATION_SILENCE_RULE_CREATED",
        defaultBody: {
          name: "maintenance-window",
          scope: "main-campus",
          starts_at: "2026-06-30T22:00:00Z",
          ends_at: "2026-07-01T02:00:00Z",
          affected_targets: ["core-switch"],
          policy: "night-escalation",
          reason: "scheduled maintenance",
        },
        guardrails: [
          "ends_at must be after starts_at",
          "tenant_id is taken from the authenticated token",
          "successful creates must persist notification_silence_rules and audit_logs",
        ],
      },
      {
        id: "notification-silence-rule-toggle",
        label: "Toggle notification silence rule",
        method: "PATCH",
        endpoint: "/v1/notifications/silence-rules/{id}",
        requiredScopes: ["admin:*"],
        acceptedScopes: ["admin:*", "*"],
        auditEvent: "NOTIFICATION_SILENCE_RULE_UPDATED",
        defaultBody: { enabled: false },
        guardrails: [
          "cross-tenant silence rule updates must return 404",
          "enabled is required for toggle requests",
          "successful toggles must update notification_silence_rules and audit_logs",
        ],
      },
    ],
  },
  settings: {
    primary: "/v1/auth/system-settings",
    secondary: [
      "/v1/tokens/scopes",
      "/v1/tokens",
      "/v1/tokens/scopes/probe",
      "/v1/auth/settings/display",
    ],
    actions: [
      {
        id: "settings-system-save",
        label: "Save tenant system settings",
        method: "PUT",
        endpoint: "/v1/auth/system-settings",
        requiredScopes: ["admin:write"],
        acceptedScopes: ["admin:write", "admin:*", "*"],
        auditEvent: "system_settings_update",
        guardrails: [
          "tenant_id and updated_by must come from the authenticated token",
          "expected_revision must prevent lost updates",
          "integration credentials must remain secret_ref values",
        ],
      },
      {
        id: "settings-scope-review",
        label: "Review tenant scopes",
        method: "POST",
        endpoint: "/v1/auth/system-settings/actions/scope-review",
        requiredScopes: ["admin:write"],
        acceptedScopes: ["admin:write", "admin:*", "*"],
        auditEvent: "system_settings_scope_review",
        guardrails: ["result must be derived from tenant roles and token aggregates", "the action must not claim to synchronize or mutate permissions", "successful reviews must write audit_logs"],
      },
      {
        id: "settings-connection-test",
        label: "Test integrations",
        method: "POST",
        endpoint: "/v1/auth/system-settings/actions/connection-test",
        requiredScopes: ["admin:write"],
        acceptedScopes: ["admin:write", "admin:*", "*"],
        auditEvent: "system_settings_connection_test",
        guardrails: ["test results must come from a real endpoint reachability probe and persist last_tested_at", "failed probes must be reported as degraded rather than healthy", "secret values must never be returned"],
      },
      {
        id: "settings-security-audit",
        label: "Run security audit",
        method: "POST",
        endpoint: "/v1/auth/system-settings/actions/security-audit",
        requiredScopes: ["admin:write"],
        acceptedScopes: ["admin:write", "admin:*", "*"],
        auditEvent: "system_settings_security_audit",
        guardrails: ["findings must use persisted settings", "successful actions must write audit_logs"],
      },
      {
        id: "settings-impact",
        label: "Review change impact",
        method: "GET",
        endpoint: "/v1/auth/system-settings/impact",
        requiredScopes: ["admin:read"],
        acceptedScopes: ["admin:read", "admin:write", "admin:*", "*"],
        auditEvent: "system_settings_impact_view",
        guardrails: ["response must state scope, risk, permission and audit action"],
      },
      {
        id: "settings-preferences-save",
        label: "Save user settings",
        method: "PUT",
        endpoint: "/v1/auth/settings/{category}",
        requiredScopes: ["token:read"],
        acceptedScopes: ["token:read", "admin:*", "*"],
        auditEvent: "USER_UPDATE",
        defaultBody: {
          action_id: "settings-action-001",
          reason: "operator updated display preferences",
          expected_revision: 0,
          page_size: 50,
          refresh_interval: 30,
          default_time_range: "last_24h",
          timezone: "Asia/Shanghai",
          show_ws_status: true,
        },
        guardrails: [
          "settings category must be notifications or display",
          "tenant_id and user_id must come from the authenticated token",
          "Idempotency-Key and action_id must identify retries while expected_revision prevents lost updates",
          "successful saves must atomically persist user_settings, history, compatible USER_UPDATE audit and user.events.v1 outbox",
        ],
      },
      {
        id: "settings-token-create",
        label: "Create API token",
        method: "POST",
        endpoint: "/v1/tokens",
        requiredScopes: ["token:write"],
        acceptedScopes: ["token:write", "*"],
        auditEvent: "create_token",
        defaultBody: {
          name: "ops-token",
          scopes: ["alert:read", "token:read"],
          expires_in_sec: 300,
        },
        guardrails: [
          "token creation requires token:write (only global * also satisfies it)",
          "requested scopes must not exceed the authenticated caller permissions",
          "plain token is returned only once and token_hash must never be returned",
          "successful creates must persist api_tokens and audit_logs action=create_token rows in one transaction",
        ],
      },
      {
        id: "settings-token-regenerate",
        label: "Regenerate API token",
        method: "POST",
        endpoint: "/v1/tokens/{id}/regenerate",
        requiredScopes: ["token:write"],
        acceptedScopes: ["token:write", "*"],
        auditEvent: "regenerate_token",
        guardrails: [
          "regeneration requires token:write (only global * also satisfies it)",
          "the caller must be allowed to delegate every scope copied from the old token",
          "old raw token must be rejected after regenerate",
          "old revoke, new credential creation and regenerate_token audit must commit atomically",
        ],
      },
      {
        id: "settings-token-revoke",
        label: "Revoke API token",
        method: "POST",
        endpoint: "/v1/tokens/{id}/revoke",
        requiredScopes: ["token:write"],
        acceptedScopes: ["token:write", "*"],
        auditEvent: "revoke_token",
        guardrails: [
          "revoke requires token:write (only global * also satisfies it)",
          "the caller must be allowed to delegate every scope held by the target token",
          "revoked raw tokens must fail /v1/tokens/validate",
          "successful revokes must persist status=revoked and write revoke_token audit_logs rows",
        ],
      },
      {
        id: "settings-token-scope-update",
        label: "Update API token scopes",
        method: "PUT",
        endpoint: "/v1/tokens/{id}/scopes",
        requiredScopes: ["token:write"],
        acceptedScopes: ["token:write", "*"],
        auditEvent: "update_token_scopes",
        defaultBody: { scopes: ["alert:read", "token:read"] },
        guardrails: [
          "scope updates require token:write (only global * also satisfies it)",
          "the caller must be allowed to delegate every existing target scope",
          "invalid scopes must be rejected by auth-service",
          "requested scopes must not exceed the authenticated caller permissions",
          "successful scope changes and update_token_scopes audit must commit atomically",
        ],
      },
      {
        id: "settings-token-validate",
        label: "Validate API token",
        method: "POST",
        endpoint: "/v1/tokens/validate",
        requiredScopes: ["token:read"],
        acceptedScopes: ["token:read", "token:write", "admin:*", "*"],
        auditEvent: "validate_token",
        guardrails: [
          "connection tests must submit the token only to /v1/tokens/validate",
          "validation responses must not expose token_hash",
          "expired, regenerated or revoked raw tokens must return invalid credentials",
        ],
      },
    ],
  },
};

export const getPageApiPlan = (pageId: string) =>
  pageApiPlans[pageId] ?? { primary: `/v1/${pageId}` };

export const getPageLoadSecondaryEndpoints = (pageId: string) => {
  const plan = getPageApiPlan(pageId);
  return (plan.pageLoadSecondary ?? plan.secondary ?? []).filter(
    (endpoint) => !hasEndpointPlaceholder(endpoint),
  );
};

export const getPageActionPlans = (pageId: string) =>
  getPageApiPlan(pageId).actions ?? [];

export const getPageActionPlan = (pageId: string, actionId: string) =>
  getPageActionPlans(pageId).find((action) => action.id === actionId);

export const getPlanEndpoints = (plan: EndpointPlan) => [
  plan.primary,
  ...(plan.secondary ?? []),
  ...(plan.actions ?? []).map((action) => action.endpoint),
];

const hasEndpointPlaceholder = (endpoint: string) => /\{[^}]+\}/.test(endpoint);
