FROM alpine:latest

ARG SERVICE_NAME

RUN apk --no-cache add ca-certificates tzdata && \
    adduser -D -u 1000 appuser

COPY bin/${SERVICE_NAME} /usr/local/bin/app

USER appuser

EXPOSE 8080 8081 8082 8083 8084 8085 8086 50051 50053 9091 9092 9093 9094
ENTRYPOINT ["/usr/local/bin/app"]
